contentful/apps

- .circleci/config.yml
- apps/ai-image-tagging/frontend/package.json
- apps/ai-image-tagging/lambda/package.json
- apps/bynder/package.json
- apps/cloudinary/package.json
- apps/commercelayer/package.json
- apps/commercetools/package.json
- apps/dropbox/package.json
- apps/frontify/package.json
- apps/gatsby/package.json
- apps/google-analytics/package.json
- apps/image-focal-point/package.json
- apps/jira/functions/package.json
- apps/jira/jira-app/package.json
- apps/netlify/package.json
- apps/optimizely/package.json
- apps/shopify/package.json
- apps/smartling/frontend/package.json
- apps/smartling/lambda/package.json
- lib/shared-dam-app/package.json
- lib/shared-sku-app/package.json
- package.json
This PR:
Note that the test deployment from all branches ends up in the same location (same bucket, same stage). It's not intended to be used for sharing because builds will eventually override each other. The sole purpose of deployment is to test if it wasn't broken.
> Build improvements

- apps/google-analytics/src/Analytics.tsx
- apps/google-analytics/src/AppConfig.tsx
- apps/google-analytics/src/utils.ts
The content type dropdown in the app config no longer gets a red border when a value isn't selected.
The slug field will be red when a content type is selected and a slug wasn't detected automatically - no `/^slug/i` field and multiple short text fields to chose from). The form will fail to save if there are no content types selected or a content type is selected without a slug field selected.
If a selected slugField is deleted from a content type or the content type itself is deleted, it will be removed from the content type list in the app's config page the next time it's opened.
> GA: Add "Last 24 hours"; Improve config validation

- apps/cloudinary/src/index.js
Also, ensure thumbnail transformation is sent to the `video_thumbnail_url` function
Fixes - https://github.com/contentful/apps/issues/58
> Support creating thumbnails for assets with 'type' `private`

- apps/typeform/frontend/src/Auth/TypeformOAuth.tsx
- apps/typeform/frontend/src/constants.ts
Since the typeform `client id` is publicly anyway in the URL it can be passed as a constant to the OAuth flow.
> fix(typeform): pass typeform client id to the frontend

- lib/shared-dam-app/src/index.tsx
This change helps improve the reusability of the utils we have from the shared-dam-app libs. For example, Mux (#80) would like to use the utilities without the UI.
> exporting targetState field utils for external use

- lib/shared-dam-app/src/index.tsx
- lib/shared-dam-app/src/utils.ts
What this fix is doing:
When importing `contentful-ui-extensions-sdk`, the `init` function is exported but before export, `createInitializer ` is called. This means that if you import the SDK multiple times in a project, it will initialize multiple times which can lead to duplication of calls.
https://github.com/contentful/ui-extensions-sdk/blob/master/lib/index.ts#L7
The Mux app has exposed this bug by trying to import components of the shared-dam-app lib through the index export file. Because of this, the SDK is also invoked.
This fix simply allows for importing the utility methods without invoking the SDK again.
> Making shared-dam utils export in different location.

- apps/mux/src/config.tsx
- apps/mux/src/index.tsx
- apps/mux/test/index.test.tsx
This handles assets that are in the errored state. This state most commonly happens when someone uploads a file that is not a video file.
> Mux asset error handling

- apps/cloudinary/src/index.html
add fixed height to Cloudinary iframe, this fixes a rendering bug where Cloudinary would
cover up the modal header when you opened the comments pane in the edit widget
This isn't a great fix really, as to be honest I'm not sure why the rendering issue is happening. Cloudinary are looking into this on their end as well, and should hopefully be able to shed more light.
> fix: stop cloudinary covering up dialog header and close button

- apps/commercetools/src/AppConfig/FieldTypeInstructions.tsx
- apps/commercetools/src/AppConfig/index.tsx
- apps/gatsby/src/AppConfig/AppConfig.js
- apps/gatsby/src/AppConfig/ContentTypesPanel.js
- apps/gatsby/src/AppConfig/ContentTypesPanel.spec.js
- apps/gatsby/src/AppConfig/__snapshots__/ContentTypesPanel.spec.js.snap
- apps/jira/jira-app/package-lock.json
- apps/jira/jira-app/package.json
- apps/jira/jira-app/src/__snapshots__/index.spec.tsx.snap
- apps/jira/jira-app/src/components/App/Config.tsx
- apps/jira/jira-app/src/components/App/Steps/ContentTypeStep.tsx
- apps/netlify/src/app/index.js
- apps/netlify/src/app/netlify-content-types.js
- apps/smartling/frontend/src/AppConfig.tsx
- apps/smartling/frontend/src/__snapshots__/index.spec.tsx.snap
- apps/typeform/frontend/src/AppConfig/AppConfig.tsx
- apps/typeform/frontend/src/Field/TypeFormField.tsx
- lib/shared-dam-app/src/AppConfig/AppConfig.tsx
- lib/shared-sku-app/src/AppConfig/AppConfig.tsx
When there a no valid content types available in an environment where the app is going to be installed, we should display an empty state and provide a link to the user to add a content type or edit an existing content model.
Ticket: https://contentful.atlassian.net/secure/RapidBoard.jspa?rapidView=38&projectKey=EXT&modal=detail&selectedIssue=EXT-1960
> feat: improve empty states of assignments [EXT-1960]

- apps/optimizely/src/AppPage/ContentTypes.js
A content type with many references, and long field names for those references would cut off some of the inputs. This Pr just ensures that they will wrap onto the next line
before: 
After:
> fix: add flex wrap to handle many references

- apps/cloudinary/package-lock.json
- apps/cloudinary/package.json
The newest version of CES allows for `contentHash` which should update
the hash of the JS files and bust the cache when updates are made.
I'm not updating other packages right now to keep this PR low-impact.
> Updating cloudinary's contentful-extension-scripts

- apps/gatsby/src/Sidebar.js
This update comes from a report on a bit of confusion about what it means for our sidebar app to show an updating status.
When the Contentful entry is saved, our sidebar reports that the preview is updated. However, this is not the case. The preview gets sent new information which is then used to build a new preview. We simply report whether or not the new entry data was sent so a new preview could be built.
> Updating wording in Gatsby manual save

- apps/mux/src/index.tsx
* we were using `asset.ratio` but the correct property on the mux asset is `asset.aspect_ratio`. As a result - `ratio` on the Contentful object was never being set, which conflicts with the documentation we have.
* also fix up resetField() to also set signedPlaybackId to `undefined`
> correctly set `ratio` on contentful object

- apps/bynder/src/index.js
Behavior:
- For existing users, unless they update the configuration, the behavior will continue to be only images are updated
- For new installations, and updates of the configuration, the default is to allow all types of assets
The implementation is not perfect. It'd much better to use checkboxes. Unfortunately we don't have an implementation for that in `shared-dam-app`. An alternative would be to use a `select` with the `multiple` attribute set. As far as I can tell the [Forma 36 `select` component](https://forma-36-react-components.netlify.app/?path=/story/components-select--default) does _not_ support this.
A great improvement in the future would be to allow users to override this on a field level. If/when field level parameters are implemented this can be revisited.
> Allow users of the Bynder app to select what types of assets can be selected

- apps/bynder/src/index.js
Bynder confirmed they won't allow update functionality in Compact View, so the copy of the affected button is misleading.
> fix: change bynder button copy

- apps/jira/jira-app/src/components/Auth/OAuth.tsx
Jira changed the amount of the messages we get from the window we open. 
Now we get a lot of messages without a payload 🤷 and we need to filter them in order for the rest of the flow to work as expected and allow storing the token and the expiration in localStorage.
> fix: wait for one of error or token to close the window

- apps/netlify/src/sidebar/index.js
Open preview was a misleading description, as the button just links to the netlify site. This PR changes the button copy to `open site` - which should be clearer.
> chore: open preview to open site

- apps/image-focal-point/src/__snapshots__/index.spec.js.snap
- apps/image-focal-point/src/components/FocalPointView/FocalPointView.js
- apps/image-focal-point/src/components/FocalPointView/FocalPointView.spec.js
- apps/image-focal-point/src/components/FocalPointView/__snapshots__/FocalPointView.spec.js.snap
- apps/image-focal-point/src/components/FocalPointView/styles.js
- apps/image-focal-point/src/index.js
A customer asked if it is possible to reset the focal point of a given image. Right now it is only to possible to reset a focal point if you create a new entry which is really inconvenient.
> feat: add reset button for image focal point [EXT-2413]

- .circleci/config.yml
- package.json
- packages/dam-app-base/package.json
- packages/dam-app-base/tsconfig.json
- packages/ecommerce-app-base/package.json
- packages/ecommerce-app-base/tsconfig.json
After initially publishing our new packages, I noticed minor issues:
* `main` and `types` is not configured correctly in `package.json`
* We include all files and not only the `lib` directory
* CI breaks on `lerna publish` because it's waiting for user interaction
> Fixes after the initial publish

- lerna.json
- package.json
Another fix...
I used `from-git` without actually updating the git tags. Now, the versions/tags should be set correctly. The package versions are updated independently.
> chore: version packages independently

- lerna.json
Config of `publish` command has to be nested under `command`
> chore: fix config of publish commit message

- lerna.json
We do not want to publish a new package version for every change to the docs. (e.g. https://github.com/contentful/apps/pull/186)
This can be tested locally by committing a change and running `lerna changed`.
Also, with this PR changes to tests and updating the package-lock.json (which might happen more frequently with dependabot) will be ignored.
We don't really care about bumping the app's versions as they are not published to npm.
> chore: don't publish when changing docs or tests

- apps/gatsby/package-lock.json
- apps/gatsby/package.json
- apps/gatsby/src/Sidebar.js
- apps/gatsby/src/__snapshots__/Sidebar.spec.js.snap
Update `apps/gatsby` so that:
1. It uses `gatsby-cms-extension-base` version `0.0.46`
2. Reference to `previewInstanceUrl` is renamed to `previewUrl` (as the CMS extension base expects)
> Update gatsby extension base

- .gitignore
- apps/bynder/src/index.html
- apps/bynder/src/index.js
Updating bynder app according to https://developer-docs.bynder.com/ui-components migration steps. 
All fields that are not there with the new version were added through `assetFieldSelection` and then tied together with `transformAsset`, to be in the shape how it was before to ensure backwards compatibility.
> refactor: [EXT-2590] update bynder version with required changes

- apps/shopify/package-lock.json
- apps/shopify/package.json
The current version of `shopify-buy` uses API `2019-10` which times out after 15s. The latest version uses the latest API version which allows request that take over 30 seconds.
For customers with a large list of products, the Shopify app currently fails to render the product picker.
> fix: use latest version of shopify-buy

- apps/shopify/src/Pagination.js
- apps/shopify/src/dataTransformer.js
In some rare cases the "Load more" button was displayed even though there was no new page with products/variants available. The root cause of this issue is that we get an unsorted list of products and only one of them had `hasNextPage=false`. So we now check whether any of the newly loaded products has this flag set to false and then hide the button.
> fix(Shopify): 'load more' button was wrongly displayed in some edge cases

- apps/shopify/src/Pagination.js
- packages/ecommerce-app-base/src/SkuPicker/SkuPicker.tsx
Sometimes the calls made in shopify can take a long time to resolve. Because of the way the pagination code is structured, this could lead to there being multiple recursive chains of calls for the function `fetchNext` happening simultaneously. Each time the function is invoked we checked whether the search term had changed, and if so, assumed that this was a new search term and that we should start fetching from scratch. If two requests became active at once, they would both repeatedly reset, as with each call it would be appear that the search term had changed.
> fix: stop simultaneous recursive chains

- apps/gatsby/src/AppConfig/ContentTypesPanel.js
Breaking Gatsby app config page in production. Can't reproduce locally, so adding a naive check as a bandaid.
> fix: add check for sys object on select maps

- apps/gatsby/src/AppConfig/AppConfig.js
- apps/gatsby/src/AppConfig/ContentTypesPanel.js
App was only returning 100 content types from a space. This means that if the app was installed with certain content types, and then new content types were introduced, it could bump old content types out of the data returned from `space.getContentTypes`. This caused two bugs:
- Made some types unavailable in the config page.
- Returned undefined for some types when matching enabled ids to their full content type.
Raised the limit for getting content types to 1000.
> fix: retrieve all content types from space

- .circleci/config.yml
Upgrade our CI pipeline to make use of Node 14 and remove the dependency on Python 2 (EOL as of this year)
> chore: update to node 14

- apps/brandfolder/src/index.js
- apps/frontify/src/index.js
- apps/jira/jira-app/src/components/Auth/OAuth.tsx
- apps/jira/jira-app/src/index.spec.tsx
- apps/smartling/frontend/src/Sidebar.tsx
- apps/typeform/frontend/src/Auth/TypeformOAuth.tsx
Currently, the message event handler is also triggered for messages being sent from the web app to the app iframe. This simple condition excludes those messages and ensures the handler only handles messages coming from the frontify iframe.
Question: Should we also include this condition in other apps to avoid infinite loops as they happed with frontify?
> fix: only handle messages events of relevant sources [EXT-2675]

- apps/cloudinary/src/index.js
The `default_transformation` option has the wrong shape but was handled correctly by cloudinary. With a server-side update of cloudinary's media library, our transformation option was not valid anymore and the user receives the error `e is not iterable` when clicking "Insert".
This PR adjusts the shape of `default_transformation` to match the [docs](https://cloudinary.com/documentation/media_library_widget).
fixes #311
> fix: adjust shape of transformation option

- apps/cloudinary/src/index.js
When "Format" and "Media Quality" from the Cloudinary App settings are set to "None" and an original asset is inserted via the Media Library Widget, no "derived" key would be present in the returned JSON. This results in the `resource.raw_transformation` called in `makeThumbnail` to be `undefined` which leads to thumbnail URLs to have a transformation of `undefined/c_fill,h_100,w_150`. As this is not a valid Cloudinary transformation/URL, no thumbnail is displayed for those inserted assets. If `raw_transformation` is undefined then we can default to an empty string and the Cloudinary `url` method would handle the transformation when it comes in as `/c_fill,h_100,w_150`.
> fix: render thumbnail correctly when quality/format transformation is disabled

- apps/gatsby/src/AppConfig/AppConfig.js
- apps/gatsby/src/AppConfig/AppConfig.spec.js
Gatsby app would previously overwrite existing config location when saving configuration changes. This would cause issues for customers who didn't want Gatsby to be the third item in their sidebar..
> feat: [] don't overwrite existing editor interface config 

- apps/ai-image-tagging/lambda/package-lock.json
- apps/ai-image-tagging/lambda/package.json
- apps/ai-image-tagging/lambda/serverless.yml
- apps/jira/functions/serverless.yml
- apps/smartling/lambda/serverless.yml
- apps/typeform/lambda/package-lock.json
- apps/typeform/lambda/package.json
- apps/typeform/lambda/serverless.yml
We're setting a certain version of the serverless framework in the serverless.yml file. This no longer corresponds with what we have in our package.json and causes the pipeline to fail on the test deploy step. Judging from https://www.serverless.com/blog/serverless-framework-v2 it looks like none of the breaking changes should impact us. 
Help in how to test this without just deploying it would be appreciated.
> chore: [] bump to v2 of the serverless framework 

- apps/ai-image-tagging/lambda/serverless.yml
- apps/jira/functions/serverless.yml
- apps/smartling/lambda/serverless.yml
- apps/typeform/lambda/serverless.yml
With serverless v3 there will be a few changes to the `serverless.yml`. I adjusted the code already to remove a few warnings
The explanations of each change are in the respective commit message.
I didn't do anything about the Lambda hash algorithm change warning:
```
Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
```
> chore: serverless v3 deprecations

- .github/dependabot.yml
Dependabot currently uses `chore:` as prefix for all dependencies. For our `...-app-base` packages this means that we release a new version without any changelog entry.
See https://github.com/contentful/apps/blob/master/packages/ecommerce-app-base/CHANGELOG.md
With this change, all regular dependencies use `fix:` as prefix. All dev dependencies still use `chore:`
Docs: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#commit-message
> chore: use `fix:` prefix for dependencies

- apps/shopify/src/skuResolvers.js
- packages/ecommerce-app-base/src/Editor/SortableComponent.tsx
- packages/ecommerce-app-base/src/Editor/SortableList.tsx
- packages/ecommerce-app-base/src/Editor/SortableListItem.tsx
- packages/ecommerce-app-base/src/Editor/__snapshots__/SortableListItem.spec.tsx.snap
Hello, this PR solves three issues:
1.) For collections preview we were fetching first 20 collections meaning that for stores with more than 20 collections the preview would break. I have increased that limit to 250 (max) as Shopify unfortunately does not support fetching multiple collections by ids
2.) This PR also makes sure that missing collections/products (if they are deleted for example) still show up in the interface. This was always the case for product variants, but I missed adding it for products/collections.
3.) I have also amended the `ecommerce-app-base` to display the correct sku type in the "missing" tag.
Thanks :)
> fix: [] Fix Shopify not displaying missing SKUs for collections/products

- apps/gatsby/src/Sidebar.js
- apps/gatsby/src/Sidebar.spec.js
Before the recent gatsby update, if the user didn't have a webhook URL in their installation params we would still show them the preview button. This causes issues for some users who just have a CMS preview URL.
This PR makes it so we only hide the button if there is a content Sync URL but no valid preview URL. This hopefully means that the behaviour for customers with older configs should not be impacted.
> fix: [] preview button incorrectly hidden

- apps/gatsby/src/AppConfig/AppConfig.spec.js
- package.json
We recently discovered a bug where we were not validating all of the url fields in the Gatsby app config component. This adds tests to help ensure that the `onConfigure` callback validates all urls before persisting configuration.
> test: add tests for onConfigure hook in Gatsby app

- apps/gatsby/src/AppConfig/AppConfig.js
- apps/gatsby/src/AppConfig/AppConfig.spec.js
- apps/gatsby/src/Sidebar.js
- apps/gatsby/src/Sidebar.spec.js
Due to some confusing naming that is in place to ensure backwards compatibility for Gatsby users who have not yet moved to Content Sync preview, we accidentally introduced a regression through #569. This happened because we had references to a configuration value called `previewWebookUrl` which was essentially unused. The correct name for the preview webhook url in the config object is `webhookUrl` (this is the confusing backwards compatibility naming.)
This bug is causing a missing url warning to display even if the "Preview Url" field in the config is filled out since that field is mapped to the `webhookUrl` and not the `previewWebhookUrl` config value.
This PR fixes that bug and also removes references to the superfluous config item `previewWebhookUrl`. @Jwhiles sorry for any confusion …
> fix: bug where preview button wouldn't show up for users

- apps/jira/jira-app/src/components/Jira/index.tsx
- apps/jira/jira-app/src/index.tsx
When the user is not authenticated with the jira app installed, we currently leave quite some space under the button as we do not resize the iframe:
We only start the auto resizer once the user has authenticated. With this PR we always start the resizer when the app is rendered in the sidebar.
> fix(jira): start auto resizer when not authenticated

- apps/optimizely/public/index.html
Create React App adds all required script tags itself. This seems like a leftover from when we didn't use CRA
> fix(Optimizely): remove index.js script tag

- apps/gatsby/src/Sidebar.js
- apps/gatsby/src/Sidebar.spec.js
This PR enables a new feature in Content Sync (Gatsby preview), called "eager redirects".
The first time a user previews a content entry they will wait on the preview loading screen for the entire build duration. The second time they press "Open Preview" for that entry, they will be immediately redirected to the frontend where they'll see a loading state in a floating sidebar item (Gatsby Cloud Preview UI).
> feat: Add Gatsby Cloud (Content Sync) eager redirects support

- apps/gatsby/src/Sidebar.js
This PR fixes a bug where we would open a new preview tab and then refresh that tab after a few seconds once Contentful saved entry data. In some cases the refresh would happen after the user was already redirected to the frontend and it looks really buggy.
In this PR we now wait for 5 seconds, checking every 100ms to see if a save happened. As soon as a save happens we open the preview window 1 time and don't need to refresh it.
In the event that somehow Contentful's entry save took longer than 5 seconds (maybe a slow network or a busy day) the old logic is still there to wait an additional 5 seconds after opening the preview window to see if a save happened afterwards and we still need to refresh the window.
In the event that a save happened earlier than that (perhaps hours even), the …
> fix(Gatsby): Check the updated at time repeatedly to wait for a save to happen

- apps/netlify/frontend/src/config.js
- apps/netlify/frontend/src/config.spec.js
The new version of the app would crash with old style configs, because the code expects there to always be an `events` key in the installation parameters. This PR handles the case that the key is missing.
> fix: [EXT-3622] handle existing netlify configs

- apps/netlify/lambda/package.json
because of a revert, lerna can't publish same version again
> fix: Netlify lerna []

- apps/netlify/frontend/src/app/edit-site-modal.js
Less verbose copy; going from `Switch` to `Checkbox`.
> fix: improve netlify CI UI

- examples/vue/.eslintrc.cjs
- examples/vue/.gitignore
- examples/vue/README.md
- examples/vue/env.d.ts
- examples/vue/index.html
- examples/vue/package-lock.json
- examples/vue/package.json
- examples/vue/src/components/LocalhostWarning.vue
- examples/vue/src/locations/AppConfig.vue
- examples/vue/src/locations/Dialog.vue
- examples/vue/src/locations/Entry.vue
- examples/vue/src/locations/Field.vue
- examples/vue/src/locations/Page.vue
- examples/vue/src/locations/Sidebar.vue
- examples/vue/src/main.ts
- examples/vue/tsconfig.app.json
- examples/vue/tsconfig.json
- examples/vue/tsconfig.vite-config.json
- examples/vue/tsconfig.vitest.json
- examples/vue/vite.config.ts
This adds a vue starter template to the examples. 
It was bootstrapped with the VueCLi and uses Vue3 and the composition API + Typescript according to https://vuejs.org/guide/typescript/composition-api.html
> feat: [] add vue as template to examples

- examples/javascript/package.json
- examples/typescript/package.json
The dependencies of our most used templates are currently not pinned. Therefore, a broken patch or minor release is getting installed on the user's machines without having passed any tests. This PR pins the `javascript` and `typescript` dependencies. That way we have more control over what is installed by the CCA users.
Ideally, we'd pin all dependencies except for the two packages within `packages`. Should I do that?
> fix: pin template dependencies

- packages/ecommerce-app-base/src/AppConfig/FieldSelector.tsx
- packages/ecommerce-app-base/src/Editor/SortableListItem.tsx
Fixing two bugs from the forma upgrade. In the ecomerce-app-base the card was added a `display: flex` to aligh the items. 
However in formav4 the styles added to the `Card` component are attached to the outer component and therefore the flex was not working anymore for the card content. : 
Here you can see the difference (the upper one is the fixed version): 
To fix this I added an inner element with the layout styles. 
The other thing was that in the config screen the radio buttons were not aligned correctly:
> fix: [] v4 update fixes

- packages/ecommerce-app-base/src/SkuPicker/SkuPicker.tsx
- packages/ecommerce-app-base/src/SkuPicker/styles.ts
* Made "Load more" button full width
* Adjusted height of save button
> fix: E-commerce app base UI fixes

- apps/mux/package.json
With source maps the bundle becomes too big and the upload fails
Mux only
> fix: disable sourcemaps

- apps/gatsby/src/Sidebar.js
- apps/gatsby/src/Sidebar.spec.js
Before this PR:
https://user-images.githubusercontent.com/14190743/179321438-2db023d4-28ef-4805-a1d2-46b4b1bf80f4.mov
With this PR:
https://user-images.githubusercontent.com/14190743/179321462-31fc55fc-5cc2-4641-a4b6-670520b6b67a.mov
You can see that the experience of opening a preview is between 3 - 8 seconds faster every time a user presses "Open Preview". 🎉
> feat(gatsby): use new sdk.entry.save() api in Previews instead of doing slow/hacky loop to check last save time

- apps/bynder/README.md
- apps/bynder/package-lock.json
- apps/bynder/src/index.js
- package-lock.json
Updated Bynder's compact view from version 2 to 3. This update improves the integration to include [DAT](https://support.bynder.com/hc/en-us/articles/360018559260-Dynamic-Asset-Transformations-DAT-) info from Bynder. It also allows the app to be configured to use various modes the Bynder Compact View allows based on what the user needs. The new mode of `SingleSelectFile` allows a user to select a specific derivative and includes the select file info in the asset response.
This update should be backwards compatible with the previous version of the app.
Also included is a readme file for the Bynder app to include more info about how to setup and use the modes. Marketplace documentation should be updated to reflect this new mode option.
> feat: upgrade bynder from compactview 2 to 3

- .npmrc
- package.json
Prevent people from installing deps with the wrong node or npm versions, so we avoid situations where the deployment pipeline breaks.
> fix: [EXT-3929] version ranges for node and npm

- apps/typeform/frontend/src/AppConfig/AppConfig.tsx
Currently, when the token is invalid, the user only sees an error message but doesn't have the option to sign in again.
Now, whenever we receive a 401 or 403, the local token is cleared and the sign-in is offered to the user.
> fix: clear token when workspace fetching returns 401 or 403 [EXT-3944]

- examples/default-values-backend/README.md
Hi, 
I ran into the issue of creating a contentful backend app through the example but the command using `npm` behaved different from other mentioned commands. Thanks to @andipaetzold, he hinted me on Slack that there was a missing double dash as npm was trying `--example` as an option rather than a positional argument.
> fix(docs): add double dash to treat positional arguments

- examples/blog-post-metrics/README.md
- examples/custom-validation/README.md
- examples/dam-app/README.md
- examples/default-values-backend/README.md
- examples/ecommerce-app/README.md
- examples/editor-assignment/README.md
- examples/home-location/README.md
- examples/nextjs/README.md
- examples/page-location/README.md
- examples/typescript/README.md
- examples/vite-react/README.md
- examples/vue/README.md
Follow-up of #1722
The `npm init` command is wrong in every template. We need to add a `--` for it to work.
This PR also removes additional spaces in the other commands.
> docs: add missing double dash for npm init

- apps/cloudinary/public/index.html
- apps/cloudinary/src/index.js
- apps/cloudinary/src/utils.js
We currently always fetch `https://media-library.cloudinary.com/global/all.js` when the app is rendered. The script is actually only required within the dialog. This PR removes the script from index.html and only loads it within the dialog.
That way we remove an unnecessary request and reduce the number of scripts that need to be executed.
> feat(cloudinary): only fetch media library when required

- examples/nextjs/README.md
- examples/nextjs/package-lock.json
- examples/nextjs/package.json
Updating `next` dependency of the nextjs example.
With 12.2.5 the config location issue is fixed (see https://github.com/vercel/next.js/pull/39514)
> fix: update next

- examples/default-values-backend/.gitignore
- examples/default-values-backend/package.json
- examples/default-values-backend/public/config.js
- examples/default-values-backend/public/index.html
- examples/default-values-backend/yarn.lock
I upgraded `f36-components` to adapt with the current design system as the documentation has moved to the newer version and some components has been replaced e.g: `TextField`. 
That led me to upgrade `parcel` as well because I wasn't able to build anymore (It was an issue with `terser`) but it was resolved in the newer versions of parcel. 
This should resolve the issue #1724
> fix: upgrade parcel and f36 components

- examples/commercelayer/README.md
Adding the readme to explain why this codebase is still useful and where people can find the current code of the marketplace app.
> Add Readme to Commerce Layer example.

- apps/mux/package.json
Do not generate source maps during the build for the mux app
* Builds have been breaking for the last few days with an error message "The uploaded archive was too large once uncompressed." It seems like one of the recent dependency updates pushed the mux app over our 10mb limit.
* Source maps are big, and not really needed for published apps, so the easy fix is just to suppress them during the mux build step
* Failed build example: https://app.circleci.com/pipelines/github/contentful/apps/10255/workflows/77570533-e07b-4f03-834a-a4b73b07c862/jobs/22098
> chore: suppress sourcemap creation during mux build [INTEGRATE-6]

- apps/commercetools/src/api/products.ts
- apps/commercetools/src/config.ts
- apps/commercetools/src/types.ts
The external link for the Commercetools components were being hardcoded with the address for their Western European servers. This uses the api url provided in the config page by the user to get the correct base url for the external link. 
I don't see a way to do this more cleanly with the data we have on hand, but if anyone has an idea, I'm happy to hear it :)
> fix: [] external product link built with provided url (Commercetools)

- apps/color-picker/src/locations/Field.tsx
We currently do not handle the field value being `undefined`.
> fix: handle empty field value

- apps/google-analytics/src/AppConfig.tsx
- apps/google-analytics/src/styles.ts
Adds a deprecation notice to the top of the Google Analytics app configuration screen.
* Google has deprecated several libraries behind the Analytics App and/or is no longer supporting them
* We need to let customers know when they are configuring the app that it will not work for new installations.
* Add a `Note` of type `negative` to make this clear and unambiguous
* Provide a link to relevant documentation / explanation in the help center
* Original ticket: https://contentful.atlassian.net/browse/INTEGRATE-8
* Help center page: https://www.contentful.com/help/deprecation-notice-google-analytics-app/
* Google notice 1: https://developers.google.com/identity/sign-in/web/sign-in
* Google notice 2: https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html
* Google notice 3: …
> fix: add Google Analytics deprecation notice [INTEGRATE-15]

- .github/CODEOWNERS
Adds team-integrations to CODEOWNER file
Team Integrations is moving toward ownership of this repository and thus should also get flagged on PR reviews etc. -- even though Team Extensibility will still carry most responsibility for maintenance.
* Add team-integrations but keep team-extensibliity -- for now treat as coowners.
* https://contentful.atlassian.net/browse/INTEGRATE-19
> Add team-integrations as co-codeowner [INTEGRATE-19]

- .github/pull_request_template.md
Note: This description reflects the proposed new template. 
It's helpful for PR submitters to provide context and background for a change. Using a simple streamlined template encourages that. At the same time we don't want a template that's so heavy that it becomes burdensome.
* Add a template with a few basic sections.
* Include super brief instructions within the template
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
Nothing is normally needed here (can be left empty or removed)
> chore: introduce pull request template [INTEGRATE-7]

- .gitignore
- apps/smartling/frontend/src/Sidebar.tsx
- apps/smartling/frontend/src/__snapshots__/index.spec.tsx.snap
- apps/smartling/frontend/src/index.scss
* We had a few user reports of “bugs” in the Smartling app. Further investigation revealed that there was no bug at all – it’s just that users believed (incorrectly) that the status was wrong
* Ultimately, the users need to visit Smartling to contextualize the status. The “submissions” list does an okay job of providing more granular context but it’s not perfect
* The status experience today is confusing not because the status is wrong but because users don’t really understand what it means in the context of Smartling
* Add an info icon with tooltip to display status details. Use copy directly from [Smartling help page](https://help.smartling.com/hc/en-us/articles/360000546974-Contentful-Connector-Overview) (see "Smartling Status")
* See /apps/smartling/frontend/src/Sidebar.tsx#L121-L142 …
> feature: add info icon that shows status on hover [INTEGRATE-20]

- apps/smartling/lambda/package.json
- apps/smartling/lambda/src/index.ts
In development mode, proxy requests to the running frontend development server rather than to the build
Since the frontend for this app is mounted to the backend (at `/frontend`), the front end is actually served via the build during normal operation.
This is annoying for local development, since you have to build every time before you refresh and see the result of your work.
* Write a simple proxier that forwards requests back to the given URL and path
* Add middleware for `/frontend` (where the app is served from on the backend)
* Also add middleware for `/static` since the development server specifies at relative paths (which get served from `http://localhost:8080/static/...` in local development
* Only use the middlewares in development, otherwise fallback to the same static …
> chore: proxy requests to frontend dev server in development [INTEGRATE-41]

- examples/compare-entries/package.json
- examples/editor-assignment/package.json
- examples/home-location/package.json
- examples/javascript/package.json
- examples/typescript/package.json
Removing duplicate white space characters from the `upload-ci` script in our templates.
There should be only a single white space character between the arguments.
> fix: remove duplicate white space in script

- apps/image-focal-point/src/index.js
Image focal point does not handle multi locale. Lets fix it
As usual, JS `this` property bit us again. `findProperLocale` would not refer to current field and not the asset's
Fixes #1932
> fix(ImageFocalPoint): handle multi locale []

- apps/typeform/frontend/src/Field/TypeFormField.tsx
Addressing customer issue. Loading form and getting bad response leads to execution of `resetLocalStorage` method and dispatching a `RESET` action, which leaves `loading: true` as it is and we're in a deadlock with no opportunity to set it to false.
Reset `loading` property when we reset form state.
> fix: [] Typeform app: reset loading state on state reset

- apps/bynder/src/index.js
Added additional context around when to use SingleSelectFile and the ramifications
Reaction to inconsistencies between the two Bynder selection modes.
This is the cheapest version of this change until better documentation and/or a new feature exists.
N/A
N/A
> Update helper text for MultiSelect

- .contentful/vault-secrets.yaml
Using NPM publish role cause we're also publishing in the CCI file and not only reading npm libraries. This is part of using vault for better security
Previously we were using read-only token which wasn't sufficient with what we needed to do in .cicleci/config.yml tasks esp with deploying after building.
Read more here: https://contentful.atlassian.net/browse/EXT-4121
No need to deploy anything
> chore: change vault key type [EXT-4121]

- .circleci/config.yml
Use ctfl-vault in CI
Finally use vault for CI secrets. This takes care of both publishing to npm & aws deploys for all apps
Read more: https://contentful.atlassian.net/browse/EXT-4121
We will know if it's successful once deploys go through. We should already see any warnings/errors in PR checks
> chore: use vault setup [EXT-4121]

- apps/color-picker/src/locations/ConfigScreen.tsx
We currently limit the number of colors to 25. There is no real reason for it as the 512kB installation parameter limit won't be reached anyway with normal usage of the app.
closes #2037
> fix: remove the 25 color limit

- apps/image-focal-point/src/components/FocalPointDialog/__snapshots__/FocalPointDialog.spec.js.snap
- apps/image-focal-point/src/components/FocalPointDialog/styles.js
Support SVG images in Image Focal Point app.
SVG images are not always scaled properly, so we force proper scaling with 100% width and height + CSS `object-fit: contain` property.
Based on [issue](https://github.com/contentful/apps/issues/2170)
> fix: [] Scale SVG images properly in Image Focal Point app

- apps/google-analytics-4/src/components/FormControlServiceAccountKey.tsx
- apps/google-analytics-4/src/locations/ConfigScreen.spec.tsx
- apps/google-analytics-4/src/locations/ConfigScreen.tsx
When installing the GA4 app, the credentials key file is required. Once the app is installed, the key file field is no longer required (since it should only be populated when replacing the key)
* Conditionally pass an is required value down to note field is required
* Throw an error on save if the field is required but no key file is present
* Add tests for this as well as more for when saving form on already installed app
* Builds directly off of #2195
> GA4: Require key file at install [INTEG-91]

- apps/smartling/frontend/package-lock.json
- apps/smartling/frontend/package.json
Force bumping version for smartling to diagnose building failures
We have had a couple of failures in building of the project in master branch. Most seem due to tag conflicts with smartling app version. This bumps the version to a conflict free one.
> fix(smartling): bump version [EXT-4239]

- .circleci/config.yml
Apps are not deploying due to lerna cryptic error `E404`
From quick research, looks like lerna expects `GH_TOKEN` instead of `GITHUB_TOKEN` env var. We now export the correct var name in circleCI
> fix: learn missing token []

- examples/typescript-github-action/.github/workflows/deploy.yml
Added a filter so Action will only run when commits are done on either master or main branches
> fix: update GHA workflow to only deploy commits to master or main

- apps/google-analytics-4/lambda/.eslintrc.js
- apps/google-analytics-4/lambda/.mocharc.yml
- apps/google-analytics-4/lambda/package-lock.json
- apps/google-analytics-4/lambda/package.json
- apps/google-analytics-4/lambda/src/app.spec.ts
- apps/google-analytics-4/lambda/src/app.ts
- apps/google-analytics-4/lambda/src/services/google-api.spec.ts
- apps/google-analytics-4/lambda/src/services/google-api.ts
- apps/google-analytics-4/lambda/src/types.ts
- apps/google-analytics-4/lambda/test/hooks.ts
- apps/google-analytics-4/lambda/test/mocks/googleApi.ts
- apps/google-analytics-4/lambda/tsconfig.json
* In order to ensure that the app will correctly be able to access analytics data from your account, we need to see that your service key has access to at minimum one account with at minimum one property
* We will also need to use the properties from the property summaries list to display a dropdown to users to specifcy which property to pull data from.
* Build a basic client module that wraps the Google Analytics admin API (https://developers.google.com/analytics/devguides/config/admin/v1)
* For now we have a fake key (the endpoint wont work!) while we wait for the request signing to be completed
* Added sinon to support stubbing API client
* Just a happy (success) path for now
TODO (follow up PR)
* Error handling states. (For now this throws a server error, later we'll separate client …
> Add endpoint to list account summaries [INTEG-93]

- apps/google-analytics-4/frontend/src/locations/ConfigScreen.tsx
> Curly quotes are typically preferred by writers today because they're more legible and flow better with the content. Straight quotes rarely have a place in any type of modern writing or typography, the technique, and art of arranging type.
Also fixes grammatical issue with `realtime` – a common misspelling of `real time` (noun) or `real-time` (adjective). In this case we are using the adjective to describe that the information is communicated or presented at the same time as it happens.
Always use "smart quotes" (a.k.a. curly quotes) in copywriting.
> replace straight quotes with curly (a.k.a. smart)

- apps/google-analytics-4/lambda/serverless.yml
fix dev env issue:
properly reference new handler path after `test` was added – our understanding is that it used to be implicitly in the build/ root dir and now it's nested because there are both `src` and `test` within it after the changes made here:
https://github.com/contentful/apps/blob/4e6d6d98f604953ba027ec2bb94eaf736c98476c/apps/google-analytics-4/lambda/tsconfig.json#L6
> fix lambda-offline conf

- apps/slack/frontend/package.json
The env var in CI was not matching env var used in code. Hardcoding the env var for now when building and will follow up with correct env var usage in staging vs prod
> fix: slack base URL for prod []

- .circleci/config.yml
- apps/slack/frontend/package.json
Separating prod vs staging deployment processes
Previously on https://github.com/contentful/apps/pull/2383, we hardcoded slack env vars which were the same regardless of deployment stage. We now separate env vars depending on the stage (i.e: staging vs prod)
> chore: separate staging vs prod []

- apps/color-picker/src/components/SelectColorButton.tsx
- apps/color-picker/src/locations/Field.tsx
We love the colorpicker tool and it really does work great. However, we have not found a way to remove a selection after it was made (for optional fields). This adds a button to the dropdown if you configure Allow Removal to Yes that allows you to remove your selection.
The approach then looks at that boolean and will then render the `Remove Selection` menu item. 
I do not have any references to the need yet. But please feel free to close this if you would not like your change in your color-picker. We've already created a custom app with my forked code to do it for us. 
This will need a parameter change to the app to add an `allowRemoval` field that is a boolean.
> feat(color-picker): Allow removal of color chosen

- apps/slack/frontend/src/components/NotificationsPanel.tsx
We currently limit Slack notifications to 8, which can easily be hit by enterprise companies. This limit is arbitrary and was selected generally to reduce potential infrastructure costs. We're proposing boosting this limit to 15 notifications, which is expected to produce a nominal increase in infrastructure spend (sub $100/mo) and ease direct customer concerns. Over time, we can evaluate if a higher limited is needed.
I roughly doubled the number of concurrent notifications. No real approach or strategy to this - more an experiment to see if anyone needs more than 15 and why.
https://contentful.slack.com/archives/C043PUB0339/p1675092171997299
> Increase Slack notifications limit to 15

- .contentful/vault-secrets.yaml
Due to failures in releases in master - we should use the correct vault orb as other public repos
semantic-release-ecosystem is the preferred way to go forward.
> chore: add semver []

- apps/jira/functions/package.json
- apps/slack/lambda/package.json
We keep trying to tag an existing tag. Manually update it for now to unblock things
Also changing names to make it easier to manually catch what app is breaking as opposed to just seeing `lambda`
> chore(deploy): fix app names and version to avoid clash []

- package.json
It's becoming impractical to catch up to all git tag conflicts and in turn we can't deploy any changes. We only need publishing for app packages which do not upgrade as often. The conflicts are usually in apps directory which doesn't need any tagging.
Remove lerna git tagging and instead use default lerna publishing.
> chore(lerna): avoid pushing git tags []

- .circleci/config.yml
Fixing slack app URL by removing CRA prefix.
For some reason build process was linking the URL as:
```js
const backendURL = {
REACT_APP_SLACK_BACKEND_BASE_URL: "http://someURL"
}.REACT_APP_BACKEND_BASE_URL
```
Note the difference between the two property names. Any [`REACT_APP_` prefix will be exposed in the build process](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env). This avoids the whole problem
Also adding a cleaner and more efficient deployment process.
> chore: change env vars for react []

- apps/google-analytics-4/frontend/src/components/FormControlServiceAccountKey.tsx
Replacing the link in the Config screen to point to the help center doc instead of pointing to the Google documentation (which is confusing and voluminous). 
[](https://contentful.atlassian.net/browse/INTEG-139)
> Feature/INTEG-139: Replace link to Google documentation with help center link

- apps/google-analytics-4/frontend/src/components/InstalledServiceAccountKey.tsx
- apps/google-analytics-4/frontend/src/services/api.spec.ts
- apps/google-analytics-4/frontend/src/services/api.ts
- apps/google-analytics-4/frontend/test/mocks/api/handlers.ts
- apps/google-analytics-4/frontend/test/mocks/api/mockData.ts
- apps/google-analytics-4/lambda/src/app.ts
- apps/google-analytics-4/lambda/src/lib/errors/middlewares.spec.ts
- apps/google-analytics-4/lambda/src/lib/errors/middlewares.ts
- apps/google-analytics-4/lambda/src/lib/verify-signed-request-middleware.spec.ts
We want to provide actionable feedback to space admins if their service account is missing access to any Google Analytics properties.
I adjusted some of the error handling on the lambda side so we could destructure the data/errors out of the `fetch()` call. Also piggy backed on the current errors we have on the lambda side instead of custom ones, with the exception of the case where the service account user is not added to any analytics dashboards yet, in which case we have a custom error text on the frontend for this.
> Feature/INTEG-86: Add listAccountSummaries Endpoint and Handle API errors

- examples/vue/package.json
We recommend to run `npm start` after the cca script, but there is no start script in the vue template.
> fix: [] change to start script in vue

- apps/wistia-videos/package.json
- apps/wistia-videos/src/components/ConfigScreen.tsx
The Wistia app production deploy was broken because assets were being served from the root (`/static/css...`) instead of a relative path (`./static/css...`). Because app bundles are deployed in a subfolder (under the deploy bundle id on the CDN) this was breaking the app.
* Just add homepage to package.json
* https://create-react-app.dev/docs/deployment/#building-for-relative-paths
*
> Fix serve path on Wistia app []

- apps/google-analytics-4/frontend/package.json
The current upload scripts are just created from the template. We need to adjust them to deploy our frontend to the actual correct production app definition.
* Point the main `deploy` to the production app definition living in the main definitions org
> Set up frontend deploy scripts [INTEG-132]

- apps/google-analytics-4/lambda/package.json
- apps/google-analytics-4/lambda/serverless.yml
[JIRA ticket](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/454?modal=detail&selectedIssue=INTEG-133)
Sets up serverless configuration so that we can deploy GA-4 to production, securely.
Mostly constructed off existing slack/netlify serverless.yml files. In the future, we may implement dynamodb to host some of the secrets we'll use here.
[AWS notes from discussion with Extensibility](https://docs.google.com/document/d/1PQhyT2gnQ5Q-BO19x2xfZlE282KESRiFvjzhT0RsdUE/edit?usp=sharing)
Deployment of deployment configuration files is always a bit more complex, no known concerns at this time though.
> INTEG-133/ ga-4 domain management and API gateway

- apps/google-analytics-4/frontend/.env
- apps/google-analytics-4/frontend/.env.development
- apps/google-analytics-4/frontend/package-lock.json
- apps/google-analytics-4/frontend/package.json
- apps/google-analytics-4/frontend/src/App.tsx
- apps/google-analytics-4/frontend/src/config.ts
- apps/google-analytics-4/frontend/src/index.tsx
Adds observability of unhandled exceptions to the frontend of the GA4 app via @sentry/react SDK
adds and configures the @sentry/react SDK
- https://github.com/getsentry/sentry-javascript/tree/master/packages/react 
- semi-related pitch from Ecosystem Extensibility team: https://contentful.atlassian.net/wiki/spaces/ECO/pages/4141350915/Pitch+-+App+Monitoring
> - [INTEG-163] adds sentry to the frontend of GA4 app

- .circleci/config.yml
Adds `staging` as a new branch name that will kick off the `deploy-staging` circleci workflow.
We are doing this to create a flow to test the apps ga4 deployment in a way that will not break other devs.
> staging branch name

- apps/google-analytics-4/lambda/config/serverless-env.prd.yml
- apps/google-analytics-4/lambda/config/serverless-env.test.yml
- apps/google-analytics-4/lambda/serverless.yml
This is an attempted refactor to handle env vars in a way that will support both development work locally as well as correct env configuration for our prod and test environments.
Currently attempting to branch to a different config.yml file depending on stage name, vs storing all information about every env in the ga4 serverless file.
> env refactor

- apps/google-analytics-4/lambda/package-lock.json
- apps/google-analytics-4/lambda/package.json
- apps/google-analytics-4/lambda/src/app.spec.ts
- apps/google-analytics-4/lambda/src/app.ts
- apps/google-analytics-4/lambda/src/services/google-api.spec.ts
- apps/google-analytics-4/lambda/src/services/google-api.ts
[JIRA Ticket](https://contentful.atlassian.net/browse/INTEG-181)
The Run Report function in GA4 is what gets the GA4 data for a given web page. This endpoint is needed so that we get that data.
Just following the existing pattern of fetching account summaries.
Adds Data GA4 dependency (changes shown in package.json file)
> [INTEG-181] Add lambda proxy endpoint for run-report through data API

- .circleci/config.yml
Adds a new job for notifying sentry of a deploy, to collect and upload artifacts. 
We followed the instructions from [Sentry's documentation on CircleCI integration](https://docs.sentry.io/product/releases/setup/release-automation/circleci/)
[JIRA](https://contentful.atlassian.net/browse/INTEG-171)
> [INTEG-171] add sentry deploy job

- .circleci/prettier-check.sh
The first iteration of ./prettier-config.sh was naive about comparisons: We looked at the diff of file changes between `your_branch` and `origin/master` and ran the prettier verification against that changeset.
This works great if you're branch is up to date, but if your branch is out of date from master it ends up with a much larger changeset which is inaccurate. Forcing rebasing here is just annoying and beyond the intention of this simple script.
What we need instead is a way to look at the changes _your PR introduced_ and ignore anything else.
* Use `git merge-base` to find the common ancestor of your branch and origin/master. This should reliably give us only the files you changed, even if other changes were added to master in the meantime. If your branch is up to date this should …
> Update prettier to use common merge base instead of origin/master

- apps/google-analytics-4/lambda/package.json
This adds a `deploy` command to the ga4 lambda package.json. This will be collected by lerna when the repo is deployed and cause the ga4 lambda to be deployed to prod. 
This is our existing standard for prod deploy infra.
[jira](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/454?modal=detail&selectedIssue=INTEG-133)
🚨 we need to execute `sls create_domain` before merging this to create the r53 record
> Prd deploy command

- apps/google-analytics-4/frontend/tsconfig.json
- apps/google-analytics-4/lambda/tsconfig.json
Sentry uses [releases](https://docs.sentry.io/product/releases/) to match the correct source maps to your events. If you're using TypeScript (tsc) to compile your project, you should configure TypeScript to generate source maps, and use Sentry CLI to create the release and upload the generated source maps.
configure sourcemaps in tsconfig
https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/typescript/
> configure sourcemaps with typescript

- apps/google-analytics-4/frontend/.env
The GA4 frontend needs the correct production url for app configuration to work. Now that we know what that is we can set it.
N/A
[jira](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/454?modal=detail&selectedIssue=INTEG-205)
> INTEG-205 Fix GA4 FE url

- apps/google-analytics-4/lambda/config/serverless-env.dev.yml.example
- apps/google-analytics-4/lambda/serverless.yml
fix failing master build
sentry DSN is not a secret and is not [currently] environment specific. simply put this in serverless.yml with no per-env abstraction
> move sentryDSN out of environment specific variables

- .github/CODEOWNERS
Currently, both teams are auto-assigned for all changes in the `apps` repo. I updated the CODEOWNERS file to be more explicit about which team owns what, so we can reduce some noise.
> chore: more explicit CODEOWNERS file

- apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.ts
fix request signing verification
coerce all headers back to strings to undo what serverless does with headers like `Content-Length`, etc and let the node-apps-toolkit do the header filtering as usual
> fix request signing verification

- apps/google-analytics-4/frontend/src/components/main-app/ChartContent.tsx
- apps/google-analytics-4/frontend/src/components/main-app/analytics-app/AnalyticsApp.styles.ts
- apps/google-analytics-4/frontend/src/components/main-app/analytics-app/AnalyticsApp.tsx
- apps/google-analytics-4/frontend/src/components/main-app/line-chart/LineChart.tsx
This PR adds some styling fixes (as per some suggestions from Hande) to the `LineChart` component as well as the `AnalyticsApp` component in the case of errors or warnings that might arise, as I noticed some unhandled text overflow. 
I am a bit blocked on the more pressing ticket right now hence why this small styling fix PR fix.
- Made the font sizes of the tooltip larger (at least 12px so they are readable). Also removed unnecessary noise within the Tooltip to save space. 
- Hande emphasized that this chart component does not have to be 'perfect' because ideally the user would click the link to view it more extensively in the Google Analytics app. I think this is an interesting point to keep in mind. 
- Handled overflow of error or warning messages by hiding the overflow and adding …
> Add some Chart + Error handling styling fixes

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeCard.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeCard.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypePage.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.tsx
- apps/google-analytics-4/frontend/src/hooks/useKeyService.tsx
- apps/google-analytics-4/frontend/src/types.ts
Space Admins need a way to select which content types will show the GA4 app in the sidebar. They should also be able to specify a slug field and a URL prefix.
The `AssignContentTypePage` component contains the logic for accessing all content types and saving selected content types as installation parameters. The `AssignContentTypeCard` component displays the input fields for each content type (Content type, Slug field, and URL Prefix) and allows users to remove and add content types. Any changes to content types are saved when the user clicks "Install" or "Save" for the app.
Empty state - no content types selected
Content types selected
> [INTEG-169] Render view list for content type, slug, and url path

- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
- apps/google-analytics-4/lambda/src/controllers/apiController.ts
[JIRA TICKET](https://contentful.atlassian.net/browse/INTEG-242)
Fixes bug with run_report throwing parsing errors and updates UI to handle unexpected errors
Issue was with a change that was made with the run_report controller without testing the config page. This fix makes it so that the parsing only occurs when it is called from the sidebar, or anytime the params are passed. 
The config page passes no params because it only checks to see if the run_report endpoint throws some API related error.
> [INTEG-242] Fix incorrect parsing of server errors

- apps/google-analytics-4/frontend/src/apis/apiTypes.ts
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
- apps/google-analytics-4/lambda/src/apiErrorMap.ts
- apps/google-analytics-4/lambda/src/errors/apiError.ts
- apps/google-analytics-4/lambda/src/middlewares/apiErrorHandler.ts
[JIRA Link](https://contentful.atlassian.net/browse/INTEG-209) - Fix error mapper
[JIRA Link](https://contentful.atlassian.net/browse/INTEG-249) - Throw errors instead of modifying the message so that sentry prints out what the actual error was.
- Also update ERROR TYPE MAP to use PascalCasing
- Updates zod error typing to only check for strings in fetchApi validate response instead of specific error types
The two tickets were small enough related tasks to throw into one PR.
Using `constructor.name` did not work for the error map. It still printed out Error, so string literals were used instead
> [INTEG-209 & INTEG-249]  Error types are misnamed (they all say error) and throw generic error e for Sentry

- apps/google-analytics-4/frontend/src/components/main-app/analytics-app/AnalyticsApp.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/analytics-app/AnalyticsApp.tsx
- apps/google-analytics-4/frontend/src/locations/Sidebar.tsx
This PR simply ties the logic of `propertyId` and `contentType` selection to the fetching of analytics chart data within the `Sidebar` itself. 
Pleas refer to the loom video below for an overview of thoughts here. 
https://www.loom.com/share/aec61cf50f204226a53cfff94304ffeb 
You will notice the data is grabbed from the `sdk` parameters directly within the `Sidebar` component. The `Api` instance is also passed down to the `AnalyticsApp` component as per a suggestion on a previous PR by Jim. 
Additionally I re-added a test that was being flaky on Friday with some adjustments.
> Integ 221 sidebar querying should make use of content types and property saved in app installation parameters

- apps/google-analytics-4/frontend/src/components/main-app/analytics-app/AnalyticsApp.styles.ts
fix styling/alignment issue with loading indicator on GA4 sidebar
use css calc to offset absolute positioning and applies 1:1 square shape on rotating element
1. Rectangular aspect ratio can cause unwanted scrollbar jitter and other unwanted side-affects on a rotating object:
2. Alignment was off center:
1. Square aspect ratio:
2. Centered alignment both horizontally and vertically:
> fix CSS for loading indicator in GA4 sidebar

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.tsx
- apps/google-analytics-4/frontend/src/locations/Sidebar.tsx
- apps/google-analytics-4/frontend/src/types.ts
Fix a misalignment on naming of `propertyId` vs `savedPropertyId`. 
Made the necessary adjustments to get things working as needed.
> hot-fix-naming-adjustments

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
1. Removes the splitter at the bottom of the config page
2. Removes the check mark in the service account in the display card 
3. Loading spinner are now consistent
Very small UI changes and fixes. Main purposes is to quickly knock out the tickets to clean up the jira board a little more.
Also made three commits (one per JIRA ticket).
Previous discussions were held. These are very low risk changes and unlikely to cause conflicts.
> [INTEG-260/262/263] Small UI Fixes (Remove checkmark, make loading spinner consistent, remove bottom css splitter)

- apps/google-analytics-4/frontend/src/helpers/signed-requests.ts
- apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.ts
remove query string from request signing verification to ensure deterministic frontend and backend comparison in production serverless environment contexts
- omit query strings from request verification signing
- adds logging so we can revisit once we can verify what format we're receiving in production after passing through aws gateway -> events -> lambda -> node (express)
> remove query string from request signing to work around AWS gateway/serverless differences vs development

- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
[JIRA Ticket](https://contentful.atlassian.net/browse/INTEG-259)
Fixes bug where statuses flash before loading the Configuration Page finishes
https://user-images.githubusercontent.com/124832189/225998498-22fb4bda-9ee9-421d-b5cd-bf1d81725d6a.mov
> [INTEG-259] No more flashing statuses on Service Account Card

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.tsx
Currently when the GA4 app configuration is saved, it removes the app from all sidebar locations. This fix ensures that the current editor interface state for the app is preserved on save.
The fix involves returning the `targetState` in the `handleConfigure` function and setting `targetState` to `currentState`. See more information [here](https://www.contentful.com/developers/docs/extensibility/app-framework/target-state/).
> [INTEG-270] Fix editor interface removal on configuration save

- apps/google-analytics-4/frontend/src/components/main-app/ChartContent.tsx
- apps/google-analytics-4/frontend/src/components/main-app/line-chart/LineChart.tsx
- apps/google-analytics-4/frontend/src/helpers/DateHelpers/DateHelpers.spec.ts
- apps/google-analytics-4/frontend/src/helpers/DateHelpers/DateHelpers.ts
- apps/google-analytics-4/frontend/src/helpers/DateRangeHelpers/DateRangeHelpers.spec.ts
- apps/google-analytics-4/frontend/src/helpers/DateRangeHelpers/DateRangeHelpers.ts
- apps/google-analytics-4/lambda/src/controllers/apiController.ts
- apps/google-analytics-4/lambda/src/services/googleApiService.ts
This PR fixes three primary issues: 
1. Fixes an off-by-one issue with the list of dates appearing on the x-axis of the chart.
2. Orders the dates in ascending order with a simply `orderBys` parameter straight to the google `runReports` api. 
3. Hydrates the missing data gaps returned from the `runReports` proxy. The GA4 endpoint is not including dates for which the metric data is zero (this case most often occurs on weekends). This caused strange gaps in time with how our dates were laid out in the chart. Therefore, I have implemented a way to supplement this data so that our axes are consistently spread.
1. The dates that are provided from the GA4 app were being translated to local strings, sometimes causing the dates to be shifted one day earlier or later. There is no need to translate …
> Integ 230 optimize date mapping for run report data

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertySection.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertySection.tsx
- apps/google-analytics-4/frontend/src/types.ts
INTEG-243 [JIRA Link](https://contentful.atlassian.net/browse/INTEG-243) Include property number (and account number) on property selection dropdown
INTEG-280 [JIRA Link](https://contentful.atlassian.net/browse/INTEG-280) Communicates to user that only GA4 properties are listed but not UA
REVIEWERS PLEASE DO THE FOLLOWING
1. Give your ideas and suggestions to improve UI for the dropdown. I think there's definitely room for potential UI improvements which I think should be done in this PR. However, let me also know if the UI update is out of scope for the sprint/cycle goal
2. Please give feedback on the wording and how the UA/GA4 compatability message is presented
Brings us one step closer to completing our sprint goal
> [INTEG-243/280] Adds account id and property id to dropdown and tells users the app only supports GA4 Accounts and Properties

- apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertySection.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ChartFooter.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ChartFooter.tsx
- apps/google-analytics-4/frontend/src/components/main-app/analytics-app/AnalyticsApp.tsx
- apps/google-analytics-4/frontend/src/utils/pathJoin.spec.ts
- apps/google-analytics-4/frontend/src/utils/pathJoin.ts
- apps/google-analytics-4/lambda/package-lock.json
We had a follow up task from a previous PR to make sure our joining of prefixes to URL slugs was robust (and not just naively joining).
* Join paths irrespective of trailing or forward `/`
* Use the same output for query as for display (assumption: this works?). display matches the output of how GA4 displays page paths.
> feat: handle prefixes and slug joining gracefully [INTEG-256]

- apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.tsx
In the current state, we show an ugly red "invalid" state on the service key entry form before the user even inputs text. 
Spellcheckers also make the input look ugly since it's just a private key.
No input:
Pasting valid key:
* Align isinvalid state with presence of error message and text input
* Clean up unneeded state
* Add explicit tests for error behaviors
No input:
Pasting valid key:
> fix: input is invalid only after user types something [INTEG-293]

- packages/dam-app-base/README.md
The Bynder entry was pointing to the Brandfolder directory.
Fix in the documentation
Just replace the link
None
> docs: Update README.md

- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsApp/AnalyticsApp.tsx
- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsMetricDisplays/AnalyticsMetricDisplay.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsMetricDisplays/AnalyticsMetricDisplay.tsx
- apps/google-analytics-4/frontend/src/helpers/externalUrlHelpers/externalUrlHelpers.spec.ts
- apps/google-analytics-4/frontend/src/helpers/externalUrlHelpers/externalUrlHelpers.ts
The 'Open in Google Analytics' link in the sidebar app should direct a user to Google Analytics where they can drill into the data for the specific page path.
Google Analytics 4 doesn't have an easy way of seeing the data for a specific page path. Our solution is to direct the user to the 'Page and Screens' report section with a pre-populated filter based on the page path. Using the sharable link on this page as a guide, I reconstructed the URL with the proper parameters and encoding. Note that certain aspects of the URL are encoded differently, which is why I abstracted this as a helper function and in some cases, am using a custom encoder function.
This is an example of where the link will take you in Google Analytics
> [INTEG-300] Update sidebar link to navigate to GA4 page

- apps/google-analytics-4/lambda/config/serverless-env.test.yml
We accidentally added the wrong staging domain name, re-adding the right one
> staging env hotfix

- catalog-info.yaml
* We're lacking a metadata file in this repo that integrations with our internal backstage tool
* Alerts for build failures are currently going to the wrong channel
* Add a catalog metadata file to the repo
> chore: [] adding catalog-info and ci-alerts

- apps/google-analytics-4/frontend/src/components/common/HyperLink/HyperLink.spec.tsx
- apps/google-analytics-4/frontend/src/components/common/HyperLink/HyperLink.tsx
- apps/google-analytics-4/frontend/src/components/common/Note/Note.styles.ts
- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsApp/AnalyticsApp.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsApp/AnalyticsApp.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ChartContent/ChartContent.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ChartContent/ChartContent.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ChartHeader/ChartHeader.styles.ts
- apps/google-analytics-4/frontend/src/components/main-app/ChartHeader/ChartHeader.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ErrorDisplay/CommonErrorDisplays.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ErrorDisplay/ErrorDisplay.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ErrorDisplay/ErrorDisplay.tsx
- apps/google-analytics-4/frontend/src/components/main-app/SlugWarningDisplay/SlugWarningDisplay.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/SlugWarningDisplay/SlugWarningDisplay.tsx
- apps/google-analytics-4/frontend/src/components/main-app/constants/noteMessages.ts
- apps/google-analytics-4/lambda/src/services/googleApiUtils.ts
This PR accomplishes the following: 
1. Adds more robust **error handling** for the common errors when rendering the GA4 app in the Sidebar. ⛔ 
2. Fixes some small **UI issues**. ✨ 
I added a component here called the `ErrorDisplay` component that is rendered in place of the Chart itself when an error is thrown. This component handles the anticipated two most common errors, providing an invalid argument somehow which is unlikely (invalid `propertyId`.), or a disabled Data api error. If the error does not belong to one of these error types, then the provided error message is displayed. I added a comment on this code to perhaps adjust the logic to display an actionable default error message if the error is not properly identified by the frontend, instead of the "mystery" error message. …
> Integ 231 improve error handling within analytics app component

- apps/google-analytics-4/LICENSE
Our GA4 repo did not carry the license we typically carry on our public apps. This adds our standard MIT license.
We copied what the other repos do
N/A - may be worth a longer conversation with legal about protections here. We likely need an updated opinion.
N/A
> Create LICENSE file for GA4

- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsApp/AnalyticsApp.tsx
- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsMetricDisplays/AnalyticsMetricDisplay.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsMetricDisplays/AnalyticsMetricDisplay.tsx
- apps/google-analytics-4/frontend/src/helpers/externalUrlHelpers/externalUrlHelpers.spec.ts
- apps/google-analytics-4/frontend/src/helpers/externalUrlHelpers/externalUrlHelpers.ts
- apps/google-analytics-4/frontend/src/types.ts
When a user is viewing GA4 data in the sidebar and clicks on the 'Open in Google Analytics' link, the report they are viewing in GA4 should have the same date filter as the sidebar. This PR adds date filter parameters to the external URL that matches the dates provided to the` run_report` endpoint.
There are some default report date filters (e.g. Today, Last 7 Days, etc.). Instead of using these, I decided to create a custom date filter that exactly matches the dates provided to the `run_report` endpoint so that the dates in the sidebar and in the linked report will be the same.
Example sidebar showing March 20-27 and corresponding GA4 report (you can see the custom date filter in the top right)
> Add date filter to GA4 external link

- apps/google-analytics-4/lambda/src/middlewares/corsConfig.ts
When we introduced the `Content-Type: application/json` here on the frontend (https://github.com/contentful/apps/blob/master/apps/google-analytics-4/frontend/src/helpers/signed-requests.ts#L16-L18) we accidentally violated our CORS rules. As a result, production API requests were broken. (Local development worked fine because we share the same host)
> Access to fetch at 'https://google-analytics-4.ctfapps.net/api/account_summaries' from origin 'https://b922ef2b-607e-4411-9386-597b9fac89a7.ctfcloud.net' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
* Add the missing header to our allowed list
> fix: include content-type in allowed cors headers

- apps/google-analytics-4/frontend/package.json
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.spec.tsx
- apps/google-analytics-4/lambda/package.json
- apps/google-analytics-4/lambda/src/controllers/apiController.ts
- apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.spec.ts
- apps/google-analytics-4/lambda/src/services/googleApi.spec.ts
- apps/google-analytics-4/lambda/src/services/googleApiService.ts
- apps/google-analytics-4/lambda/src/services/googleApiUtils.ts
* We've had a few lint warnings build up in both frontend and lambda over the last few weeks. They are silently passing our lint checks because eslint doesn't exit non-zero for warnings by default
* A few actual code logic problems snuck in as a result of misuse of `any`
* We didn't have a linter at all on the frontend
* Add lint script to frontend
* Enable stricter checks vis `--max-warnings=0` (we tolerate 0 warnings)
* Clean up some GoogleAPI errors that were wrong
* https://eslint.org/docs/latest/use/command-line-interface#--max-warnings
> Enable lint checks and fix errors [INTEG-334]

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.tsx
This PR resolves a bug that was occurring where a user could not return to the config page after install and save any changes to the config without a warning that 'A valid service account key file is required'. 
This is most definitely a patch fix to this issue, but essentially the problem was that we were setting the `validKeyFile` state within the `GoogleAnalyticsConfigPage` only once on original install. This state was never set again to reference a valid key file when the user returns to the config page, because given the security enhancements, we do not reference the key file again on the frontend. Without this state being present, errors were being thrown, some warranted, and some not. 
Follow-up specs to come today!
> Fix save error with valid key presence

- apps/google-analytics-4/frontend/package.json
- apps/google-analytics-4/frontend/src/config.ts
- apps/google-analytics-4/frontend/src/index.tsx
- apps/google-analytics-4/lambda/.env
- apps/google-analytics-4/lambda/package.json
- apps/google-analytics-4/lambda/src/app.ts
- apps/google-analytics-4/lambda/src/config.ts
- apps/google-analytics-4/lambda/src/middlewares/setSentryContext.spec.ts
- apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.spec.ts
- apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.ts
We want to use `getEnvironmentVariable` to actually access our env vars instead of `process.env` so that we have more control of when the application should error out/succeed when accessing environment variables
Also updates the `getEnvironmentVariable` function to cleanup some of the package.json commands to set some of the env vars.
-Make sure all tests run successfully
-Clean up package.json 
-Build should pass successfully
> [Cleanup] Remove process.envs to use the function getEnvironmentVariable instead

- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
When the configuration steps are incomplete or when there exist issues within the config setup, the checklist is currently hidden and the user has to open it manually, an unnecessary extra step asked of the user. Ex:
This checklist should instead render automatically in these cases. 
One adjustment in state was needed for the checklist to render appropriately when the checklist is incomplete or there exist error states.
> Show checks when incomplete or problems with config

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/WarningDisplay/constants/warningMessages.ts
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeRow.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeRow.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/ContentTypeWarning.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/ContentTypeWarning.tsx
This PR fixes some issues with the content type configuration:
- When adding a new content type row, do not show an error state before the user has taken any action
- When there are content type errors, the user should still be able to save the configuration page
Here's a [quick video](https://www.loom.com/share/8a2221b92342447da3060b5ae89a5867) showing current state and how I've addressed these issues in this PR.
- I removed the error state when adding a new row. If there is an empty row when saving, we are now filtering this row out instead of throwing an error
- I removed the validation on save if there is a content type error (e.g. a previously saved content type that has been deleted)
- I updated relevant tests and also removed a `console.log` from another PR
> [INTEG-331 & INTEG-352] Fix content type errors and allow config save

- apps/sap-commerce-cloud/.env
- apps/sap-commerce-cloud/.env.development.sample
- apps/sap-commerce-cloud/.gitignore
- apps/sap-commerce-cloud/README.md
Calls to the SAP server from localhost will only work if `Application Interface Key` header is unset, however we will need this sent in a production environment so SAP knows Contentful is making the requests. This PR adds an environment context between development and production. 
I added `.env.development` that is gitignored and a `.env.development.sample` with the correct env vars for setting the Application Interface Key. On start, the app will default to production unless working in a development (i.e. localhost) context. 
Should monitor the deploy and make sure in the prod space that the Application Interface Key is set correctly.
> Add .env to SAP for environment switching

- apps/google-analytics-4/frontend/src/components/common/HyperLink/HyperLink.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
- apps/google-analytics-4/frontend/src/locations/Sidebar.tsx
This PR fixes an error in the `Sidebar` component when there are no configured content types. Additionally, I fixed two warnings in the `HyperLink` and `DisplayServiceAccountCard` components.
Reproduction steps for `Sidebar` error:
- Install the app but do not configure any content types
- Add the app manually to the sidebar of a content type
- Navigate to an entry of that content type. You should see the error: "Cannot read properties of undefined (reading 'content type id')"
In the `HyperLink` component, there was a warning for "Each child in a list should have a unique 'key' prop"
In the `DisplayServiceAccountCard` component, there was a warning for "div cannot appear as a descendant of p"
> [INTEG-361] Fix sidebar error when there are no content types

- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertySection.tsx
* Button names on the service account details were confusingly located and named in a confusing way (people didn't realize you needed to click "Test" to check the status after making changes in Google
* Loading states were unnecessarily big
* Move "Text" to a little refresh wheel next to status (closer to the action and obvious action)
* Change the "edit" link (inaccurate) to "Replace key" button
* Add line loading skeletons instead of ad hoc mix of spinners and loaders
https://www.loom.com/share/1fb1e4243a184825ba6e9080244664c8
> Cleanup of account detail buttons and loading stages

- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ServiceAccountChecklist.tsx
Fix spacing on service account status checklist
Before:
After:
> fix spacing in GA4 status checklist

- apps/google-analytics-4/frontend/src/helpers/DateRangeHelpers/DateRangeHelpers.spec.ts
Failures in GA4 tests because we are in a new month. 
Update the test to not compare the date diffs, but the actual date number that's extracted from the parser
> [Fix] Date range tests GA4

- apps/sap-commerce-cloud/src/api/fetchProductPreviews.ts
- apps/sap-commerce-cloud/src/components/Dialog.tsx
An experienced developer would want a full URL to fetch their products. This makes the developer experience a lot nicer
Store the data as the full URL, and split on `/products/` when we need the sku ID (this avoids the issue of the sku ID containing `/`)
> feat: stores product url instead of only sku id

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.tsx
When pasting in the service account key for the GA4 app configuration, the validation message `Service account key is valid` was confusing. We are only checking to see if the key is valid JSON, not if the key itself is valid. 
Updated the validation message to `Service account key file is valid JSON` and also updated some content in the Note text. Below are examples of the messages presented to users with valid and invalid JSON service account key files.
> [INTEG-319] Update content for service account key setup

- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
Makes it easier for space admins to copy the service account email address to invite it as a viewer to their Google Analytics account property
Uses f36 CopyButton component
https://user-images.githubusercontent.com/492573/229912071-cd9c626d-b6b5-4a4d-a5f0-64e1684762c2.mov
> adds copy button for service account email

- apps/google-analytics-4/frontend/src/apis/apiTypes.ts
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ChecklistUtils.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ServiceAccountChecklist.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ErrorDisplay/ErrorDisplay.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/ErrorDisplay/ErrorDisplay.tsx
This PR fixes two issues with error handling related to invalid/missing service account keys for the GA4 app configuration.
The first issue is that when there is an invalid service account, the wrong error message was showing. It was showing "unknown error" when it should be showing the service key check as "Service account key is not valid".
Incorrect
Correct
The second issue is when there is a missing service account key error, the API and property checks were showing as "enabled" when they should be showing as "Provide a valid service account key to run this check".
Incorrect
Correct
This PR also adds handling for the "InvalidServiceAccountKey" error and fixes some of the tests in `ServiceAccountChecklist.spec.tsx`.
To reproduce an invalid service account error from Google: 
- Install …
> [INTEG-356-373] Fix invalid and missing service account error handling

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
This addressed a jarring UX from the moment a user clicks "save" or "install" through the post configuration/installation step when we write their secret key to dynamodb.
It wraps both the `onConfigure` and `onConfigurationCompleted` callbacks with a boolean loading state so we can eagerly reset from the `isInEditMode` state, but avoid making eager calls to `verifyAdminApi()` and `verifyDataApi()` which are in a useEffect in the DisplayServiceAccountCard.tsx component (see newly added guard clause)
https://user-images.githubusercontent.com/492573/230084523-7fbef44d-bc49-48c7-b852-7871d4b57cb9.mov
> improve loading status indication onConfigure and onConfigurationCompleted

- apps/google-analytics-4/frontend/src/hooks/useSidebarSlug/useSidebarSlug.spec.tsx
- apps/google-analytics-4/frontend/src/hooks/useSidebarSlug/useSidebarSlug.tsx
When the user updates the slug field value of an entry while viewing the GA4 app in the sidebar, each keystroke was causing a network request to the `runReports` endpoint. This is because we are using the `useFieldValue` hook from the `react-apps-toolkit` to grab that slug field value, so when the hook updated, all subsequent statetful hooks and components updated. 
This was trickier than most classic debounce fixes. We are not debouncing a user typing into an input that is rendered as part of our component tree, for example, but rather trying to debounce a hook's ever changing value and how that value is used. 
I originally began by using the `lodash` `debounce` with the `useSidebarSlug` hook, where we grab the field value, but in any approach that I took to manipulate the hook's value, …
> Add waiting period when updating slug field to avoid a network call on every keystroke

- apps/google-analytics-4/README.md
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.tsx
Update the documentation links in the configuration page and in the README for GA4. Also make some copy changes to the README.
Note: The marketplace app link referenced in the README is broken until we release tomorrow.
> [INTEG-363-365] Update docs link on config page and README

- apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
The "unknown error" state on the GA4 app config page is a bit confusing and unhelpful. 
Make the message more actionable by adding a link to contact support. Also make the Note component "negative" variant to match the badge state.
Before
After
Throw a random error from the lambda or stop the server to get into this state.
> [INTEG-329] Update unknown error on config page

- apps/slack/lambda/serverless.yml
Just noticed that the Slack lambda is still on node 14. We want to have all our lambdas on a (Maintenance) LTS. Node 14 LTS ends on the 30th.
It should only be this one-line change. The lock file is already on v2.
No testing done
No code change
> chore: upgrade Slack to node 16

- apps/google-analytics-4/lambda/src/app.spec.ts
- apps/google-analytics-4/lambda/src/controllers/apiController.ts
- apps/google-analytics-4/lambda/test/hooks.ts
We have a few GA4 lambda tests tests that fail (incorrectly) when run in watch mode, as a result of unneeded hook stubbing.
- Add stubbing for `getServiceAccountKeyFile` returning correctly formatted file.
- Remove stubbing for `getServiceAccountKeyFile` that happens every test to provide more granular and accurate stubbing.
- Quick deprecation fix for sendStatus
google-analytics-/lambda > `npm run test:watch`
- Ensure all tests pass first time as well as subsequent runs
> [INTEG-336] Fix broken tests in watch mode

- apps/google-analytics-4/lambda/package-lock.json
- apps/google-analytics-4/lambda/package.json
- apps/google-analytics-4/lambda/serverless.yml
We have limited lambda deploy space. Adding this configuration will automatically delete versions 3 older from the current.
I used the purpose-built [sls prune plugin](https://www.serverless.com/plugins/serverless-prune-plugin
)
We'll need to deploy this production to test unfortunately. That said, it seems fairly straightforward.
There might be additional IAM roles needed for this to work.
> Auto prune GA4 lambdas

- apps/google-analytics/src/index.tsx
- apps/google-analytics/src/styles.ts
Now that we have officially launched the Google Analytics 4 app, we need to message existing users about the legacy GA app and properly warn them about the deprecation of Google Analytics UA. 
- Added the Note component from forma36 to the Sidebar
- Made it so it persists no matter the circumstance (whether authed or not authed)
1. Log into the Google Analytics (Development) space
2. Verify the deprecation warning shows in the Sidebar area whether authed or non authed
- No breaking changes
> Feature/INTEG-393: Added deprecation notice Note to legacy analytics

- apps/optimizely/src/optimizely-client.js
A customer reported an issue with not being able to see all of their experiments in the dropdown when working on a Variation Container entry. When querying experiments, we had a limit of 500 and the customer had over 500 experiments.
I updated the limit to 1000. I also noticed that the experiments were not sorted in any way, and especially given the number of experiments, I thought it would be helpful to sort the experiments alphabetically in the dropdown.
In addition when researching this bug, I also noticed that there was a limit on the number of projects we were querying. Since we did not explicitly set the number of items per page, it defaulted to only 25. So I was not seeing all of my Optimizely projects in the dropdown on the app configuration page. I updated this to the same limit …
> [INTEG-416] Fix limits for Optimizely experiments and projects

- apps/image-focal-point/src/components/FocalPointDialog/__snapshots__/FocalPointDialog.spec.js.snap
- apps/image-focal-point/src/components/FocalPointDialog/styles.js
We are trying to fix the marker and preview image position, previously marker was able to focus even om the blank area.
After this change marker will not be focused apart from image.
We allowed max width and height for image to take as much space as needed within parent div without changing its aspect-ratio.
> fix: preview and image and marker position[NONE]

- apps/google-analytics-4/frontend/src/helpers/DateRangeHelpers/DateRangeHelpers.spec.ts
- apps/google-analytics-4/frontend/src/helpers/DateRangeHelpers/DateRangeHelpers.ts
There was a reported issue for a GA4 app user in a different locale where the Sidebar app wasn't displaying data and the 'Open in Google Analytics' link was showing the wrong date range in the Google Analytics report.
Initially we were taking the date, converting it to a locale date string, and then reformatting the date string from there. The problem with this is when the locale date format was not in the 'MM/DD/YYYY', our parsing would generate the wrong date string. To fix this, we are now using methods on the JavaScript Date object to get the year, month, and date, rather than formatting to the locale date string first.
If you change your locale (changing your language and region on your device) and test the app, you should see that the startDate and endDate query parameters are …
> [INTEG-426] Fix formatting of sidebar date range

- apps/smartling/lambda/package-lock.json
- apps/smartling/lambda/package.json
- apps/smartling/lambda/serverless.yml
Lambda storage is getting full again. Instead of manual intervention and kicking the can down the road, I'm just adding the same [pruning method that worked for GA4](https://github.com/contentful/apps/pull/3172) in smartling, which is the largest app by storage:
Use the serverless prune extension, saving 3 versions to maintain the same backups as GA4.
We'll want to make sure we watch this post-deploy to make sure the last 3 smartling versions are still standing.
> prune smartling

- examples/javascript/package-lock.json
- examples/javascript/package.json
- examples/typescript/package-lock.json
- examples/typescript/package.json
We need the latest version of app scripts available in the ts and js templates in order to automatically create built app actions in the connected app definition.
> chore: update app scripts versions in js and ts templates

- apps/gatsby/package-lock.json
- apps/gatsby/package.json
- apps/google-analytics/package-lock.json
- apps/google-analytics/package.json
- apps/graphql-playground/package-lock.json
- apps/graphql-playground/package.json
- apps/image-focal-point/package-lock.json
- apps/image-focal-point/package.json
- apps/optimizely/package-lock.json
- apps/optimizely/package.json
- apps/sap-commerce-cloud/package-lock.json
- apps/sap-commerce-cloud/package.json
- apps/sap-commerce-cloud/src/components/CategoryPreviews/__snapshots__/SortableList.spec.tsx.snap
- apps/sap-commerce-cloud/src/components/CategoryPreviews/__snapshots__/SortableListItem.spec.tsx.snap
- apps/sap-commerce-cloud/src/components/ProductPreviews/__snapshots__/SortableList.spec.tsx.snap
- apps/sap-commerce-cloud/src/components/ProductPreviews/__snapshots__/SortableListItem.spec.tsx.snap
Dependabot tried to update the forma-36-tokens package in [this PR](https://github.com/contentful/apps/pull/3140) and the tests failed (see failed job [here](https://app.circleci.com/pipelines/github/contentful/apps/19296/workflows/b8ed0c7c-d35a-496b-baf7-37d70a111e84/jobs/49187)). Specifically, the SAP Commerce Cloud app has snapshot tests that needed to be updated after updating the package.
> fix(deps): bump forma-36-tokens and fix tests

- apps/ai-content-generator/package.json
See [marketplace partner app change for context](https://github.com/contentful/marketplace-partner-apps/pull/29)
Eventually we will remove the entire AI content gen app, for now we are just going to disable to build flow to prod as we get a feel for the proces.
This will prevent AI content gen from deploying, but that's expected.
This will be merged before the MPA change
> [INTEG-475] disable AI content gen build / deploy

- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage/GoogleAnalyticsConfigPage.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/WarningDisplay/WarningDisplay.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeRow.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/ContentTypeWarning.spec.tsx
- apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertyDropdown.spec.tsx
Update the tests to have the `userEvent` creation to occur before the rendering of the component
`https://testing-library.com/docs/ecosystem-user-event/`
Tests and build pass
> [INTEG-389] Moved userEvents creation to occur before render

- .circleci/config.yml
- apps/smartling/lambda/package.json
This is a POC which shows that it is possible to hack together a solution where the unit tests for the repo can be run without triggering a build for the entire repo.
What I do here is simply build the Smartling frontend package as a prerequisite for running the Smartling lambda tests. This allows the tests to run properly without triggering a build for the entire codebase.
~This PR has stripped actual building of the code, that will need to be added as a separate build step~
This should be now addressed.
> Proof of Concept: unit test run without building whole repo

- apps/smartling/lambda/package-lock.json
- apps/smartling/lambda/package.json
Updated packages in Smartling lambda that contained minimist, qs, and simple-git in order to address security vulnerabilities.
**Minimist**
This is a dependency of mkdirp, which is a dependency of TSLint. Although TSLint is deprecated, I decided to bump the version of TSLint to the most recent version for the scope of this PR, which resolves Minimist to version 1.2.8. We can address moving from TSLint to ESLint in follow up work (there are other apps that use TSLint, too).
**qs**
This is a dependency in a few packages. I bumped versions of the following packages: qs, serverless-express, body-parser, express, superagent, and supertest. The security vulnerability is resolved in qs >6.10.3 and backported to some versions (https://github.com/advisories/GHSA-hrpp-h998-j3pp).
**simple-git** …
> [INTEG-445] Chore: Update dependencies for Smartling lambda

- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsMetricDisplays/AnalyticsMetricDisplay.spec.tsx
- apps/google-analytics-4/frontend/src/components/main-app/AnalyticsMetricDisplays/AnalyticsMetricDisplay.tsx
The old google analytics app gave useful short form formatting of page view data from Google Analytics, this PR looks to replicate that behavior in the new GA4 app.
> feat: [INTEG-470] short format for page views

- .circleci/config.yml
- apps/ecommerce/frontend/package-lock.json
- apps/ecommerce/frontend/package.json
- apps/ecommerce/lambda/package-lock.json
- apps/ecommerce/lambda/package.json
- apps/google-analytics-4/frontend/package-lock.json
- apps/google-analytics-4/frontend/package.json
- apps/google-analytics-4/lambda/package-lock.json
- apps/google-analytics-4/lambda/package.json
- package-lock.json
- package.json
We don't want each app responsible for the shared sentry project release, so this moves it from the ad hoc post-deploy phase that lerna runs to a single job in the deploy-prod workflow
> refactored to unified sentry release job

- apps/ecommerce/lambda/package-lock.json
- apps/google-analytics-4/lambda/package-lock.json
- apps/mux/.eslintrc.js
- apps/mux/package-lock.json
- apps/mux/package.json
- apps/slack/frontend/package-lock.json
The purpose of this PR is to remedy a build error found in these following `dependabot` initiated PRs: 
1 . https://github.com/contentful/apps/pull/3301 : @typescript-eslint/eslint-plugin update (changes incorporated into this PR).
2. https://github.com/contentful/apps/pull/3302 : @typescript-eslint/parser update (build error will be fixed within this open PR).
The build error occurring in both PRs, specifically when building the Mux app, is the following error: 
`Failed to load config "react-app" to extend from.`
After investigating the issue, I believe it is due to an incompatibility of the `eslint-config-react-app` package, which is found as part of the outdated `react-scripts` package within the Mux app. Therefore, my first attempt at fixing this issue was simply to update the …
> Fix Mux specific @typescript-eslint Dependabot updates 

- .contentful/vault-secrets.yaml
This adds a policy to utilize our npm vault secrets during our ci/cd pipeline.
> Add npm-read vault policy

- apps/mux/.eslintrc.js
- apps/mux/package.json
- apps/mux/src/components/playercode.tsx
- apps/mux/src/index.test.tsx
- apps/mux/src/index.tsx
- apps/mux/src/locations/config.tsx
- apps/mux/src/util/apiClient.tsx
- apps/mux/src/util/types.tsx
The purpose of this PR is to follow-up the addition of an .`eslintrc.js` file to the Mux app code (see [this](https://github.com/contentful/apps/pull/3336) PR for context there.), with an extension of `eslint` itself. Therefore enforcing recommended `eslint` rules. 
I wanted to be as minimally disruptive to active code as possible, while also providing basic `eslint` guidelines and enforcment (and not ignoring too many rules).
Therefore in files and on specific lines you will notice I disabled `eslint` rules where I felt that changing the code may cause unintended consequences.
I also ignored rules that I felt were rampant throughout the code, and could not be safely adjusted without unforeseen consequences. 
Open to any and all suggestions/opinions on the calls I made here! 
Test that …
> Extend linting to mux app

- apps/graphql-playground/package-lock.json
- apps/graphql-playground/package.json
- apps/sap-commerce-cloud/package-lock.json
- apps/sap-commerce-cloud/package.json
- apps/wistia-videos/package-lock.json
- apps/wistia-videos/package.json
This PR resolves two issues found [this](dependabot/npm_and_yarn/contentful/field-editor-test-utils-0.17.3) dependabot PR: 
1. This fixes the test error that occurs within the `graphql-playground` app. 
2. This reverses the dependabot incurred downgrade found in the `wistia` `package.json` with the `field-editor-test-utils` package. 
**To clarify, this PR includes the changes from the original dependabot PR, but with the appropriate changes made.**
1. In order to resolve the test error found in the PR, I installed the latest version of the `field-editor-test-utils` package within the `graphql-playground` `package.json`. This update resolved the peer dependency issues. I would prefer to test that everything is as it should be locally with the `graphql-playground` app, however the local …
> fix: Dependabot/npm and yarn/contentful/field editor test utils 0.17.3 wistia downgrade

- .circleci/config.yml
- package.json
Apps don't deploy to staging and production because the --since option doesn't work once the PR is merged. So a separate command is needed at the root level for the apps to deploy
> [Fix] Deploy staging and prod works now

- .circleci/config.yml
* The `publish-packages` step in our build requires git write privileges in order to push new versions of our packages as git tags to our repo
* Our current configuration of that step missed a key configuration, which meant instead of using the predefined `GH_TOKEN` github token, which has these write permissions, the publish package command was falling back to using deploy keys (https://github.com/contentful/apps/settings/keys)
* Deploy keys were an okay workaround, since we had a read/write key defined, but the deploy step frequently broke when folks inadvertently introduced read only deply keys
* Use the `vault/configure-lerna` orb
* The key difference is that it sets up the origin URL to use the GH_TOKEN explicitly via this command:
```
git remote set-url origin …
```
> Use the config-lerna orb to use the correct GH token for package publishing

- .github/CODEOWNERS
Two new apps were added in the repo recently, adding `team-integrations` as the code owner for both.
> chore: Update CODEOWNERS with new apps

- apps/ecommerce/lambda/package-lock.json
- apps/ecommerce/lambda/package.json
- apps/ecommerce/lambda/src/controllers/apiController.ts
- apps/ecommerce/lambda/src/controllers/shopifyController.ts
- apps/ecommerce/lambda/src/helpers/shopifyAdapter.ts
- apps/ecommerce/lambda/src/middlewares/verifySignedRequests.ts
- apps/ecommerce/lambda/src/routers/shopifyRouter.spec.ts
- apps/ecommerce/lambda/src/routers/shopifyRouter.ts
- apps/ecommerce/lambda/src/types.ts
For the e-comm stack work, it's necessary to connect our lambda to a real Provider to emulate customer needs. 
This PR connects to our Partner Shopify account for testing against our test shop data. 
- Was trying to use `shopify-api-js`, but that ended up being way too much overhead and requiring user-based authentication with OAuth, we might revisit this down the road, but it will depend on the UX for space admins adding Shopify as an integration (i.e., do we want them to authenticate the same way we do with GA4, through a dialog, or just with access token/domain)
- Switched to https://shopify.dev/docs/custom-storefronts/additional-sdks/js-buy since it's lighter weight and requires less for authentication
- Can test with the following Postman collection if you comment out L30 in …
> Feature INTEG-540: Connect to and retrieve products from Shopify

- examples/hosted-app-action-templates/javascript/contentful-app-manifest.json
- examples/hosted-app-action-templates/typescript/contentful-app-manifest.json
NB: the relative path with `./` is on purpose, I think it makes it more clear to what we are referring. 
The buildscript should use `resolve` to resolve the  relative path (which it does right now), has been tested
> chore: add entryFile-property to app-manifest [EXT-4550]

- .circleci/config.yml
- package.json
Fixing production deploy, currently it is breaking because of installing too many packages at once.
Trying to reduce the concurrency.
Using cache in circle ci.
> fix: prod deploy build

- apps/ecommerce/frontend/src/components/Config/ConfigBody.tsx
- apps/ecommerce/frontend/src/components/Config/ConfigPage.tsx
- apps/ecommerce/frontend/src/helpers/mockValue.ts
- apps/ecommerce/frontend/src/hooks/useExternalResource.tsx
- apps/ecommerce/frontend/src/types.ts
- apps/ecommerce/lambda/public/shopify/config.json
- apps/ecommerce/lambda/src/controllers/shopifyController.ts
- apps/ecommerce/lambda/src/mocks/resourceLink.mock.ts
- apps/ecommerce/lambda/src/routers/shopifyRouter.spec.ts
- apps/ecommerce/lambda/src/types.ts
refactors shopify app installation parameter to be "shopName" instead of "apiEndpoint"
- also adds placeholder to `ParameterDefinition` interface
> refactors shopify app installation parameter to be "shopName" instead of "apiEndpoint"

- apps/ecommerce/frontend/src/components/Dialog/DialogBody.tsx
- apps/ecommerce/frontend/src/components/Dialog/DialogHeader.tsx
- apps/ecommerce/frontend/src/components/Dialog/ResourceCard/ResourceCard.styles.ts
- apps/ecommerce/frontend/src/components/Dialog/ResourceCard/ResourceCard.tsx
- apps/ecommerce/frontend/src/components/Dialog/ResourceList.tsx
- apps/ecommerce/frontend/src/components/Dialog/ResourceSelectionDialog.tsx
- apps/ecommerce/frontend/src/components/Field/Wrappers/MultipleResources.tsx
- apps/ecommerce/frontend/src/components/Field/Wrappers/SingleResource.tsx
- apps/ecommerce/frontend/src/helpers/resourceProviderUtils.ts
- apps/ecommerce/frontend/src/types.ts
- apps/ecommerce/lambda/src/helpers/shopifyAdapter.ts
- apps/ecommerce/lambda/src/types.ts
Content editors needs to be able to select a product from the picker and save that selection to an entry.
In the product picker I added:
- Hover state for the displayed resources
- Selection state for when a resource is clicked
- Header updates to reflect the number of items selected
- On save, the dialog closes and the field is then updated with the selected item
This works for the single reference field as well as a multiple reference field. For multiple reference, it works similar to the native reference field where items selected are just appended to the field.
For now, there is still the "Add content" button as well as the "Add a product" button until we have our design sync and decide on what we want for that.
Single reference field showing hover on a card:
Multiple reference field …
> Select a resource in the product picker

- examples/hosted-app-action-templates/javascript/build-actions.js
- examples/hosted-app-action-templates/typescript/build-actions.js
If you try using node builtin libraries, current setup wont work. This fixes it
For some reason esbuild strips out `node:` in imports. E.g: `import process from 'node:process'` transforms to `import process from 'process'`. Using https://esbuild.github.io/api/#external to avoid this.
Run `cca test-app --typescript --action`, edit the `actions/example.ts` file by import a built-in  and then run `npm run build-actions`. The output action file should not strip out `node:` prefix
> fix(HostedActions): allow using node libs []

- apps/ecommerce/providers/shopify/src/app.ts
- apps/ecommerce/providers/shopify/src/controller/MetadataController.ts
- apps/ecommerce/providers/shopify/src/controller/ResourceTypeController.ts
- apps/ecommerce/providers/shopify/src/handlers/ShopifyHandler.ts
- apps/ecommerce/providers/shopify/src/helpers/ClientHelper.ts
- apps/ecommerce/providers/shopify/src/services/metadata/MetadataService.ts
- apps/ecommerce/providers/shopify/src/services/resourceType/ResourceTypeService.ts
- apps/ecommerce/providers/shopify/src/types/types.ts
Fill out the logic to hit the Shopify API for a single products, and a list of products.
DOES NOT HANDLE PAGINATION, QUERYING, NOR PAGINATION
This backend logic is not yet hooked into the proxy. This will be done in a separate PR where that PR will delete all the business Shopify API logic in the proxy and instead forward those requests to this Provider backend
Use postman to get data back (link to postman collection: https://elements.getpostman.com/redirect?entityId=27394115-97ca61c3-8f3b-4b81-869f-0432b6914a13&entityType=collection)
SINGLE
MULTIPLE
None
None
> [INTEG-646] Shopify provider business logic

- apps/ecommerce/frontend/package-lock.json
- apps/ecommerce/frontend/src/components/App/Field/SingleResource/SingleResource.spec.tsx
- apps/ecommerce/lambda/package.json
Builds won't deploy and work because of some limit lambdas imposes on header sizes (5120bytes)
Remove deploy command until we have a real solution for this. Real solution will bring back this deploy command.
Builds pass 
None
None
Builds should start working again
> [INTEG-677] Remove deploy command from the ecomm lambda to have builds running again

- apps/ecommerce/frontend/src/components/App/Dialog/ResourceCard/ResourceCard.tsx
- apps/ecommerce/frontend/src/components/App/Field/MultipleResources/MultipleResources.tsx
- apps/ecommerce/frontend/src/components/App/Field/ResourceCard/ResourceCard/ResourceCard.tsx
- apps/ecommerce/frontend/src/components/App/Field/SingleResource/SingleResource.tsx
Small fixes to have the `Add Product` button logo and the `ResourceCard` badges rendering correctly after we merged in this PR: https://github.com/contentful/apps/pull/3720
Note: Future work will consolidate the UI display mapping and fetching, this just gets these components back to their working state. These are the elements that this PR fixes:
> Fix ecom button logo and badges

- .github/CODEOWNERS
With recent shifting around of team responsibilities, it became clear that the old CODEOWNERS file was out of date and incorrect. 
* Refactor so @contentful/team-integrations owns everything by default, @contentful/team-integrations can specify specific packages they own as exceptions
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> Update CODEOWNERS to reflect correct ownership

- packages/ecommerce-app-base/package-lock.json
- packages/ecommerce-app-base/package.json
Older version of @contentful/app-sdk had a type error that was fixed in version 4.21.1. **This is breaking the master build.**
* Upgrade to 4.21.1 app-sdk
* Upgrade contentful-management and @contentful/rich-text-types to latest
* https://github.com/contentful/ui-extensions-sdk/pull/1549
> fix: update @contentful/app-sdk to fix type error

- .circleci/prettier-check.sh
Currently, any changed files (added, modified, or deleted) are being included in the prettier check. Adding a filter to exclude deleted files from the prettier check to avoid getting an error of `No files matching the pattern were found` on this check. Also removed the `HEAD` from this line since we are already getting that in the line above for `MERGE_BASE`.
Fun fact, using the lowercase `d` in the filter excludes that status whereas an uppercase `D` includes that status in the filter (https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203).
> Fix: Filter out deleted files in prettier check

- apps/gatsby/src/AppConfig/AppConfig.js
The Gatsby App has an optional field , authToken for private sites, but if the site is using [Content Sync](https://www.gatsbyjs.com/docs/conceptual/content-sync/), adding said token to the app's config settings will cause errors with the preview feature (which Gatsby has [acknowledged](https://support.gatsbyjs.com/hc/en-us/articles/360056047134-Add-the-Gatsby-Cloud-App-to-Contentful#:~:text=(Optional)%20Fill%20in%20the%20input%20labeled%20%E2%80%9CAuthentication%20Token%E2%80%9D%20with%20an%C2%A0authToken.%20This%20is%20necessary%20for%20Gatsby%20Preview%20instances%20that%20require%20the%20user%20to%20login%20before%20they%20can%20view%20the%20Preview.%20(Note%20that%20this%20doesn%27t%20yet%20work%20when%20using%20Content%20Sync))).
As long as this issue remains unfixed, the helper …
> fix: improved clarity for gatsby app helper text

- apps/mux/src/index.tsx
By default `MuxUploader` will render a drop, since we made our own drop with `MuxUploaderDrop` use the `noDrop` property to prevent `MuxUploader` from rendering the default one
Current bug in Mux Uploader shows 2 drop areas
There was a slight change between `beta.8` and `beta.9` that included `MuxUploader` rendering a drop area by default.
See docs: https://docs.mux.com/guides/video/mux-uploader
None
> Fix MuxUploader double drop area

- apps/gatsby/package-lock.json
To fix the currently broken builds related to gatsby's package-lock
```
lerna ERR! npm ci exited 1 in '@**********/gatsby-preview'
lerna ERR! npm ci stderr:
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
```
Update package-lock in gatsby app
Build passes 
None 
None
Standard
> [Fix-Build] Update gatsby package-lock to fix builds

- apps/ai-content-generator/tsconfig.json
- apps/ai-content-generator/vite.config.ts
This allows us have easy-to-read imports from a variety of locations in the codebase while keeping the path descriptive
eg. `import Slider from '@components/common/slider'` vs `import Slider from '../../../common/slider'
> updates ts and vite configs with aliases

- apps/google-analytics-4/frontend/src/components/main-app/constants/noteMessages.ts
- apps/google-analytics-4/frontend/src/hooks/useApi.ts
- apps/google-analytics-4/frontend/src/locations/Sidebar.tsx
When the GA4 app is programmatically installed without the necessary app installation parameters, the Sidebar app was throwing errors for a missing `serviceAccountKeyId` and/or a missing `propertyId`. 
This PR handles checking whether these installation parameters exist, and then displaying a helpful message if they don't exist rather than throwing an error and not rendering anything in the Sidebar. The Sentry errors we are seeing should be resolved by this.
Change the values of the app installation parameters in the Sidebar component to undefined to see the Note in the Sidebar.
> Fix [INTEG-529]: Display Sidebar Note when GA4 installation params are missing

- apps/slack/frontend/src/useConnect.ts
- apps/slack/lambda/lib/clients/slack.ts
- apps/slack/lambda/lib/errors/conflict.ts
- apps/slack/lambda/lib/errors/exception.ts
- apps/slack/lambda/lib/errors/not-found.ts
- apps/slack/lambda/lib/errors/slack-error.ts
- apps/slack/lambda/lib/errors/unprocessable-entity.ts
- apps/slack/lambda/lib/helpers/getWorkspaceId.ts
- apps/slack/lambda/lib/middlewares/request-verification/contentful-request-verification.ts
- apps/slack/lambda/lib/routes/auth-token/controller.ts
- apps/slack/lambda/lib/routes/auth-token/repository.test.ts
- apps/slack/lambda/lib/routes/auth-token/repository.ts
- apps/slack/lambda/lib/routes/events/service.ts
- apps/slack/lambda/lib/routes/messages/controller.ts
- apps/slack/lambda/lib/routes/workspaces/repository.ts
- apps/slack/lambda/lib/utils.ts
This PR adjusts the following: 
1. Adds more meaningful messages and identifiers to errors thrown within the Slack app lambda. 
2. Fixes [this](https://contentful.atlassian.net/browse/INTEG-652) issue. 
Also as you will notice, lots of trailing commas are added as per the prettier commit hook. I am not sure if this is standard, but I have trouble reverting the changes locally given the commit hook does them, though I could via github if they are an issue. Please let me know your thoughts!
1. This PR adjusts the `Exception` class within the API to handle the addition of identifying information like `environmentId` and `spaceId`. Additionally, more meaningful error messages are provided when the errors are manually thrown. 
2. This was a small issue where a snackbar was rendering and …
> Improve error logging in Slack app and fix bug

- apps/aws-amplify/package.json
- apps/brandfolder/package.json
- apps/color-picker/package.json
- apps/commercetools/package.json
- apps/dropbox/package.json
- apps/ecommerce/frontend/src/components/App/Dialog/ResourceSelectionDialog/ResourceSelectionDialog.spec.tsx
- apps/ecommerce/frontend/src/components/App/Field/ResourceField/FieldFallback/FieldFallback.spec.tsx
- apps/ecommerce/frontend/src/components/App/Field/ResourceField/FieldJsonEditor/FieldJsonEditor.spec.tsx
- apps/ecommerce/frontend/src/components/Config/ConfigPage/ConfigPage.spec.tsx
- apps/frontify/package.json
- apps/gatsby/package.json
- apps/google-analytics-4/frontend/package.json
- apps/graphql-playground/package.json
- apps/image-focal-point/package.json
- apps/mux/package.json
- apps/netlify/frontend/package.json
- apps/saleor/package.json
- apps/wistia-videos/package.json
Have our `staging:deploy` script actually do something and point and deploy to an actual app in our Dev & Testing org.
Also completed one part of 3 movements in improving our infrastructure https://contentful.atlassian.net/browse/INTEG-873.
Create staging apps in the Apps - Dev & Testing org.
Update scripts to point to those app ids
Check app ids from package.json versus the [Apps marketplace place](https://app.contentful.com/account/organizations/6xdLsz6lCsk0yPOccSsDK7/apps)
Deployment should succeed
Could break if there are mismatched app ids
Standard
> [INTEG-875] Point apps deploy:staging to actual apps in the dev & testing orgs

- apps/ai-content-generator/src/components/app/dialog/common-generator/field-selector/FieldSelector.tsx
- apps/ai-content-generator/src/components/app/dialog/common-generator/field-selector/field-list/EntryFieldList.tsx
- apps/ai-content-generator/src/hooks/dialog/useSupportedFields.ts
- apps/ai-content-generator/src/utils/dialog/common-generator/field-selector/fieldSelectorHelpers.ts
- apps/ai-content-generator/src/utils/dialog/supported-fields/supportedFieldsHelpers.ts
This PR updates the logic for which fields will be shown in the source and output fields. 
- The source field should show: Short text, long text, and rich text fields that have content in the field
- The output field should show: All Short text, long text, and rich text fields 
Additionally, I also updated these field selectors so that field id is saved rather than field name because field name is not unique.
Note that there are some quirks regarding whether a field is localized that will be addressed in another PR.
Tested with fields of supported types and ensured that fields of different types were not listed as options.
> [INTEG-871]: Update filtering for source and output field selectors

- .circleci/config.yml
More than half our deploys are failing due to our Install Dependency step (staging) or our Bootstrap step (prod) running into `Too long with no output (exceeded 10m0s): context deadline exceeded`.
Even successful builds come pretty close to 10minutes but just finished in time.
So it's very likely that those failed deploys are actually still working and just needed more time. This wasn't a problem before when we had less apps, but now it's an issue since these are dependency install steps for ALL the apps in the repo.
Just double the standard default 10m wait time to 20m.
Build passes more often and no longer fails with `Too long with no output (exceeded 10m0s): context deadline exceeded`
None
None
Standard
> [INTEG-895] Exceeded Context timeout fix

- apps/ai-content-generator/src/configs/prompts/contentPrompt.ts
The old content prompt would output weird extra data
Update the prompt with a bit more constraints (courtesy of Gavin)
Try generating some content from a title or an existing blog post. It should be in a normal text style now
> fix: content generation now uses gavin's new prompt

- apps/ai-content-generator/package.json
This is the real deal, the crème de la crème, the one, the PR to finish it all!
We want to verify our code can deploy to prod with the rewrite. But we only want to show the V1 UI while we are finishing up V2 work
After the deploy saga, we have hit our final road block: the name of our access token. Changing our token's name from `CONTENTFUL_ACCESS_TOKEN` to `CONTENTFUL_CMA_TOKEN` should be the last change needed to deploy.
_I sure hope it is..._
> chore: fixes token name in aicg

- packages/ecommerce-app-base/src/AppConfig/OrchestrationEapNote/OrchestrationEapNote.tsx
[JIRA TICKET](https://contentful.atlassian.net/jira/software/c/projects/MONET/boards/384?modal=detail&selectedIssue=MONET-1373)
This PR changes the copy on app configuration screen for Shopify and Commercetools apps. 
See the screenshot below to see how it looks like.
> chore: change copy [MONET-1373]

- apps/ai-content-generator/src/components/app/sidebar/SidebarButtons.tsx
- apps/ai-content-generator/src/components/app/sidebar/feature-button/FeatureButton.tsx
When a user edits a field and launches the ai content generator, if it has not auto-saved yet we are using old data
We decided to go with the route of least resistance here and force a save before launching the modal.
Edge cases:
- We are handling if a user spams the button
- We are handling if a user clicks one button and a different one before the save completes
- We are handling if the save fails for any reason
1. Edit the entry
2. Click a button
3. Verify the spinner appears and then the modal launches
___
1. Don't edit anything
2. Click a button
3. Verify it opens instantaneously 
___
1. Edit the entry
2. Spam click the button
3. Verify nothing bad happens
___
1. Edit the entry
2. Click two different features
3. Verify nothing bad happens
> fix: save content before launching ai content generator

- apps/aws-amplify/package.json
There's a bug in extensibility-api right now where if the same app action id is included for two different org ids / app definition ids, the most recent deploy overwrites the app action it does not own instead of creating a new one.
* Disable "staging" deploy so that we have only one app action deploy active
> Disable staging deploy to prevent race condition in hosted app action deploys

- apps/ecommerce/frontend/package-lock.json
- apps/ecommerce/frontend/src/components/Config/ConfigPage/ConfigPage.tsx
This PR fixes an [error](https://app.circleci.com/pipelines/github/contentful/apps/22390/workflows/5bd63496-c0aa-44bd-a542-8326c0764b5c/jobs/63503) thrown with the accompanying dependabot update within ecomm. The new update caused a type error, and frankly because of the deprecation of ecomm, I made adjustments that passed the build, but nothing beyond that. The app still renders locally. 
This fixes this PR: https://github.com/contentful/apps/pull/4300
> Fix(deps): Dependabot/npm and yarn/contentful/default field editors 1.4.10

- apps/google-analytics-4/frontend/package-lock.json
- apps/google-analytics-4/frontend/package.json
- apps/google-analytics-4/frontend/src/index.tsx
This PR resolves a dependabot build issue found in the GA4 app, in [this](https://github.com/contentful/apps/pull/4350) PR. The dependabot update was updating `@sentry/tracy` package, which caused a type error in the build. This package is actually deprecated and no longer necessary, as its functionality is encapsulated by the Sentry react sdk. 
I have updated the file where the type error is being thrown by adjusting the import. Additionally have removed the `@sentry/tracing` package entirely as its antiquated now. 
Confirmed that the app still works as before. 
Sentry React package: https://www.npmjs.com/package/@sentry/react 
Sentry Tracing package deprecation info: https://www.npmjs.com/package/@sentry/tracing
> Fix (dependabot): Remove deprecated sentry tracing package

- apps/ai-content-generator/src/components/app/dialog/common-generator/field-selector/SourceAndFieldSelectors.tsx
- apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/generated-text-panel/GeneratedTextPanel.tsx
- apps/ai-content-generator/src/components/common/text-counter/TextCounter.tsx
We added character count validation on a [previous PR](https://github.com/contentful/apps/pull/4356). This is a quick follow up to display the correct character count, supporting maximum and minimum allowed number of characters. This PR also fixes a bug where the Apply button wasn't disabled if the character count was invalid immediately after generating content.
Below are the three states of the warning:
We are showing different messages based on whether there is a minimum, a maximum, or both. I used the same language shown on the field editor.
Set up some fields with various character limits.
> [INTEG-993] Display message for min character validation

- apps/salesforce-commerce-cloud/src/components/dialog/ProductPreview.tsx
- apps/salesforce-commerce-cloud/src/components/dialog/ProductSearchResults.tsx
- apps/salesforce-commerce-cloud/src/components/dialog/SearchBar.tsx
- apps/salesforce-commerce-cloud/src/components/field/ItemCard.tsx
This PR fixes a TypeError that a customer encountered while using the Salesforce app. See the thread [here](https://discord.com/channels/1030176999471321129/1111352040413724712/1138094064558952478). 
I had difficulty replicating this issue locally, and I believe it is because of variance in images being provided as part of a product object. Locally these images are provided, but I am making the assumption, in this first attempt at resolving the customer's issue, that images are not always guaranteed. This can also be further supported by the way the code was setup to conditionally render the images if they exist. Unfortunately the code did not originally account for an undefined image object, so I have added several safeguards here. 
I can also add optional chaining to the `product` …
> Resolve Salesforce app TypeError

- apps/wistia-videos/src/components/Field.tsx
When the videos have a long name the text overlaps the next column, creating a bad editor experience. Applying the correct styles to the paragraph will create an ellipsis when the name is long.
Apply correct styles to the Paragraph on the Card component.
Connect Wistia App with a Contentful Environment. Check for videos with long names, which should be visible with a ellipsis.
> Update Field.tsx on Wistia App

- apps/ai-content-generator/src/components/config/ConfigPage.tsx
- apps/ai-content-generator/src/components/config/model/Model.tsx
- apps/ai-content-generator/src/configs/gptModels.ts
- apps/ai-content-generator/test/mocks/sdk/utils/generateRandomParameters.ts
Follow up PR for updating copy on the Configuration Page, this PR updates the options listed for the models. 
We are removing any date-specific models and instead adding support for the 4x context models. The names in the dropdown are now listed as they should be according the OpenAI branding guidelines. The default selection is GPT-3.5. I added a follow up task to better handle validation on the Config Page in general, so this will cover the case where a user had previously selected a date-specific model that we have now removed.
Navigate to the Config Page and you should see the new options listed.
> [INTEG-1040] Update supported GPT models on config page

- apps/ai-image-generator/frontend/actions/aiig.ts
- apps/ai-image-generator/frontend/build-actions.js
Experience package PR relies on this change https://github.com/contentful/experience-packages/pull/2234. This is so that we can deal with an array of images and return them so we can continue developing the modal
Hardcode urls
Tested it in the user_interface override - aka local development
None
None
Standard
> [INTEG-1064] HAA adds 3 more hardcoded urls and return it as an array

- .gitignore
- packages/ecommerce-app-base/package-lock.json
- packages/ecommerce-app-base/package.json
- packages/ecommerce-app-base/src/Editor/Field.tsx
- packages/ecommerce-app-base/src/Editor/IntegrationContext.tsx
- packages/ecommerce-app-base/src/index.tsx
Prepare `ecommerce-app-base` for future changes
Introduce an Integration (React) context to avoid excessive prop drilling through the code in the future.  
Allow react hooks usage by migrating the Field component to a functional component.  
This is exclusively a cleanup up task for future work on the codebase. No changes to the public interface have been intorduced.
For now this is only tested with realtive-deps on the shopify app
> feat: introduce integration context [MONET-1338]

- apps/ai-image-generator/frontend/src/components/config/ApiKeySection/APIKeySection.stories.tsx
- apps/ai-image-generator/frontend/src/components/config/ApiKeySection/APIKeySection.tsx
- apps/ai-image-generator/frontend/src/components/config/ApiKeySection/ApiKeySection.spec.tsx
- apps/ai-image-generator/frontend/src/components/config/ConfigPage/ConfigPage.spec.tsx
- apps/ai-image-generator/frontend/src/components/config/ConfigPage/ConfigPage.tsx
- apps/ai-image-generator/frontend/src/components/config/CostSection/CostSection.spec.tsx
- apps/ai-image-generator/frontend/src/components/config/CostSection/CostSection.stories.tsx
- apps/ai-image-generator/frontend/src/components/config/CostSection/CostSection.styles.ts
- apps/ai-image-generator/frontend/src/components/config/CostSection/CostSection.tsx
- apps/ai-image-generator/frontend/src/components/config/DisclaimerSection/DisclaimerSection.spec.tsx
- apps/ai-image-generator/frontend/src/components/config/DisclaimerSection/DisclaimerSection.stories.tsx
- apps/ai-image-generator/frontend/src/components/config/DisclaimerSection/DisclaimerSection.tsx
- apps/ai-image-generator/frontend/src/components/config/Hyperlink/Hyperlink.tsx
- apps/ai-image-generator/frontend/src/constants/configPageCopies.ts
This PR adds two more sections to the config page. The sections are not really interactive (aside from being links) so there is little logic added here. 
I added the `CostSection` and the `DisclaimerSection` as per [these](https://www.figma.com/file/MyzNyHqDo1vjyAVGCMD852/AI-Images-powered-by-Dall-e?type=design&node-id=64-40895&mode=design&t=jzs5OwkTLjPO6LcJ-4) designs. 
I believe I have added the correct hyperlink hrefs, but also something that is easily adjustable. 
Pull down this branch and head to the AI Image Generator (development) app in our testing org. Notice the newly added sections on the config page.
> Add aiig config page info

- apps/gatsby/src/AppConfig/AppConfig.js
I noticed the link for installation instructions on the Gatsby config page lead to a dead page (I think Gatsby reorganized a lot of their site). I have added the updated page link to the component link itself. 
New page link: https://support.gatsbyjs.com/hc/en-us/articles/17278047641876-Add-the-Gatsby-Cloud-App-to-Contentful 
Added to the `installation instructions` hyperlink as seen on the config page below:
> Fix dead Gatsby docs link

- apps/ai-image-generator/backend/package-lock.json
- apps/ai-image-generator/backend/package.json
- apps/ai-image-generator/backend/src/actions/aiig-generate-image.spec.ts
- apps/ai-image-generator/backend/src/actions/aiig-generate-image.ts
- apps/ai-image-generator/backend/test/mocks.ts
We need to fetch the actual API key that the user saved in their config during app installation, and use that when calling OpenAI.
* Grab it from the CMA
* Throw an error if no API key
* Remove dependency injection since sinon.stub() now works as expected. 🤷 
* Proper error handling and testing around unhappy paths (next PR)
> Fetch OpenAI API key from app install params

- apps/ai-image-generator/backend/.nvmrc
- apps/ai-image-generator/backend/package-lock.json
- apps/ai-image-generator/backend/package.json
- apps/ai-image-generator/backend/tsconfig.json
- apps/ai-image-generator/build-actions.js
Since the AIIG hosted app action is an internal org, we recently realized this will run with the Node18 runtime instead of Deno. We also fixed our development organization to be marked as "internal" to better align with this.
Doing that broke our current build settings, so we need to make some tweaks.
* Set .nvrmc explicitly to the LTS version of Node 18 used by AWS (`lts/hydrogen`)
* Set target to `cjs` since that's what the Node18 runtime uses
* Align the `tsconfig` settings
* https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/
> Fix build to match correct runtime

- apps/ai-image-generator/backend/src/actions/aiig-generate-image.spec.ts
- apps/ai-image-generator/backend/src/actions/aiig-generate-image.ts
We need to have a fairly standard yet lightweight way to differentiate between successful and unsuccessful app action calls.
* Implement a "result type" to differentiate between error and success
* Update the generate image action to use this format
> Update responses to agreed upon types

- apps/ai-image-generator/backend/src/actions/aiig-generate-image.spec.ts
- apps/ai-image-generator/backend/src/actions/aiig-generate-image.ts
We don't want to hardcode an assumption in the front end that image types will always be a certain type (ie png) so instead we want the backend to specify the image type explicitly.
* Add an `imageType` attribute
* Hard code to `png` for OpenAI
* Idea is it's the second half of the mime type https://www.iana.org/assignments/media-types/media-types.xhtml#image
> Add image type to backend result

- apps/ai-content-generator/src/utils/dialog/supported-fields/supportedFieldsHelpers.ts
This PR filters out fields that are marked as `Hidden when editing` so that they are not available as an option in the field selectors in the AICG modal.
The field property is called `field.disabled`, so I filtered out fields set to true.
Add a text field on a content type and mark it as `Hidden when editing`. You should not see it as an option in the modal for either source or output field.
> [INTEG-1044] Remove hidden fields from field selectors

- apps/ai-content-generator/src/utils/dialog/supported-fields/supportedFieldsHelpers.ts
For AI Content Generator, we noticed an issue with applying the content to fields. We were handling fields where there was custom size validation, but if there was no custom size validation, then we were not respecting the [default field character length](https://www.contentful.com/developers/docs/technical-limits/). For example, Short Text fields have a default max length of 256 characters. If you had a Short Text field and wanted to output content there that was 500 characters, the apply button was still enabled, you could click it, but then it wouldn't apply and a useful error was not being shown to the user.
To fix this, I leaned into our existing handling for character count validation. I added a method when formatting the field response to add in a max length if one doesn't exist. …
> [INTEG-1147] Add default max length to char validation

- examples/hosted-delivery-function-templates/javascript/example.js
- examples/hosted-delivery-function-templates/javascript/package.json
- examples/hosted-delivery-function-templates/typescript/example.ts
- examples/hosted-delivery-function-templates/typescript/package.json
The interface for Delivery Functions has changed with [this PR](https://github.com/contentful/node-apps-toolkit/pull/327)
This PR updates the `hosted-delivery-function-templates` to confirm to the new interface
In addition, the example has been expanded to include a minimal setup to call a GraphQL API to better show developers how they could implement custom delivery functions for their own GraphQL API
Note that the example does call a publicly hosted Starwars GraphQL API. If this is not an appropriate API we can easily change it with a different one.
> feat: update example to make use of new interface [MONET-1335]

- apps/ecommerce/lambda/src/middlewares/corsConfig.ts
- apps/google-analytics-4/lambda/src/middlewares/corsConfig.ts
- apps/sap-commerce-cloud-with-air/lambda/src/middlewares/corsConfig.ts
- apps/slack/lambda/lib/middlewares/corsConfig.ts
Adds the new X-Contentful-CRN header to the cors config.
Why are we so picky about the headers at all? 🤷
> feat: add X-Contentful-CRN to cors config

- apps/ai-image-generator/package.json
We are at the point in aiig where it's important to have a stable staging so that the frontend can keep developing from a consistent backend/app action.
But we also want to ability to test backend changes and since HAA doesn't have local development abilities, having a separate app that acts like a sandbox where we can just deploy freely to that app is a decent workaround.
Make sure app defn ids match
`npm run build`
`npm run deploy:sandbox`
None
None
Standard
> Add aiig staging sandbox that acts like our development sandbox

- apps/optimizely/src/EditorPage/index.js
Fixed #3790
Fixes #3790
Ran the `npm test` from the Optimizely app
> Bug fix - Optimizely App - variation container allows incorrect variant type to be selected on first render

- apps/ai-content-generator/src/hooks/dialog/useEntryAndContentType.ts
- apps/ai-content-generator/src/hooks/dialog/useEntryAndContentTypes.spec.ts
- apps/ai-content-generator/test/mocks/index.ts
- apps/ai-content-generator/test/mocks/sdk/entry/mockEntry.ts
- apps/ai-content-generator/test/mocks/sdk/mockSdk.ts
- apps/ai-content-generator/test/mocks/sdk/utils/createSdk.ts
For AI Content Generator, we want users to know whether their content from the modal has been successfully applied or not. 
Added notifications for when content is applied successfully and when there is an error. For the error, the modal remains open so that users will not lose their work in the modal. For success, the modal closes and the notification appears. I also added a test for the `useEntryAndContentTypes` hook.
Screenshots:
Success notification should appear when you click "Apply" for any action.
> [INTEG-1186] Success and error notification on apply

- apps/google-analytics-4/frontend/src/apis/api.ts
- apps/google-analytics-4/frontend/src/apis/fetchApi.ts
- apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage/GoogleAnalyticsConfigPage.tsx
- apps/google-analytics-4/frontend/src/helpers/signed-requests.ts
- apps/google-analytics-4/frontend/src/hooks/useSidebarSlug/useSidebarSlug.spec.tsx
- apps/google-analytics-4/frontend/test/mocks/mockSdk.ts
GA4 broke when I merged, this will fix it.
The tests were failing and the typing of the CMA changed when the SDK was updated
> fixes GA4 tests and cma usage

- apps/netlify/frontend/package-lock.json
- apps/netlify/frontend/package.json
- apps/netlify/frontend/src/app/index.js
- apps/netlify/frontend/src/app/netlify-content-types.js
- apps/netlify/frontend/src/index.js
Netlify wasn't rendering after our EU Data residency changes
Instead of using hooks to access the SDK, we are just passing down the relevant SDK property from the parent. Probably should have done this anyways since it's consistent with the current codebase
> fix: remove sdk hook from netlify so it renders

- apps/ai-image-generator/backend/src/transform-images.ts
This PR updates the brush color (`ERASE_COLOR`) to match the gray200 being used on the frontend in [this](https://github.com/contentful/experience-packages/pull/2297) PR.
> AIIG: update brush color in backend

- apps/optimizely/src/EditorPage/index.js
Optimisely is not handling variant containers with 0 references
Return the empty reference object. Lower the retry amount so the user isn't sitting there for 25 seconds
> fix: optimisely now handles having zero references

- examples/hosted-delivery-function-templates/javascript/example.js
- examples/hosted-delivery-function-templates/javascript/package.json
- examples/hosted-delivery-function-templates/typescript/example.ts
- examples/hosted-delivery-function-templates/typescript/package.json
node-apps-toolkit is built into commonjs which throws errors in runtime as it's not "treeshakeable". Trying to modify the library to build into esm is too complicated to support both commonjs & esm. It's doesn't make much sense to do a major version upgrade just because of this tiny change.
Hardcode the enum for now
> fix: avoid relying on node-apps-toolkit on runtime [MONET-1463]

- apps/ai-content-generator/src/components/config/api-key/APIKey.tsx
- apps/ai-content-generator/src/components/config/config-page/ConfigPage.tsx
- apps/ai-content-generator/src/components/config/config-section/ConfigSection.tsx
- apps/ai-content-generator/src/components/config/configText.ts
- apps/ai-content-generator/src/components/config/model/Model.tsx
- apps/ai-content-generator/src/components/config/profile/Profile.tsx
- apps/ai-content-generator/src/components/config/profile/ProfileTextArea.tsx
- apps/ai-content-generator/src/components/config/profile/ProfileTextInput.tsx
- apps/ai-content-generator/src/configs/ai/baseUrl.ts
- apps/ai-content-generator/src/configs/ai/gptModels.ts
- apps/ai-content-generator/src/hooks/config/useSaveConfigHandler.spec.tsx
- apps/ai-content-generator/src/hooks/config/useSaveConfigHandler.ts
- apps/ai-content-generator/src/hooks/dialog/useAI.tsx
- apps/ai-content-generator/src/utils/aiApi/index.ts
- apps/ai-content-generator/test/mocks/sdk/utils/createSdk.ts
This PR updates the error handling on the app config page for AI content generator. In addition, there are also a few small fixes this PR addresses:
- Fixes a typo in the model name for gpt-4-32k
- Fixes some failing tests from the introduction of the SDK `hostnames` property
- Fully obfuscates the API Key on save to match the pattern in V1
- Makes the brand profile section optional and adds a debounce for that section to reduce re-renders
The API Key and Model fields are now the only two required fields on the config page. On blur, the API Key entered is validated against the [list models](https://platform.openai.com/docs/api-reference/models) OpenAI API endpoint. The user will see a "Validating" message below the API Key field while it is validating. If there is an error, then the user …
> [INTEG-1181] Update AICG config page error handling

- examples/hosted-delivery-function-templates/javascript/build-delivery-functions.js
- examples/hosted-delivery-function-templates/typescript/build-delivery-functions.js
Follow up on https://github.com/contentful/apps/pull/4759. Bundle everything now that node-apps-toolkit is "fixed"
Back to bundling all delivery function code before upload
> feat: bundle code after fixing node-apps-toolkit [MONET-1463]

- apps/ai-content-generator/src/components/config/config-page/ConfigPage.tsx
- apps/ai-content-generator/src/components/config/parameterReducer.ts
- apps/ai-content-generator/src/components/config/profile/ProfileTextArea.tsx
- apps/ai-content-generator/src/components/config/profile/ProfileTextInput.tsx
- apps/ai-content-generator/src/hooks/dialog/useAI.tsx
- apps/ai-content-generator/src/locations/ConfigScreen.tsx
- apps/ai-content-generator/src/locations/Sidebar.tsx
- apps/ai-content-generator/test/mocks/sdk/parameters/happyPathParameter.ts
- apps/ai-content-generator/test/mocks/sdk/parameters/initParameters.ts
- apps/ai-content-generator/test/mocks/sdk/utils/generateRandomParameters.ts
We were clearing the V1 configs on update to v2
There were two approaches, I think this one will be more implicit and lead to less developer error long term. The original versioning config plan had too many potholes and added some in-repo knowledge that a new dev wouldn't necessarily know
> Feat/integ 1133 - Backwards compatibility with V1 config

- apps/ai-image-generator/backend/src/actions/aiig-select-fill.ts
We need to only return 3 images as part of the Select and Edit flow, as opposed to 4. Therefore i have adjusted the explicit return value.
> chore: reduce number of images returned

- apps/ai-image-generator/package.json
We started seeing build failures during the `publish-package` step of the deploy-prod workflow. Example: https://app.circleci.com/pipelines/github/contentful/apps/24206/workflows/72689d12-eadd-4067-aaaa-81f2abe09c02/jobs/71745
Further investigation uncovered the problem was in the `build-sharp` script of the `ai-image-generator` app. This step (used to build an version of sharp that can run in an AWS lambda) was using `npm install`, which was polluting the git working space. This was causing a failure down the road when lerna tried to do it's git magic during `lerna version --conventional-commits --no-private --force-git-tag --create-release github --yes && lerna publish from-git --yes`
* Use `npm ci` instead of `npm install`: https://docs.npmjs.com/cli/v7/commands/npm-ci . "It will never …
> Fix pollution of package and package lock during sharp build

- examples/hosted-delivery-function-potterdb/.gitignore
- examples/hosted-delivery-function-potterdb/.prettierrc
- examples/hosted-delivery-function-potterdb/README.md
- examples/hosted-delivery-function-potterdb/build-delivery-functions.js
- examples/hosted-delivery-function-potterdb/contentful-app-manifest.json
- examples/hosted-delivery-function-potterdb/delivery-functions/index.ts
- examples/hosted-delivery-function-potterdb/delivery-functions/types.ts
- examples/hosted-delivery-function-potterdb/package-lock.json
- examples/hosted-delivery-function-potterdb/package.json
- examples/hosted-delivery-function-potterdb/public/index.html
- examples/hosted-delivery-function-potterdb/src/App.tsx
- examples/hosted-delivery-function-potterdb/src/components/LocalhostWarning.tsx
- examples/hosted-delivery-function-potterdb/src/index.tsx
- examples/hosted-delivery-function-potterdb/src/locations/Field.spec.tsx
- examples/hosted-delivery-function-potterdb/src/locations/Field.tsx
- examples/hosted-delivery-function-potterdb/src/react-app-env.d.ts
- examples/hosted-delivery-function-potterdb/src/setupTests.ts
- examples/hosted-delivery-function-potterdb/test/mocks/index.ts
- examples/hosted-delivery-function-potterdb/test/mocks/mockCma.ts
- examples/hosted-delivery-function-potterdb/test/mocks/mockSdk.ts
- examples/hosted-delivery-function-potterdb/tsconfig.json
Ticket https://contentful.atlassian.net/browse/MONET-1473
This PR adds an example that includes a hosted delivery function. The functions forwards GraphQL queries to the [PotterDB](https://docs.potterdb.com/apis/graphql) so that we can query Contentfuls GraphQL API for data from the potter universe.
> [MONET-1473] feat: adds hosted delivery function example for PotterDB

- apps/ai-image-generator/backend/package-lock.json
- apps/ai-image-generator/backend/package.json
- apps/ai-image-generator/backend/src/actions/aiig-select-edit.ts
- apps/ai-image-generator/backend/src/helpers/upload-images.spec.ts
- apps/ai-image-generator/backend/src/helpers/upload-images.ts
- apps/ai-image-generator/backend/test/mocks.ts
- apps/ai-image-generator/backend/test/scripts/call-hosted-app-action.ts
Right now, we upload all images to the US region (hard coded). We also report back in our `url` field that the image was uploaded to the US bucket.
Going forward, images might be uploaded to the EU region, depending on how the cma client was instantiated. We need to ensure that the URL points to the correct bucket, no matter where the image is uploaded.
* We have no way of knowing which host or upload host the cmaClient was initialized with. However we can use the `cmaHost` value to deduce which region was used and build a correct url computation.
* We don't have support for flinkly or other environments. This current implementation is pretty brittle as a result. Better to build the upload url at the API level then hardcode this stuff in apps though.
* Go to the EU region, to a space …
> Support EU region in upload URLs

- apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeCard.tsx
- apps/google-analytics-4/frontend/src/helpers/contentTypeHelpers/contentTypeHelpers.spec.ts
- apps/google-analytics-4/frontend/src/helpers/contentTypeHelpers/contentTypeHelpers.ts
- apps/google-analytics-4/frontend/src/hooks/useGetFieldValue.tsx
- apps/google-analytics-4/frontend/src/hooks/useSidebarSlug/useSidebarSlug.spec.tsx
- apps/google-analytics-4/frontend/src/utils/pathJoin.spec.ts
- apps/google-analytics-4/frontend/src/utils/pathJoin.ts
We received customer feedback that they want to use short text list fields as the "slug" field when configuring the GA4 app. Currently, the app only supports short text fields.
In order to support short text list fields, I made the following changes:
1. Config page: Updated the help text displayed when selecting a slug field and updated the filtering so that both short text and short text list fields are displayed as options.
2. Sidebar app: Updated how we are creating the page path to handle an array of strings. The elements of the array will be joined by a forward slash
**Updated config page:**
**Example field on an entry and what appears in the sidebar:**
1. Create a short text list field on a content type
2. Select that field as the slug field on the app config
4. Navigate to an entry …
> feat: support short text list fields in GA4 [INTEG-1344]

- apps/ai-content-generator/src/components/app/sidebar/BrandProfileMissingWarning.spec.tsx
- apps/ai-content-generator/src/components/app/sidebar/BrandProfileMissingWarning.tsx
- apps/ai-content-generator/src/components/app/sidebar/DisplaySidebarWarning.tsx
- apps/ai-content-generator/src/components/app/sidebar/ParametersMissingWarning.tsx
- apps/ai-content-generator/src/components/app/sidebar/SidebarButtons.tsx
- apps/ai-content-generator/src/components/app/sidebar/feature-button/FeatureButton.tsx
- apps/ai-content-generator/src/components/app/sidebar/sidebarText.ts
- apps/ai-content-generator/src/components/common/Note/Note.styles.ts
- apps/ai-content-generator/src/components/common/Note/Note.tsx
- apps/ai-content-generator/src/components/config/api-key/APIKey.tsx
- apps/ai-content-generator/src/components/config/config-page/ConfigPage.tsx
- apps/ai-content-generator/src/components/config/config-section/ConfigSection.tsx
- apps/ai-content-generator/src/hooks/dialog/useAI.tsx
- apps/ai-content-generator/src/hooks/sidebar/useSidebarParameters.spec.ts
- apps/ai-content-generator/src/hooks/sidebar/useSidebarParameters.ts
- apps/ai-content-generator/src/locations/ConfigScreen.tsx
- apps/ai-content-generator/src/locations/Sidebar.tsx
- apps/ai-content-generator/src/utils/aiApi/handleAiApiErrors.ts
- apps/ai-content-generator/src/utils/aiApi/index.ts
- apps/ai-content-generator/src/utils/segment/getTrackedAppData.ts
- apps/ai-content-generator/test/mocks/sdk/mockSdk.ts
- apps/ai-content-generator/test/mocks/sdk/utils/createSdk.ts
We want to improve the error handling in the Sidebar for AI Content Generator.
This PR adds several things:
- Checks to see if the API key is valid by hitting the OpenAI models endpoint
- Handles when model is undefined by defaulting to a model in the AI class
- Displays appropriate warning messages and disables the sidebar buttons when there is an OpenAI error
I added different warning components and created a hook for the logic to check the sidebar parameters.
**Example of a missing brand profile (this is a dismissible warning and buttons are still enabled):**
**Example of a missing or invalid API Key:**
**Example of Chat GPT not available :**
**Example of a different OpenAI API error, showing the error message from OpenAI:**
**Example of default error message (when there is no message …
> feat: add AICG sidebar error handling [INTEG-1182]

- apps/ai-image-generator/backend/src/actions/aiig-static.ts
- apps/ai-image-generator/backend/src/helpers/process-images-after-edit.ts
- apps/ai-image-generator/backend/src/helpers/upload-images.spec.ts
- apps/ai-image-generator/backend/src/helpers/upload-images.ts
- apps/ai-image-generator/backend/src/types.ts
Frontend has a Preview UI/UX experience that requires the image size and image dimensions to display to the end user
Refactor upload image backend to create the image buffer (somewhat inefficient) to get the image metadata that is about to be uploaded to Contentful.
Through User interface and experience packages.
None
None
Standard
> Adds backend image upload metadata for image size and dimensions

- apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/OutputTextPanels.tsx
- apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/generated-text-panel/GeneratedTextPanel.tsx
- apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/original-text-panel/OriginalTextPanel.tsx
- apps/ai-content-generator/src/components/common/text-field-with-buttons/TextFieldWIthButtons.tsx
- apps/ai-content-generator/src/hooks/dialog/useAI.tsx
- apps/ai-content-generator/src/hooks/dialog/useEntryAndContentType.ts
There was no error handling outside of some try/catches in the original modal.
Have stateful errors in the modal, as well as launch toasts as needed
> feat: add error handling to modal

- apps/ai-content-generator/src/components/app/dialog/common-generator/generatorReducer.tsx
- apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/original-text-panel/OriginalTextPanel.tsx
- apps/ai-content-generator/src/components/common/text-field-with-buttons/TextFieldWIthButtons.tsx
- apps/ai-content-generator/src/components/config/api-key/APIKey.tsx
- apps/ai-content-generator/src/components/config/appInstallationParameters.ts
- apps/ai-content-generator/src/components/config/brand-section/BrandSection.tsx
- apps/ai-content-generator/src/components/config/config-page/ConfigPage.tsx
- apps/ai-content-generator/src/components/config/config-section/ConfigSection.tsx
- apps/ai-content-generator/src/components/config/configText.ts
- apps/ai-content-generator/src/components/config/parameterReducer.ts
- apps/ai-content-generator/src/components/config/profile/Profile.tsx
- apps/ai-content-generator/src/components/config/profile/ProfileTextArea.tsx
- apps/ai-content-generator/src/components/config/profile/ProfileTextInput.tsx
- apps/ai-content-generator/src/configs/ai/gptModels.ts
- apps/ai-content-generator/src/configs/prompts/baseSystemPrompt.ts
- apps/ai-content-generator/src/hooks/config/useInitializeParameters.ts
- apps/ai-content-generator/src/hooks/config/useSaveConfigHandler.spec.tsx
- apps/ai-content-generator/src/hooks/config/useSaveConfigHandler.ts
- apps/ai-content-generator/src/hooks/dialog/useAI.tsx
- apps/ai-content-generator/src/hooks/dialog/useDialogParameters.ts
- apps/ai-content-generator/src/hooks/sidebar/useSidebarParameters.ts
- apps/ai-content-generator/src/locations/ConfigScreen.tsx
- apps/ai-content-generator/src/providers/segmentAnalyticsProvider.tsx
- apps/ai-content-generator/src/utils/segment/getTrackedAppData.ts
- apps/ai-content-generator/test/mocks/sdk/mockSdk.ts
- apps/ai-content-generator/test/mocks/sdk/parameters/happyPathParameter.ts
- apps/ai-content-generator/test/mocks/sdk/parameters/initParameters.ts
- apps/ai-content-generator/test/mocks/sdk/utils/createSdk.ts
- apps/ai-content-generator/test/mocks/sdk/utils/generateRandomParameters.ts
ChatGPT 3 has a character limit of ~16k. Also the ai gets significantly worse when user adds too much data for it to consider
Create a `Validator` type that takes an existing type and recursively adds `{ value: originalValue, isValid: bool }` to every field.
Then reorganized the code so the validation happens during the dispatch
Verify:
- The config page still has original functionality
- You can't submit the form when exceeding the character count
- Prompt/From Source shows a character count when using gpt3 and not in gpt4
> feat: add character limit to brand fields and the prompt field in aicg

- apps/typeform/lambda/app.js
- apps/typeform/lambda/package.json
- apps/typeform/lambda/serverless.yml
We have not been providing a `Last-Modified` header to our express static middleware used to host the Typeform frontend; as a result, the value of `Last-Modified` sent by AWS gateway has been 1980.
This has caused aggressive browser local caching, which often leads to "broken" deploys since the browser doesn't try to fetch the most recent value.
* Capture the "current time" at deploy; pass through to as env var to serverless
> Add last-modified header to static frontend

- apps/ai-content-generator/src/components/app/dialog/common-generator/errorMessages.ts
- apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/generated-text-panel/GeneratedTextPanel.styles.ts
- apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/generated-text-panel/GeneratedTextPanel.tsx
- apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/original-text-panel/OriginalTextPanel.tsx
- apps/ai-content-generator/src/components/common/text-field-with-buttons/TextFieldWIthButtons.tsx
- apps/ai-content-generator/src/components/config/configText.ts
- apps/ai-content-generator/src/components/config/cost-section/CostSection.spec.tsx
- apps/ai-content-generator/src/components/config/cost-section/CostSection.tsx
- apps/ai-content-generator/src/hooks/dialog/useAI.tsx
- apps/ai-content-generator/src/utils/aiApi/index.ts
We wanted to improve the feedback to AICG users about rate limits for Chat GPT. This PR adds more helpful messaging to the config page and the modal.
Added new copy to the config page:
For the modal, refactored the API call to the completions endpoint so that we could display different messages based on the response status. If a 429 response is returned, we have a custom message, otherwise, the default will show.
Rate limit error message:
Default modal error message:
- Ensure that all actions still work as expected for the happy path
- Trigger an error (e.g. make an invalid API key) and the error message should appear in the modal after clicking "Generate"
None
Links go to this page: https://platform.openai.com/docs/guides/rate-limits/overview
OpenAI error …
> feat: improved handling for rate limits [INTEG-1381]

- apps/jira/jira-app/src/components/Auth/OAuth.tsx
- apps/jira/jira-app/src/index.spec.tsx
- apps/jira/jira-app/src/standalone.ts
In browsers where cross-site tracking and/or third party storage access partitioning features were enabled, token and expire time values received from Jira during the Oauth flow were not being saved to local storage in a way such that they were accessible from the main Jira Contentful app.
Instead, what was observed was that those values were not present in local storage from the main app at all.
Basically same as https://github.com/contentful/apps/pull/5000
* Send data via postMessage
> fix: set localstorage in correct place

- apps/jira/jira-app/src/index.tsx
There's a bug that's masking error messaging:
```
react-dom.production.min.js:216 Error: SDKContext not found. Make sure this hook is used inside the SDKProvider
at t.useSDK (useSDK.js:14:15)
at y (ContentTypeStep.tsx:28:15)
at ca (react-dom.production.min.js:157:137)
at Yc (react-dom.production.min.js:267:460)
at Cs (react-dom.production.min.js:250:347)
at Ts (react-dom.production.min.js:250:278)
at Is (react-dom.production.min.js:250:138)
at bs (react-dom.production.min.js:243:163)
at react-dom.production.min.js:123:115
at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```
* Add the missing `SDKProvider`
> Add SDK provider

- nx.json
- package-lock.json
- package.json
We are currently using Lerna v5 in this repo, upgrading to v6 will allow us to take advantage of some useful improvements. Additionally, it should resolve the alerts noted here: https://github.com/contentful/apps/pull/4071
Upgrading from v5 to v6 is non-breaking. I upgraded lerna and then ran `npx lerna add-caching` to generate a `nx.json` file to enable caching (https://lerna.js.org/docs/features/cache-tasks).
Upgrading to v7 is a breaking change that will require us to replace our usage of `lerna bootstrap` (https://lerna.js.org/docs/legacy-package-management). This can be addressed in a follow up task. 
I ran several lerna commands locally (lint, test, bootstrap, build) and verified that it is still working as anticipated.
Upgrading to v6 should not be a breaking change according to …
> chore: upgrade Lerna to v6 [INTEG-1422]

- apps/aws-amplify/src/locations/Sidebar.tsx
This PR adds the `useAutoResizer()` functionality to the AWS Amplify so that is it not awkwardly taking up unnecessary spice in the Sidebar. This was a nit thing pointed out a while ago while on support, felt it was low-handing fruit to adjust ✅
> Add useAutoResizer functionality to AWS Amplify app

- package-lock.json
- package.json
We thought `prettier@3` would work with `lerna@6`, but we need to upgrade to `lerna@7` ([see here](https://github.com/lerna/lerna/releases/tag/v7.1.2))
> fix: downgrade prettier

- apps/microsoft-teams/frontend/package.json
After confirming that the newly created MS Teams app build runs correctly, this PR adds the deploy scripts for the staging and production apps.
> chore: add deploy scripts to MS Teams app [INTEG-1469]

- apps/typeform/frontend/package.json
Same thing as [this](https://github.com/contentful/apps/pull/5304) PR but for Typeform app because of current build failure on pipeline. 
_With the upgrade to node18 in our build environment, the build for smartling (Typeform) started to break: https://app.circleci.com/pipelines/github/contentful/apps/25320/workflows/f43a3c59-b6fb-4359-bf0b-f5092d0b55bb/jobs/76824
The problem appears to be a lack of support for node 17+ in the legacy babel loader this project uses. See https://stackoverflow.com/questions/74726224/opensslerrorstack-error03000086digital-envelope-routinesinitialization-e_
> fix: pipeline build - specifically the Typeform app build given recent Node upgrade

- apps/brandfolder/package.json
- apps/dropbox/package.json
- apps/netlify/frontend/package.json
In order to fix the current pipeline build failures, I have tested the builds (after running `npm i `😅 ) of all apps locally and updated the rest of the scripts in this PR - they should resemble the scripts that exist in most other apps now. 🤞 
See this [PR](https://github.com/contentful/apps/pull/5304) and this [PR](https://github.com/contentful/apps/pull/5305) for more context around this update - the origin of these changes are from a Node update last week.
> fix pipeline - netlify, brandfolder, dropbox builds

- apps/jira/jira-app/src/components/App/Config.tsx
- apps/slack/frontend/src/components/ConfigScreen.tsx
Currently there exists a customer that cannot successfully render the app config page of two apps, Slack and Jira. They recieve [this](https://p29.zdusercontent.com/attachment/284868/VDxt5gsmyGa9J7gKRY8yQtfry?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..acgWQ7Ztly-1azuNPv4N5A.zZ_osPEu6v0d4ocunubHEstHM8QKEhLd6zHl3Xovrrr0y17V9sI5BYBKQs0DKYguzmkSc0_8ln_BFc7cIbyfyd4lf9ZjFwQU0QXUrXgLj_7Kjm4yfg1c6O2myFNvjVYffQ2NSrAWwzQWdPRTabnaKnjZNVtyHdasc8brbnq7MSXgxmVtS4iVHgywerP_l3glK4yG6TVnCPT8pq1FDlqCWEwb1JDsnxK9SaiJylxohdUKIvpPUstlshN1p0xDms0RJbKqBkgW92U9HzrumvbVznlkn_mE-OZh8kI8d4TSybY.sDAVMicg4pWTPgQ4FuX9Gg) warning page. 
This is an especially tricky bug because when either I or the customer support engineer impersonate the user, the bug does not appear and we can successfully render the …
> add a few logs to Slack app and Jira app in order to debug customer issue

- apps/microsoft-teams/msteams-bot-service/.eslintignore
- apps/microsoft-teams/msteams-bot-service/.eslintrc.js
- apps/microsoft-teams/msteams-bot-service/.mocharc.yml
- apps/microsoft-teams/msteams-bot-service/package-lock.json
- apps/microsoft-teams/msteams-bot-service/package.json
- apps/microsoft-teams/msteams-bot-service/src/app.spec.ts
- apps/microsoft-teams/msteams-bot-service/src/app.ts
- apps/microsoft-teams/msteams-bot-service/tsconfig.json
We need a basic express service set up to starting introducing the MS Team bot SDK and service
* Add vanilla express server with "health" endpoint
* Use mocha and chai for tests
* Eslint for linting
* TSC for typescript
* Build, lint and test runner scripts
> feat: Get basic msteams-bot-service setup

- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
- apps/microsoft-teams/frontend/src/components/config/ConfigPage/ConfigPage.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ConfigPage/ConfigPage.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.styles.ts
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.styles.ts
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
- apps/microsoft-teams/frontend/src/components/config/parameterReducer.ts
- apps/microsoft-teams/frontend/src/constants/defaultParams.ts
- apps/microsoft-teams/frontend/src/customTypes/configPage.ts
- apps/microsoft-teams/frontend/src/hooks/useInitializeParameters.spec.ts
- apps/microsoft-teams/frontend/src/hooks/useInitializeParameters.ts
- apps/microsoft-teams/frontend/src/locations/ConfigScreen.tsx
- apps/microsoft-teams/frontend/test/mocks/index.ts
- apps/microsoft-teams/frontend/test/mocks/mockSdk.ts
- apps/microsoft-teams/frontend/tsconfig.json
- apps/microsoft-teams/frontend/vite.config.ts
Updating the MS Teams app config page to use a reducer to manage the installation parameters and added a hook to initialize the parameters and dispatch them to the reducer. 
Followed much of the pattern we established in the AICG app. I also implemented the ability to remove a notification, so now you can add and remove empty notifications on the config page.
Run MS Teams (development) app locally. You should be able to edit the Tenant Id and add/remove notifications and save the app config page.
> refactor: implement reducer to manage installation params [INTEG-1524]

- apps/microsoft-teams/frontend/src/components/config/ChannelSelection/ChannelSelection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ChannelSelection/ChannelSelection.tsx
- apps/microsoft-teams/frontend/src/components/config/ChannelSelectionModal/ChannelSelectionModal.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelection/ContentTypeSelection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelection/ContentTypeSelection.styles.ts
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelection/ContentTypeSelection.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.styles.ts
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.tsx
- apps/microsoft-teams/frontend/src/components/config/EventsSelection/EventsSelection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/EventsSelection/EventsSelection.tsx
- apps/microsoft-teams/frontend/src/components/config/ModalHeader/ModalHeader.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/constants/defaultParams.ts
- apps/microsoft-teams/frontend/src/customTypes/configPage.ts
- apps/microsoft-teams/frontend/src/hooks/useGetContentTypes.spec.ts
- apps/microsoft-teams/frontend/src/hooks/useGetContentTypes.ts
- apps/microsoft-teams/frontend/test/mocks/index.ts
- apps/microsoft-teams/frontend/test/mocks/mockContentTypes.ts
- apps/microsoft-teams/frontend/test/mocks/mockSdk.ts
This PR creates the content type selection modal for the MS Teams app config page. It also adds the ability to save and persist the selected content type and app events for a notification.
Added modal for content type selection and now selected content type, channel, and events are all persisted in app installation parameters.
New modal:
App Events/Action selection:
Run locally in MS Teams development app.
> feat: add content type and event selection for notifications [INTEG-1543-1551]

- apps/microsoft-teams/frontend/package-lock.json
- apps/microsoft-teams/frontend/package.json
- apps/microsoft-teams/frontend/src/components/config/ChannelSelection/ChannelSelection.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelection/ContentTypeSelection.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.styles.ts
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.styles.ts
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/customTypes/configPage.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.spec.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.ts
- apps/microsoft-teams/frontend/test/mocks/index.ts
- apps/microsoft-teams/frontend/test/mocks/mockContentTypes.ts
- apps/microsoft-teams/frontend/test/mocks/mockNotification.ts
- apps/microsoft-teams/frontend/tsconfig.json
- apps/microsoft-teams/frontend/vite.config.ts
This PR creates the "view mode" for configured notifications in the MS Teams app config page.
A couple of additions with this PR:
- Only one notification can be in edit mode at a time. When a notification is in edit mode, other notifications have the `Edit` button disabled
- When a notification is in edit mode, save will only be enabled when all the fields have been filled out
- A cancel button has been added to edit mode
Run the app locally in an MS Teams development app.
> feat: add notification view mode [INTEG-1552]

- apps/smartling/frontend/src/Sidebar.tsx
This fixes a bug with perpetual auth call out for smartling sidebar app, users were required to re-auth everytime they navigated away from content or configuration.
We were overwriting tokens in local storage with OR || logic for component state, this implicitly sets tokens to null and forces a refresh, or the per usual initial auth flow.
> Update null check and persist to localstorage properly

- apps/microsoft-teams/frontend/src/components/config/DeleteModal/DeleteModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/DeleteModal/DeleteModal.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
This PR adds the confirmation modal when a user tries to delete a notification.
This is the confirmation modal that appears when a user clicks Delete for a notification.
Delete a notification in the MS Teams (development) environment.
> feat: add delete confirmation modal [INTEG-1449]

- packages/ecommerce-app-base/src/AppConfig/AppConfig.spec.tsx
- packages/ecommerce-app-base/src/AppConfig/AppConfig.tsx
- packages/ecommerce-app-base/src/AppConfig/OrchestrationEapNote/OrchestrationEapNote.tsx
We realized that EAP note was never able to get closed. This PR fixes the issue.  Once note is dismissed, it's not showed again. 
Related ticket: https://contentful.atlassian.net/browse/MONET-1607
> fix: bug [MONET-1607]

- apps/microsoft-teams/frontend/package-lock.json
- apps/microsoft-teams/frontend/package.json
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelection/ContentTypeSelection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelection/ContentTypeSelection.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.tsx
- apps/microsoft-teams/frontend/src/components/config/EmptyState/EmptyState.styles.ts
- apps/microsoft-teams/frontend/src/components/config/EmptyState/EmptyState.tsx
- apps/microsoft-teams/frontend/src/components/config/EmptyState/WebApp.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/context/ContentTypeProvider.tsx
- apps/microsoft-teams/frontend/src/hooks/useGetContentTypeConfigLink.spec.ts
- apps/microsoft-teams/frontend/src/hooks/useGetContentTypeConfigLink.ts
- apps/microsoft-teams/frontend/test/helpers/ContentTypeCustomRender.tsx
- apps/microsoft-teams/frontend/test/mocks/mockSdk.ts
- apps/microsoft-teams/frontend/tsconfig.json
- apps/microsoft-teams/frontend/vite.config.ts
This PR adds the empty state in the content type selection modal for MS Teams. This empty state will be visible when the app is installed in an environment where there are no content types.
I made a few additional updates when adding this feature:
- I added a hook `useGetContentTypeConfigLink` to get the link to navigate to the content type config page within the web app
- I had to bump the `app-sdk` package in order to get `hostname`  from the sdk
- In order to reduce prop drilling the content types and the config link, I created context for the content type and the config link
- The Modal component cannot directly call the hooks to get the content types and config link, nor can it consume the context directly since it doesn't have the sdk context since it's not within the SDKProvider. …
> feat: add empty state for content type selection [INTEG-1579]

- .github/dependabot.yml
- apps/ai-image-generator/backend/package-lock.json
- apps/ai-image-generator/backend/package.json
- apps/ai-image-generator/package-lock.json
- apps/ai-image-generator/package.json
* Sharp introduced a new installation packaging set up where they distribute prebuilt binaries. Details here https://github.com/lovell/sharp/issues/3750. This was released in v0.33.0 which we upgraded to (via dependabot) a few days ago.
* The change broke the image generator with the following errors:
```
Error: Could not load the \"sharp\" module using the linux-x64 runtime
Possible solutions:
- Add platform-specific dependencies:
npm install --os=linux --cpu=x64 sharp
or
npm install --force @img/sharp-linux-x64
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
at Object.<anonymous> (/var/task/7dFRjNacIIBFc6CVoVP822/node_modules/sharp/lib/sharp.js:85:9)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js …
```
> fix: lock down sharp to v0.32.6 due to installation errors in AWS lambda

- .github/dependabot.yml
- apps/ai-image-generator/backend/package-lock.json
- apps/ai-image-generator/backend/package.json
- apps/ai-image-generator/backend/src/actions/aiig-select-edit.spec.ts
- apps/ai-image-generator/bundle-sharp.js
- apps/ai-image-generator/package-lock.json
- apps/ai-image-generator/package.json
* We had to pin sharp to version 0.32.6 due to breaking changes with sharp's new installation process
* We want / need to unpin to continue to support new upstream sharp updates
* Set package to 0.33 and remove dependabot exclusions
* Install the linux-x64 packages supplied by sharp during the build step
* Remove excess darwin* packages from node modules since they contain huge binaries that break our upload (our bundle size becomes too big)
* Make sure we copy over our new @img packages into the build artifact
* Uploaded and tested this action on sandbox and confirmed it works ✨
> chore: support sharp 0.33

- apps/ai-image-generator/bundle-sharp.js
- apps/ai-image-generator/package.json
* Previous attempt to fix sharp (#5674) almost worked, but the build artifact was too big: https://app.circleci.com/pipelines/github/contentful/apps/26276/workflows/24c38da4-5537-40a8-bb96-78a70f62d160/jobs/81197?invite=true#step-117-5288_19
* Instead of removing unneeded files, copy over only what's needed. This is a better approach and also has the advantage of minimzing the build size
> fix: cleaner sharp install to reduce folder size

- packages/dam-app-base/README.md
- packages/dam-app-base/docs/README.md
- packages/dam-app-base/src/Editor/Field.tsx
- packages/dam-app-base/src/Editor/SortableComponent.tsx
- packages/dam-app-base/src/index.tsx
- packages/dam-app-base/src/interfaces.ts
This PR updates the `dam-app-base` with two new optional functions. These changes are being made to support feedback from customers to improve the Bynder app, which utilizes this package.
I added two new optional functions to be passed into the `dam-app-base` setup integration. Since these functions are optional, adding these will not impact other apps that utilize this package.
1. `customUpdateStateValue`: changes the default save behavior. The current behavior is that newly selected assets are appended to the end of the selected assets. If you want to instead resave all the selected assets each time, this new function will enable you to do so.
2. `getAdditionalData`: passes additional data to display in the asset card. When this function is passed in, then you see a "more details" …
> feat: support custom update and additional details display [INTEG-1611]

- packages/dam-app-base/src/Editor/SortableComponent.tsx
The drag area was conflicting with the more details section in the `dam-app-base` asset card. This PR makes the more details section selectable, and then the drag are to move assets is the image.
Moved the more details section outside of the draggable `div`. Also updated the cursor when selecting the additional info.
Tested the package updates in Bynder using `npm link`.
> fix: allow additional data to be selectable [INTEG-1627]

- apps/netlify/lambda/helpers/build-hook.js
There was a missed api url in netlify for the data residency update.
Use the host property in the appContextDetails to populate the url
> fix: data residency for netlify

- apps/ai-image-generator/backend/package-lock.json
- apps/ai-image-generator/backend/package.json
- apps/ai-image-generator/backend/src/actions/aiig-generate-image.ts
- apps/ai-image-generator/backend/src/actions/aiig-select-edit.spec.ts
- apps/ai-image-generator/backend/src/actions/aiig-select-edit.ts
- apps/ai-image-generator/backend/src/helpers/upload-images.spec.ts
- apps/ai-image-generator/backend/src/helpers/upload-images.ts
- apps/ai-image-generator/backend/src/utils.ts
- apps/ai-image-generator/package-lock.json
- apps/ai-image-generator/package.json
The create asset upload function has been changed to take both spaceId and the environmentId, therefore we need to adjust accordingly to the new api params.
* Pass environment id when creating the upload
* Check the created upload and return the environment scoped URL when the environment is present. (Preserves backward compatibility when CMA.js doesn't have support for environment ids in uploads.)
Testing results on sandbox:
Correct images: 
Using environment scoped upload URLs:
Will require latest contentful-management.js package version or else merging this PR will break the backend
> [INTEG-1417] Update aiig create upload function to handle latest upload function for both spaceId and environmentId

- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
- apps/microsoft-teams/frontend/src/components/config/ChannelSelectionModal/ChannelSelectionModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ChannelSelectionModal/ChannelSelectionModal.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.tsx
- apps/microsoft-teams/frontend/src/components/config/EmptyState/EmptyState.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
This PR updates copy and links in the MS Teams app config page based on feedback in our Mob QA session.
Updated copy and links. Also ensured that when the empty state is visible for the content type and channel selection modals, that the "select" button is not visible, see example below:
Navigate to the MS Teams development app.
> chore: update copy and links [INTEG-1648]

- apps/google-analytics-4/frontend/package-lock.json
- apps/google-analytics-4/frontend/src/components/main-app/LineChart/LineChart.tsx
Dependabot tried to update the Chart.js dependency in GA4 and the update failed: https://github.com/contentful/apps/pull/5663
[Chart.js version 4.4.1](https://github.com/chartjs/Chart.js/releases/tag/v4.4.1) changes the type of font weight from string to number ([see this PR](https://github.com/chartjs/Chart.js/pull/11605/files)). This PR bumps the package and then changes the font weight for the line chart from a string to a number.
Note: I did change the tooltip font weight from `700` to the `fontWeightDemiBold` token (which equates to `600`), and I still think it looks ok, see screenshot.
I verified that the line chart still renders correctly in the GA4 app sidebar.
https://github.com/chartjs/Chart.js/releases/tag/v4.4.1
https://github.com/chartjs/Chart.js/pull/11605 …
> chore: bump chart.js and fix font weight type

- apps/microsoft-teams/frontend/src/components/config/DuplicateModal/DuplicateModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/DuplicateModal/DuplicateModal.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.spec.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.ts
- apps/microsoft-teams/frontend/src/hooks/useGetTeamsChannels.ts
We want to avoid allowing the creation and configuration of duplicate notifications, this adds that logic and a modal for confirming or canceling editing of existing notification.
Ticket: https://contentful.atlassian.net/browse/INTEG-1587
1.) Navigate to the development space, and start the app.
2.) Make sure there is a configured notification for content type and channel.
3.) Attempt to create a new notification with the same content type, and same channel.
4.) Observe this modal:
5.) Test CTA(s)
- Click `Go back to editing` to cancel creation
- Click `Update existing notification` to edit the existing notification
6.) Observe editing state for previously existing notification:
> feat: [INTEG-1587] - Add notification dedupe modal

- apps/microsoft-teams/frontend/src/components/config/ChannelSelection/ChannelSelection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ChannelSelection/ChannelSelection.tsx
- apps/microsoft-teams/frontend/src/components/config/ChannelSelectionModal/ChannelSelectionModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ChannelSelectionModal/ChannelSelectionModal.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/constants/defaultParams.ts
- apps/microsoft-teams/frontend/src/context/ChannelProvider.tsx
- apps/microsoft-teams/frontend/src/customTypes/configPage.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.spec.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.ts
- apps/microsoft-teams/frontend/test/mocks/mockNotification.ts
This PR makes a few changes to channels in the config page:
- Previously we were only storing channel id and we instead want to store all the channel info returned from the app action
- We are prop drilling channels from the `NotificationsSection` component and this PR refactors that to use context to store the channel info
- Removes a helper function that was previously used to get the channel name
In a follow up task we can add additional error handling for channels that are deleted, can't be found, etc.
This may require you to uninstall and reinstall the app in our development environment to test the changes locally (or at least delete all of the configured notifications).
> refactor: add channel context and update installation params [INTEG-1669]

- apps/netlify/frontend/src/sidebar/message-processor.js
- apps/netlify/frontend/src/sidebar/message-processor.spec.js
See this [original PR](https://github.com/contentful/apps/pull/5082) and [issue](https://github.com/contentful/apps/issues/5081). Our CI checks were not passing on the original PR, so I cherry-picked the commit to open this new PR.
Replace date-fns format pattern `a..aa` with `a`. Tests were passing even with the incorrect date pattern, so I also updated the tests to be more specific, so that they will fail with the old pattern.
> fix: correct Netlify date pattern [INTEG-1670]

- packages/ecommerce-app-base/docs/README.md
- packages/ecommerce-app-base/src/SkuPicker/SkuPicker.spec.tsx
- packages/ecommerce-app-base/src/SkuPicker/SkuPicker.tsx
- packages/ecommerce-app-base/src/SkuPicker/renderSkuPicker.tsx
- packages/ecommerce-app-base/src/SkuPicker/styles.ts
- packages/ecommerce-app-base/src/types/product.ts
This PR adds functionality to the ecommerce base package to search products within the SkuPicker by sku only. 
This is to at least partially solve a customer issue that they are not able to accurately find a product using the commerce tools app when searching by sku or name. This is a consequence of the commerce tools api, as noted [here](https://github.com/contentful/apps/pull/5880), as the current search implementation will not provide unique results. 
We have introduced a prop to optionally render a "Search by sku" within the search modal itself.
When `showSearchBySkuOption` prop is not provided: 
When `showSearchBySkuOption` prop is provided: 
This can easily be seen by running storybook locally on this branch from the package itself. …
> feat: add search by sku functionality to ecommerce base package

- apps/ai-image-generator/bundle-sharp.js
Adds missing deps to `copy-sharp.js` for bundling correctly
> fix: [INTEG-1697] - Add missing deps to copysharp method

- apps/commercetools-without-search/src/config.ts
- apps/commercetools/src/config.ts
- apps/commercetools/src/dialog.ts
[Ticket](https://contentful.atlassian.net/browse/MONET-1737)
When the API URL contains a trailing / the 3rd-party API request in graph-api fails. This PR removes the '/' if there is one, inside `validateParameters` function. 
I tested locally by running this app. Only when you refresh the page, the value on the form changes but I think this is not a problem for the bug fix. There were no tests for the application.
> feat: add validation for commercetools [MONET-1737]

- apps/microsoft-teams/frontend/src/context/SdkWithCustomApiProvider.tsx
- apps/microsoft-teams/frontend/src/hooks/useCustomApi.spec.tsx
- apps/microsoft-teams/frontend/src/hooks/useCustomApi.ts
- apps/microsoft-teams/frontend/src/index.tsx
We want to support the ability for the MS Teams app to trigger a save of configurations directly.
* Expose the undisclosed API (implemented in experience packages) that allows for self installs to be triggered via the SDK (via an undocumented ability to provide a custom API to the SDK set up)
* Provide a custom SDK provider which leverages the custom API
* Provide a hook to expose the API itself
* Named it `saveConfiguration` in the API we use to make it more clear what's actually happening
> feat: introduce provider with custom api for self installs

- apps/microsoft-teams/frontend/src/context/SdkWithCustomApiProvider.tsx
- apps/microsoft-teams/frontend/src/hooks/useCustomApi.ts
The `useSDK` hook was no longer working after we introduced the `SdkWithCustomApiProvider`. The problem was that the `SDKContext` needed to be populated with a provider, which was missing.
* Just split the two contexts and include the SDK provider in the custom provider as a child element
Screenshot of config actually working:
> fix: separate custom api and sdk contexts

- apps/microsoft-teams/app-actions/package-lock.json
- apps/microsoft-teams/app-actions/package.json
- apps/microsoft-teams/app-actions/src/actions/list-channels.spec.ts
- apps/microsoft-teams/app-actions/src/actions/list-channels.ts
- apps/microsoft-teams/app-actions/src/actions/send-test.ts
- apps/microsoft-teams/app-actions/src/config.ts
- apps/microsoft-teams/app-actions/src/helpers/get-channels-list.spec.ts
- apps/microsoft-teams/app-actions/src/helpers/get-channels-list.ts
- apps/microsoft-teams/app-actions/src/helpers/index.ts
- apps/microsoft-teams/app-actions/src/types.ts
- apps/microsoft-teams/app-actions/test/fixtures/mockInstallations.ts
- apps/microsoft-teams/frontend/src/hooks/useGetTeamsChannels.ts
This PR adds a hosted app action to call our MS Teams Bot Service to get the list of channels for the teams where the Contentful app is installed for a given tenant id. This eventually displays in the channel selection modal.
We already had this stubbed out using mock data, so I just implemented actually calling the bot service to get the channels. I also decided to have the HAA get the tenant id from the installation parameters, rather than passing it from the frontend. In order to utilize some types from MS Teams, I installed the `botbuilder` package.
Deployed to our sandbox space and you are able to see the list of actual channels.
> feat: add HAA to get channels list [INTEG-1633]

- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
When a user sends a test notification from the app config page, we want them to know whether or not it succeeded.
Display toast message on success or error for the test notification:
Note: we need to make some changes in the bot service in order for the full error message to display as is shown in the screenshot above.
> feat: add toast confirmation for test message

- apps/microsoft-teams/frontend/src/components/config/EventsSelection/EventsSelection.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/constants/defaultParams.ts
- apps/microsoft-teams/frontend/src/customTypes/configPage.ts
- apps/microsoft-teams/frontend/test/mocks/mockNotification.ts
The current topic names we chose for event subscription in the app config are somewhat ambiguous and could cause us problems if we decide to support notifications for other resources in the future. It's also a bit more cumbersome to compare incoming events with the object where those notification subscriptions are specified.
* Rename the events to the app event topics
* A bit of reshuffling of files
> Rename app event topics

- apps/microsoft-teams/app-actions/src/actions/handle-app-event.spec.ts
- apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
- apps/microsoft-teams/app-actions/src/constants.ts
- apps/microsoft-teams/app-actions/src/helpers/app-installation.spec.ts
- apps/microsoft-teams/app-actions/src/helpers/app-installation.ts
- apps/microsoft-teams/app-actions/src/helpers/entry-activity.spec.ts
- apps/microsoft-teams/app-actions/src/helpers/entry-activity.ts
- apps/microsoft-teams/app-actions/src/types.ts
- apps/microsoft-teams/app-actions/test/mocks.ts
When we receive an incoming app event to our app, we need to possibly send one or more entry activity messages to MS Teams for any matching notifications in their app config parameters.
In a following PR we will send the actual messages (by calling our API endpoint) but this endpoint builds the actual message object to send and returns the result.
* Make sure the notificaitions and app instlallation params are in the type we expect
* FIlter down the whole notification set by matching content type ids and selected events
* build the object and just return it in a list for now
> feat: build enteryactity messages for API

- apps/microsoft-teams/app-actions/src/actions/handle-app-event.spec.ts
- apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
- apps/microsoft-teams/app-actions/src/actions/list-channels.ts
- apps/microsoft-teams/app-actions/src/actions/send-test.ts
- apps/microsoft-teams/app-actions/src/config.ts
- apps/microsoft-teams/app-actions/src/helpers/get-channels-list.ts
- apps/microsoft-teams/app-actions/src/services/msteams-bot-service.spec.ts
- apps/microsoft-teams/app-actions/src/services/msteams-bot-service.ts
- apps/microsoft-teams/app-actions/src/types.ts
- apps/microsoft-teams/app-actions/test/mocks.ts
Our handle app event knows what message data it needs to send and which channels it needs to send it to. The last step is to _actually_ call the API and send the messages.
* made an intentional change to error object in the result type
> feat: add support for actually sending messages

- apps/microsoft-teams/app-actions/src/actions/handle-app-event.spec.ts
- apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
- apps/microsoft-teams/app-actions/src/actions/list-channels.ts
- apps/microsoft-teams/app-actions/src/actions/send-test.ts
- apps/microsoft-teams/app-actions/src/helpers/error-handling.spec.ts
- apps/microsoft-teams/app-actions/src/helpers/error-handling.ts
Our existing error handling is a bit repetitive and non-robust (errors could still be thrown by certain actiions and not "handled".
* Provide a wrapper for our handlers
> feat: standardize error handling

- apps/microsoft-teams/app-actions/src/types.ts
- apps/microsoft-teams/app-actions/test/mocks.ts
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationViewMode/NotificationViewMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/constants/defaultParams.ts
- apps/microsoft-teams/frontend/src/customTypes/configPage.ts
- apps/microsoft-teams/frontend/test/mocks/mockNotification.ts
This PR removes the activate/deactivate toggle from a configured notification, as we decided that this is more of a V2 feature that we can implement later.
Remove the toggle from the UI and remove the `isEnabled` installation parameter since it's only purpose is to support activating/deactivating notifications.
Notifications section without the toggle on each notification:
> chore: remove notification activate toggle [INTEG-1742]

- apps/ai-image-generator/backend/package-lock.json
- apps/ai-image-generator/backend/package.json
- apps/ai-image-generator/backend/tsconfig.json
Dependabot can't upgrade TS to 5.3.2. See https://github.com/contentful/apps/pull/5657
We're getting an error "ERROR: error TS6053: File '@tsconfig/node18/tsconfig.json' not found."
Culprit seems to be a change in the internal API of TS. Issue here: https://github.com/TypeStrong/ts-node/issues/2076
* Workround here https://github.com/TypeStrong/ts-node/issues/2076#issuecomment-1824874350
> chore: upgrade TS 5.3.2 for AIIG

- apps/jira/functions/package-lock.json
- apps/jira/functions/package.json
* Upgrade to latest lodash types to unblock dependabot PR https://github.com/contentful/apps/pull/5519
* Move types to devdependencies
> chore: fix lodash types

- apps/netlify/frontend/package-lock.json
- apps/netlify/frontend/package.json
* Unblock dependabot upgrade https://github.com/contentful/apps/pull/6038
* Need to update to react-scripts v5
> chore: upgrade forma36 components

- apps/netlify/frontend/package-lock.json
* Package lock did not get updated correcly in this PR: https://github.com/contentful/apps/pull/6169/files
* Seeing build failures in prod deploy: https://app.circleci.com/pipelines/github/contentful/apps/27598/workflows/3cd626c4-3ea2-4ca9-a500-1600f1e2c4e6/jobs/87321
* Not sure what happened, but ran `npm i` again and there were some package-lock.json changes. So committing those here.
> fix: provide missing package-lock.json update

- .circleci/prettier-check.sh
- .github/dependabot.yml
- package.json
There's a problem that can arise for developers in this repository where:
* You haven't installed the root app (i.e. `npm i` at the root level)
* You make some code changes
* Your globally installed prettier has a different version than the version for this repo
* Your prettier post commit hook defers to the globally installed version (since no local is present)
* Your code gets autoformatted in a way that's incompatible with the prettier checks for this repo
* Use `npx` for all prettier invocations (directly or indirectly) and fix these to match the declared version
* Prevent dependabot from upgrading prettier and instead force a manual upgrade
> chore: pin prettier explicitly to installed version

- apps/microsoft-teams/app-actions/src/actions/send-test.ts
- apps/microsoft-teams/app-actions/src/errors.ts
- apps/microsoft-teams/app-actions/src/helpers/error-handling.ts
- apps/microsoft-teams/app-actions/src/helpers/get-channels-list.ts
- apps/microsoft-teams/app-actions/src/types.ts
The MS teams bot service no longer returns simple strings but instead returns error objects. We need to adjust our expectations and handling for this error response as a result.
> fix: handle errors from ms teams service correctly

- .circleci/prettier-check.sh
In the recent prettier fix we introduced a problem.
When we switched from calling prettier directly to calling it indirectly via `npm run` we failed to realize that npm run sends data to STDOUT which messed with the logic of our script here: https://github.com/contentful/apps/blob/master/.circleci/prettier-check.sh#L18
Basically our script expects NO OUTPUT when the prettier check is okay.
* add the `--silent` flag to remove echoing of the command
> fix: silence excess output

- apps/microsoft-teams/frontend/src/App.tsx
The purpose of this PR is to update the app name that will be passed on all Sentry exceptions, to be consistent with the backend implementation. 
Perhaps eventually this can be a constant, for all apps, in the frontend-toolkit AND a constant in the future node-toolkit. For now, I have noted how these should be consistent in [this](https://contentful.atlassian.net/wiki/spaces/ECO/pages/4479189315/WIP+Sentry+for+Integrations) WIP documentation.
> chore: update sentry app name to support consistency

- apps/dropbox/package-lock.json
- apps/dropbox/package.json
- apps/frontify/package-lock.json
- apps/frontify/package.json
- apps/mux/package-lock.json
- apps/mux/package.json
- packages/dam-app-base/package-lock.json
Update to unblock https://github.com/contentful/apps/pull/6200 . Force a version bump since it appears some downstream dependencies are incompatible with latest version of f36 components
* Upgrade f36 in dam app
* Pin dam app version in apps like dropbox and mux, since lerna tries to build them _against the change in this PR_, which they fail. These apps will need to update to this version of the dam app indepdently
> fix(deps): bump @contentful/f36-components from 4.40.6 to 4.59.1

- apps/ai-content-generator/src/hooks/dialog/useAI.spec.ts
- apps/bedrock-content-generator/src/hooks/dialog/useAI.spec.ts
chore: fix flaky AICG tests
We have some flaky tests, e.g. https://app.circleci.com/pipelines/github/contentful/apps/27834/workflows/8c815bcb-0aff-4164-a6d0-a1c76c1920a5/jobs/88408?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary . Let's disable them.
> chore: skip flaky AICG tests

- apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
- apps/microsoft-teams/app-actions/src/actions/list-channels.ts
- apps/microsoft-teams/app-actions/src/actions/send-test.ts
- apps/microsoft-teams/app-actions/src/helpers/get-channels-list.ts
- apps/microsoft-teams/app-actions/src/services/msteams-bot-service.spec.ts
- apps/microsoft-teams/app-actions/src/services/msteams-bot-service.ts
- apps/microsoft-teams/app-actions/src/types.ts
- apps/microsoft-teams/app-actions/test/mocks.ts
- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/hooks/useGetTeamsChannels.ts
- apps/microsoft-teams/frontend/src/index.tsx
The purpose of this PR is to pass headers from the app actions to the ms-teams-bots-service API. 
Generally we would expect headers that describe the user and browser Contentful details, but since we are using app actions, we have to pass these headers a bit more manually. App actions already have a request context that we can utilize for this to get some information. 
I decided to add `requestContext` as an argument for each method calling the MSTeamsBotService, instead of instantiating the service with the requestContext, to ensure the service remains flexible, and so that we don't need to instantiate it multiple times to save an extra argument . Though I would be happy to adjust, it seems to me that there are pros and cons to both approaches.
> feat: add headers to be passed to bots service

- apps/saleor/package-lock.json
- apps/saleor/package.json
* Saleor is trying to upgrade to a version of the ecommerce package is not compatible with https://github.com/contentful/apps/pull/6275
* Pin ecomm package
> chore: pin saleor to ecomm package

- apps/microsoft-teams/frontend/package.json
- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
Ideally we don't want to rely on a logout flow from MS where you have to select which account you are logging out of if you want to switch accounts on the MS Teams app config page. After digging around the MSAL documentation, I same across this [promptless logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/e7a55511680aec602310f63db0bb5b7d2b07fab3/lib/msal-browser/docs/logout.md#promptless-logout)
Implemented promptless logout. This required adding the `login_hint` optional claim for our app in the MS Entra admin center. Then, I passed in the logged in account to the `logoutPopup` method in order to create a logout experience where you don't need to select an account. You still do see a popup, but I could not find a away to work around this.
In addition, I …
> feat: improve logout flow for MS Teams [INTEG-1785]

- apps/vercel/src/App.tsx
- apps/vercel/src/components/config-screen/ConfigScreen.styles.tsx
- apps/vercel/src/components/parameterReducer.ts
- apps/vercel/src/constants/defaultParams.ts
- apps/vercel/src/hooks/useInitializeParameters.tsx
- apps/vercel/src/hooks/uzeInitializeParameters.spec.tsx
- apps/vercel/src/locations/ConfigScreen.tsx
- apps/vercel/src/types/index.ts
- apps/vercel/test/mocks/mockSdk.ts
We want a naive way to verify the status of a vercel access token, this adds that implmentation. This is intentionally very simple, as we flush out technical implementations the network call can be adjusted and better seperated.
Ticket: https://contentful.atlassian.net/browse/INTEG-1692 
1.) Uninstall the app in development if installed, and re-install the custom app
2.) Confirm error is thrown when trying to install without a token
3.) Follow the detailed instructions for creating a vercel token, and attempt to install after token has been created
NOTE: Token cannot be accessed again after creation
4.) Malform the saved vercel token, and verify error status is displayed
> feat: [INTEG-1692] - Add status under token field

- apps/commercetools/package-lock.json
- apps/commercetools/package.json
The latest version of ecommerce app breaks commerce tools.
* Pin to latest known working version.
> fix: pin ecommerce-app to 3.5.1

- apps/sap-commerce-cloud-with-air/frontend/package-lock.json
- apps/sap-commerce-cloud-with-air/frontend/package.json
- apps/sap-commerce-cloud/package-lock.json
- apps/sap-commerce-cloud/package.json
- examples/commercelayer/package-lock.json
- examples/commercelayer/package.json
To prevent inadvertent upgrades due to lerna symlinking to the local version instead of using the version specified in the dependency, we will hard pin all `ecommerce-app-base` dependency references.
> chore: pin ecommerce app to explicit version

- apps/brandfolder/package-lock.json
- apps/brandfolder/package.json
- apps/wistia-videos/package-lock.json
- apps/wistia-videos/package.json
To prevent inadvertent upgrades due to lerna symlinking to the local version instead of using the version specified in the dependency, we will hard pin all `dam-app-base` dependency references.
> chore: pin dam app to explicit version

- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.ts
In order to ensure that space admins are saving their changes after creating/editing/deleting notifications, we want to give a user a warning that they need to save the config page in order for their changes to persist. Note that this is an interim solution while we work on triggering a save from the app config page.
Per our designs, after a user creates, edits, or deletes a notification, they will see a confirmation that notifications are updated, followed by a warning that they need to save the app config page.
I also implemented this for the access section/tenant id section:
In our development space, make changes to the notifications section and authenticate to different tenants to see the notifications.
> feat: add notifiers when config page should be saved [INTEG-1802]

- apps/microsoft-teams/frontend/src/components/config/ChannelSelectionModal/ChannelSelectionModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ChannelSelectionModal/ChannelSelectionModal.styles.ts
- apps/microsoft-teams/frontend/src/components/config/ChannelSelectionModal/ChannelSelectionModal.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.styles.ts
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.tsx
When selecting a Channel or Content Type from the `<ContentTypeSelectionModal>` or `<ChannelSelectionModalProps>`, clicking anywhere inside the table's row should select that option.
This is from a Mob QA feedback session demo'ing MS-teams.
Instead of adding the `onClick` callback to the `<Radio>`, add it to the `<Table.Row>`.  React will complain that you did not provide a `onChange` handler to the `<Radio>`, so just add a noop to placate react.  If there is a better solution, I'm all ears :)
Tested in "Apps - Development and Testing Org", "Microsoft Teams (development)", master env.
None
> ContentTypeSelectionModal & ChannelSelectionModalProps - Clicking entire row should select the option.

- apps/mux/package.json
Mux is on fire right now when we moved to webpack5. We have reverted back to a previous bundle while we figure out a longterm fix to this issue.
Removing the deploy scripts for mux so our customers can stay on the stable version while we fix the probelm.
> chore: freezes mux while we troubleshoot signing secrets

- apps/microsoft-teams/frontend/package-lock.json
- apps/microsoft-teams/frontend/package.json
- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.styles.ts
- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
- apps/microsoft-teams/frontend/src/configs/authConfig.ts
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/context/AuthProvider.tsx
- apps/microsoft-teams/frontend/src/utils/msGraphApi.spec.ts
- apps/microsoft-teams/frontend/src/utils/msGraphApi.ts
- apps/microsoft-teams/frontend/test/mocks/api/handlers.ts
- apps/microsoft-teams/frontend/test/mocks/api/server.ts
- apps/microsoft-teams/frontend/test/mocks/mockMsal.ts
- apps/microsoft-teams/frontend/test/setup.ts
- apps/microsoft-teams/frontend/tsconfig.json
- apps/microsoft-teams/frontend/vite.config.ts
This PR updates the access section of the MS Teams app config page to display the organization name and logo after a user authenticates with Microsoft. 
While the tenant Id and the username can be accessed from the MSAL hook, we need to call the MS Graph API in order to get the organization name and logo. I created a new `msGraphApi` util class to work with the API. This class handles getting the access token for the API request, calling the correct endpoints, and error handling. 
If there is an error getting the organization name and logo, these items won't display and a notification will show saying that there is error getting organization details
In order to create tests for `msGraphApi`, I utilized MSW to mock the HTTP requests. 
Navigate to the MS Teams development space and …
> feat: display MS org name logo [INTEG-1782]

- apps/microsoft-teams/frontend/src/components/config/DuplicateModal/DuplicateModal.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
Update the copy of `<DuplicateModal>` to better explain to a user their options when they are attempting to make changes to an existing notification.
1. Confirm option => "If yes, edits to entry actions will apply to your existing notification."
2. Cancel option => "If you prefer to cancel, you can then edit the content type or Teams channel."
This is part of the Mob QA feedback for MS Teams.
> Clarify update/cancel duplicate notification instructions for MS Teams

- apps/microsoft-teams/frontend/src/components/config/ConfigPage/ConfigPage.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx
Lifting the state up <NotificationSection> up to <ConfigPage> will enable the <ConfigPage> to be run validations on a currently open (in edit mode) notification.
There is an [existing concept in MS Teams of whether or not a notification is being edited](https://github.com/contentful/apps/blob/master/apps/microsoft-teams/frontend/src/components/config/NotificationsSection/NotificationsSection.tsx#L29).  As part of the effort to improve validations for MS-Teams, we want to check to see if there are any "pending changes" when a user attempts to save by clicking the save button in the top right.  In order to detect any pending changes from the `<ConfigPage>`, the `notificationIndexToEdit` state needs to be lifted up one level.
Tested manually and with unit tests.
None
> Refactor(MS-Teams) - Lift "notification index to edit" state from <NotificationSection> to <ConfigPage>

- apps/microsoft-teams/frontend/src/components/config/ConfigPage/ConfigPage.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/ConfigPage/ConfigPage.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/test/mocks/mockSdk.ts
Add a validation to MS Teams `onConfigure()` method that checks to see if there are any "pending changes".  If there are, inform the user via modal that they need to cancel/save their changes and return false (do no update configuration).  
The User has pending changes because they are in the process of editing a notification, but have not saved their work.
Use the existing concept of "pending changes", see `notificationIndexToEdit`.  If so launch a modal and return false.
1. Launch MS Teams FE locally and navigate to [MS Teams development space](https://app.contentful.com/spaces/zgiu00cobrsj/apps/4BaHsPHryAsKkDuNFdKRVM).  Invoke pending changes by editing an existing notification, or creating a new one.  Even if the notification is valid, if it is not saved we should inform the user and …
> MS Teams - validate "Pending Changes" when User clicks top-right (widgetRenderer?) save.

- apps/microsoft-teams/app-actions/src/types.ts
- apps/microsoft-teams/app-actions/test/mocks.ts
- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.styles.ts
- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
- apps/microsoft-teams/frontend/src/components/config/AccessSectionCard/AccessSectionCard.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/AccessSectionCard/AccessSectionCard.styles.ts
- apps/microsoft-teams/frontend/src/components/config/AccessSectionCard/AccessSectionCard.tsx
- apps/microsoft-teams/frontend/src/components/config/ConfigPage/ConfigPage.tsx
- apps/microsoft-teams/frontend/src/components/config/parameterReducer.ts
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/constants/defaultParams.ts
- apps/microsoft-teams/frontend/src/customTypes/configPage.ts
- apps/microsoft-teams/frontend/test/mocks/mockSdk.ts
In order to prevent a user from having to regularly authenticate to Microsoft on the app config page, this PR updates the app installation parameters so that the org details (name, logo, and username) are persisted. 
Persist additional information from Microsoft in the installation parameters. Also updated error handling for the Auth flow to align with designs. 
Here's the error a user sees if they are unable to authenticate to Microsoft
Here's the error a user sees if they cannot get the organization details from Microsoft
Here's an updated version of what successful authentication looks like (removed username)
Run the MS Teams frontend app locally in our testing environment
This PR introduces new installation parameters, so an app might need to be reinstalled to see the full changes.
> feat: save org details as params from auth flow [INTEG-1818]

- apps/microsoft-teams/frontend/src/components/config/NotificationEditMode/NotificationEditMode.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/NotificationEditModeFooter/NotificationEditModeFooter.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.spec.ts
- apps/microsoft-teams/frontend/src/helpers/configHelpers.ts
This PR ensures that the `Test Message` button is disabled when a notification is incomplete. Also, it updates the error handling for sending the message to ensure that an error message is displayed.
`Test Message` button should be disabled for incomplete notifications. The error handling for the test message was built on a previous implementation where the body had an errors array, this is now updated to be a single error object. Note that there is additional work that needs to be done in another PR in the bot service to display the proper error message, currently the error message says `malformed MsTeamsBotServiceResponse returned from MsTeamsBotService API`.
Deployed to sandbox and sent a test to a deleted channel to see an error message.
> feat: disable test message and update test errors [INTEG-1812]

- examples/function-mock-shop/src/locations/Field.tsx
While playing with the MockShop tutorial I encountered a bug that was caused by the fact I used a different field id.
This should be handled by the app sdk instead of by the app implementation itself.
Also added the ability to remove a product that was already set on the field
Make use of `useFieldValue` with `sdk.field.id`
> remove hardcoded fieldId []

- apps/microsoft-teams/frontend/package-lock.json
- apps/microsoft-teams/frontend/package.json
Bump MS-teams version of Forma-36, to use the new `ModalConfirm` Component that has an `x` close icon in the header.
Tested locally
> dependency(forma-36): Bump MS-Teams version of forma-36 to 4.60.1

- apps/dropbox/src/index.js
This solves a customer issue where they are not able to add non-image file types to their Contentful entry using the Dropbox app.
Remove the file type restrictions on the Dropbox picker and ensure that if there isn't a thumbnail image, the app won't break. Confirmed that a non-image file can be added to an entry and here's how it renders.
Eventually we can update this to have the same fallback images that are used in the Bynder app.
Tested locally.
> fix: support non-image file types in Dropbox

- .circleci/config.yml
- package.json
We publish two packages in this repo: `dam-app-base` and `ecommerce-app-base`. This PR migrates the publishing of those packages from npm to GitHub packages. This is PR 2 of 3 after merging in this first one: https://github.com/contentful/apps/pull/6608
Followed directions in the migration instructions.
> chore: migrate app-base package publishing to GitHub [INTEG-1809]

- .contentful/vault-secrets.yaml
Builds failed after merging the last PR (https://github.com/contentful/apps/pull/6625). This is an attempt to fix it to ensure that the `semantic-release` policy matches in the CircleCI config and `vault-secrets.yml`.
> fix: change semantic release policy in vault config

- apps/microsoft-teams/frontend/src/constants/contentTypeLimit.ts
- apps/microsoft-teams/frontend/src/hooks/useGetContentTypes.spec.ts
- apps/microsoft-teams/frontend/src/hooks/useGetContentTypes.ts
In order to support customers who have 100+ content types, we need to batch multiple requests (of 100 at a time, configurable) to retrieve all content types.  This also will be needed for pagination.
I chose to use a `while` loop, despite the fact that I usually despise `while` loops.  But in this case I think it makes the most sense, since we know we will have to enter a loop at least one time to get the first 100 content types, and then _if_ we have to batch request more, then we can restart the loop.  I'm definitely open to other ways of solving this.
Unit testing and locally
This hook is a good candidate to be moved to the [integration-frontend-toolkit](https://github.com/contentful/integration-frontend-toolkit/tree/master).  In the name of speed/scope this PR will implement the hook …
> MS-Teams - batch requests to fetch content types.

- .circleci/config.yml
- .contentful/vault-secrets.yaml
As part of the GH package migration, we changed the `semantic-release-ecosystem` policy to `semantic-release`. However, this was preventing our packages from publishing to npm, so we are reverting this back.
> fix: change policy back to semantic-release-ecosystem

- .circleci/config.yml
- package.json
The original PR (https://github.com/contentful/apps/pull/6625) was reverted (https://github.com/contentful/apps/pull/6647) while we worked to troubleshoot the GitHub packages migration. We are now ok to reapply these changes now that we have confirmed that the migration script should be updated with the vault policy used in this repo.
Reapply changes in the original PR, with the exception of changing the vault policy. It should remain as `semantic-release-ecosystem`, and the GH package to npm mirroring script has been updated accordingly.
> chore: reapply changes to migrate to GitHub packages [INTEG-1809]

- apps/microsoft-teams/frontend/package-lock.json
- apps/microsoft-teams/frontend/package.json
- apps/microsoft-teams/frontend/src/components/config/ContentTypeSelectionModal/ContentTypeSelectionModal.tsx
- apps/microsoft-teams/frontend/src/components/config/DebouncedSearchInput/DebouncedSearchInput.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/DebouncedSearchInput/DebouncedSearchInput.tsx
- apps/microsoft-teams/frontend/src/components/config/SearchableList/SearchableList.spec.tsx
- apps/microsoft-teams/frontend/src/components/config/SearchableList/SearchableList.tsx
- apps/microsoft-teams/frontend/src/constants/configCopy.ts
Add the ability for Users to search for a specific content type by searching for the content type's `id, displayField, name, or description` attributes.
1. No content types were returned from `useGetContentTypes()`.  In this case we should show the "No content types" empty state, with the search input disabled.
2. Ka-boom, an error occurred while attempting to retrieve content types.  In this case, we should show the Error state, without the search input.
3. N content types were returned from `useGetContentTypes()` and a search query has filtered the set down to a subset (could possibly be entire set).  In this case, we should render the search input.
4. N content types were returned from `useGetContentTypes()` and a search query has filtered the set down to 0 results, i.e. failed search. …
> Microsoft Teams - add fuzzy search for content types

- .contentful/vault-secrets.yaml
This PR removes the `npm-read` and `packages-read` vault policies from this repo. We are not using private packages in this repo so we should be able to safely remove these policies from here.
As part the GH package migration we are removing `npm-read` from repos. We should be ok removing the new `packages-read` policy as well since this is a public repo that is not using private packages.
> chore: remove npm-read and packages-read policies [INTEG-1822]

- apps/microsoft-teams/app-actions/src/helpers/entry-activity.spec.ts
- apps/microsoft-teams/app-actions/src/helpers/entry-activity.ts
When we unpublish or delete an entry, the payload we get from the AppEvent is _not_ a regular Entry. Instead it's of type `DeletedEntry`. It looks like this:
```json
{
"sys": {
"type": "DeletedEntry",
"id": "19bRpH5BASo0WIu9i2vH6Z",
"space": {
"sys": {
"type": "Link",
"linkType": "Space",
"id": "zl9er5nqimd0"
}
},
"environment": {
"sys": {
"id": "master",
"type": "Link",
"linkType": "Environment"
}
},
"contentType": {
"sys": {
"type": "Link",
"linkType": "ContentType",
"id": "blogPost"
}
},
"revision": 7,
"createdAt": "2024-03-15T18:37:58.806Z",
"updatedAt": "2024-03-15T18:37:58.806Z",
"deletedAt": "2024-03-15T18:37:58.806Z"
}
}
```
The main difference is it's missing fields and thus missing a title.
Our logic was choking on the missing fields.
* Provide a backup title if fields are …
> fix: handle DeletedEntry entry type

- apps/mux/app-actions/package-lock.json
- apps/mux/app-actions/package.json
- apps/mux/app-actions/src/actions/get-jwt-tokens.spec.ts
- apps/mux/app-actions/src/actions/get-jwt-tokens.ts
- apps/mux/frontend/src/index.tsx
As part of the effort to get the Mux app functional again, we need to move token signing to the backend (since jsonwebtoken is no longer supported in browsers).
This PR introduces token signing in a backend app action. Later, the front end will be updated to call these values instead of attempting to sign on the frontend.
* Use jsonwebtoken and move signing to app action
> feat: add mux token signing as HAA

- apps/microsoft-teams/app-actions/src/actions/handle-app-event.spec.ts
- apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
- apps/microsoft-teams/app-actions/src/constants.ts
- apps/microsoft-teams/app-actions/src/services/msteams-bot-service.ts
- apps/microsoft-teams/app-actions/src/types.ts
- apps/microsoft-teams/frontend/src/hooks/useGetTeamsChannels.ts
**DO NOT MERGE**
Extend the existing `"handle-app-event"` app action to also handle Workflows.  
In the interest of time, as well as prototyping/learning we made the explicit choice
to re-use/extend this "app-events" app-action to handle "workflow" events as well.
This block of code to handle workflow topics is intentionally repetative and intrusive.
The end goal is to create a new app action to specifically handle "workflow" events.
Ideally, at that time, it will be a simple copy/paste operation, leaving this
app-action unchanged.
So, obviously an alternative would be to create a distinct app-action solely to handle workflows.  I'm not sure what the pros/cons of that decision would be beyond cleaner code. 
Unit tested.
1. Exact structure/format of payload coming to this app from …
> Extend "handle-app-event" to support workflows

- apps/dropbox/package-lock.json
- apps/frontify/package-lock.json
- apps/image-focal-point/package-lock.json
- apps/saleor/package-lock.json
The purpose of this PR is to fix the misaligned packages and their package.locks. It looks like this issue came from a a few dependabot updates. 
I went into each app and ran the `npm ci` command, which is the command that is throwing [this](https://app.circleci.com/pipelines/github/contentful/apps/29609/workflows/cd39ccc4-213a-4d2d-b331-eaf54cd544bc/jobs/96794) pipeline error. If the package and package.lock were not aligned, I ensured they were. 
I am curious how this happens 🤔 I am assuming the dependabot updates happen so quickly that they merge one after the other and do not "rebase" or pull from master to ensure the packages are in sync, but am curious if others have a hypothesis.
> fix: pipeline errors from misaligned packages

- apps/optimizely/package-lock.json
This PR is is a follow-up to [this](https://github.com/contentful/apps/pull/6987) one. This includes a package fix for Optimizely based on [this](https://app.circleci.com/pipelines/github/contentful/apps/29678/workflows/f27de892-f534-4c0c-a1ae-9485ffcec7f5/jobs/97134) current error within the CI.
I originally went into each app and ran the `npm ci` command, and if the package and package.lock were not aligned, I ensured they were. I must have missed Optimizely in the first round 🤔
> chore: fix optimizely package

- apps/vercel/contentful-app-manifest.json
- apps/vercel/package.json
Our deploys were failing (silently! 😢 ) for Vercel deploy to production:
```
> **********-app-scripts upload --ci --bundle-dir ./dist --organization-id ${DEFINITIONS_ORG_ID} --definition-id 4QsJrTg4fFjX7UmQDkeayq --token ${CONTENTFUL_CMA_TOKEN}
- Validating your input...
----------------------------
App Actions found in ./**********-app-manifest.json.
----------------------------
Creation error:
Something went wrong while creating the app upload.
Message:  ENOENT: no such file or directory, scandir 'dist'
```
Reason appears to be we forgot to update the target directory for the build from `dist` (what vite uses by default for the frontend) to `build` (what we use for our parent apps that bundle front end with app actions)
After fixing and testing (on sandbox) everything in order:
```
$ …
```
> fix: use correct build directory for vercel

- apps/vercel/app-actions/src/actions/get-preview-envs.spec.ts
- apps/vercel/app-actions/src/actions/get-preview-envs.ts
- apps/vercel/contentful-app-manifest.json
The `PreviewEnvironment` objects returned from our API look like this:
```
{
"total": 2,
"limit": 100,
"skip": 0,
"sys": {
"type": "Array"
},
"items": [
{
"name": "Basic Website Preview",
"description": "New test",
"sys": {
"type": "PreviewEnvironment",
"id": "6zBSooMWPFS3T5KNisBPQI",
"version": 2,
"space": {
"sys": {
"type": "Link",
"linkType": "Space",
"id": "89g1bvvv07u0"
}
},
"createdAt": "2024-03-13T19:50:18Z",
"updatedAt": "2024-03-18T14:38:45Z"
},
"configurations": [
{
"url": "http://www.example.com",
"contentType": "author",
"enabled": true,
"example": false
},
{
"url": "http://www.example.com",
"contentType": "food",
"enabled": true,
"example": false
}
]
},
{
"name": "Test",
"description": "",
"sys": {
"type": "PreviewEnvironment",
"id": "45jZnNXTa1WgQg4WQkXSjF",
"version": 0, …
```
> fix: remove content type param

- apps/microsoft-teams/app-actions/src/actions/handle-app-event.spec.ts
- apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
- apps/microsoft-teams/app-actions/src/helpers/entry-activity.spec.ts
- apps/microsoft-teams/app-actions/src/helpers/entry-activity.ts
- apps/microsoft-teams/app-actions/src/types.ts
For `create`, `unpublish`, and `delete` events, we do not have access to the entry title. This needs to be addressed to unblock us on the testing/validation from Microsoft since this was labeled as a mandatory fix from them.
So we are no going to pass `entryId` as part of the payload for the `entry_activity_message` endpoint. There is a companion PR in the bot service to implement changes in the adaptive card.
We construct a title with the entry ID in the app action and displayed that in the adaptive card. I kept this login in there as a fallback.
> feat: add entry id to EntryActivity [INTEG-1922]

- apps/vercel/frontend/src/components/common/GrayInfoBox/GrayInfoBox.spec.tsx
- apps/vercel/frontend/src/components/common/GrayInfoBox/GrayInfoBox.styles.ts
- apps/vercel/frontend/src/components/common/GrayInfoBox/GrayInfoBox.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalModal.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalModal.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalModal.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InfoTable/InfoTable.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InfoTable/InfoTable.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InfoTable/InfoTable.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InformationalTables.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InformationalTables.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InformationalTables.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/PreviewPathInfoNote/PreviewPathInfoNote.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/PreviewPathInfoNote/PreviewPathInfoNote.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/PreviewPathInfoNote/PreviewPathInfoNote.tsx
- apps/vercel/frontend/src/constants/copies.ts
- apps/vercel/frontend/src/constants/styles.ts
- apps/vercel/frontend/tsconfig.json
- apps/vercel/frontend/vite.config.ts
This PR adds the InformationalModal that will help guide the user when configuring their content types and preview paths on the Vercel config page. 
Designs: https://www.figma.com/file/3zhaUVyNKPZOFjVPL7mG00/Vercel?type=design&node-id=758-43738&mode=design&t=VTfQ2mppRDRTqXiM-4
I created several new components to create this modal, some reusable and some very specific. 
Render the modal from the config page link "View more examples".
End result screenshot (can't quite include the footer 😅 )
1. Determine if there should be user feedback onClick of the copy buttons that are throughout the modal. Right now the copy functionality works, but there is nothing telling the user that something has been copied to their clipboard.
> feat: Add informational table modal to config page

- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionList/ContentTypePreviewPathSelectionList.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionList/ContentTypePreviewPathSelectionList.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.spec.tsx
- apps/vercel/frontend/src/utils/getAvailableContentTypes.spec.ts
- apps/vercel/frontend/src/utils/getAvailableContentTypes.ts
- apps/vercel/frontend/test/mocks/index.ts
- apps/vercel/frontend/test/mocks/mockContentTypePreviewPathSelections.ts
- apps/vercel/frontend/test/mocks/mockContentTypes.ts
- apps/vercel/frontend/tsconfig.json
- apps/vercel/frontend/vite.config.ts
The purpose of this PR is to enforce the concept that you can only configure a preview path per content type. Therefore the dropdown selection of the content types filters down appropriately based on selections. 
I created a utility function called `getAvailableContentTypes`. I chose not to make this a hook as there is no React logic involved. This utility function takes into account the available contentTypes, the already selected contentTypes within the configuration, and if there exists a current selection within the row. 
I also only render the Add Content Type button if there are more contentTypes to select from and configure.
https://github.com/contentful/apps/assets/58186851/579cf497-1e74-4435-802f-8ff0831154e5
Feel free to add content type and preview path configurations, ensuring …
> Limit content type configuration

- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionList/ContentTypePreviewPathSelectionList.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.tsx
- apps/vercel/frontend/src/components/parameterReducer.ts
- apps/vercel/frontend/src/customTypes/configPage.ts
The purpose of this PR is to improve the current approach to saving the `contentType` and `previewPath` parameters on the Vercel config page, from a user and technical perspective. 
The original approach was using an awkward debounce (it would lose focus on the input when the debounce ended, blah!), and required that the user input a `contentType` AND `previewPath` to save the parameters (even though this wasn't obvious). We are now requiring that the user input a `contentType`, and sequentially enabling the `previewPath` input field once this `contentType` is filled out. It is not mandatory to have a `previewPath` per `contentType` in order to save the config. Having this mandatory `contentType` helps immensely from a technical standpoint in order to update data and app installation …
> feat: enforce contentType requirement when configuring Vercel

- apps/vercel/app-actions/src/helpers/build-preview-urls-for-content-types.spec.ts
- apps/vercel/app-actions/src/helpers/build-preview-urls-for-content-types.ts
When the content preview widget gets a preview URL, it needs to "interpolate" any tokens in the string demarcated by `{` and `}`.
Because we were using `searchParams.set` our path value was encoding those curly brackets as `%7B` and `%7D` respectively, and the value was not getting correctly interpolated.
* Just manually decode the curly brackets and leave everything else in it's place
> fix: decode curly brackets

- apps/vercel/app-actions/src/helpers/build-preview-urls-for-content-types.spec.ts
- apps/vercel/app-actions/src/helpers/build-preview-urls-for-content-types.ts
We allow users to save a confiiguration but not specify a preview path for a given content type (ie they can leave it blank). In this case, we want to make sure the configuration doesn't get included in the provided preview environment.
* Don't include if the (trimmed) preview path is not found
> fix: don't include configuration if preview path not specified

- examples/asset-upload/.gitignore
- examples/commercelayer/.gitignore
- examples/compare-entries/.gitignore
- examples/dam-app/.gitignore
- examples/ecommerce-app/.gitignore
- examples/editor-assignment/.gitignore
- examples/function-potterdb-rest-api/.gitignore
- examples/function-potterdb/.gitignore
- examples/home-location/.gitignore
- examples/last-fm/.gitignore
- examples/nextjs/.gitignore
- examples/page-location/.gitignore
- examples/typescript-github-action/.gitignore
- examples/typescript/.gitignore
- examples/vite-react/.gitignore
- examples/vue/.gitignore
I learned recently that using `npm run upload` will automatically create an `.env` file with the OrganizationId, AppDefinitionId and **Access Token**.
We don't want customers to accidentally upload their access token to their git repository as that would create a serious security risk.
Therefore I updated all `.gitignore` files in the app examples to ignore `.env` files.
> Add .env file to gitignore of app examples []

- examples/function-appevent-filter/javascript/example.js
- examples/function-appevent-filter/typescript/example.ts
The errors field has been removed for appevent.filter functions, as there is no way to have a partial success of an appevent filter function.
> fix: remove errors field from appevent-filter example response [EXT-4976]

- apps/vercel/frontend/src/clients/Vercel.spec.ts
- apps/vercel/frontend/src/clients/Vercel.ts
- apps/vercel/frontend/src/customTypes/configPage.ts
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
- apps/vercel/frontend/test/mocks/index.ts
- apps/vercel/frontend/test/mocks/mockDeploymentSummary.ts
The purpose of this PR is to render the list of api-paths dynamically on the config page. 
We first fetch the latest `deploymentId`, scoped by the selected projectId, and use this `deploymentId` to then fetch a `deploymentSummary`. We filter this data based on `serverlessFunctions` that are of type `Page` and include 'api' within the path. 
https://github.com/contentful/apps/assets/58186851/8d235ef1-802e-4fd0-bec1-67588499c845
Paste a valid token, select a project, and select an api path on the vercel config page. You should be able to change projects and render the new list of paths as well. 
As you will notice in the comments I have added there are a few follow-up items: 
1. Ensure we are scoping the `listDeploymentSummary` endpoint appropriately by team. It seems that if we scope by …
> chore: Add functionality to fetch apiPaths

- examples/function-appevent-filter/typescript/package-lock.json
- examples/function-appevent-filter/typescript/package.json
Fixes types on example appevent-filter
> chore: bump NAT version in function-appevent-filter example [EXT-4978]

- apps/vercel/frontend/src/clients/Vercel.ts
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSection.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.spec.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
The purpose of this PR is to do some minor cleanup with the configuration of Api paths on the Vercel configuration page. 
1. I ensured that when the user changes the project, but there is an already selected API path, then it clears this state so as not to render API paths that may not existed with the new project. 
2. I added a broader test for the Config page
3. I tested pretty thoroughly that the list of deployments returned from Vercel does in fact return the deployments in order of most recent to least recent. I added a note within the code about this.
> chore: Vercel API path selection clean-up

- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.styles.ts
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.styles.ts
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionList/ContentTypePreviewPathSelectionList.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionList/ContentTypePreviewPathSelectionList.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalModal.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalModal.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InfoTable/InfoTable.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InformationalTables.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/PreviewPathInfoNote/PreviewPathInfoNote.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/PreviewPathInfoNote/PreviewPathInfoNote.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/PreviewPathInfoNote/PreviewPathInfoNote.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.styles.ts
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.tsx
- apps/vercel/frontend/src/constants/copies.ts
- apps/vercel/frontend/src/locations/ConfigScreen.styles.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
- apps/vercel/frontend/tsconfig.json
- apps/vercel/frontend/vite.config.ts
The purpose of this PR is to accomplish the following: 
1. Always render the Add Content type button, but disable it when there are no more content types to select (Mob QA feedback). 
2. Consolidate the sections of the Config page into fewer distinct sections based on design updates. 
3. Add functioning href's into the Config page links. 
4. Adjust some of the copies and layouts on the config page per design updates (small amount of spacing here and there). Most copies are not yet finalized so there is a follow-up ticket to finalize copies. Ensured there is a `marginBottom` to the entire page itself. 
I abstracted the authentication logic into its own section/component, as I foresee much more logic to be added and isolated here as we flesh this section out. I also adjusted some file …
> chore: add design updates for Vercel config page

- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalModal.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalModal.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InfoTable/InfoTable.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InformationalTables.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InformationalTables.tsx
- apps/vercel/frontend/src/components/parameterReducer.ts
- apps/vercel/frontend/src/constants/copies.ts
- apps/vercel/frontend/src/constants/defaultParams.ts
- apps/vercel/frontend/src/customTypes/configPage.ts
- apps/vercel/frontend/src/locations/ConfigScreen.spec.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
The purpose of this PR is to progressively render the sections on the config page as the user fills out certain steps. Additionally, I adjusted some of the copies and spacing on the informative modal on the config page to match the designs. 
The user will not be able to select a project until there is a valid access token, they will not be able to select an API path until there is a project selected, and they will not be able to configure content types and preview paths until all the above is complete. 
The spacing changes within the modal can be seen below:
Follow the workflow as described above ^
> feat: conditionally render config page sections

- apps/vercel/app-actions/src/actions/get-preview-envs.ts
- apps/vercel/app-actions/src/helpers/build-preview-urls-for-content-types.spec.ts
- apps/vercel/app-actions/src/helpers/build-preview-urls-for-content-types.ts
- apps/vercel/app-actions/src/helpers/fetch-app-installation-parameters.ts
- apps/vercel/app-actions/src/types.ts
- apps/vercel/app-actions/test/mocks.ts
We want to use the selected api path from Vercel configuration page, this adds the configured `selectedApiPath` pulled from app installation parameters
Ticket: https://contentful.atlassian.net/browse/INTEG-2004
> chore: [INTEG-2004] - Update app installation parameters

- apps/vercel/frontend/src/components/common/Select/Select.styles.ts
- apps/vercel/frontend/src/components/common/Select/Select.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelect/ApiPathSelect.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelect/ApiPathSelect.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.styles.ts
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelect/ProjectSelect.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelect/ProjectSelect.tsx
- apps/vercel/frontend/src/constants/copies.ts
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
With respect to the Vercel config page, the purpose of this PR is the following: 
1. Adjust the error state for an invalid authentication pasted token
2. Adjust the empty state for when projects do not exist
3. Update all of the page copies to align with designs
4. Update layout of Content type section
The approach is fairly straightforward - removed the original "Status" badge that was used for the authentication section and instead placed the error message as per the [designs](https://www.figma.com/file/3zhaUVyNKPZOFjVPL7mG00/Vercel?type=design&node-id=857-15326&mode=design&t=8txI8tLGkelAsTuO-4). See below:
Additionally, ensured that the Content type field and Preview path field each have their own labels (previously it was one label per row- see below). 
1. More error states and empty …
> feat: add authentication token error to field

- apps/vercel/frontend/src/components/common/Select/Select.tsx
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionList/ContentTypePreviewPathSelectionList.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionList/ContentTypePreviewPathSelectionList.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.tsx
- apps/vercel/frontend/src/components/parameterReducer.ts
- apps/vercel/frontend/src/constants/copies.ts
- apps/vercel/frontend/src/contexts/ConfigPageProvider.tsx
- apps/vercel/frontend/src/hooks/useInitializeParameters/useInitializeParameters.tsx
- apps/vercel/frontend/src/hooks/useInitializeParameters/uzeInitializeParameters.spec.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
- apps/vercel/frontend/test/helpers/renderConfigPageComponent.tsx
- apps/vercel/frontend/tsconfig.json
- apps/vercel/frontend/vite.config.ts
This PR accomplishes the following: 
1. Updates the Select error state to also include the red outline of the field (follow-up from last PR)
2. Adds a tooltip to the Add Content Type button when all content types have been configured.
3. Adds an error state to the preview path input that appears when the field is empty and the user has saved/installed the page. This error message disappears when the user interacts with that section once again. 
4. Creates a context that can be used to manage props being passed from the Config page to child components. 
5. Fixes a few imports that were not compiling correctly.
> Account for empty content type and empty preview path

- apps/mux/frontend/package-lock.json
- apps/mux/frontend/package.json
- apps/mux/frontend/src/setupTests.ts
Unblock upgrade of mux player (see https://github.com/contentful/apps/pull/7123). There was a test failure because `matchMedia` is not supported in the Jest test environment.
* Mock `matchMedia` per the handy guidance [from the docs](https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom).
> chore: upgrade mux player to 2.4.1

- apps/mux/package.json
Re-enable the Mux app deploy script, to start deploying Mux app to the production app definition. Currently, Mux is "pinned" to a build from Feb 5 while we rearchitected how tokens were being generated for signed URLs.
* Add back the production deploy script to start deploying again
For piece of mind I recorded a walkthrough of an end to end walkthrough of the Mux app, both with and without signed URLs. This was recorded from our sandbox space, which I built and deployed the current `master` too. So theoretically it's tested against the same artifact we will start deploying in this PR.
https://www.loom.com/share/d095b751fe1246829f6b6f4c1060f89a
> chore: reenable mux production deploys

- apps/vercel/frontend/src/clients/Vercel.ts
- apps/vercel/frontend/src/components/common/Select/Select.spec.tsx
- apps/vercel/frontend/src/components/common/Select/Select.tsx
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.tsx
- apps/vercel/frontend/src/constants/copies.ts
- apps/vercel/frontend/src/contexts/ConfigPageProvider.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.spec.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
- apps/vercel/frontend/test/helpers/renderConfigPageComponent.tsx
The purpose of this PR is to resolve the flashing error messages that may occur when the Vercel config page originally renders. This is really an optimization of state and data fetching management on the page itself, mostly with respect to validating the authentication token. 
1. I created a loading state that reflects API loading when checking the token, fetching projects, and fetching API paths. This ensures we can not prematurely render error messages or empty messages in any of these sections.
2. I also separated the logic of validating the token when it is updated and also validating it on render of the page. Also this introduces some duplicate code, this ensures that we are not just relying on useEffect updates to validate this logic, which tends to introduce complexity with various …
> fix: improve loading experience of vercel config page

- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/constants/copies.ts
The purpose of this PR is to ensure a user is not confused by the wording of the error message, as well as the default selection of another new project, when a project they had configured is no longer available in the list of projects. 
Originally, when a configured project value no longer existed, a different project was selected AND the error was shown, causing confusion to the user.
I have adjusted the copy and logic to ensure that when there is in incompatible configured project or path  with the current list of projects or paths, that the user understands clearly how to resolve it.
> fix: resolve issue when project no longer exists

- packages/ecommerce-app-base/docs/README.md
- packages/ecommerce-app-base/src/SkuPicker/SkuPicker.spec.tsx
- packages/ecommerce-app-base/src/SkuPicker/SkuPicker.tsx
- packages/ecommerce-app-base/src/SkuPicker/renderSkuPicker.tsx
- packages/ecommerce-app-base/src/SkuPicker/styles.ts
- packages/ecommerce-app-base/src/types/ui.ts
The SkuPicker component had the placeholder text hardcoded to "Search for a Product...", which is not helpful if your ecommerce app supports multiple sku types (e.g. categories). Also, this PR adds the ability to create help text under the search box. This is the first step in adding in category search functionality in the commercetools app, and also addresses bugs in apps with multiple sku types, since the placeholder text was incorrect.
I added two new functions: `MakeSearchHelpText` and `MakeSearchPlaceholderText`. I ensured that these were backwards compatible if the app doesn't pass in these functions. Otherwise, the app consuming this library will need to pass in these functions in order to have configured placeholder and help text. Here's a branch where I am testing these changes …
> feat: make SkuPicker search placeholder and help text configurable [INTEG-2017]

- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.tsx
- apps/vercel/frontend/src/constants/copies.ts
The purpose of this PR is to provide validation within the preview path input when a user saves the configuration. 
The following rules apply for the validation: 
1. The input must start with a '/' and must contain at least one set of closed curly braces i.e '{}' somewhere within the string. 
The validation of the preview path input will only run when the user has saved the configuration.
I also adjusted the messages that appear for preview path error messages (either empty or invalid). Would love input on those!
Input an invalid preview path, save the config, and notice the error message that appears. The error message should then clear once you interact with the section.
> feat: add preview path input validation on save

- apps/commercetools/package-lock.json
- apps/commercetools/package.json
- apps/commercetools/src/api/categories.ts
- apps/commercetools/src/dialog.ts
This PR updates the category API call and implements the changes made in the ecommerce-app-base package (https://github.com/contentful/apps/pull/7337) in order to add category search to the commercetools app.
I added the `where` query parameter and used their query predicate structure to query based on category name, key, and slug ([documentation here](https://docs.commercetools.com/api/projects/categories#query-categories)).
I bumped the `ecommerce-app-base` package and implemented the two new functions available to customize the search placeholder text and help text. I also updated the `hideSearch` and `showSearchBySkuOption` parameters accordingly
I tested the changes with single and multiple products and categories to ensure everything still worked as expected.
> feat: add exact match search to category picker [INTEG-2018]

- apps/vercel/frontend/src/clients/Vercel.spec.ts
- apps/vercel/frontend/src/clients/Vercel.ts
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.spec.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
The purpose of this PR is to do the following: 
1. Ensure that the VercelClient is never instantiated without the applied access token. 
2. Ensure that the loading and "validity" states that are dictating the rendering and error states on the Config page are being adjusted based on valid calls and responses from API communication. 
3. Ensure you cannot save an invalid token. 
You will notice comments throughout the code, but I have made a few conditional adjustments within the ConfigPage code. Transparently, I am not excited by the ever-increasing complexity of our loading states and conditional statements, so I have a follow-up task to really abstract some of this, but feel its higher priority to work on other things at this time. 
Work through the following testing flows: 
1. Clean …
> fix: ensure authentication token logic is handled consistently 

- apps/vercel/frontend/src/clients/Vercel.ts
- apps/vercel/frontend/src/components/common/Select/Select.tsx
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.spec.tsx
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/components/common/SelectionWrapper/SelectionWrapper.spec.tsx
- apps/vercel/frontend/src/components/common/SelectionWrapper/SelectionWrapper.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/TextFieldSection/TextFieldSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/TextFieldSection/TextFieldSection.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.tsx
- apps/vercel/frontend/src/constants/copies.ts
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
- apps/vercel/frontend/src/utils/validateApiPathData/validateApiPathData.spec.ts
- apps/vercel/frontend/src/utils/validateApiPathData/validateApiPathData.ts
The purpose of this PR is to add the fallback component that will render if the fetched API paths are 1. not feasibly fetched or 2. if the results are empty.
If there is an error with the API path endpoint or if the results are empty, this fallback input is rendered. 
Rendering this fallback component when the results are empty is something I am wavering on, as it seems to me that if the results are empty, their application is not configured correctly in the first place, so should we evens support this? But I also could perhaps since this API path endpoint is potentially unreliable, the endpoint just may at some point not return anything or return differing data, even if the user has set-up their application appropriately. 
The error handling I have added also denotes the data as …
> feat: add fallback component for an API path

- apps/side-notes-app/package-lock.json
- apps/side-notes-app/package.json
Single line fields in sidenotes crash the app. This updates the package to a version that supports our current version of react
> chore: update sidenotes packages

- apps/commercetools/package-lock.json
- apps/commercetools/package.json
After implementing changes in the `ecommerce-app-base` to make the search placeholder and help text configurable (https://github.com/contentful/apps/pull/7337), this PR bumps the package in commercetools so we can utilize the new changes.
This PR just bumps the package. Previously when I did this with the code changes to implement the category search, it introduced a bug where you couldn't save products to an entry (see revert PR: https://github.com/contentful/apps/pull/7365), so I am trying this one step at a time.
I tested this locally and pushed changes to staging the app is rendering correctly.
> chore: bump ecommerce-base-app in commercetools [INTEG-2016]

- apps/vercel/frontend/src/components/common/Select/Select.tsx
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.spec.tsx
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/components/common/SelectionWrapper/SelectionWrapper.spec.tsx
- apps/vercel/frontend/src/components/common/SelectionWrapper/SelectionWrapper.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.tsx
- apps/vercel/frontend/src/constants/copies.ts
The naming and help text for choosing your draft mode route handler are confusing at the moment.
* Update the copy and provide a link to the guide
* Refactor components a bit to support providing a react node and not just a string for help text
* UPDATE LINK is intentionally there and ugly, to remind us that we need to update it with the real link once we publish the guide
Before:
After:
> feat: add link to help text for api path

- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
There was a regression in the MS Teams app when a user clicks the "Disconnect" button on the app config page, it wasn't working.
The error that occurred was an invalid hook call. Our `handleLogout` function was calling `useContext` to get the `trackEvent` so we removed this.
Tested locally and it fixes the issue.
> fix: remove useContext call from handleLogout function [INTEG-2085]

- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
The purpose of this PR is to quickly resolve a bug that is occurring on the Vercel config page, when a user interacts with the content type/preview path selection section, the component itself umounts and Draft mode path selection is cleared. This unmounting should not be happening. 
I simply removed the problem `useEffect` on the Config page and moved it to the logic where the project is being changed. This logic is to essentially clear the API path parameter when the project is changed, so it has just been moved closer to that logic.
> fix: fix flashing bug of components when clicking on Content type selection

- apps/side-notes-app/package.json
Disable deployments in the side notes app, because the app is broken in production.
[zendesk](https://contentful.atlassian.net/browse/ZEND-4890)
[discord](https://discord.com/channels/1030176999471321129/1111352040413724712/1234496414843928677)
> ci(side-notes): disable deployments

- apps/commercetools/package-lock.json
- apps/commercetools/package.json
Continuing to troubleshoot why the commercetools app isn't compatible with ecommerce-app-base ^3.5.1, bumping the `react` and `react-dom` versions.
> chore: bump react and react-dom in commercetools []

- apps/commercetools/package-lock.json
- apps/commercetools/package.json
Bump the ecommerce-base-app in commercetools after bumping the react version.
> chore: bump ecommerce-app-base in ct []

- packages/ecommerce-app-base/package-lock.json
- packages/ecommerce-app-base/package.json
Remove unused dependency from the ecommerce-app-base package.
Testing locally and in staging using npm pack.
> fix: remove unused usehooks-ts dependency []

- apps/commercetools/package-lock.json
- apps/commercetools/package.json
Bumping ecommerce-app-base to 3.6.0 after the package is now at 3.6.1 for most recent version
Deployed manually to staging and there were no errors. Now testing CI for staging app.
> chore: bump ecom-app-base to 3.6.0 in ct []

- apps/commercetools/package-lock.json
- apps/commercetools/package.json
Bumps ecommerce-app-base to version 3.6.0 in commercetools app. 
Trying this again after the ecommerce-app-base has incremented to a new version so 3.6.0 is no longer the current version of that package.
Tested on staging branch and there are no errors.
> chore: bump ecom-app-base to 3.6.0 in commercetools [INTEG-2055]

- apps/commercetools/src/api/categories.ts
- apps/commercetools/src/dialog.ts
This PR updates the category API call and implements the changes made in the ecommerce-app-base package (https://github.com/contentful/apps/pull/7337) in order to add category search to the commercetools app. The ecommerce-app-base was bumped to version 3.6.0 in a previous PR (https://github.com/contentful/apps/pull/7474). This implements the changes previously approved in this PR (https://github.com/contentful/apps/pull/7357) that had to be reverted due to an issue with the ecommerce-app-base.
I added the `where` query parameter and used their query predicate structure to query based on category name, key, and slug ([documentation here](https://docs.commercetools.com/api/projects/categories#query-categories)).
I bumped the `ecommerce-app-base` package and implemented the two new …
> feat: add category search commercetools [INTEG-2018]

- packages/dam-app-base/package.json
Add react 18 as a peer dependency, as apps that use DAM-app-base sometimes have react 18 installed.
> chore(deps): add react 18 as a possible peer dependency

- apps/microsoft-teams/frontend/src/components/config/DebouncedSearchInput/DebouncedSearchInput.tsx
Our original design had the search icon on the right side of the text input for the channel and content type selection modals. However, it was rendering as a button which was confusing for users since it wasn't actionable.
Utilize the icon prop for the TextInput Forma36 component rather than the action button (https://f36.contentful.com/components/text-input). This moves the icon from the right to the left, but checked with design and we are good to make this change since it aligns with our design system. This changes the look for both the content type and channel selection modals.
Before
After
Run the app locally and use the channel and content type selection modals
> fix: update search icon for channel and content type selection [INTEG-1840]

- apps/vercel/frontend/src/clients/Vercel.ts
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.spec.tsx
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/HelpText/HelpText.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/TextFieldSection/TextFieldSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/TextFieldSection/TextFieldSection.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.tsx
- apps/vercel/frontend/src/constants/defaultParams.ts
- apps/vercel/frontend/src/constants/enums.ts
- apps/vercel/frontend/src/constants/errorMessages.ts
- apps/vercel/frontend/src/customTypes/configPage.ts
- apps/vercel/frontend/src/hooks/useFetchAndValidateData/useFetchAndValidateData.tsx
- apps/vercel/frontend/src/hooks/useFetchData/useFetchData.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
The purpose of this PR is to effectively communicate to the user that we are either unable to fetch the API paths or there do not exist API paths within their Vercel setup to render. 
1. When there are no errors thrown on retrieval of the data, but there are no API paths to render. I am most curious around opinions for this. Does this make it clear enough to the user that they have not configured routes correctly?
2. When there is an error on retrieval of the data (particularly important if this endpoint goes down). 
3. When the API path they have selected previously no longer exists within the current list (this logic already existed and exists for the projects as well).
> feat: handle warning messages when API paths are missing

- apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
Update link on the app config page to point to the new help center app guide.
Note: page is not live on the help center yet, but the updated link reflects the slug of the help article I just created.
> fix: update link to help center app guide [INTEG-2062]

- examples/vite-react/package-lock.json
- examples/vite-react/package.json
vite-react template needs these new react versions in order to build properly 
also went ahead and safely bumped other deps to resolve all security issues from audit
See https://github.com/contentful/apps/issues/7538
These upgrades should not introduce any breaking changes
See https://github.com/remix-run/remix/issues/7514
> fix: update vite-react deps to fix build and security issues []

- packages/dam-app-base/package.json
As a team, it was decided to create new major versions of the `dam-app-base` and `ecommerce-app-base` for any consumers that are running react v18+.
This PR **removes** the peer dependency definition of react 18, i.e. this current major version is expected to only work with consumers running react v16 or v17.
Going forward, if a consumer is running react v18+ they will need to use dam-app-base v3+
> chore(dam-app-base): remove react v18 peer dependency.

- apps/vercel/frontend/README.md
- apps/vercel/frontend/src/components/common/Select/Select.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.spec.tsx
The purpose of this PR is to add a very basic README to the Vercel frontend module and to add a bit more testing to the functionality of the overall Vercel config page. 
README => This adds a very basic frontend README for how to interact with that module as a developer. 
Testing => wanted to make sure a lot of the conditional logic paths of the Config page were accounted for in testing.
> docs: add more testing to config page and add basic frontend README

- apps/vercel/frontend/src/clients/Vercel.ts
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.spec.tsx
- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.tsx
- apps/vercel/frontend/src/constants/defaultParams.ts
- apps/vercel/frontend/src/constants/enums.ts
- apps/vercel/frontend/src/constants/errorMessages.ts
- apps/vercel/frontend/src/contexts/ConfigPageProvider.tsx
- apps/vercel/frontend/src/customTypes/configPage.ts
- apps/vercel/frontend/src/hooks/useFetchData/useFetchData.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.spec.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
- apps/vercel/frontend/test/helpers/renderConfigPageComponent.tsx
- apps/vercel/frontend/test/helpers/renderConfigPageHook.tsx
- apps/vercel/frontend/test/mocks/mockSdk.ts
The purpose of this PR is to add an error message when the user selects a project that is not configured to be in the space where the current app is installed/being installed. 
I added the below error message on render of the page AND when the user changes project, and the selected project contains an incompatible `CONTENTFUL_SPACE_ID` variable. The error lingers until the user changes to a valid project, but they are still able to install and save changes. 
Within [this](https://app.contentful.com/spaces/5rotc6q2lcs7/apps/656HN4kwcFsgd1lmZ5BhvP) space, I have created one Vercel project that is compatible with the space:` nextjs-lb-4`. The rest of the projects are not compatible, so you should see warnings for all other project selections.
> feat: add error message when project not aligned to spaceId

- packages/dam-app-base/package-lock.json
- packages/dam-app-base/package.json
- packages/dam-app-base/src/AppConfig/AppConfig.spec.tsx
- packages/dam-app-base/src/Editor/SortableComponent.tsx
- packages/dam-app-base/src/index.tsx
1. Update DAM-app-base to react v18
2. implement new style root.render(<Component>), as opposed to render(<Component>, node). [see react article](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis)
3. resolve a critical dependency update
```
$ npm audit
minimatch  <3.0.5
Severity: high
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix`
node_modules/minimatch
path-parse  <1.0.7
Severity: moderate
Regular Expression Denial of Service in path-parse - https://github.com/advisories/GHSA-hj48-42vr-x3v9
fix available via `npm audit fix`
node_modules/path-parse
semver  6.0.0 - 6.3.0 || 7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - …
```
> update DAM-app-base to react v18 [INTEG-1881]

- apps/dropbox/package-lock.json
- apps/dropbox/package.json
Update the Dropbox app's version of react to 18, as well as update dam-app-base to v3.0.0
v3 of the dam-app-base is a breaking change for consumers that are on a version of react less than 18.0.0.  Fortunately for the dropbox app, we don't render any actual react code, instead depending on dam-app-base to render react code.  So no changes to the dropbox app necessary.
See [dam-app-base changelog](https://github.com/contentful/apps/blob/master/packages/dam-app-base/CHANGELOG.md#300-2024-05-07)
> chore(dropbox): update to dam-app-base v3.0.0 and update to react v18

- packages/dam-app-base/src/Editor/SortableComponent.tsx
**Bug:** A minor CSS bug was discovered with the new version of dndkit that replaced react-sortable-hoc for sortable components in dam-app-base.  When dragging/sorting components, if the heights of the components vary, it creates a jarring UX.  See video:
**Broken**
Resolution is a quick style fix to sortable cards.  Something must have changed when migrating from react-sortable-hoc to dndkit.  just a few lines of CSS.
**Fixed**
Tested locally, see videos.
> fix(dam-app-base): sortable images should have min height

- apps/vercel/frontend/src/components/common/SelectSection/SelectSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/ApiPathSelectionSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ApiPathSelectionSection/TextFieldSection/TextFieldSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionList/ContentTypePreviewPathSelectionList.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.spec.tsx
- apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.tsx
- apps/vercel/frontend/src/components/config-screen/ProjectSelectionSection/ProjectSelectionSection.spec.tsx
- apps/vercel/frontend/src/constants/errorMessages.ts
- apps/vercel/frontend/src/hooks/useError/useError.spec.tsx
- apps/vercel/frontend/src/hooks/useError/useError.tsx
- apps/vercel/frontend/src/hooks/useFetchData/useFetchData.tsx
- apps/vercel/frontend/src/locations/ConfigScreen.tsx
- apps/vercel/frontend/test/mocks/index.ts
- apps/vercel/frontend/test/mocks/mockSdk.ts
The purpose of this PR is to accomplish the following: 
1. Adjust the 'X' button height mis-alignment in the Content type/preview path selection section. 
2. Fine tune general loading of the config page
3. Add [spaceId](url) to error message when selected project `spaceId` is not aligned with current `spaceId`. 
1. 'X' button: 
2. Config page loading. This is a bit more difficult to visualize, but when reloading the page the components flashed a bit more before, and now with some adjustments of the conditional rendering and the `useEffect` dependencies, the loading is a bit more seamless. 
3. Error message with `spaceId`:
> chore: add some polish improvements for Vercel config page

- apps/vercel/frontend/src/components/config-screen/GettingStartedSection/GettingStartedSection.spec.tsx
- apps/vercel/frontend/src/components/config-screen/GettingStartedSection/GettingStartedSection.tsx
- apps/vercel/frontend/src/constants/copies.ts
The purpose of this PR is to add a link to the App setup guide to the bottom of the Vercel config page, to further support the user with their app setup experience. 
As you see below, the link is added to the bottom of the page =>` 'Need help with app setup?....'.`. 
The link also directs to [this](https://www.contentful.com/help/vercel-app/) app setup guide page. Open to any and all suggestions here :)
> feat: add app setup guide link to vercel config page

- apps/ai-image-tagging/lambda/serverless.yml
Update AI Image Tagging Lambda runtime from node v16 to node v18.
Tested deploying to lambda staging environment.
> chore(ai-image-tagging): bump lambda runtime to node to v18 [INTEG-1959]

- apps/ai-content-generator/src/components/config/api-key/APIKey.tsx
Since most users will paste in their api key, a common user path is to paste in the key and then immediately click save. The save happens before the text input change event fires since the text input is never unfocused. Switching to an input event instead of a change event ensures we capture the users input. 
Install AICG, paste in your key and immediately click save. With these changes, refresh and the key should be preserved.
n/a
n/a
n/a
> fix: use input event instead of change event to ensure input is captured [EXT-5237]

- examples/function-mock-shop/src/hooks/useProduct.ts
There was no fallback url set for the `useProduct` hook
> Fallback to default API URL in useProducts hook []

- packages/dam-app-base/src/Editor/SortableComponent.tsx
[This PR](https://github.com/contentful/apps/pull/7431/files) to get the `dam-app-base` ready to support React 18 introduced some changes to the `deleteItem` login in the `SortableComponent`. These changes caused issues with deleting, where when clicking on an item in the list to delete, the first item instead got deleted.
The `key` was being used to splice the item from the list, but this turned out to be the URL of the asset, so this was getting passed as `NaN` and then removing the first item in the list. This PR updates the `deleteItem` logic to instead use index instead of key.
I tested this locally using `npm pack` to test the changes to the `dam-app-base` within the Bynder app.
After updating the `dam-app-base` we will open a PR for the Bynder app to bump the package version.
> fix: use index for deleting asset [ZEND-5025]

- apps/vercel/app-actions/src/actions/get-preview-envs.ts
- apps/vercel/app-actions/src/helpers/fetch-app-installation-parameters.ts
- apps/vercel/app-actions/src/services/vercel-service.spec.ts
- apps/vercel/app-actions/src/services/vercel-service.ts
- apps/vercel/app-actions/src/types.ts
- apps/vercel/app-actions/test/mocks.ts
* Team ID is required in Vercel API calls. We've added it to all our frontend API calls but missed updating the app action
* We should handle error responses from the Vercel API (at least acknowledge what went wrong and capture the error)
* Add the teamId as a query param. Since it's "required" by the frontend now we will assume it's present in the app installation parameter
* Add a rudimentary error handler to the app action Vercel api service
> fix: handle teamId in Vercel API call

- packages/ecommerce-app-base/src/AppConfig/AppConfig.spec.tsx
- packages/ecommerce-app-base/src/Editor/SortableComponent.spec.tsx
- packages/ecommerce-app-base/src/Editor/SortableComponent.tsx
- packages/ecommerce-app-base/src/__mocks__/index.ts
- packages/ecommerce-app-base/src/__mocks__/mockContentTypes.ts
- packages/ecommerce-app-base/src/__mocks__/mockSdk.ts
Fix a bug that was introduced in this [PR](https://github.com/contentful/apps/pull/7666) that was causing an infinite loop rerender to occur.
**Root cause**
1. On initial render, `usePreviousSkus()` hook is invoked to track `skus` from previous mount, 
2. This [useEffect](https://github.com/contentful/apps/blob/master/packages/ecommerce-app-base/src/Editor/SortableComponent.tsx#L75C3-L82) invokes `fetchProductPreviews()` on mount, as expected.
3. `fetchProductPreviews()` retrieves product previews via network request
4. `fetchProductPreviews()` updates the `productPreviews` state, causing a rerender, as expected.
5. on rerender, `usePreviousSkus()` runs and retrieves the list of skus from previous mount, as well as updates the current ref to the most current list of skus (list of skus …
> Fix ecommerce-app-base bug in drag-n-drop refetch logic

- .npmrc
- apps/dropbox/package-lock.json
- examples/function-appevent-filter/typescript/package-lock.json
- examples/function-appevent-handler/typescript/package-lock.json
- examples/function-appevent-transformation/typescript/package-lock.json
- examples/vite-react/package-lock.json
Several of our examples had `package-lock.json` files that had dependencies installed from github packages instead of from npm. I changed my `.npmrc` to point to the npm registry and re-generated these `package-lock.json` files. This also upgraded several dependencies in these examples.
Updated to also include a change to the Dropbox `package-lock.json` since it also was installing packages from github instead of npm.
Also updated root .npmrc with npm registry.
Tested Dropbox app locally to ensure it still functions as expected
> fix: update package-lock in examples to remove gh packages references []

- examples/function-mock-shop/package-lock.json
- examples/function-mock-shop/package.json
- examples/function-potterdb-rest-api/package-lock.json
- examples/function-potterdb-rest-api/package.json
- examples/function-potterdb/package-lock.json
- examples/function-potterdb/package.json
- examples/javascript/package-lock.json
- examples/javascript/package.json
- examples/typescript/package-lock.json
- examples/typescript/package.json
This PR bumps the `f36-components` package to the newly released version (`4.67.3`) which includes a fix that should remove the issue where create-contentful-app CLI users were seeing the error `Attempted import error: 'PaintBrushIcon' is not exported from '@contentful/f36-icons-alpha' (imported as 'PaintBrushIcon')` when cloning from one of our examples that was on version `4.67.2`.
Bump the package in the relevant examples. Verified that all packages are imported from npm instead of GitHub packages.
I tested that I could run and build all of these examples. I also tested using the `EntityList` component in the Typescript example and it worked with no errors.
> fix: bump f36-components package to 4.67.3 in examples [ZEND-5170]

- examples/nextjs/pages/index.tsx
As reported by #6904, the nextjs example had an error in the `index.tsx` file where the page location was listed twice in the `ComponentLocationSettings` object. This PR fixes this and correctly assigns the Home location for the Home component.
Verified that both the Home and Page component render as expected and that this example runs and build locally.
> fix: update home location entry in nextjs example []

- apps/vercel/frontend/src/clients/Vercel.ts
We added more information to the Vercel deployment metadata. This is an non-versioned API route so that's why it was an undocumented breaking change. The previous team was aware this was an non-versioned API route.
Added a filter to remove .rsc files.
Configure app and under Draft Mode route handler you shouldn't see any .rsc options.
No
N/A
No
> fix: remove .rsc files from api paths.

- apps/sap-commerce-cloud/frontend/package-lock.json
- apps/sap-commerce-cloud/frontend/package.json
- apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.spec.tsx
- apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.styles.ts
- apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.tsx
- apps/sap-commerce-cloud/frontend/src/components/Dialog/__snapshots__/Dialog.spec.tsx.snap
The dialog component is currently working both on keystroke and also has a search button. This PR removes that search button in favor of a search-as-you-type approach. A debounce was added to avoid fetching too often. 
Also in the Dialog component, a fix was implemented for being unable to change the selected basesite. 
Screenshot here showing the removal of the search button + the fact that the electronics-spa base site is actually shown as selected with the correct product list rendering.
> feat: debounce search and dialog component fixes [EXT-5636]

- .circleci/config.yml
- packages/eslint-plugin-contentful-apps/package.json
- override repo level npmrc with registry setup and auth on publish step
- bump eslint-plugin-contentful-apps to deploy
> fix: package publishing []

- packages/eslint-plugin-contentful-apps/index.js
simplify the plugin `meta` with a static name
> fix: (eslint-plugin-contentful-apps) static plugin name

- examples/function-appaction/INSTRUCTIONS.md
- examples/function-appaction/package.json
We updated the `app-scripts` package so that the `create-app-definition` script now allows you to set the `navigationItem` when creating the app definition, so that the page location will be listed in the main navigation. This PR bumps `app-scripts` for the app action function example (since that app relies on the page location) and updates the instructions for how to set up the app.
> chore(function-appaction): update instructions to show page in main nav [EXT-5710]

- examples/autotagger/README.md
- examples/autotagger/build-functions.js
- examples/autotagger/contentful-app-manifest.json
- examples/autotagger/functions/autotagger.ts
- examples/autotagger/package.json
- examples/autotagger/src/locations/ConfigScreen.tsx
- examples/autotagger/src/locations/Dialog.tsx
- examples/autotagger/src/locations/EntryEditor.tsx
- examples/autotagger/src/locations/Field.tsx
- examples/autotagger/src/locations/Home.tsx
- examples/autotagger/src/locations/Page.tsx
- examples/autotagger/src/locations/Sidebar.tsx
Contentful Functions can now be linked to App Actions (see https://www.contentful.com/developers/docs/extensibility/app-framework/functions/#use-case-app-actions)
This changeset extends the Autotagger example app, so that users can now trigger autotagging on demand using an App Action Function, as opposed to or in addition to using the existing App Event Function.
> feat: allow autotagger to be called by an app action [EXT-00]

- examples/function-appaction/package.json
Add `yargs` as a dev dependency for the app action function example, as `yargs` is used in the `build-functions.js` script. Previously this was working fine when the example was using `react-scripts`, and now since refactoring to `vite`, this was not working properly. When running `npm run build`, I was seeing this error: `Cannot find module 'yargs/yargs'`.
> fix: add yargs as dev dependency for building functions []

- examples/function-appevent-handler/javascript/example.js
- examples/function-appevent-handler/typescript/example.ts
Comment in example handler functions incorrectly refers to filter events
> fix: handler example comments [EXT-00]

- apps/ai-content-generator/src/components/config/configText.ts
Update text on the AI Content Generator app config page, specifically the help text for models and the link to the pricing page.
The help text for the models was out of date, especially since we updated the dropdown to display all models available via the API key. The pricing info info was for ChatGPT as a whole, and not for API usage specifically, so I updated this link with the more relevant API pricing info.
Before:
After:
> chore: update AICG config page text []

- examples/native-external-references/package.json
- examples/native-external-references/src/locations/ConfigScreen.tsx
- examples/native-external-references/src/tools/http.ts
For customers using EU Data Residency it is not trivial to get our `native-external-references` example to work. 
I've added environment variables to the custom scripts to allow customers to switch the hostname with `api.eu.contentful.com` easily
> Add host name options to package.json scripts to be more easily adapted to EU DR

- apps/ai-image-tagging/lambda/app.js
- apps/typeform/lambda/app.js
Resolves a caching issue for apps frontend assets, done for Smartling in this PR https://github.com/contentful/apps/pull/9228 following up to apply the same pattern to Typeform and AI image tagging which likely have the same issue
> Chore: set last modified header for apps using express to serve frontend assets [INTEG-2309]

- examples/custom-validation/vite.config.ts
Our custom validation example did not have the base option set to support relative paths, so this warning was showing on upload and causing issues when using the app.
If you're using Vite, adding [`base: ''` or `base: './'`](https://vite.dev/config/shared-options.html#base) to your `vite.config.js` will resolve this warning. I have also submitted a PR to update this in our developer documentation here: https://www.contentful.com/developers/docs/extensibility/app-framework/app-bundle/#limitations 
Tested to confirm that the example app works properly.
> fix: add base to vite config for relative paths [EXT-5983]

- examples/autotagger/package.json
Similar to [this PR](https://github.com/contentful/apps/pull/9186), this resolves an issue with the autotagger example where a customer was reporting that they were seeing an error `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'yargs'` after copying this example.
> fix: add yargs as dev dep for functions build [ZEND-5632]

- apps/graphql-playground/package.json
The gql app had its deploy script disabled. We want to make a change to add the deprecation banner
> chore: fix build deploy script for gql app

- apps/slack/lambda/config/serverless.dev.yml.example
- apps/slack/lambda/config/serverless.prd.yml
- apps/slack/lambda/config/serverless.test.yml
- apps/slack/lambda/lib/config.ts
- apps/slack/lambda/lib/middlewares/corsConfig.ts
Workflows call the Slack app's lambda to discover channels and get and save channel IDs in step configurations. After the Workflows frontend has been migrated into the web app this is broken due to CORS.
This PR adds the web app as an allowed request origin.
Ticket: https://contentful.atlassian.net/browse/CFISO-2167
I added a new `webAppUrl` config key pointing to `'https://app.contentful.com'`.
> feat: allow web app to access Slack app

- apps/graphql-playground/src/components/GqlPlayground.tsx
The banner saying we're sunsetting the app has a date of 2-31-25 instead of 3-31-25
> fix: correct banner date in graphql app [INTEG-2425]

- apps/slack/lambda/package-lock.json
- apps/slack/lambda/package.json
- apps/slack/lambda/serverless.yml
We need to upgrade our node versions to LTS
[INTEG-2182](https://contentful.atlassian.net/browse/INTEG-2182)
[INTEG-2182]: https://contentful.atlassian.net/browse/INTEG-2182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: upgrade slack node version [INTEG-2182]

- apps/typeform/lambda/serverless.yml
We need to upgrade node to a LTS
[INTEG-2184](https://contentful.atlassian.net/browse/INTEG-2184)
[INTEG-2184]: https://contentful.atlassian.net/browse/INTEG-2184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: upgrade typeform node version [INTEG-2184]

- apps/ai-image-tagging/lambda/serverless.yml
We need to upgrade node to LTS
[INTEG-2179](https://contentful.atlassian.net/browse/INTEG-2179)
[INTEG-2179]: https://contentful.atlassian.net/browse/INTEG-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: upgrade ai-image-tagging node version [INTEG-2179]

- .github/workflows/pr-title-check.yml
Dependabot PRs are all failing the pr title workflow check to enforce attaching JIRA tickets. We shouldn't enforce this for dependabot PRs.
> fix: don't run pr title check workflow for dependabot PRs [INTEG-2430]

- apps/smartling/lambda/serverless.yml
- examples/javascript/index.html
- examples/javascript/package.json
- examples/javascript/src/locations/ConfigScreen.spec.jsx
- examples/javascript/src/locations/Dialog.spec.jsx
- examples/javascript/src/locations/EntryEditor.spec.jsx
- examples/javascript/src/locations/Field.spec.jsx
- examples/javascript/src/locations/Home.spec.jsx
- examples/javascript/src/locations/Page.spec.jsx
- examples/javascript/src/locations/Sidebar.spec.jsx
- examples/javascript/src/setupTests.js
- examples/javascript/test/mocks/mockSdk.js
- examples/javascript/vite.config.js
- examples/typescript/index.html
- examples/typescript/package.json
- examples/typescript/src/locations/ConfigScreen.spec.tsx
- examples/typescript/src/locations/Dialog.spec.tsx
- examples/typescript/src/locations/EntryEditor.spec.tsx
- examples/typescript/src/locations/Field.spec.tsx
- examples/typescript/src/locations/Home.spec.tsx
- examples/typescript/src/locations/Page.spec.tsx
- examples/typescript/src/locations/Sidebar.spec.tsx
- examples/typescript/src/setupTests.ts
- examples/typescript/test/mocks/mockSdk.ts
- examples/typescript/vite.config.ts
React-scripts is outdated and causes security vulnerabilities
[INTEG-2432](https://contentful.atlassian.net/browse/INTEG-2432)
[INTEG-2432]: https://contentful.atlassian.net/browse/INTEG-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update cca to use vite for javascript and typescript examples [INTEG-2432]

- apps/braze/package-lock.json
- apps/braze/package.json
- apps/braze/src/components/CodeBlocksStep.tsx
- apps/braze/src/components/FieldsSelectionStep.tsx
- apps/braze/src/components/LocalesSelectionStep.tsx
- apps/braze/src/components/WizardFooter.tsx
- apps/braze/src/helpers/assembleQuery.ts
- apps/braze/src/helpers/generateLiquidTags.spec.ts
- apps/braze/src/helpers/transformEntryFields.ts
- apps/braze/src/locations/Dialog.tsx
- apps/braze/src/locations/Sidebar.tsx
- apps/braze/test/mocks/mockSdk.ts
Users are now able to select the locales so they can be used when generating the liquid tags
The locales are retrieved from the space. If the entry has no localized fields, the step is skipped.
Use the app with an entry that has localized fields
N/A
N/A
N/A
> Braze app: allow to select locales

- examples/javascript/package.json
- examples/javascript/vite.config.mjs
- examples/typescript/package.json
- examples/typescript/src/App.tsx
- examples/typescript/src/components/LocalhostWarning.tsx
- examples/typescript/src/locations/ConfigScreen.spec.tsx
- examples/typescript/src/locations/ConfigScreen.tsx
- examples/typescript/src/locations/Dialog.spec.tsx
- examples/typescript/src/locations/Dialog.tsx
- examples/typescript/src/locations/EntryEditor.spec.tsx
- examples/typescript/src/locations/EntryEditor.tsx
- examples/typescript/src/locations/Field.spec.tsx
- examples/typescript/src/locations/Field.tsx
- examples/typescript/src/locations/Home.spec.tsx
- examples/typescript/src/locations/Home.tsx
- examples/typescript/src/locations/Page.spec.tsx
- examples/typescript/src/locations/Page.tsx
- examples/typescript/src/locations/Sidebar.spec.tsx
- examples/typescript/src/locations/Sidebar.tsx
- examples/typescript/src/react-app-env.d.ts
- examples/typescript/tsconfig.json
- examples/typescript/vite.config.mts
We updated the JS and TS apps to use Vite instead of CRA in this PR: https://github.com/contentful/apps/pull/9516. This is a follow up PR to fix a few items in these examples; fixing a bug with how these templates work with the function templates and updating some dependencies.
Here's a summary of the updates:
- When CCA users use a function template, the resulting code is based off of these TS or JS examples with functions added to them. The functions build script expects the build to be in a `./build` directory, but these examples were set to `./dist` for the build directory. In order to accommodate the functions templates, we are changing the build directory to `./build` for these TS and JS templates
- Added a `npm start` script in addition to `npm dev` since the `README` and …
> fix: update Vite config in JS and TS example apps [EXT-6273]

- function-examples/appaction-call/javascript/INSTRUCTIONS.md
- function-examples/appaction-call/typescript/INSTRUCTIONS.md
- function-examples/appevent-filter/javascript/INSTRUCTIONS.md
- function-examples/appevent-filter/typescript/INSTRUCTIONS.md
- function-examples/appevent-handler/javascript/INSTRUCTIONS.md
- function-examples/appevent-handler/typescript/INSTRUCTIONS.md
- function-examples/appevent-transformation/javascript/INSTRUCTIONS.md
- function-examples/appevent-transformation/typescript/INSTRUCTIONS.md
- function-examples/external-references/javascript/INSTRUCTIONS.md
- function-examples/external-references/typescript/INSTRUCTIONS.md
- function-examples/kitchen-sink/javascript/INSTRUCTIONS.md
- function-examples/kitchen-sink/typescript/INSTRUCTIONS.md
The `INSTRUCTIONS.md` files in our new function templates were referencing a [CER tutorial](https://www.contentful.com/developers/docs/extensibility/app-framework/function-tutorial/). Now that we published the new [Working with Functions](https://www.contentful.com/developers/docs/extensibility/app-framework/working-with-functions/) guide, we want to link this guide instead.
Change all references to the old tutorial to instead link to the new guide.
Also, in the `external-references` template, I added additional resources links and removed reference to the deprecated GraphQL Playground app and instead replaced that with the new GraphiQL app link.
> chore: update dev doc links in function templates [EXT-5566]

- apps/braze/src/fields/Entry.ts
- apps/braze/src/fields/Field.ts
- apps/braze/src/fields/FieldsFactory.ts
- apps/braze/src/utils.ts
- apps/braze/test/fields/FieldsFactory.spec.ts
This PR includes two main changes:
- Save the id of the content type instead of the name
- Save the content type setting the first letter to lowercase
> Fix queries case

- .github/CODEOWNERS
Change ownership of the delivery function (CER/NER) examples from Monet to Fusion
> chore: add fusion to codeowners for delivery function examples []

- apps/braze/src/locations/ConfigScreen.tsx
Adding a type password for the Contentful API key input in the configuration screen that was removed in a previous [PR](https://github.com/contentful/apps/pull/9577).
> Adding type password to the contentful api key input

- apps/braze/src/components/CheckboxCard.tsx
- apps/braze/src/components/FieldCheckbox.tsx
- apps/braze/src/components/FieldsSelectionStep.tsx
- apps/braze/src/fields/Entry.ts
- apps/braze/src/fields/Field.ts
- apps/braze/src/fields/ReferenceArrayField.ts
- apps/braze/src/fields/ReferenceField.ts
- apps/braze/src/fields/ReferenceItem.ts
- apps/braze/test/components/FieldCheckbox.spec.tsx
We're updating the checkbox behavior per the designs.
Before: if at least one nested checkbox was selected, the parent checkbox was selected as well
Now: all nested checkboxes need to be selected in order for the parent to be automatically selected
We've separated the "internal" `selected` logic (used for assembling the graphql query and the liquid tags) from the view logic (what is shown to the user).
The internal logic needs that the parent checkbox if at least one of the nested ones are selected (which is different from the view logic).
Use the app with a content type that has references or array of references.
N/A
The base of this PR is not master, so we may need to update it if the base branch gets squashed
N/A
https://github.com/user-attachments/assets/4d8c54ad-6f02-4d8d-9562-77d10e4 …
> Braze app: Adjust checkbox 'select all' behaviour [INTEG-2507]

- apps/braze/src/components/InformationLinkComponent.tsx
- apps/braze/src/components/InformationWithLink.tsx
- apps/braze/src/locations/ConfigScreen.tsx
- apps/braze/src/locations/Sidebar.styles.ts
- apps/braze/src/locations/Sidebar.tsx
- apps/braze/src/utils.ts
- apps/braze/test/components/InformationWithLink.spec.tsx
- apps/braze/test/locations/ConfigScreen.spec.tsx
- apps/braze/test/locations/Sidebar.spec.tsx
This update adds a Create button to the sidebar, renames the existing one to Generate, and includes descriptions for each option.
In addition of the changes mentioned above, this update also adds a new component to reuse some repeated logic between the config screen and the sidebar.
With these changes now the sidebar looks like this:
Automated tests were added for the new component and the new sidebar button. Additionally, some updates were made to existing ones.
Link to the [ticket](https://contentful.atlassian.net/browse/INTEG-2535).
**Important note:** This PR doesn’t include the logic in the dialog to distinguish which button was clicked. That will be handled in a separate ticket.
> Braze app: create and generate sidebar buttons [INTEG-2535]

- apps/braze/src/locations/ConfigScreen.tsx
- apps/braze/src/utils.ts
- apps/braze/test/locations/ConfigScreen.spec.tsx
This update adds a new input to the config screen. This is because we'll need the `braze rest endpoint` to use the braze api.
- **Context**: Depending on the link of your Braze dashboard (the one you see in your browser's address bar, which can also be found in this [table](https://www.braze.com/docs/api/basics#endpoints) in the URL column), Braze assigns you a specific REST URL endpoint. it’s not something the user can choose. We need that `REST URL endpoint` from the user.
Now the config screen has this new input with it's non empty value validation:
https://github.com/user-attachments/assets/f65498d0-cda6-4798-96de-e102e8c08ea4
Added automated tests and updated some existing ones
Link to the ticket: [INTEG-2575](https://contentful.atlassian.net/browse/INTEG-2575)
[INTEG-2575]: …
> Braze app: add braze endpoint input to config screen [INTEG-2575]

- apps/braze/src/components/FieldsSelectionStep.tsx
- apps/braze/src/fields/AssetArrayField.ts
- apps/braze/src/fields/AssetField.ts
- apps/braze/src/fields/BasicField.ts
- apps/braze/src/fields/Entry.ts
- apps/braze/src/fields/Field.ts
- apps/braze/src/fields/FieldsFactory.ts
- apps/braze/src/fields/LocationField.ts
- apps/braze/src/fields/ReferenceArrayField.ts
- apps/braze/src/fields/ReferenceField.ts
- apps/braze/src/fields/ReferenceItem.ts
- apps/braze/src/fields/RichTextField.ts
- apps/braze/src/fields/TextArrayField.ts
- apps/braze/src/fields/fieldRegistry.ts
- apps/braze/src/locations/Dialog.tsx
- apps/braze/src/locations/Sidebar.tsx
- apps/braze/test/components/CodeBlock.spec.tsx
- apps/braze/test/fields/FieldsFactory.spec.ts
- apps/braze/test/locations/Dialog.spec.tsx
- apps/braze/test/locations/Sidebar.spec.tsx
Until now we were using `fullWidth` for all three steps of the app, but we needed to use the `large` width for the first two steps.
Since the width of the Dialog cannot be changed once open, it has to be closed and reopened before the last step. So we had to serialize and deserialize all information from the entry and the fields.
Automated tests were added.
To test manually, just use the app and get to the last step, the Dialog should close and reopen in the last step.
https://github.com/user-attachments/assets/7683965b-75a3-48f3-8daa-fb37b5255f5e
N/A
N/A
N/A
> Braze app: change width of Dialog for last step [INTEG-2506]

- apps/braze/contentful-app-manifest.json
- apps/braze/functions/createContentBlocks.ts
- apps/braze/package-lock.json
- apps/braze/package.json
- apps/braze/src/components/create/CreateFlow.tsx
- apps/braze/test/functions/createContentBlocks.test.ts
- apps/braze/test/locations/Dialog.spec.tsx
- apps/braze/test/mocks/mocksForFunctions.ts
Implement content block creation
Add implementation to existing function and call it from the frontend using an action.
For each connected field, this saves the id of the field and the newly created content block id in an installation parameters called "brazeConnectedFields".
Configure the app with all required params and follow the 'create' flow. A content block should be created in Braze. Note that the name of the content block can't be repeated. Content blocks cannot be deleted but the name can be changed
N/A
N/A
N/A
> [WIP] Braze app: create content blocks [INTEG-2541]

- apps/braze/functions/createContentBlocks.ts
- apps/braze/src/components/create/ClientErrorStep.styles.ts
- apps/braze/src/components/create/ClientErrorStep.tsx
- apps/braze/src/components/create/CreateFlow.tsx
- apps/braze/src/components/create/DraftStep.tsx
- apps/braze/test/fields/FieldsFactory.spec.ts
- apps/braze/test/functions/createContentBlocks.test.ts
- apps/braze/test/locations/Dialog.spec.tsx
This update was needed to display the user the 4xx class errors in the creation of the content blocks.
The following changes were introduced:
- We added status codes in the app function to identify the types of the errors.
- We added a new modal step that is showed when the creation of the content blocks fails due to a 4xx class error.
- Testing to validate this changes.
Here is an example of the result when the creation fails and when it is successfull:
https://github.com/user-attachments/assets/bbeb186c-96da-42c2-b697-b16ff346b3df
- `createContentBlocks.ts` function tests were updated and one more automated test was added into `Dialog.spec.tsx`
N/A
Link to [INTEG-2544](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/454?selectedIssue=INTEG-2544) ticket.
N/A …
> Braze app: Error modal for 4XX errors [INTEG-2544]

- apps/braze/contentful-app-manifest.json
- apps/braze/functions/createContentBlocks.ts
- apps/braze/package-lock.json
- apps/braze/package.json
- apps/braze/src/components/create/CreateFlow.tsx
- apps/braze/src/components/create/CreateStep.tsx
- apps/braze/src/components/create/DraftStep.tsx
- apps/braze/test/components/create/CreateStep.spec.tsx
- apps/braze/test/components/create/CreateStep.test.tsx
- apps/braze/test/functions/createContentBlocks.test.ts
- apps/braze/test/locations/Dialog.spec.tsx
We want users to be allowed to edit name and description of a contentblock when creating a new one
The following changes were introduced:
- Introduce description to card component and to create content block action
- Add validations for name
- Enhance UI for editing name and description
- Updated package.json to better test in the dev environment
Updated automatic testing.
Tested using my own app:
https://github.com/user-attachments/assets/88112a47-466c-4a4a-933e-ba2ddc545cae
> Braze app: Edit card component [INTEG-2539]

- apps/braze/src/locations/Sidebar.tsx
- apps/braze/test/locations/Sidebar.spec.tsx
- apps/braze/test/mocks/mockSdk.ts
Handle edge case in which we don't have available the installation parameters. This can happen if the user was already using the v1 version of the app.
In this PR:
- Added warning note
- Added link to config page 
- Disable buttons of the app, until the user re-configures the page
Added test to handle edge cases. Tested using the v1
https://github.com/user-attachments/assets/0b33892a-a7ba-47a2-a267-8af24bb184a5
> Braze app : Update config screen edge case [INTEG-2610]

- apps/braze/src/components/create/CreateFlow.tsx
- apps/braze/src/locations/ConfigScreen.tsx
- apps/braze/src/locations/Sidebar.tsx
- apps/braze/src/utils.ts
- apps/braze/test/locations/ConfigScreen.spec.tsx
- apps/braze/test/locations/Dialog.spec.tsx
- apps/braze/test/locations/Sidebar.spec.tsx
- apps/braze/test/mocks/mockSdk.ts
We were storing the information for connected fields in app installation parameters, but that's actually not possible (the parameters weren't actually persisted).
The new solution is to create a content type specifically for storing this information, with one single entry with one single json field.
- Configure app
- Check that content type and entry were created
- Connect fields and check they're visible in the sidebar
https://github.com/user-attachments/assets/a0e4774f-44bc-4433-b6bd-c1a60472949a
> Braze app: Change approach for storing connected fields info [INTEG-2650]

- apps/braze/functions/createContentBlocks.ts
- apps/braze/src/components/InformationWithLink.tsx
- apps/braze/src/components/create/CreateFlow.tsx
- apps/braze/src/components/create/CreateStep.tsx
- apps/braze/src/components/create/ErrorStep.tsx
- apps/braze/test/components/create/CreateStep.spec.tsx
- apps/braze/test/functions/createContentBlocks.test.ts
- apps/braze/test/locations/Dialog.spec.tsx
If the chosen content block name for a field is already in use in Braze, the creation will fail. We now allow to edit the name and retry.
Instead of going directly into the ErrorStep, we first check if any of the errors were caused by the name of the content block already existing in Braze. If that's the case, we return to the CreateStep showing the errors and allowing to edit the names for the content blocks.
The main change in the implementation is that now the `creationResultFields` **accumulates** all results instead of having only the results for the last call. That way we can now the status of all the selected fields.
If there are errors but none of them are from the name already existing, we do display the ErrorStep as we used to do.
Try to create a content block using a name that …
> Braze: Allow to retry when name already in use [INTEG-2540]

- apps/braze/functions/createContentBlocks.ts
- apps/braze/src/components/create/CreateFlow.tsx
- apps/braze/src/components/create/ErrorStep.tsx
- Differentiate between customer errors (e.g. when a field is empty, we don't even call Braze in that case) and client errors (when we call Braze and get a 4xx error). In the first one we don't want to show the "get support" link.
- Small fix in the `CreateFlow` file: if errors had happened there were cases in which we would still go to the "success step".
- Only display the "Content Blocks were successfully created" in the error step if that's the case (we when displaying it in all cases).
- Use content block name instead of field name in the error step when displaying correctly created content blocks
> Braze: Fixes in error handling [INTEG-2540]

- apps/braze/src/locations/Page.styles.ts
- apps/braze/src/locations/Page.tsx
- apps/braze/test/locations/Page.spec.tsx
- apps/braze/test/mocks/mockSdk.ts
This update includes the base modal structure for the page view location when the user clicks a `view fields` button.
Added a new component in the `Page.tsx` location to show the modal. For now, the modal just show you the connected fields and let you select them. The disconnection will be done in another ticket.
Now the page view location has the following modal:
https://github.com/user-attachments/assets/acf46386-9d1d-4e36-9097-17991a94b4eb
Automated tests were added. To see the modal and test it manually, you can follow the video steps.
N/A
Link to [INTEG-2548](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/454?selectedIssue=INTEG-2548) ticket.
N/A
[INTEG-2548]: https://contentful.atlassian.net/browse/INTEG-2548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
> Braze: Modal Layout for page location [INTEG-2548]

- apps/braze/src/locations/ConfigScreen.tsx
- apps/braze/test/locations/ConfigScreen.spec.tsx
- If a content type already has the app in the sidebar and we configure the app again, the app gets removed: we weren't keeping the current state, now we do
- We should display the content types that already have the app in the sidebar: done
- Do not display the “brazeConfig” content type as an option: done
https://github.com/user-attachments/assets/5a7191e0-e32c-4d79-9c1a-39aa580bdba7
> Braze: Config screen issues [INTEG-2685]

- apps/braze/functions/createContentBlocks.ts
- apps/braze/src/components/create/ErrorStep.tsx
- apps/braze/test/functions/createContentBlocks.spec.ts
We were showing a 400 error and the link to contact support when a field that is localized is empty instead of displaying that it's a custom error
https://github.com/user-attachments/assets/2f9770d4-eab8-4fac-a9e1-8948a0e5cc70
> Braze: Display correct error when content for locale is empty [INTEG-2687]

- apps/braze/functions/appEventHandler.ts
- apps/braze/test/functions/appEventHandler.spec.ts
- When the app gets uninstalled it tries to remove the config entry and its content type. Before deleting each of them, it tries to unpublish them, but if they aren't published, it fails. So we now wrap each call in a retry block in case the entry or the content type got unpublished
> Braze: Fix uninstall handler [INTEG-2687]

- apps/braze/contentful-app-manifest.json
- apps/braze/functions/appEventHandler.ts
- apps/braze/functions/customError.ts
- apps/braze/src/locations/Page.styles.ts
- apps/braze/src/locations/Page.tsx
- apps/braze/src/utils.ts
- apps/braze/test/functions/appEventHandler.spec.ts
- apps/braze/test/locations/Page.spec.tsx
- apps/braze/test/mocks/connectedFields.ts
- apps/braze/test/mocks/entryResponse.ts
This update includes the error handling in the modal of the page location. Also, an indicator is shown in the page table when a certain connected entry has an error in the connection of the fields.
We had to modify the **save** event handler function, if the connected entry is changed and the connection to Braze fails during the update, the error code and message is stored in the config entry. Later, from the page location, we can get the information of the config entry and verify if we should show a error message if necessary.
If there are errors, they are displayed in the following way:
https://github.com/user-attachments/assets/a943bed5-38ad-4916-ae08-83d59231be45
Automated tests were added. In addition, manual testing was made changing the appEventHandler function so it fails when the …
> Braze: Page modal error handling [INTEG-2550]

- apps/braze/src/fields/FieldsFactory.ts
- apps/braze/test/fields/FieldsFactory.spec.ts
When the user deletes an entry that is being referenced from another which has a `reference or array reference` field, the fetch from the Dialog failed because the content types were undefined.
The proper validation to skip the references and array of references, which doesn't have content type, were added.
An automated test to validate this edge case was added.
N/A
Link to [INTEG-2705](https://contentful.atlassian.net/browse/INTEG-2705)
N/A
[INTEG-2705]: https://contentful.atlassian.net/browse/INTEG-2705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Braze: Handle undefined c-type for ref and array of ref [INTEG-2705]

- apps/braze/functions/appEventHandler.ts
- apps/braze/functions/common.ts
- apps/braze/functions/getContentBlocks.ts
- apps/braze/src/locations/Sidebar.tsx
An error was being thrown in the Sidebar if the entry did not have any connected fields. We now return an empty array since it's a valid scenario.
> Braze: Handle empty sidebar []

- apps/braze/functions/appEventHandler.ts
- apps/braze/test/functions/appEventHandler.spec.ts
Change the callAndRetry method (to retry actions in the app event function) implementation of the Braze app from recursive to iterative and update the wait times in between
> Braze: Update callAndRetry implementation []

- apps/bulk-edit/src/locations/Page/components/BulkEditModal.tsx
- apps/bulk-edit/test/locations/Page/BulkEditModal.test.tsx
Value from previous updated field gets carried over when opening the modal for editing a different field.
https://github.com/contentful/apps/pull/9910#issuecomment-2967741763
Used a useEffect to clean the modal value every time it's reopened, since it toggles between visible and hidden without re-rendering.
Added an automated test to check this edge case. You can check it manually if wanted:
https://github.com/user-attachments/assets/95c6c376-1cee-44af-ad77-9bb2054c7f35
Now the modal value is always empty when opened.
N/A
Link to [INTEG-2799](https://contentful.atlassian.net/browse/INTEG-2799) ticket.
N/A
[INTEG-2799]: https://contentful.atlassian.net/browse/INTEG-2799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bulk Edit App: Fix value carried over when opening modal [INTEG-2799]

- apps/bulk-edit/src/locations/Page/index.tsx
The spinner wasn't showing when fetching the entries.
https://github.com/user-attachments/assets/cedbd7ee-3c65-4d1c-8f85-a34f3914f661
A minimal fix was made in the condition of the if that shows the spinner.
Now the spinner works correctly:
https://github.com/user-attachments/assets/95a4f775-b4a7-4e3b-a9bb-e31c2e992228
N/A
N/A
N/A
> Bulk Edit App: fix condition to show spinner [INTEG-2728]

- apps/bulk-edit/src/locations/Page/index.tsx
- apps/bulk-edit/test/locations/Page/ErrorNote.test.tsx
- apps/bulk-edit/test/locations/Page/Page.test.tsx
When an error occurs after an update, we were displaying the previous value of the updated field for the failed entry. We now display the title of the entry so help the user recognize the entry that failed
> Bulk edit: Use display field when showing update errors [INTEG-2801]

- apps/hubspot/src/components/Splitter.tsx
- apps/hubspot/src/locations/ConfigScreen.styles.ts
- apps/hubspot/src/locations/ConfigScreen.tsx
- apps/hubspot/src/utils.ts
- apps/hubspot/test/locations/ConfigScreen.spec.tsx
- apps/hubspot/test/mocks/mockSdk.ts
This update introduce the first version of the config screen with the base structure:
- the hubspot access token (with empty check validation)
- the instructions expandable section
Note: Deeper validations are handled in another ticket.
The config screen location was modified so the UI matches the figma design.
Automated tests added. Manual check:
https://github.com/user-attachments/assets/ae323ced-623a-43db-a34a-5981f2ebcc17
N/A
Link to [INTEG-2769](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?issueParent=367108%2C365033%2C346554&selectedIssue=INTEG-2769) ticket
N/A
[INTEG-2769]: https://contentful.atlassian.net/browse/INTEG-2769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hubspot: Config screen base structure [INTEG-2769]

- apps/braze/functions/appEventHandler.ts
- apps/braze/functions/common.ts
- apps/braze/functions/createContentBlocks.ts
- apps/braze/test/functions/appEventHandler.spec.ts
- apps/braze/test/functions/createContentBlocks.spec.ts
- apps/braze/test/mocks/contentTypeResponse.ts
Fix a bug from Braze that prevents the user to create contentblocks with field types different to text, symbol or rich text. Types we also want to handle:
- Integer
- Number
- Date
- Boolean
- Object
- Location
- Stringify all allowed fields because braze API only accepts content that is a string
- Change create handler to accept types
- Change update handler to accept types
- Added more tests for this cases
Automated testing and local testing
All fields except location:
https://github.com/user-attachments/assets/a095991e-7aaf-4053-8794-58fde016f2c0
Location field:
https://github.com/user-attachments/assets/55aea82b-dd1c-49ab-8435-22e9e1b0e77b
Boolean:
> Braze app v2: Handle other field types []

- apps/hubspot/src/locations/Sidebar.tsx
- apps/hubspot/test/locations/Sidebar.spec.tsx
- apps/hubspot/test/mocks/mockSdk.ts
Adding the sidebar location for the Hubspot app.
It consists of two buttons: one opens the dialog location and the other one redirects to the page location.
- Add app to the sidebar of a content type
- Go to an entry of that content type
- Use both buttons
https://github.com/user-attachments/assets/53648082-6fca-4ca7-8189-0c5820dba948
> Hubspot app:Add sidebar []

- apps/braze/src/fields/FieldsFactory.ts
- apps/braze/src/locations/Dialog.tsx
- apps/braze/src/utils/fetchBrazeConnectedEntries.ts
- apps/braze/test/fields/FieldsFactory.spec.ts
We want to fix a bug that causes an infinite loader.
The way we were getting the displayName(title) for references and arrays of references with no displayName(title) was undefined when doing` Object.values(f.fields[fieldContentType.displayField] as { [key: string]: any })[0] `and that cause it to infinite load.
- Fix the logic for getting a name for references and array references
- Encapsulate logic
- Added tests
Automated testing
Use a duplicated entry for the one that failed. This reference is untitle and has no content
https://github.com/user-attachments/assets/ea05fe52-cccf-44ad-9c7f-509618bb8ba1
Testing everything still works
https://github.com/user-attachments/assets/75af5758-3b5e-47ee-a970-3a3739bc5b10
> Braze app: Fix long loading time [INTEG-2822]

- apps/braze/src/locations/Sidebar.tsx
We want to fix a bug in which when a user changes the title of the entry, the modal shows a default content block name that is stale
- Make sure we are calculating the initialInvocationParams everytime by making it into a function
Make sure automated tests are working and:
https://github.com/user-attachments/assets/d7db9d89-9014-48c3-b9a8-5eefda7fbac2
Thanks to @joaquincasal for this easy and elegant solution.
>  Braze app: Use freshest title for ContentBlocks [INTEG-2823]

- apps/braze/functions/createContentBlocks.ts
- apps/braze/test/functions/createContentBlocks.spec.ts
Improve error message for empty fields
- Improve readability by updating error message
- Update tests
https://github.com/user-attachments/assets/422438c1-4955-4fcd-b8e5-729954a9e668
> Braze app: Improve error message for empty fields[INTEG-2824]

- apps/braze/src/locations/Page.tsx
- apps/braze/test/locations/Page.spec.tsx
Page: Change position of number of connected field to be more inline with the design and avoid issues with longer title names
- Change position of number of connected field to the select all checkbox label between “()”
Before 
After
> Braze app: Page modal adjustment to be more inline with the design [INTEG-2825]

- apps/braze/src/locations/ConfigScreen.tsx
- apps/braze/test/locations/ConfigScreen.spec.tsx
Update copy to: “Enter your Braze REST API key. If you need to generate a key, visit the APIs and Identifiers page under Settings on your Braze dashboard.” (without a link)
- Changed used components
- Remove link test
Before
After
> Config screen: Update helper text with no link [INTEG-2835]

- apps/bulk-edit/src/locations/Page/utils/entryUtils.ts
- apps/bulk-edit/test/locations/Page/entryUtils.test.tsx
Emily found a bug while working with bulk edit.  
https://github.com/user-attachments/assets/571feaf3-2514-416c-a250-2f98e3a74dc5
After investigating a bit, realized the error had to do with empty fields for localized fields
- Changed the logic for stringifying undefined values
- Added tests
https://github.com/user-attachments/assets/b09716ce-8c32-4d55-986d-0993580f5450
> Fix undefined for localized fields bulk edit app []

- apps/hubspot/src/locations/ConfigScreen.tsx
This update adds the warning note to let the user know that a config entry would be created if he installed the app (the same way as Braze does). And warn them to not delete or modify that entry.
Adding the Note component to match the figma design.
Now the config screen looks like this:
N/A
Link to the original ticket [INTEG-2769](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?issueParent=367108&label=10-Pines&selectedIssue=INTEG-2769)
N/A
[INTEG-2769]: https://contentful.atlassian.net/browse/INTEG-2769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hubspot: config entry warning note [INTEG-2769]

- apps/hubspot/src/locations/ConfigScreen.tsx
- apps/hubspot/src/utils/ConfigEntryService.ts
- apps/hubspot/src/utils/utils.ts
This update includes a refactor to have a configuration entry service so we can fetch, update or create the config entry in a simpler way and more reusable.
A ConfigEntryService was created and we now use that service in the config screen to create the config entry when the app is installed.
The methods of the service:
- getConfig
- updateConfig
Are not being used for the moment but are going to be needed later so they were also included to simplify the following tickets implementations.
This was the use case:
https://github.com/user-attachments/assets/ac8e2848-5393-4a93-bf76-043f7dcd68f2
N/A
This PR is a refactor for this ticket: [App Events - Setup custom content type for configuration](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?issueParent=367108&label=1 …
> Hubspot: adding config entry service [INTEG-2785]

- apps/hubspot/src/locations/Sidebar.tsx
- apps/hubspot/src/utils/ConfigEntryService.ts
- apps/hubspot/test/locations/Sidebar.spec.tsx
- apps/hubspot/test/mocks/mockSdk.ts
Add sync information in the Sidebar.
- If there are errors in synced fields, we display an error note.
- If there are synced fields, display how long ago they were sinced.
- Update the config entry with one connected field (make sure to include the `updatedAt` property), go to the entry and check the "Synced x time ago" appears
- Update the config entry with one connected field that includes the "error" property and check the warning appears in the sidebar
> Hubspot: add sync info to sidebar [INTEG-2773]

- apps/hubspot/src/locations/ConfigScreen.tsx
Found this can happen in Iterable
- Trim leading and trailing whitespaces
First add white spaces => Add trim => User no longer can leave white spaces as lead or trail:
https://github.com/user-attachments/assets/cc8f6825-a015-416f-bf6b-95e21d14a48c
> Trim whitespaces for access token in Config Screen []

- apps/iterable/package-lock.json
- apps/iterable/package.json
- apps/iterable/src/components/ContentfulApiKeyInput.tsx
- apps/iterable/src/locations/ConfigScreen.tsx
- apps/iterable/src/locations/Sidebar.tsx
- apps/iterable/test/mocks/index.ts
- apps/iterable/test/mocks/locations/Sidebar.spec.tsx
- apps/iterable/test/mocks/mockSdk.ts
Add the sidebar part to Iterable 
Out of scope: Add link with information, as we need the tech doc
- Add sidebar
- Add error handling
- Fix some whitespace error in the config screen (when the api key had spaces at the end or beginning, it affected the link creation)
-  Updated error handling in config screen to make it looks like the design
Sidebar
Using it to create a data feed with a 50 field content type
https://github.com/user-attachments/assets/d95f1886-660f-4357-b293-864906b2a97b
Using data feed to create email templates
https://github.com/user-attachments/assets/1b134ee0-1200-4756-9f4b-d2c09b781fa6
Using a reference
https://github.com/user-attachments/assets/354f0c9b-ac6d-4ec5-9d0f-496870040711
> Iterable: Sidebar [INTEG-2842]

- .github/workflows/codeql.yml
Enable CodeQL scans for GitHub workflow.
For more details on why we do this, please refer to https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
After the merge, navigate to the code-scanning findings available under the security tab --> code-scanning
> chore(ci): [SECURITY-936] Enable CodeQL scans for GitHub workflow+customise for existing flows

- apps/hubspot/src/locations/Dialog.tsx
- apps/hubspot/src/locations/Sidebar.tsx
- apps/hubspot/test/locations/Sidebar.spec.tsx
Give more details and a CTA if there's an error with the hubspot token when creating new modules.
The Dialog returns a boolean indicating if there was an error related to the token so a note can be displayed in the sidebar.
Paste an invalid token in the config screen and try to create new modules. An error should be displayed in the sidebar.
> Hubspot: Persist error in sidebar []

- apps/hubspot/contentful-app-manifest.json
- apps/hubspot/functions/appEventHandler.ts
- apps/hubspot/functions/createModules.ts
- apps/hubspot/src/locations/Dialog.tsx
- apps/hubspot/src/locations/Sidebar.tsx
- apps/hubspot/src/utils/ConfigEntryService.ts
- apps/hubspot/src/utils/utils.ts
- apps/hubspot/test/functions/appEventHandler.spec.ts
- apps/hubspot/test/functions/createModules.spec.ts
- apps/hubspot/test/locations/Dialog.spec.tsx
- apps/hubspot/test/locations/Sidebar.spec.tsx
- apps/hubspot/test/utils/ConfigEntryService.spec.ts
- This update includes:
- the storage on the config entry when the user create a module through the app
- the addition of more methods for the config entry service that are used in the createModule function
- the addition of some refactors for the Dialog and also for the createModule function
- The second part of the ticket will be contemplated on another PR: The update of the module when a user modifies a field
We use the config entry service to update the config entry.
Automated tests were added.
N/A
Link to [INTEG-2785](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?issueParent=367108&label=10-Pines&selectedIssue=INTEG-2785) ticket
N/A
[INTEG-2785]: https://contentful.atlassian.net/browse/INTEG-2785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> Hubspot: storage on module creation [INTEG-2785]

- apps/hubspot/functions/appEventHandler.ts
- apps/hubspot/functions/common.ts
- apps/hubspot/functions/createModules.ts
- apps/hubspot/functions/exceptions.ts
- apps/hubspot/test/functions/appEventHandler.spec.ts
- apps/hubspot/test/locations/Sidebar.spec.tsx
This update includes the second part of the [Update modules on entry save](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?issueParent=367108&label=10-Pines&selectedIssue=INTEG-2785) ticket pending in this [PR](https://github.com/contentful/apps/pull/9972).
- Logic to update a module on Hubspot was added inside the `appEventHandler` function when the user change a connected field in Contentful.
- Refactors were added, specially to extract the repeated logic between the `createModule` and `appEventHandler` functions
Changes in the appEventHandler and createModule functions.
Automated tests were added. You can check this update manually by creating a module through the app and then modifying the field and going to Hubspot to check the update: …
> Hubspot: Update modules on entry save [INTEG-2785]

- apps/hubspot/src/components/FieldSelection.tsx
- apps/hubspot/src/utils/ConfigEntryService.ts
- apps/hubspot/src/utils/utils.ts
Address several comments that rose up during QA.
Out of scope: This doesn't include the Get's started section. We'll take care of that after the Page view is ready
In the config screen:
- Updated instructions for creation
- Remove sound from the Hubspot's video 
In the Dialog:
- Added tooltip for unsupported fields during Field Selection
When creating the configEntry:  
- Updated the title so it says do not delete
Config:
https://github.com/user-attachments/assets/ade24c57-6a3d-43af-95e6-b9c7688950d3
Dialog:
https://github.com/user-attachments/assets/47b03167-0862-4cdf-a667-852b1030f96d
ConfigEntry title modification
https://github.com/user-attachments/assets/c2c44a39-da64-4df0-a5a3-20945a47740c
> Hubspot: Address QA comments [INTEG-2907]

- apps/hubspot/src/components/ConnectedEntriesTable.styles.ts
- apps/hubspot/src/components/ConnectedEntriesTable.tsx
- apps/hubspot/src/components/DisplayMessage.tsx
- apps/hubspot/src/locations/Page.styles.ts
- apps/hubspot/src/locations/Page.tsx
- apps/hubspot/test/locations/Page.spec.tsx
This update includes the table for the page location connected entries.
The table was created and some edge cases were handled (such as "loading state", "no connected entries" and "error when fetching").
Automated test were added.
https://github.com/user-attachments/assets/f81dce4c-0ab6-47c0-b201-0b4922809100
Error message:
N/A
Link to [INTEG-2780](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?issueParent=367108&label=10-Pines&selectedIssue=INTEG-2780) ticket.
N/A
[INTEG-2780]: https://contentful.atlassian.net/browse/INTEG-2780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hubspot: page location table [INTEG-2780]

- apps/mux/frontend/src/index.tsx
When an Entry contains the Mux plugin and the Asset is protected (or signed), an error occurred when trying to display the player because it attempted to play the video without the required tokens. This happened because the token retrieval call was made after rendering the player.
We now ensure that the token is retrieved before rendering the player. This change guarantees that the player has the necessary credentials at render time.
1. Create an Entry with a protected Asset.
2. Refresh the page.
3. The player should now render correctly without errors.
None.
No additional dependencies or references.
No deployment-related changes or concerns.
> Mux: Fixed signed tokens in Entry preview []

- apps/hubspot/src/locations/Dialog.tsx
- apps/hubspot/test/locations/Dialog.spec.tsx
Localize and non-localized fields have the same default name when creating a module. We want to change that.
- Improve naming convention to include localization. 
- Every whitespace is now a hypen
https://github.com/user-attachments/assets/ed2cffee-d1cd-4375-b6c7-6b26824fce8f
> Hubspot: Fix localization default names for modules issue [INTEG-2936]

- apps/hubspot/src/components/FieldSelection.tsx
- apps/hubspot/src/locations/Dialog.tsx
- apps/hubspot/test/locations/Dialog.spec.tsx
We want to avoid creating the same module for a field in an entry twice
- Call the Config entry service to get Connected fields for that entry 
- Block selection from Field Selection
- Add tooltip to warn the user that field is already Connected 
https://github.com/user-attachments/assets/8e94bc57-b172-41ea-b8de-1d47a5696447
> Hubspot: Avoid duplicated module creation [INTEG-2935]

- apps/hubspot/src/locations/Page.tsx
- apps/hubspot/test/locations/Page.spec.tsx
We found the following bug while testing the demo route in the table for the page view:
https://github.com/user-attachments/assets/a72cf34e-a0cc-4510-a374-a4b19481ec87
- Update entries after a disconnect
- Modify tests
With one entry:
https://github.com/user-attachments/assets/70f5af5a-3a4d-4f8b-ba6a-edd851159c40
With multiple entries:
https://github.com/user-attachments/assets/83b0d65d-a5fa-455d-8d08-36a325e0da1e
> Hubspot: Fix page view table issue []

- apps/hubspot/src/components/ConnectedEntriesTable.tsx
- apps/hubspot/src/components/ConnectedFieldsModal.tsx
- apps/hubspot/test/locations/Page.spec.tsx
- Use field name instead of id in the modal 
- Use content type name instead of id in the table
The Page table and modal were modified so the name is displayed instead of the id.
Automated tests were changed as well to match the field and content type name. Now it displays the name:
N/A
Link to [INTEG-2971](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?selectedIssue=INTEG-2971) ticket.
N/A
[INTEG-2971]: https://contentful.atlassian.net/browse/INTEG-2971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hubspot: changing displaying field and content type id for name [INTEG-2971]

- apps/hubspot/src/components/FieldModuleNameMapping.tsx
- apps/hubspot/src/locations/Dialog.tsx
- apps/hubspot/test/locations/Dialog.spec.tsx
This update includes the validation of the no duplicate names in the naming module selection step.
- The `Dialog.tsx` and `FieldModuleNameMapping.tsx` components were updated so the components doesn't allow duplicated names.
- Some modifications were made in the components, so the validations are re-triggered when the user changes the name again.
- The "Save and sync" button of the modal was modified: now it is disabled when there are errors in the naming validations
Automated tests were added. Manual test:
https://github.com/user-attachments/assets/54dc8504-f160-440f-8c1d-6de05a1e0ba1
N/A
Link to [INTEG-2967](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?issueParent=367108&selectedIssue=INTEG-2967) ticket. This ticket came from the mob QA.
N/A
[INTEG-2967]: …
> Hubspot: no duplicated names in module selection [INTEG-2967]

- apps/bulk-edit/package-lock.json
- apps/bulk-edit/package.json
- apps/bulk-edit/src/locations/Page/utils/entryUtils.ts
- apps/bulk-edit/test/locations/Page/entryUtils.test.tsx
Rich text fields appeared empty in the table. Now we show the truncated HTML for rich text if it has any value
- Add rich text case
- Add dependency to 
- Added bunches of tests for renderFieldValue
https://github.com/user-attachments/assets/b2f19dba-646b-4b07-a05b-7f88bfdaa8e3
> Bulk edit fix rich text visualization []

- apps/mux/frontend/src/index.tsx
- apps/mux/frontend/src/util/constants.ts
the sdk.ids.orgId refers to the current orgId but when we search for app actions, we need to search for the org where the app action lives. This code makes sure we use the correct org - if the app is the marketplace version, use the marketplace apps org, if this is a custom version, use the current orgId.
I was worried about exposing the orgId but Tyler said they are already exposed in our api calls so whatevs
> fix: use correct orgId for app actions [INTEG-3018]

- apps/rich-text-versioning/src/locations/Dialog.tsx
- apps/rich-text-versioning/test/locations/Dialog.spec.tsx
This update was introduced because the current content was not being shown in the modal when the published content was empty.
The conditional rendering to show the diff was updated, so now if there is current content the diff is going to be shown too.
An automated test was added to validate this change.
**Before**:
> <img width="1512" height="852" alt="Captura de pantalla 2025-08-14 a la(s) 10 55 11 a  m" src="https://github.com/user-attachments/assets/267ce18c-5208-403c-bd0b-47f704edc7bd" />
**Now**:
> <img width="1512" height="852" alt="Captura de pantalla 2025-08-14 a la(s) 10 54 54 a  m" src="https://github.com/user-attachments/assets/f8b1a4ae-8c65-4130-84b7-1099d3d4f13b" />
N/A
Link to [INTEG-3028](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?label=10-Pi …
> Rich-Text-Versioning: fix current content not showing [INTEG-3028]

- apps/mux/frontend/src/index.test.tsx
- apps/mux/frontend/src/index.tsx
- apps/mux/frontend/src/util/constants.ts
We were using the wrong method to get the app actions - we need to use getManyForEnvironement so that users can get the app actions, getMany only gets app actions the belong to that space, which when a user installs a marketplace app with actions, the action does not belong to their space it is just enabled.
> mux: use getmanyforenv for app actions [INTEG-3018]

- apps/rich-text-versioning/src/components/HtmlDiffViewer.tsx
- apps/rich-text-versioning/src/components/createOptions.tsx
- apps/rich-text-versioning/src/locations/Dialog.tsx
- apps/rich-text-versioning/src/locations/Field.tsx
- apps/rich-text-versioning/src/utils.ts
- apps/rich-text-versioning/test/locations/ConfigScreen.spec.tsx
- apps/rich-text-versioning/test/locations/Dialog.spec.tsx
- apps/rich-text-versioning/test/locations/Field.spec.tsx
- apps/rich-text-versioning/test/mocks/mockCma.ts
- apps/rich-text-versioning/test/mocks/mockSdk.ts
Display added or removed assets in the diff
Same approach as with references: add options to the renderer so it displays an AssetCard when it finds an asset node
Add or remove assets from a rich text and verify the diff
> Rich text versioning: Asset support [INTEG-3019]

- apps/bulk-edit/src/locations/Page/index.tsx
- apps/bulk-edit/src/locations/Page/styles.ts
We needed to change the spinner loader for a skeleton.
Used the Skeleton component from forma. Needed to wrap it up inside a table so the styles were applied to the skeleton correctly.
https://github.com/user-attachments/assets/0ee66894-6348-43e0-87ae-86df372cc67a
N/A
Link to [INTEG-3014](https://contentful.atlassian.net/jira/software/c/projects/INTEG/boards/3109?selectedIssue=INTEG-3104)
N/A
[INTEG-3014]: https://contentful.atlassian.net/browse/INTEG-3014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bulk-Edit-App: Changing the spinner for a skeleton [INTEG-3104]

- .github/dependabot.yml
- apps/rich-text-versioning/package-lock.json
- apps/rich-text-versioning/package.json
Dependabot updated the version of the field-editr-rich-text package in the Rich Text Versioning app and that broke it. The PR returns the version to the previous one and also updates the dependabot configuration so it ignores updates from that package in **all apps**.
> Rich Text Versioning: Downgrade field-editor-rich-text and stop automatic updates []

- apps/bulk-edit/.env.example
- apps/bulk-edit/.env.test
- apps/bulk-edit/.gitignore
- apps/bulk-edit/package-lock.json
- apps/bulk-edit/package.json
- apps/bulk-edit/src/locations/Page/components/BulkEditModal.styles.ts
- apps/bulk-edit/src/locations/Page/components/BulkEditModal.tsx
- apps/bulk-edit/src/locations/Page/components/TableHeader.tsx
- apps/bulk-edit/src/locations/Page/components/TableRow.tsx
- apps/bulk-edit/src/locations/Page/components/UndoBulkEditModal.tsx
- apps/bulk-edit/src/locations/Page/index.tsx
- apps/bulk-edit/src/locations/Page/styles.ts
- apps/bulk-edit/src/locations/Page/utils/constants.ts
- apps/bulk-edit/src/locations/Page/utils/entryUtils.ts
- apps/bulk-edit/src/scripts/deleteEntries.ts
- apps/bulk-edit/src/scripts/generateEntries.ts
- apps/bulk-edit/src/scripts/utils.ts
- apps/bulk-edit/test/locations/Page/BulkEditModal.test.tsx
- apps/bulk-edit/test/locations/Page/entryUtils.test.tsx
- apps/bulk-edit/test/scripts/deleteEntries.spec.ts
- apps/bulk-edit/test/scripts/generateEntries.spec.ts
- apps/bulk-edit/vite.config.mts
- apps/bulk-edit/vitest.config.mts
Version 1.1 for bulk edit
In this iteration:
- Freeze top headers and status column
- Editing more than 100+ at a time. 
- Viewing more than 100+ at a time
- Skeletons for loading
- Modal adjustments:
- Loading waiting times.
- Disable cancel button
- Fix values for fields using truncation
Main tickets:
2847, 2953, 3106 y 3104
> Bulk Edit v1.1 []

- examples/native-external-references-mockshop/functions/mockShop.ts
- examples/native-external-references-mockshop/package.json
We can remove the `ts-ignore` warning now since we updated the types.
We are updating the types in node app toolkit here 
- https://github.com/contentful/node-apps-toolkit/pull/780
Tested by updating the local node modules files in code.
Do not merge until this PR is merged.
https://github.com/contentful/node-apps-toolkit/pull/780
> chore: remove ts ignore warning[CNX-271]
