apps/ai-image-tagging/frontend/src/components/AITagView/AITagView.js
apps/ai-image-tagging/frontend/src/components/AITagView/AITagView.spec.js
apps/ai-image-tagging/frontend/src/components/AITagView/__snapshots__/AITagView.spec.js.snap
apps/ai-image-tagging/frontend/src/components/AppView/InstallationContent.js
apps/ai-image-tagging/frontend/src/components/AppView/__snapshots__/AppView.spec.js.snap

- Adding extra file validations (image dimensions and file size limits)
- Only show warning for content id collision on content id field and not name

AI Image tags QA Feedback

---

apps/jira/jira-app/src/__snapshots__/index.spec.tsx.snap
apps/jira/jira-app/src/components/App/Config.tsx
apps/jira/jira-app/src/components/Auth/index.tsx
apps/jira/jira-app/src/components/Jira/ErrorMessage.tsx
apps/jira/jira-app/src/components/Jira/IssueList.tsx
apps/jira/jira-app/src/components/Jira/Search.tsx
apps/jira/jira-app/src/components/Jira/index.tsx
apps/jira/jira-app/src/index.spec.tsx
apps/jira/jira-app/src/index.tsx
apps/jira/jira-app/src/jiraClient.ts
apps/jira/jira-app/src/mockResponses/fetchMock.ts
apps/jira/jira-app/typings.d.ts

Fixes:
1. Fixing issue where selected project doesn't automatically show up on the configuration screen after installation.
2. Fixing issue where a 401 or 403 wouldn't indicate any type of error. Now a user can choose to 'sign out' and go through the auth flow again.
3. Changing the amount of characters required in the search field to start a search. Was originally 4 now it is 2. This should get the search firing a bit faster.

Jira fixes

---

apps/gatsby/src/AppConfig.js
apps/gatsby/src/Sidebar.js
apps/gatsby/test/__snapshots__/sidebar.spec.js.snap
apps/gatsby/test/sidebar.spec.js

Gatsby fixes

---

apps/commercelayer/.prettierignore
apps/commercelayer/.prettierrc
apps/commercelayer/src/index.js
apps/commercetools/.prettierignore
apps/commercetools/.prettierrc
apps/commercetools/src/AppConfig/index.spec.tsx
apps/commercetools/src/AppConfig/parameters.ts
apps/commercetools/src/Editor/CategoryPreviews/CategoryPreviews.tsx
apps/commercetools/src/Editor/CategoryPreviews/SortableListItem.tsx
apps/commercetools/src/Editor/CategoryPreviews/__snapshots__/SortableListItem.spec.tsx.snap
apps/commercetools/src/Editor/ProductPreviews/SortableListItem.tsx
apps/commercetools/src/Editor/ProductPreviews/__snapshots__/SortableListItem.spec.tsx.snap
apps/commercetools/src/api/dataTransformers.ts
apps/commercetools/src/api/fetchCategoryPreviews.ts
apps/commercetools/src/api/fetchProductPreviews.ts
apps/commercetools/src/interfaces.ts
apps/shopify/.prettierignore
apps/shopify/.prettierrc
apps/shopify/src/Pagination.js
apps/shopify/src/dataTransformer.js
apps/shopify/src/index.js
apps/shopify/src/productResolvers.js

Fixes the behavior of all ecommerce apps for missing products

Ecommerce apps missing products bug

---

apps/google-analytics/src/index.tsx

GA: try to detect and inform about blocked GA requests (Firefox)

---

apps/jira/jira-app/src/components/App/Steps/InstanceStep.tsx

UI example: https://codesandbox.io/s/hoimb

Mimic the exact UI from example

---

lib/shared-dam-app/src/AppConfig/AppConfig.tsx
lib/shared-sku-app/src/AppConfig/AppConfig.tsx

Updating the UI and messaging to be clear.

Updating warning message about JSON in shared DAM and SKU

---

apps/ai-image-tagging/frontend/src/index.js
apps/google-analytics/src/index.tsx
apps/image-focal-point/src/index.js
apps/smartling/frontend/src/index.tsx
apps/typeform/frontend/src/index.tsx

There were some unguarded locations where the app potentially renders something when it shouldn't.

fix unguarded locations

---

apps/typeform/frontend/src/AppConfig/AppConfig.tsx

Adds a field type hint to see which fields are supported for the typeform app

fix(typeform): add field type hint

---

apps/netlify/src/constants.js

Rotate Netlify OAuth app

---

apps/jira/README.md
apps/jira/functions/fixtures/offline-secrets-manager.ts
apps/jira/functions/index.ts
apps/jira/functions/package-lock.json
apps/jira/functions/package.json
apps/jira/functions/serverless.yml
apps/jira/jira-app/package-lock.json
apps/jira/jira-app/package.json
apps/jira/jira-app/src/constants.ts
apps/jira/package-lock.json
apps/jira/package.json
apps/jira/scripts/dev.js

The dev script is supposed to
* create a `serverless.yml`file to be lunched on localhost
* lunch lunch lambda function locally along with the Contentful App
* revert everything in case of errors or normal process termination
Readme goes into the details of how this happens and what are the expectations for this to work.
I think it's not ideal yet, and can probably be generalized for all the apps using lambda functions, but this is meant to be a starting point for now.

chore: Improve development experience for Jira

---

.circleci/config.yml

Fixing the lerna issue
```
lerna ERR! *** Please tell me who you are.
lerna ERR! 
lerna ERR! Run
lerna ERR! 
lerna ERR!   git config --global user.email "you@example.com"
lerna ERR!   git config --global user.name "Your Name"
lerna ERR! 
lerna ERR! to set your account's default identity.
```

chore: setup git user for release commit

---

packages/dam-app-base/README.md
packages/dam-app-base/docs/README.md
packages/dam-app-base/src/interfaces.ts
packages/ecommerce-app-base/README.md
packages/ecommerce-app-base/docs/README.md
packages/ecommerce-app-base/docs/interfaces/integration.md
packages/ecommerce-app-base/src/interfaces.ts

Fixing some example code and fix copy-paste errors in the docs

chore: minor package doc fixes

---

packages/dam-app-base/README.md
packages/dam-app-base/package.json
packages/ecommerce-app-base/README.md
packages/ecommerce-app-base/package.json

* added the `description` field to `package.json`
* fix links to existing apps in package readmes

Minor fixes to packages

---

packages/ecommerce-app-base/package-lock.json
packages/ecommerce-app-base/package.json

Fixes https://github.com/contentful/apps/issues/194
There's a dependency conflict between the Forma36 version used in Create Contentful App, and the one used in `ecommerce-app-base`

fix(ecommerce-app-base): bump Forma36 dependency

---

packages/ecommerce-app-base/package-lock.json
packages/ecommerce-app-base/package.json

BREAKING CHANGE: React now needs to be installed separately when using this package.

fix(ecommerce-app-base): move react to peerDependencies and bump react 

---

.gitignore
apps/bynder/src/index.html
apps/bynder/src/index.js

This reverts commit 26515c2e1e53ddef0e0661bf4372830711f8ca7b, reversing
changes made to e257930f5410fbc3c0344b6e8c039256c7b69a2a.

fix: [] Revert "Merge pull request #203 from contentful/update-bynder-app"

---

apps/gatsby/src/Sidebar.js

feat: define entry slugs

---

.circleci/config.yml
apps/ai-image-tagging/lambda/package.json
apps/brandfolder/package.json
apps/bynder/package.json
apps/cloudinary/package.json
apps/commercelayer/package.json
apps/commercetools/package.json
apps/dropbox/package.json
apps/frontify/package.json
apps/gatsby/package.json
apps/google-analytics/package.json
apps/image-focal-point/package-lock.json
apps/image-focal-point/package.json
apps/jira/functions/package.json
apps/jira/jira-app/package.json
apps/mux/package.json
apps/optimizely/package.json
apps/saleor/package.json
apps/shopify/package.json
apps/smartling/lambda/package.json
apps/typeform/lambda/package.json
package.json

Generally this is pretty straightforward. 
The weirdest change is probably that I've created a `test:deploy` script in each package.json. At the moment just calls the deploy script for most apps. However in the focal point app, this is now an actually different script, which will try and upload the bundle to a test org/definition. 
I've done this, because it seems tricky to manage a test deployment using our new scripts just using environment variables. It would mean making each app definition an environment variable, and then overwriting those definitions for the test script.

feat: [EXT-2722] use contentful hosting for image focal point app

---

apps/brandfolder/package-lock.json
apps/bynder/package-lock.json
apps/cloudinary/package-lock.json
apps/commercelayer/package-lock.json
apps/commercelayer/package.json
apps/dropbox/package-lock.json
apps/frontify/package-lock.json
apps/mux/package-lock.json
apps/saleor/package-lock.json
apps/saleor/package.json
apps/shopify/package-lock.json
apps/shopify/package.json

This reverts commit b4f398f7fe4fb2952e8505a7657b876861fe3a24.

fix: [] Revert "feat: [EXT-2533] use new version of ecommerce base app (#239)"

---

examples/content-type-selection-config/set-editors.tsx

We changed the requirements for target state at some point, breaking this example
this pr get's it working again

chore: update set-editors example

---

apps/bynder/package-lock.json
apps/bynder/package.json

Deploy Bynder with app hosting

feat: [EXT-2717] deploy bynder app with ctf app hosting

---

apps/optimizely/package-lock.json
apps/optimizely/package.json

This reverts commit f92e8cce4b854a8045f9d96bb8724e0530c5d38e.
App hosting is breaking the optimizley app due to url changes

Revert "feat: [EXT-2717] build optimizely with app hosting (#365)"

---

apps/mux/package-lock.json
apps/mux/package.json

This reverts commit 4232d1f586d13519eccff7f05be02b0852a07c49.

fix: [EXT-2717] revert use app hosting for MUX

---

apps/jira/jira-app/package-lock.json
apps/jira/jira-app/package.json

Another update in a frontend app

chore: [] bump contentful cli to latest version

---

apps/bynder/package-lock.json
apps/cloudinary/package-lock.json
apps/dropbox/package-lock.json

Reinstalling react-scripts updated some underlying packages, fixing some vulnerabilities

chore: [] updating react scripts packages

---

apps/mux/package-lock.json
apps/mux/package.json

This reverts commit 52d6d1cec64675ecadc741fc3853e4f13d61f7ae.

feat: [EXT-2717] use app hosting for MUX 

---

apps/bynder/package-lock.json
apps/bynder/package.json
apps/cloudinary/package-lock.json
apps/cloudinary/package.json
apps/dropbox/package-lock.json
apps/dropbox/package.json
apps/frontify/package-lock.json
apps/frontify/package.json

according to https://github.com/facebook/create-react-app/issues/11174 most of the vulnerabilities from react-scripts are false positive. 
Moving it to the devDependencies should make them disappear.

chore: [] make react scripts dev dep

---

apps/ai-image-tagging/lambda/package-lock.json
apps/ai-image-tagging/lambda/package.json
apps/ai-image-tagging/lambda/serverless.yml
apps/jira/functions/serverless.yml
apps/smartling/lambda/serverless.yml
apps/typeform/lambda/package-lock.json
apps/typeform/lambda/package.json
apps/typeform/lambda/serverless.yml

see https://github.com/contentful/apps/pull/423
Changes:
* Pin serverless dependency
* Rename stages for jira app. It was still using the old `dev` stage
Current production is already on the latest version to avoid permission issues in the future

feat: upgrade serverless to v2

---

apps/commercetools/src/AppConfig/FieldSelector/ToggleGroup.tsx
apps/commercetools/src/AppConfig/FieldSelector/index.tsx
apps/commercetools/src/AppConfig/FieldTypeInstructions.tsx
apps/commercetools/src/AppConfig/fields.spec.ts
apps/commercetools/src/AppConfig/fields.ts
apps/commercetools/src/AppConfig/index.tsx
apps/commercetools/src/interfaces.ts

We currently only show "Short text" fields, but not "Short text, list" fields

feat: show "Short text, list" fields on app config page [EXT-3146]

---

apps/commercetools/src/Editor/ProductPreviews/__snapshots__/SortableList.spec.tsx.snap
apps/commercetools/src/Editor/ProductPreviews/__snapshots__/SortableListItem.spec.tsx.snap
apps/commercetools/src/__mocks__/productPreviews.ts
packages/ecommerce-app-base/src/Editor/__snapshots__/SortableList.spec.tsx.snap
packages/ecommerce-app-base/src/Editor/__snapshots__/SortableListItem.spec.tsx.snap
packages/ecommerce-app-base/src/SkuPicker/ProductList/__snapshots__/ProductListItem.spec.tsx.snap
packages/ecommerce-app-base/src/SkuPicker/ProductList/__snapshots__/index.spec.tsx.snap
packages/ecommerce-app-base/src/SkuPicker/ProductSelectionList/__snapshots__/index.spec.tsx.snap
packages/ecommerce-app-base/src/SkuPicker/__snapshots__/SkuPicker.spec.tsx.snap
packages/ecommerce-app-base/src/__mocks__/productPreviews.ts

Remove references to s3 buckets in mocks. It's mock data and dont want to give impression we own those

chore(S3): remove references in mocks for buckets [EXT-3400]

---

.github/dependabot.yml
templates/typescript/package-lock.json
templates/typescript/package.json
templates/typescript/src/components/ConfigScreen.tsx

📉 `emotion` v11 → `emotion` v10

chore: Downgrade emotion package

---

.circleci/config.yml
.github/dependabot.yml
templates/javascript/README.md
templates/javascript/package-lock.json
templates/javascript/package.json
templates/javascript/public/index.html
templates/javascript/src/components/ConfigScreen.jsx
templates/javascript/src/components/ConfigScreen.spec.jsx
templates/javascript/src/components/Dialog.jsx
templates/javascript/src/components/Dialog.spec.jsx
templates/javascript/src/components/EntryEditor.jsx
templates/javascript/src/components/EntryEditor.spec.jsx
templates/javascript/src/components/Field.jsx
templates/javascript/src/components/Field.spec.jsx
templates/javascript/src/components/LocalhostWarning.jsx
templates/javascript/src/components/Page.jsx
templates/javascript/src/components/Page.spec.jsx
templates/javascript/src/components/Sidebar.jsx
templates/javascript/src/components/Sidebar.spec.jsx
templates/javascript/src/index.jsx
templates/javascript/src/setupTests.js
templates/javascript/test/mocks/index.js
templates/javascript/test/mocks/mockCma.js
templates/javascript/test/mocks/mockSdk.js

Like it says in the title - support JS template

feat(JSTemplate): Add js template for CCA [EXT-3407]

---

apps/netlify/frontend/src/config.spec.js

Updating unit tests to match new parameters shape

test: [] Update tests

---

examples/javascript/src/App.jsx
examples/javascript/src/index.jsx
examples/javascript/src/locations/ConfigScreen.jsx
examples/javascript/src/locations/ConfigScreen.spec.jsx
examples/javascript/src/locations/Dialog.jsx
examples/javascript/src/locations/Dialog.spec.jsx
examples/javascript/src/locations/EntryEditor.jsx
examples/javascript/src/locations/EntryEditor.spec.jsx
examples/javascript/src/locations/Field.jsx
examples/javascript/src/locations/Field.spec.jsx
examples/javascript/src/locations/Page.jsx
examples/javascript/src/locations/Page.spec.jsx
examples/javascript/src/locations/Sidebar.jsx
examples/javascript/src/locations/Sidebar.spec.jsx
examples/typescript/src/App.tsx
examples/typescript/src/index.tsx
examples/typescript/src/locations/ConfigScreen.spec.tsx
examples/typescript/src/locations/ConfigScreen.tsx
examples/typescript/src/locations/Dialog.spec.tsx
examples/typescript/src/locations/Dialog.tsx
examples/typescript/src/locations/EntryEditor.spec.tsx
examples/typescript/src/locations/EntryEditor.tsx
examples/typescript/src/locations/Field.spec.tsx
examples/typescript/src/locations/Field.tsx
examples/typescript/src/locations/Page.spec.tsx
examples/typescript/src/locations/Page.tsx
examples/typescript/src/locations/Sidebar.spec.tsx
examples/typescript/src/locations/Sidebar.tsx

Ran prettier in JS and TS examples + renaming the location component

refactor: [] cleanup examples

---

apps/jira/README.md
apps/jira/jira-app/package-lock.json
apps/jira/jira-app/package.json
apps/jira/jira-app/src/components/Jira/IssueCard.tsx
apps/jira/jira-app/src/constants.ts
apps/jira/jira-app/src/interfaces.ts
apps/jira/scripts/dev.js

This includes a few changes in the local setup documentation, due since the react-script migration

feat(jira): make priority optional EXT-3649

---

apps/bynder/src/index.js

Json object now has tags coming from Bynder

Tags added to the Bynder Json Object

---

apps/mux/README.md
apps/mux/src/config.tsx
apps/mux/src/index.tsx
apps/mux/src/player.tsx
apps/mux/src/signingTokens.tsx

feat: added audioonly, max_stored_resolution, max_stored_frame_rate, duration
feat: added custom domain support for dashboard playback.

feat: custom domain support and additional parameters

---

apps/commercelayer/src/index.js

- fix: Validate parameters and allow empty scope for retro compatibility

fix: Configuration page

---

apps/commercetools/src/api/client.ts

Issue:
https://github.com/contentful/apps/issues/1425

fix: [EXT-3846] Parameterize api url

---

examples/vite-react/.gitignore
examples/vite-react/README.md
examples/vite-react/index.html
examples/vite-react/package-lock.json
examples/vite-react/package.json
examples/vite-react/src/App.tsx
examples/vite-react/src/components/LocalhostWarning.tsx
examples/vite-react/src/index.tsx
examples/vite-react/src/locations/ConfigScreen.spec.tsx
examples/vite-react/src/locations/ConfigScreen.tsx
examples/vite-react/src/locations/Dialog.spec.tsx
examples/vite-react/src/locations/Dialog.tsx
examples/vite-react/src/locations/EntryEditor.spec.tsx
examples/vite-react/src/locations/EntryEditor.tsx
examples/vite-react/src/locations/Field.spec.tsx
examples/vite-react/src/locations/Field.tsx
examples/vite-react/src/locations/Page.spec.tsx
examples/vite-react/src/locations/Page.tsx
examples/vite-react/src/locations/Sidebar.spec.tsx
examples/vite-react/src/locations/Sidebar.tsx
examples/vite-react/src/vite-env.d.ts
examples/vite-react/test/mocks/index.ts
examples/vite-react/test/mocks/mockCma.ts
examples/vite-react/test/mocks/mockSdk.ts
examples/vite-react/tsconfig.json
examples/vite-react/vite.config.ts

As the title says.
Same as the default typescript example just with vite & vitest instead of react-scripts and jest

Vite/Vitest React example

---

apps/netlify/frontend/package-lock.json
apps/netlify/frontend/package.json

fix(deps): revert pubnub from 7.2.0 to 4.24.3

---

apps/commercetools/src/api/products.ts

Addressing issue: https://github.com/contentful/apps/issues/1592

feat: [] Fetch all pages of previews

---

apps/netlify/frontend/src/constants.js

This is an interim solution to unblock #1623. We will followup with some retry/batching logic to prevent rate limiting issues.

feat: [] increase max configs to 20

---

apps/bynder/src/README.md
apps/bynder/src/index.js

Fixes https://github.com/contentful/apps/pull/1641 that https://github.com/contentful/apps/pull/1586 update PR created. Also removes all the odd edited files that appeared [here](https://github.com/contentful/apps/pull/1656)
Not sure why, but Bynder base URL had to be https://d8ejoa1fys2rk.cloudfront.net instead of the URL the Bynder docs recommended to allow login.

feat: upgrade bynder from compactview 2 to 3

---

examples/home-location/package.json
package-lock.json

Pin app-sdk version to get canary branch version.

chore: [] Fix home-location example app-sdk version

---

.github/dependabot.yml
apps/cloudinary/package-lock.json
apps/cloudinary/package.json

Downgrade App SDK in Cloudinary App to v4.10.0

fix(cloudinary): temporarily downgrade App SDK

---

apps/mux/package.json

fix: set Contentful packages to latest

fix: change deploy script naming

---

apps/graphql-playground/package.json

Temporarily pinning version of graphql playground app

fix: [] temporarily disable deploys for graphql playground

---

.contentful/vault-secrets.yaml

chore: add vault support [EXT-4121]

---

.contentful/vault-secrets.yaml

chore: remove name sharing [EXT-4121]

---

examples/asset-upload/.gitignore
examples/asset-upload/README.md
examples/asset-upload/index.html
examples/asset-upload/package-lock.json
examples/asset-upload/package.json
examples/asset-upload/src/components/LocalhostWarning.tsx
examples/asset-upload/src/index.tsx
examples/asset-upload/src/locations/Field.tsx
examples/asset-upload/src/vite-env.d.ts
examples/asset-upload/tsconfig.json
examples/asset-upload/vite.config.ts

Adds an example to demo how to upload/create an asset from a field location
Created a new example `asset-upload` that show's a button to upload a file. Once clicked, the file is uploaded, an asset created and the asset linked in the current field.

feat: Asset Upload example

---

apps/smartling/lambda/package-lock.json
apps/smartling/lambda/package.json

Similar to #2292 but for lambda this time

fix(Smartling): Bump smartlin lambda

---

examples/typescript-github-action/.github/workflows/deploy.yml
examples/typescript-github-action/.gitignore
examples/typescript-github-action/README.md
examples/typescript-github-action/package-lock.json
examples/typescript-github-action/package.json
examples/typescript-github-action/public/index.html
examples/typescript-github-action/src/App.tsx
examples/typescript-github-action/src/components/LocalhostWarning.tsx
examples/typescript-github-action/src/index.tsx
examples/typescript-github-action/src/locations/ConfigScreen.spec.tsx
examples/typescript-github-action/src/locations/ConfigScreen.tsx
examples/typescript-github-action/src/locations/Dialog.spec.tsx
examples/typescript-github-action/src/locations/Dialog.tsx
examples/typescript-github-action/src/locations/EntryEditor.spec.tsx
examples/typescript-github-action/src/locations/EntryEditor.tsx
examples/typescript-github-action/src/locations/Field.spec.tsx
examples/typescript-github-action/src/locations/Field.tsx
examples/typescript-github-action/src/locations/Home.spec.tsx
examples/typescript-github-action/src/locations/Home.tsx
examples/typescript-github-action/src/locations/Page.spec.tsx
examples/typescript-github-action/src/locations/Page.tsx
examples/typescript-github-action/src/locations/Sidebar.spec.tsx
examples/typescript-github-action/src/locations/Sidebar.tsx
examples/typescript-github-action/src/react-app-env.d.ts
examples/typescript-github-action/src/setupTests.ts
examples/typescript-github-action/test/mocks/index.ts
examples/typescript-github-action/test/mocks/mockCma.ts
examples/typescript-github-action/test/mocks/mockSdk.ts
examples/typescript-github-action/tsconfig.json

Add a new template with github-actions workflow
for review; focus on the `.github`-folder and the readme. All other files have been copied from the typescript-template

feat: add a typescript template with github-actions workflow

---

apps/google-analytics-4/frontend/.env
apps/google-analytics-4/frontend/.env.development
apps/google-analytics-4/frontend/package-lock.json
apps/google-analytics-4/frontend/package.json
apps/google-analytics-4/frontend/src/components/InstalledServiceAccountKey.spec.tsx
apps/google-analytics-4/frontend/src/components/InstalledServiceAccountKey.tsx
apps/google-analytics-4/frontend/src/config.ts
apps/google-analytics-4/frontend/src/locations/ConfigScreen.spec.tsx
apps/google-analytics-4/frontend/src/services/api.spec.ts
apps/google-analytics-4/frontend/src/services/api.ts
apps/google-analytics-4/frontend/src/setupTests.ts
apps/google-analytics-4/frontend/test/mocks/api/handlers.ts
apps/google-analytics-4/frontend/test/mocks/api/server.ts
apps/google-analytics-4/lambda/nodemon.json
apps/google-analytics-4/lambda/package-lock.json
apps/google-analytics-4/lambda/package.json
apps/google-analytics-4/lambda/serverless.yml
apps/google-analytics-4/lambda/src/app.spec.ts
apps/google-analytics-4/lambda/src/app.ts
apps/google-analytics-4/lambda/src/index.ts

Implements the "status" check on the installed credentials components.
When a user has installed service account credentials in the GA4 app, they want to know whether the credentials are in fact correct and "active" -- that is whether they actually are functional against the GA APIs we will use to query analytics data.
For now, we just need the basic plumbing in place to fetch the status from the lambda backend and display it on the front end. In subsequent PRs we will make the actual calls to GA APIs etc.
* Hard code a status object to be returned from the Lambda API endpoint
* Create an API client to fetch from the Lambda
* Use [zod](https://github.com/colinhacks/zod) to handle schema validation and types. Super cool! (I saw that atools is using it in a handful of their projects)
* Use …

feat: check credentials endpoint on app configuration screen [INTEG-97]

---

apps/slack/frontend/package.json

We had TEST urls for prod env 😞 . Updating build command to use our prod env.
Check if prd-slack app has the correct URLs

fix: Slack prd URLs [EXT-4253]

---

apps/google-analytics-4/lambda/package-lock.json
apps/google-analytics-4/lambda/package.json

standardize our frontend/backend package configurations for the google analytics 4 app
follow the same naming and versioning pattern in lambda and frontend

updates lambda package.json

---

package.json

chore: fix typo []

---

examples/last-fm/src/locations/Field.tsx

fix(Last.fm): type issue

---

apps/wistia-videos/package-lock.json
apps/wistia-videos/package.json

Recent introduction of Wistia Video apps broke the build. I overlooked that the app didn't have `@contentful/app-scripts` already installed!
* Just install the package
* Example build that broke: https://app.circleci.com/pipelines/github/contentful/apps/15201/workflows/934db333-5604-4c9a-a15a-687210ee3c24/jobs/35543

fix: add contentful-app-scripts []

---

apps/google-analytics-4/lambda/package.json
apps/google-analytics-4/lambda/serverless.yml

This reverts commit 5aacd356665935f5ebc2f30aad978f693d78564f.
We broke our dev process in addition to this not working for our deploy needs. We'll use this code later but need to un-stuck the team now.
Doing a single revert (the squashed merge commit) for now. We'll revert-revert this later once we're in a better place.

Revert "INTEG-133/ ga-4 domain management and API gateway (#2530)"

---

apps/google-analytics-4/lambda/src/lib/errors/middlewares.ts

Address eslint error related to superfluous imports
Removes unused imports

remove unused import

---

apps/google-analytics-4/lambda/src/services/google-api.ts

[JIRA Link](https://contentful.atlassian.net/browse/INTEG-183)
We need API error types for the front in the error message so that we know how to handle them in the front end (ie: what kind of badges to show, what status, etc...)
Also cleans up some of the un-needed google-api functions like (fetchAccounts, and erroneous call to run report in accountSummary)
Smallest changes we can make to the backend lambda without a larger re-architecture
None

[INTEG-183] Adds Admin and Data API Error types

---

apps/google-analytics-4/frontend/src/App.tsx
apps/google-analytics-4/frontend/src/helpers/contentfulContext.ts
apps/google-analytics-4/frontend/src/services/api.spec.ts
apps/google-analytics-4/frontend/src/services/api.ts
apps/google-analytics-4/frontend/src/types.ts
apps/google-analytics-4/lambda/src/app.spec.ts
apps/google-analytics-4/lambda/src/middlewares/serviceAccountKeyProvider.spec.ts
apps/google-analytics-4/lambda/src/middlewares/serviceAccountKeyProvider.ts
apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.spec.ts
apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.ts

be consistent with our contentful header casing
adds some useful abstraction and types for contentful context (`sdk.ids` & `sdk.location`) and contentful context headers (`X-Contentful-<Whatever>`)

normalizes casing of headers (upperfirst+camelcasing)

---

.circleci/config.yml

We misspelled conten`t`ful in the org name setting for sentry, unsurprisingly this causes the job to fail.
I have added a missing 't' to Contentful.

Fix sentry org naming

---

apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.ts

adds logging for request verification

---

apps/google-analytics-4/lambda/src/middlewares/corsConfig.ts

fix CORS issue in ga4 app in production
allow recently added contentfulContextHeaders

adds ContentfulContextHeaders to cors policy

---

apps/google-analytics-4/lambda/src/middlewares/index.ts
apps/google-analytics-4/lambda/src/middlewares/verifySignedRequests.ts

fix bug and add logging for further debugging
adds useful logging for debugging

restore apiErrorMap and add logging for request signing headers

---

apps/google-analytics-4/frontend/src/locations/ConfigScreen.tsx
apps/google-analytics-4/lambda/src/middlewares/index.ts

Fixes a duplication bug in the app.ts and errorHandler in the middleware

[Build-Fix] Fixes error mapper duplication bug

---

apps/google-analytics-4/frontend/package-lock.json

keep deps up to date
npm update
Resolve minor inline dependency update that happens in CI

bump caniuse-lite

---

apps/google-analytics-4/lambda/src/app.ts

fix git rebase mistake from: https://github.com/contentful/apps/pull/2636/files#diff-45d0041a623995e1e3d8489b53abc54a5cd25589cd4e2d7f06bf2d05971d91a0
git conflicts are hard

fix git rebase mistake

---

.github/workflows/dependabot-approve-and-request-merge.yml

chore: [ATOOLS-424] Update dependabot-approve-and-request-merge.yml

---

apps/google-analytics-4/frontend/src/components/main-app/ChartHeader.tsx
apps/google-analytics-4/frontend/src/components/main-app/analytics-app/AnalyticsApp.tsx
apps/google-analytics-4/frontend/src/components/main-app/line-chart/LineChart.tsx

[JIRA Ticket](https://contentful.atlassian.net/browse/INTEG-266)
Turn this
into this
Talked with stakeholders on what needs to be updated

[INTEG-266] Updated Ga4 Sidebar chart with new fixes

---

apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertySection.tsx

Bug fix, graph should show up in sidebar now 
Test in Config page, Test in sidebar

[BUG FIX INTEG-243] Fixes properties prefix bug being set in app params

---

apps/google-analytics-4/lambda/.env
apps/google-analytics-4/lambda/config/serverless-env.dev.yml.example
apps/google-analytics-4/lambda/config/serverless-env.prd.yml
apps/google-analytics-4/lambda/config/serverless-env.test.yml
apps/google-analytics-4/lambda/docker-compose.yml
apps/google-analytics-4/lambda/serverless.yml
apps/google-analytics-4/lambda/src/config.ts
apps/google-analytics-4/lambda/src/services/dynamoDbService.ts

simplify env vars

---

apps/google-analytics-4/lambda/.env
apps/google-analytics-4/lambda/docker-compose.yml
apps/google-analytics-4/lambda/serverless.yml
apps/google-analytics-4/lambda/src/config.ts
apps/google-analytics-4/lambda/src/services/dynamoDbService.ts

clean up env vars

---

apps/google-analytics-4/frontend/src/apis/apiTypes.ts
apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ChecklistSplitter.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ChecklistUtils.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/GenericCheckRow.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ServiceAccountChecklist.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ServiceAccountChecklist.tsx
apps/google-analytics-4/lambda/src/errors/apiError.ts
apps/google-analytics-4/lambda/src/services/googleApiUtils.ts

[JIRA Ticket](https://contentful.atlassian.net/browse/INTEG-261) - Builds UI Checklist
[JIRA Ticket](https://contentful.atlassian.net/browse/INTEG-299) - Adds call to action for api checklist rows
[JIRA Ticket](https://contentful.atlassian.net/browse/INTEG-255) - Properly hides and shows Property mapping dropdown
Iterative discussions about the UI/UX

[INTEG-261] Service Account Checklist

---

apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.tsx
apps/google-analytics-4/frontend/src/components/config-screen/header/AboutSection.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/header/AboutSection.tsx

Resolve ambiguous references to Google Analytics and remove an & in favor of "and"
Targeted copy replacement following QA
N/A
N/A

Integ 316 copy updates

---

apps/sap-commerce-cloud/src/AppConfig/AppConfig.spec.tsx

Build breaks because of a compilation error
https://app.circleci.com/pipelines/github/contentful/apps/17813/workflows/ca9a349a-10d5-4db7-83cd-57f04ed44743/jobs/44094
Fix compilation error so that the build passes

[Bug] Fix broken SAP test

---

apps/sap-commerce-cloud/package-lock.json
apps/sap-commerce-cloud/package.json

Forgot app scripts, needed for the deploy

add app scripts

---

apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeCard.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.tsx
apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertySection.tsx

Presently our instruction copy is not great for configuring your property and content types. Specifically we need to:
* Help the user understand what choices they are making and why
* Point the user to appropriate instructions copy
* Provide contextual help as simply as possible
* Add helpful text on the property dropdown.
* Move contextual "if you don't see a property" text to help text. Lower volume reduces noise and also confusion (since it only applies to some users)
* Add helpful text under content type configuration
* Add tooltips with descriptions + examples. (Examples might sound goofy but I think they make concrete what is otherwise very abstract for normal users)
* Add link to docks. It says "WRONG" because we don't have the real link and this intended to stick out like a sore …

Ux/configuration instructions [INTEG-294]

---

apps/google-analytics-4/frontend/src/apis/apiTypes.ts
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ChecklistUtils.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/GenericCheckRow.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ServiceAccountChecklist.spec.tsx
apps/google-analytics-4/frontend/src/components/main-app/ErrorDisplay/ErrorDisplay.spec.tsx
apps/google-analytics-4/frontend/src/components/main-app/ErrorDisplay/ErrorDisplay.tsx

The first draft copy used for the status checks was a bit confusing and inconsistent in places. We want it to be very clear so the UX for service account installation is super clean.
There were also a few small edge case bugs and inconsistencies that need to be addressed. A lot of this compounded by the number of combinations, which makes it easy to over look edge cases.
A few bugs were found that are out of scope; tickets created.
* Update the copy as needed. See screenshots for pertinent details

Update status check copy for clarity

---

apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeCard.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeRow.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeRow.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.tsx

optimize keyboard navigability and accessibility of the content type configuration section of the GA4 config screen
ensure focus is set to newly added content type configuration rows
https://user-images.githubusercontent.com/492573/229544975-255699a1-92b5-4b54-b673-31da2763be90.mov

optimizes keyboard navigability in content type configuration section

---

apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage.spec.tsx
apps/sap-commerce-cloud/src/AppConfig/AppConfig.tsx
apps/sap-commerce-cloud/src/api/dataTransformers.ts
apps/sap-commerce-cloud/src/api/fetchCategoryPreviews.ts
apps/sap-commerce-cloud/src/components/Dialog.tsx
apps/sap-commerce-cloud/src/components/Dialog/ProductList.tsx

Lint errors is causing SAP builds to fail
Fix the lint errors wherever possible

[Fix] SAP Lint errors

---

apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.styles.ts
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.tsx
apps/google-analytics-4/frontend/src/components/main-app/LineChart/LineChart.styles.ts
apps/google-analytics-4/frontend/src/components/main-app/LineChart/LineChart.tsx

This PR fixes two UI issues: 
1. Misaligned components on Config page. (someone had an eagle eye during Mob QA)
2. Resizing issue of the chart - I noticed it when switching the browser from large to small screen.
Digging thru the Chart.js docs, I found [this](https://www.chartjs.org/docs/latest/configuration/responsive.html#important-note) that outlines how best to resize the chart. Ultimately, for responsiveness, the Charts needs a parent component with relative position.

Integ 318 UI status checks component not vertically aligned on app config page

---

apps/ai-content-generator/package-lock.json
apps/ai-content-generator/src/locations/Sidebar.jsx

- fixes issue with poluted state when changing the action after running a different one
- better error handling and presentation to user

tweaks and fixups for ai-content-generator

---

apps/sap-commerce-cloud/src/api/fetchProductPreviews.ts
apps/sap-commerce-cloud/src/components/Dialog/ProductList.tsx

Fix: bug with single product selection in SAP app (was storing incomplete URL identifier)

fix: [] populate full URL before trying to fetch from SAP API

---

apps/google-analytics-4/README.md
apps/google-analytics-4/lambda/Makefile

adds make go command

---

apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage/GoogleAnalyticsConfigPage.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/ApiAccessSection.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/DisplayServiceAccountCard.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/display/ServiceAccountChecklist.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/header/AboutSection.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertySection.spec.tsx
apps/google-analytics-4/frontend/src/components/main-app/AnalyticsApp/AnalyticsApp.spec.tsx

Flakey GA4 tests is killing our dev flow
Most likely it has something to do with the rendering of components in an async await method

[Fix] Flakey GA4 tests

---

apps/google-analytics/src/index.tsx

Change deeplink to Marketplace link
Cmd+C, Cmd+V
Click the link
None
None
N/A

Fix link to marketplace

---

apps/google-analytics-4/frontend/package.json
apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage/GoogleAnalyticsConfigPage.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/WarningDisplay/WarningDisplay.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeRow.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/ContentTypeWarning.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertyDropdown.spec.tsx
apps/google-analytics-4/frontend/src/components/main-app/AnalyticsApp/AnalyticsApp.spec.tsx
apps/google-analytics-4/frontend/src/components/main-app/ErrorDisplay/ErrorDisplay.spec.tsx

Tests that were flakey were skipped/xdescribed. This PR un-skips the flakey tests and fixes them to be as reliable as the bitcoin network
Run the build several times in different PRs and they pass

[INTEG-389] Fix flakey GA4 Tests

---

apps/graphql-playground/src/components/GqlPlayground.tsx

This might help people to see that the default limit of the `collections` is `100`
https://user-images.githubusercontent.com/38977667/232449691-3c203ec2-8ecb-41cd-b3bd-4ca40f8fdf1f.mp4

feat: add a note about default limits []

---

apps/google-analytics-4/frontend/package.json

Adds run in band for CI test

---

apps/google-analytics-4/frontend/src/components/config-screen/GoogleAnalyticsConfigPage/GoogleAnalyticsConfigPage.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/WarningDisplay/WarningDisplay.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/api-access/setup/SetupServiceAccountCard.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeRow.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/ContentTypeWarning.spec.tsx
apps/google-analytics-4/frontend/src/components/config-screen/map-account-property/MapAccountPropertyDropdown.spec.tsx

-Remove FakeTimers, and anti-pattern WaitFors.
-Also unskip skipped tests now that the build is stable
Build should pass and tests should pass.

[INTEG-389] Clean up waitFor, and fakeTimers, and unskip skipped tests

---

apps/ecommerce/frontend/package-lock.json
apps/ecommerce/frontend/package.json

adds missing sentry package

---

.circleci/config.yml
package.json

fix sentry release command execution

move sentry release into npm script

---

apps/ecommerce/frontend/package-lock.json
apps/ecommerce/frontend/package.json
apps/ecommerce/frontend/src/components/MissingResourceCard.tsx
apps/ecommerce/frontend/src/components/ResourceCard.tsx

adds generalized MissingResourceCard
Single reference field:
Multi reference field (with drag handle):
Compared to native:
Single or Multi reference field:

adds missing resource card

---

apps/ecommerce/frontend/src/components/MissingResourceCard.tsx
apps/ecommerce/frontend/src/components/ResourceCard.tsx
apps/ecommerce/frontend/src/components/ResourceCardMenu.tsx
apps/ecommerce/frontend/src/components/ResourceCardRawData.tsx
apps/ecommerce/lambda/src/middlewares/verifySignedRequests.ts

tweaks to show/hide data and fix bug with react rerendering race condition with useLayoutEffect in Collapse component
https://github.com/contentful/apps/assets/492573/cdd61090-5c25-4a83-a2b5-ff42672f1d3c

addresses UI feedback from team about show/hide data feature

---

README.md

chore: CircleCI badge in README

---

apps/ecommerce/frontend/src/components/MissingResourceCard.tsx
apps/ecommerce/frontend/src/components/MultipleResources.tsx
apps/ecommerce/frontend/src/components/ResourceCard.tsx
apps/ecommerce/frontend/src/components/SingleResource.tsx
apps/ecommerce/frontend/src/helpers/fakeFetch.ts
apps/ecommerce/frontend/src/types.ts
apps/ecommerce/lambda/src/controllers/apiController.ts
apps/ecommerce/lambda/src/controllers/magentoController.ts
apps/ecommerce/lambda/src/controllers/shopifyController.ts
apps/ecommerce/lambda/src/mocks/combinedResource.mock.ts
apps/ecommerce/lambda/src/mocks/resourceData.mock.ts
apps/ecommerce/lambda/src/mocks/resourceLink.mock.ts
apps/ecommerce/lambda/src/routers/apiRouter.spec.ts
apps/ecommerce/lambda/src/types.ts

refactors to align with ResourceLink specification in [CEP draft](https://contentful.atlassian.net/wiki/spaces/ENG/pages/4221043197/DRAFT+CEP-0163+Extending+ResourceLink+to+reference+external+resources)

refactors to align with CEP for ResourceLink schema spec

---

apps/ecommerce/frontend/README.md
apps/ecommerce/lambda/config/serverless-env.dev.yml.example

This PR updates the `severless-env.dev.yml.example` file with the correct base url and also adds some additional information about the local dev environment setup in the e-commerce app's README.

Fix/Update README and secrets config example

---

packages/ecommerce-app-base/package-lock.json

* We need to make a small change in this package to verify that deploy works correctly for publishing packages
* Just update apps-sdk from 4.13 to 4.17. This should be harmless
* #3479

Upgrade app SDK to 4.17

---

apps/ecommerce/lambda/package-lock.json

Fix bad package-lock.json changes introduced in [this commit](https://github.com/contentful/apps/commit/4983bc3f147b632f7cb1777fdb418c534e0cf4f7#diff-27639113204542122f45a41e6c32a090c6c13c3e7e312132be91fa2140062e5c)

fix package-lock

---

examples/hosted-app-action-templates/typescript/build-action.js
examples/typescript/package-lock.json
examples/typescript/package.json

Introduced a build script to bundle the transpiled code in ESM.
Every action will be bundled  in ESM code for the TypeScript template with the help of build script.

fix: build script for actions in typescript template[EXT-4509]

---

apps/ecommerce/frontend/package.json
apps/ecommerce/frontend/scripts/post-deploy.sh

update `ecommerce-app.ctfapps.net` API gateway proxy URL to latest bundle each time the ecommerce app is successfully deployed

adds post-deploy script to update API Gateway proxy to latest ecommerce bundle

---

apps/ecommerce/frontend/scripts/post-deploy.sh

fix post-deploy script for ecom frontend

swap ANY to GET for ecommerce API Gateway integration

---

apps/ecommerce/frontend/scripts/post-deploy.sh

fix api gateway configuration for ecommerce frontend

update API gateway integration to disclude filepath so it works for relative assets (duh)

---

apps/ecommerce/frontend/scripts/post-deploy.sh

deploy API gateway changes in post-deploy, too

deploy ecommerce API Gateway in post-deploy script

---

examples/hosted-app-action-templates/javascript/contentful-app-manifest.json
examples/hosted-app-action-templates/typescript/contentful-app-manifest.json

Adding allow Networks property in manifest for better DX

fix: allow Networks property added in manifest for DX

---

apps/ecommerce/frontend/src/components/Config/ConfigPage.tsx
apps/ecommerce/frontend/src/helpers/contentfulContext.ts
apps/ecommerce/frontend/src/helpers/signedRequests.ts
apps/ecommerce/frontend/src/hooks/useExternalResource.tsx

adds contentful context headers to all signed requests from the frontend

adds contentful context headers

---

apps/ecommerce/frontend/scripts/post-deploy.sh

fix missed API Gateway deployment activation step in ecommerce frontend post-deploy

---

apps/salesforce-commerce-cloud/src/locations/ConfigScreen.tsx

SFDC CC copy updates

---

apps/salesforce-commerce-cloud/package.json

deploy salesforce-commerce-cloud to production in CI/CD

adds deploy commands for salesforce-commerce-cloud

---

apps/ecommerce/providers/magento/.eslintignore
apps/ecommerce/providers/magento/.eslintrc.js
apps/ecommerce/providers/magento/.gitignore
apps/ecommerce/providers/magento/config/serverless-env.dev.yml.example
apps/ecommerce/providers/magento/config/serverless-env.prd.yml
apps/ecommerce/providers/magento/config/serverless-env.test.yml
apps/ecommerce/providers/magento/nodemon.json
apps/ecommerce/providers/magento/package-lock.json
apps/ecommerce/providers/magento/package.json
apps/ecommerce/providers/magento/serverless.yml
apps/ecommerce/providers/magento/src/app.ts
apps/ecommerce/providers/magento/src/index.ts
apps/ecommerce/providers/magento/tsconfig.json

Barebones Magento provider - purpose is to have it launched offline/locally successfully and can be run in parallel with the integration proxy lambda locally. 
No deployment, no testing - just the barebones to get the service up and running. Deployment, testing, api endpoints will be developed in the next iterative PR.
Make sure Integration Proxy, Provider, and Client can all be run in parallel locally
Test locally in the approach section
None 
None

[Provider] Adds Magento skeleton provider integration

---

apps/wistia-videos/package-lock.json

We have broken Prod/Staging deploys due to package-lock conflicts in the Wistia-app
https://app.circleci.com/pipelines/github/contentful/apps/20640/workflows/a86203ec-611e-4ab8-8e79-903dd68d8bd4/jobs/55320
Update package-lock in Wista app
Merge and hope for the best 
None
None
Deployment will determine if this fix worked or not

[INTEG-655] Update package-lock for Wista app to fix broken Prod/Staging deploys

---

apps/ecommerce/frontend/package-lock.json
apps/ecommerce/frontend/src/components/App/Dialog/DialogBody/DialogBody.spec.tsx
apps/ecommerce/frontend/src/components/App/Dialog/ResourceCard/ResourceCard.spec.tsx
apps/ecommerce/frontend/src/components/App/Dialog/ResourceList/ResourceList.spec.tsx
apps/ecommerce/frontend/src/components/App/Dialog/ResourceSelectionDialog/ResourceSelectionDialog.spec.tsx
apps/ecommerce/frontend/src/components/App/Field/MultipleResources/MultipleResources.spec.tsx
apps/ecommerce/frontend/src/components/App/Field/MultipleResources/MultipleResources.tsx
apps/ecommerce/frontend/src/components/App/Field/SingleResource/SingleResource.tsx
apps/ecommerce/frontend/src/helpers/fakeFetch.ts
apps/ecommerce/frontend/src/types.ts
apps/ecommerce/frontend/test/mocks/common.ts

Fix incorrect urls and update package-lock
Products get displayed

[INTEG-653] Fix outdated env url references in the resource components

---

apps/aws-amplify/package-lock.json
apps/aws-amplify/package.json

Was pointing at the app id in the wrong org. Now we have the correct app id in the correct org
Build should upload
Deploys to this app defn https://app.contentful.com/account/organizations/5EJGHo8tYJcjnEhYWDxivp/apps/definitions/1mVogDvuE0GuW4qp4dk4zQ/general

[NONE] Update app id for aws-amplify

---

apps/commercetools/package-lock.json
apps/commercetools/package.json
apps/commercetools/src/index.tsx
packages/ecommerce-app-base/src/AppConfig/AppConfig.spec.tsx

[Jira Ticket](https://contentful.atlassian.net/browse/MONET-1253)
This PR is a follow-up PR to add `isInOrchestrationEAP` prop to commercetools app so that we can render the EAP note.
Related PR: #3802

add prop [MONET-1253]

---

examples/hosted-app-action-templates/javascript/example.js
examples/hosted-app-action-templates/typescript/example.ts

Example code relied on specific action parameter shape. Lets use a more generic example

fix: cleaner example code []

---

apps/commercetools/package-lock.json
apps/commercetools/package.json
apps/commercetools/src/index.tsx
packages/ecommerce-app-base/src/AppConfig/AppConfig.spec.tsx

This reverts commit 9e5ac567a78b403e742ca77a3947e0b6a93e9ab3.
Because of type conflicts in the version of ecommerce app that #3855 depended on, the master build broke. As a result, the "fix" that we merged in #3874 . 
So we need to revert that earlier PR, publish the change then, revert the revert.

Revert "add prop [MONET-1253] (#3855)"

---

apps/sap-commerce-cloud-with-air/lambda/config/serverless-env.prd.yml
apps/sap-commerce-cloud-with-air/lambda/config/serverless-env.test.yml
apps/sap-commerce-cloud-with-air/lambda/package-lock.json
apps/sap-commerce-cloud-with-air/lambda/serverless.yml
apps/sap-commerce-cloud-with-air/lambda/src/controller/SAPController.ts
apps/sap-commerce-cloud-with-air/lambda/src/middlewares/verifySignedRequests.ts
apps/sap-commerce-cloud-with-air/lambda/src/services/sap/SAPService.ts
apps/sap-commerce-cloud-with-air/lambda/src/types/types.ts
apps/sap-commerce-cloud-with-air/lambda/src/utils/utils.ts
apps/sap-commerce-cloud-with-air/lambda/tsconfig.json

All the sap air api calls are in the frontend which will run into cors issue. This PR takes that frontend API code and moves it to the backend
One way of enforcing security while getting around cors
Tested endpoints via postman
None
None

[INTEG-764] Map over existing API calls to lambda backend

---

apps/sap-commerce-cloud-with-air/frontend/src/api/fetchBaseSites.ts
apps/sap-commerce-cloud-with-air/frontend/src/api/fetchProductList.ts
apps/sap-commerce-cloud-with-air/frontend/src/api/fetchProductPreviews.ts

Getting 404's and can't tell what URL they are hitting so need logging
None as they are just console.logs
None
None
Standrard

Add logging for help debug production sap-air 404 issues with lambda

---

apps/sap-commerce-cloud-with-air/frontend/src/api/fetchBaseSites.ts
apps/sap-commerce-cloud-with-air/frontend/src/api/fetchProductList.ts
apps/sap-commerce-cloud-with-air/frontend/src/api/fetchProductPreviews.ts
apps/sap-commerce-cloud-with-air/frontend/src/api/signed-requests.ts
apps/sap-commerce-cloud-with-air/lambda/src/middlewares/corsConfig.ts
apps/sap-commerce-cloud-with-air/lambda/src/services/sap/SAPService.ts

Update headers SAP air

---

apps/sap-commerce-cloud-with-air/frontend/src/api/fetchProductList.ts
apps/sap-commerce-cloud-with-air/lambda/src/app.ts

Update cors config for SAP AIR

---

apps/json-viewer/package.json

Adds deploy script for the JSON viewer
Check the app ids
https://app.contentful.com/account/organizations/5EJGHo8tYJcjnEhYWDxivp/apps
https://app.contentful.com/account/organizations/6xdLsz6lCsk0yPOccSsDK7/apps
Deploy and smoke test
None
None
Standard

[INTEG-788] Adds deploy scripts for the JSON viewer

---

apps/json-viewer/package.json

Necessary for a successful staging deploy
Standard

[] Adds correct CMA token for Apps dev & testing

---

apps/json-viewer/src/locations/EntryEditor.tsx

Useful feature to have - Great idea by @rusticpenguin 
Smoke test the app
Copy the clip board and beautify it and compare https://jsonformatter.org/
Standard

[] Json viewer copy to clipboard

---

apps/commercetools-without-search/src/api/products.ts

Follow up to https://github.com/contentful/apps/pull/4148, fixing an issue with the pagination in the product picker.

Fix: pagination on product picker

---

apps/slack/frontend/src/components/NotificationsPanel.tsx
apps/slack/frontend/src/requests.ts

Improved frontend slack debugging
None
None
None
Standard

[] Update slack response and errors for better debugging

---

apps/netlify/lambda/handlers/action.js
apps/netlify/lambda/handlers/app-event.js
apps/netlify/lambda/helpers/build-hook.js

Updates some of the error handling and adds some additional info for AWS logging to be able to narrow and better understand errors
Simple changes
Smoke test app
None
None
Standard

[INTEG-908] Netlify fixes for unhandled missing build hook parameters error

---

apps/ai-content-generator/src/utils/aiApi/aiHelpers.ts
apps/ai-content-generator/src/utils/aiApi/index.ts

The stream parser was half getting data it needed, sometime squashing words together.
I changed how we do the parsing by reducing the whole array and splitting on a different condition
Run some Content generation and monitor for lack of spaces, weird cut off words, or apostrophes at the beginning of words
eg. the **dogran** faster than...  || **'s** the way you... ||  And if you wanted to you **cou** try to ...

fixes stream parser

---

apps/ai-content-generator/package.json

This will deploy the merged AICG changes to prod.
Outcome:
Visibly nothing should change on prod, it should remain using V1

chore: add aicg deploy script

---

apps/ai-image-generator/.gitignore
apps/ai-image-generator/README.md
apps/ai-image-generator/index.html
apps/ai-image-generator/package-lock.json
apps/ai-image-generator/package.json
apps/ai-image-generator/src/App.tsx
apps/ai-image-generator/src/components/LocalhostWarning.tsx
apps/ai-image-generator/src/index.tsx
apps/ai-image-generator/src/locations/ConfigScreen.spec.tsx
apps/ai-image-generator/src/locations/ConfigScreen.tsx
apps/ai-image-generator/src/locations/Dialog.spec.tsx
apps/ai-image-generator/src/locations/Dialog.tsx
apps/ai-image-generator/src/locations/EntryEditor.spec.tsx
apps/ai-image-generator/src/locations/EntryEditor.tsx
apps/ai-image-generator/src/locations/Field.spec.tsx
apps/ai-image-generator/src/locations/Field.tsx
apps/ai-image-generator/src/locations/Home.spec.tsx
apps/ai-image-generator/src/locations/Home.tsx
apps/ai-image-generator/src/locations/Page.spec.tsx
apps/ai-image-generator/src/locations/Page.tsx
apps/ai-image-generator/src/locations/Sidebar.spec.tsx
apps/ai-image-generator/src/locations/Sidebar.tsx
apps/ai-image-generator/src/vite-env.d.ts
apps/ai-image-generator/test/mocks/index.ts
apps/ai-image-generator/test/mocks/mockCma.ts
apps/ai-image-generator/test/mocks/mockSdk.ts
apps/ai-image-generator/tsconfig.json
apps/ai-image-generator/vite.config.ts

No business logic or deploy scripts. Just create the app through Vite and make sure the build passes
Just use `npx create-contentful-app` and iterate
None
None
None
No deployment

[INTEG-941] Initialize AI Image Generator package with Vite

---

apps/ai-content-generator/package.json

I disabled prod in AICG for testing out launch darkly. Verified it worked, and now am ready to deploy the changes to prod

chore: deploy ai-cg to prod

---

apps/aws-amplify/build-actions.js

See an error in our logs indicating that we're compiling to a format not supported by our runtime:
```
"body": "{\"errorType\":\"SyntaxError\",\"errorMessage\":\"Unexpected token 'export'\",\"trace\":[\"/var/task/6DA5FCwpCKbzQHpmXpW4eW/actions/amplify.js:1\",\"var c=(a,r,e)=>new Promise((l,i)=>{var p=t=>{try{o(e.next(t))}catch(n){i(n)}},s=t=>{try{o(e.throw(t))}catch(n){i(n)}},o=t=>t.done?l(t.value):Promise.resolve(t.value).then(p,s);o((e=e.apply(a,r)).next())});var A=(a,r)=>c(void 0,null,function*(){let{amplifyWebhookUrl:e}=a;try{yield fetch(e,{method:\\\"POST\\\",headers:{\\\"Content-Type\\\":\\\"application/json\\\"}})}catch(l){}return{message:\\\"Build successfully initiated.\\\"}});export{A as handler};\",\" …
```

Use cjs as build target explicitly

---

apps/ai-image-generator/package.json

Spaces and app definitions have been created - so now it's time to hook the deploy scripts to those app definitions.
Should create a new bundle in those app definitions.
None
None
Standard

[INTEG-946] Adds deploy script to AI Image Generator

---

apps/aws-amplify/contentful-app-manifest.json
apps/aws-amplify/src/locations/Sidebar.tsx

- update app action name to redeploy and make use of new index compound key

[WIP] update app action name

---

apps/ai-content-generator/src/locations/SidebarV1.tsx

We have a lot of unneeded code that are just arbitrarily calling the CMA.
Removed all reference to the CMA
Verify the V1 app still works

removes a lot of unneeded code from aicg v1

---

apps/ai-content-generator/src/components/app/dialog/common-generator/field-selector/SourceAndFieldSelectors.tsx
apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/OutputTextPanels.tsx
apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/original-text-panel/OriginalTextPanel.tsx
apps/ai-content-generator/src/components/common/text-field-with-buttons/TextFieldWIthButtons.tsx
apps/ai-content-generator/src/configs/features/featureConfig.tsx
apps/ai-content-generator/src/configs/features/featureTypes.tsx

This PR updates the copy in the Sidebar and Dialog locations for the AI Content Generator app to match the designs.
The specific copy that needed to be updated includes:
- Button text (Sidebar)
- Placeholder text (Dialog)
- Help text (Dialog)
- Field selection labels (Dialog)
For the feature-specific copy, I added the new copy to the `featureConfig`.
Test each action and change the content source to see that it matches designs.

[INTEG-1035] Update AICG sidebar and dialog copy

---

apps/ai-image-generator/backend/package.json
apps/ai-image-generator/backend/scripts/validate-actions.js

We're compiling our backend to the wrong format (cjs) and we're getting failures when we try the action:
```
exports is not defined\",\"errorType\":\"ReferenceError\"
```
* Change to the correct type ("module")
* Adjust the validate script to use esm modules instead of cjs require
```js
export const handler = async (payload, context) => {
const { prompt } = payload;
try {
console.log(prompt);
}
catch (err) { }
return {
status: 201,
prompt,
images: [
`https://www.americanhumane.org/app/uploads/2021/12/Cat-8-1024x1024.png`,
`https://4kwallpapers.com/images/wallpapers/cat-kitten-pet-domestic-animals-cute-cat-portrait-fur-baby-1024x1024-3528.jpg`,
`https://wallpaperaccess.com/full/2448381.jpg`,
`https://images.infoseemedia.com/wp-content/uploads/2022/02/Black-White-Cat-Image-1024x1024.jpg`, …
```

Fix build target

---

examples/hosted-app-action-templates/javascript/build-actions.js
examples/hosted-delivery-function-templates/javascript/build-delivery-functions.js
examples/hosted-delivery-function-templates/javascript/contentful-app-manifest.json
examples/hosted-delivery-function-templates/javascript/example.js
examples/hosted-delivery-function-templates/javascript/package.json
examples/hosted-delivery-function-templates/typescript/build-delivery-functions.js
examples/hosted-delivery-function-templates/typescript/contentful-app-manifest.json
examples/hosted-delivery-function-templates/typescript/example.ts
examples/hosted-delivery-function-templates/typescript/package.json

Adding example templates for hosted delivery functions

Add templates for hosted delivery functions [MONET-1334]

---

apps/ai-image-generator/.gitignore

[NONE] Update AIIG gitignore to ignore .env files

---

apps/ai-image-generator/backend/src/actions/aiig-generate-image.spec.ts
apps/ai-image-generator/backend/src/actions/aiig-generate-image.ts

We'd like to add minimal error handling so we at least handle errors with a common format.
* Use our Result type and treat any error as `ok: false`
* Change error to plural (assume possible to have multiple errors at some point)

Handle errrors with our action response type

---

apps/graphql-playground/package-lock.json
apps/graphql-playground/package.json
apps/graphql-playground/src/components/ConfigScreen.tsx
apps/graphql-playground/src/components/Dialog.tsx
apps/graphql-playground/src/components/EntryEditor.tsx
apps/graphql-playground/src/components/Field.tsx
apps/graphql-playground/src/components/GqlPlayground.tsx
apps/graphql-playground/src/components/Page.tsx
apps/graphql-playground/src/components/Sidebar.tsx
apps/graphql-playground/src/index.tsx

Also switch to `@contentful/app-sdk`

fix(gql-playground): use Hostnames API

---

packages/ecommerce-app-base/src/ProductCard/ProductCard/ProductCard.tsx

Remove curly braces, were accidentally added.

fix: remove curly braces on description fallback

---

apps/ai-content-generator/src/components/common/text-counter/TextCounter.spec.tsx
apps/ai-content-generator/src/components/common/text-counter/TextCounter.tsx

Updates the character limit validation for AI Content Generator to match new designs. Example:
Specifically, this removes the error message, moves the error icon next to the character count, and makes both the character count and limits red when the count doesn't meet the limit. Updated tests for the component accordingly.
Select an output field with character limits and then generate content that is out of bounds for that limit.

[INTEG-1184]: Update character limit validation warning

---

examples/hosted-delivery-function-templates/javascript/build-delivery-functions.js
examples/hosted-delivery-function-templates/javascript/package.json
examples/hosted-delivery-function-templates/typescript/build-delivery-functions.js
examples/hosted-delivery-function-templates/typescript/package.json

Update node-apps-toolkit to remove type complaints

fix: node-apps-toolkit typescript [MONET-1440]

---

apps/ai-image-generator/package-lock.json

`deploy-prod` is failing on CI due to this error:
`lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M apps/ai-image-generator/package-lock.json
lerna ERR! EUNCOMMIT  M apps/ai-image-generator/package.json`
Updated `pacakge-lock.json` for AIIG.

fix: update AIIG package-lock.json

---

apps/ai-content-generator/src/configs/features/featureConfig.tsx

Fix casing for AICG buttons
Ctrl+F, Ctrl+V
N/A
No
N/A
N/A

[INTEG-1185] - Fix button label case for SEO features

---

apps/typeform/lambda/fetch-workspaces.js
apps/typeform/lambda/workspaces-handler.js

Include details from Typeform API when workspaces error occurs.
* Add a details attribute and include the Typeform error response in it

feat: add error details for workspaces

---

apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/OutputTextPanels.tsx

I deleted the sdk.close() when the user hits apply
I readded the sdk.close() for when the user hits apply

fix: modal not closing

---

apps/ai-content-generator/src/components/config/parameterReducer.ts

AICG config page V2 was not rendering if you had not saved a model in V1.

fix: handling for no model saved on config

---

apps/typeform/lambda/serverless.yml

Forgot to rename the env var in serverless.yaml

fix serverless env var

---

apps/ai-image-generator/frontend/src/components/config/GettingStartedSection/TryImageGeneratorButton.tsx

Everyone missed this button during user testing so we're making it primary so users notice it

aiig try out Ai image generator button on config page is now a primary button

---

apps/aws-amplify/package-lock.json
apps/aws-amplify/package.json
apps/aws-amplify/src/index.tsx

The purpose of this PR is to introduce the component library import into a low-risk (not high profile like the AI apps right now) app, to ensure that the production build works! I will then have a follow-up PR to add more components to the AIIG app to establish an even more foundational POC for this component library. 
I added the LocalHostWarning component from the component library to replace the current version in the AWS Amplify app.
I was able to test that the component rendered locally within the app, the build worked correctly, and the tests ran ✅ 
[
Integration-component-library](https://github.com/contentful/integration-component-library)

Add component from new component library to AWS Amplify

---

apps/ai-image-generator/frontend/src/components/config/CostSection/CostSection.styles.ts
apps/ai-image-generator/frontend/src/components/config/CostSection/CostSection.tsx
apps/ai-image-generator/frontend/src/constants/configPageCopies.ts

[INTEG-1396] adds missing link about dall e credits in aiig config page

---

examples/default-values-backend/README.md
examples/default-values-backend/package-lock.json
examples/default-values-backend/package.json
examples/default-values-backend/src/setup.ts
examples/default-values-backend/yarn.lock

Opening for feedback, ~~DNM until https://github.com/contentful/contentful-management.js/pull/2011 is released~~
Replaces raw http calls in default-values-backend example app with plainclient sdk calls

feat: use contentful-management.js in default-values-backend example [EXT-4786]

---

apps/ai-content-generator/src/components/app/dialog/rewrite-generator/RewriteGenerator.tsx
apps/ai-content-generator/src/configs/segment/segmentEvent.ts

we would like to track what the user puts in the rewrite field
Added it to the segment payload

add rewrite prompt data to segment event

---

apps/microsoft-teams/frontend/.eslintrc.json
apps/microsoft-teams/frontend/.gitignore
apps/microsoft-teams/frontend/.nvmrc
apps/microsoft-teams/frontend/README.md
apps/microsoft-teams/frontend/index.html
apps/microsoft-teams/frontend/package-lock.json
apps/microsoft-teams/frontend/package.json
apps/microsoft-teams/frontend/src/App.tsx
apps/microsoft-teams/frontend/src/components/LocalhostWarning.tsx
apps/microsoft-teams/frontend/src/index.tsx
apps/microsoft-teams/frontend/src/locations/ConfigScreen.spec.tsx
apps/microsoft-teams/frontend/src/locations/ConfigScreen.tsx
apps/microsoft-teams/frontend/src/locations/Dialog.spec.tsx
apps/microsoft-teams/frontend/src/locations/Dialog.tsx
apps/microsoft-teams/frontend/src/locations/EntryEditor.spec.tsx
apps/microsoft-teams/frontend/src/locations/EntryEditor.tsx
apps/microsoft-teams/frontend/src/locations/Field.spec.tsx
apps/microsoft-teams/frontend/src/locations/Field.tsx
apps/microsoft-teams/frontend/src/locations/Home.spec.tsx
apps/microsoft-teams/frontend/src/locations/Home.tsx
apps/microsoft-teams/frontend/src/locations/Page.spec.tsx
apps/microsoft-teams/frontend/src/locations/Page.tsx
apps/microsoft-teams/frontend/src/locations/Sidebar.spec.tsx
apps/microsoft-teams/frontend/src/locations/Sidebar.tsx
apps/microsoft-teams/frontend/src/vite-env.d.ts
apps/microsoft-teams/frontend/test/mocks/index.ts
apps/microsoft-teams/frontend/test/mocks/mockCma.ts
apps/microsoft-teams/frontend/test/mocks/mockSdk.ts
apps/microsoft-teams/frontend/tsconfig.json
apps/microsoft-teams/frontend/vite.config.ts

This PR creates an initial app for Microsoft Teams.
Utilized Create Contentful App using the Vite configuration. Also made some additional updates:
- Update test scripts
- Add linting
- Add support for absolute paths
- Add `.nvmrc`
Ran app locally and was able to verify that the app rendered in our Microsoft Teams development environment. Also ran `test`, `lint`, and `build` scripts.
Deploy scripts will be added in a separate PR.

feat: add initial Microsoft Teams app [INTEG-1468]

---

apps/ai-image-tagging/frontend/package.json
apps/commercetools-without-search/package.json
apps/commercetools/package.json
apps/frontify/package.json
apps/gatsby/package.json
apps/google-analytics/package.json
apps/graphql-playground/package.json
apps/image-focal-point/package.json
apps/mux/package.json
apps/optimizely/package.json
apps/saleor/package.json

Instead of creating a PR for each app build that fails because of the latest Node upgrade, I have tested the builds of all apps locally and updated the necessary scripts in this PR. 🤞 
See this [PR](https://github.com/contentful/apps/pull/5304) and this [PR](https://github.com/contentful/apps/pull/5305) for more context. We fixed Smartling and Typeform with individual PRs, this PR is for the rest of the apps!

fix all app builds

---

apps/jira/jira-app/package.json

Of course the one app, Jira, that I struggled to build locally because I was silly and missed the nested nature of the app, has failed on master because of latest Node upgrade 😵‍💫 This should be the last fix. 
See [this](https://github.com/contentful/apps/pull/5306) PR for more context.

fix jira build

---

apps/microsoft-teams/backend/src/actions/send-test-notification.spec.ts
apps/microsoft-teams/backend/src/actions/send-test-notification.ts
apps/microsoft-teams/build-actions.js
apps/microsoft-teams/contentful-app-manifest.json
apps/microsoft-teams/frontend/package.json
apps/microsoft-teams/frontend/vite.config.ts
apps/microsoft-teams/package-lock.json
apps/microsoft-teams/package.json

Since HAAs need to be deployed in the same artifact as the frontend build, our "true" build needs to be set up a top level which knows how to combine the two.
* Like we did for AIIG, create a separate backend build and frontend build, and munge them together at the end
* Test script combined with sandbox account to allow for local verification of HAA

Create a combined build for backend and frontend

---

apps/ai-content-generator/package.json

Tests won't run for aicg
make them run with the test:ci command

add command to run aicg ci tests

---

apps/microsoft-teams/msteams-bot-service/.env
apps/microsoft-teams/msteams-bot-service/nodemon.json
apps/microsoft-teams/msteams-bot-service/package-lock.json
apps/microsoft-teams/msteams-bot-service/package.json
apps/microsoft-teams/msteams-bot-service/src/app.spec.ts
apps/microsoft-teams/msteams-bot-service/src/app.ts
apps/microsoft-teams/msteams-bot-service/src/config.ts
apps/microsoft-teams/msteams-bot-service/src/index.ts
apps/microsoft-teams/msteams-bot-service/src/services/ms-teams-conversation-service.spec.ts
apps/microsoft-teams/msteams-bot-service/src/services/ms-teams-conversation-service.ts
apps/microsoft-teams/msteams-bot-service/test/mocks.ts
apps/microsoft-teams/msteams-bot-service/tsconfig.json

We need an endpoint to handle incoming messages from the MS Teams framework.
* Create a service to handle the various calls we'll be making to the teamsfx and botbuilder SDKs
* Use `ConversationBot.requestHandler` to handle the actual messages: https://learn.microsoft.com/en-us/javascript/api/@microsoft/teamsfx/conversationbot?view=msteams-client-js-latest#@microsoft-teamsfx-conversationbot-requesthandler This one is not deprecated and also used in a few examples.

Add endpoint to handle incoming activity from MS Teams

---

apps/microsoft-teams/msteams-bot-service/src/app.spec.ts
apps/microsoft-teams/msteams-bot-service/src/app.ts
apps/microsoft-teams/msteams-bot-service/test/mocks.ts

When there's an error in the request handler we need to ensure that it's both logged and handled at the server level.
* Add simple try/catch clause -- move to middleware later
* Capture message activity as mocks (may remove the unused ones later, but useful at this stage)

chore: error handling of incoming message handling

---

packages/ecommerce-app-base/src/AppConfig/AppConfig.spec.tsx
packages/ecommerce-app-base/src/AppConfig/OrchestrationEapNote/OrchestrationEapNote.tsx

This PR changes the EAP copy.
Ticket https://contentful.atlassian.net/browse/MONET-1607

feat: change EAP copy [MONET-1607]

---

apps/ai-content-generator/LICENSE

Missing a license for this app
* Add MIT license, same as other apps

chore: add license for AICG

---

apps/jira/jira-app/src/components/App/Config.tsx
apps/slack/frontend/src/components/ConfigScreen.tsx

I added error logs to diagnose an issue within the Slack and Jira apps while on support. This PR removes those logs. 
Original addition of logs: https://github.com/contentful/apps/pull/5345

Remove extraneous logs

---

.github/dependabot.yml
apps/ai-image-generator/backend/package-lock.json
apps/ai-image-generator/backend/package.json
apps/ai-image-generator/package-lock.json
apps/ai-image-generator/package.json

Dependabot ignored my ignore conditions for the sharp library.
* Remove versons altogether, dependabot ignores sharp entirely.

chore: ignore sharp more forcefully

---

packages/ecommerce-app-base/src/ProductCard/ProductCard/ProductCard.tsx

Capitalizing the more details label to match normal formatting

chore: Capitalize more details []

---

apps/side-notes-app/package-lock.json
apps/side-notes-app/package.json
apps/side-notes-app/src/locations/Dialog.tsx

[This dependabot PR](https://github.com/contentful/apps/pull/5813) was failing when updating `@contentful/field-editor-rich-text` in the sidenotes app. 
We needed to update the `app-sdk` and utilize `DialogAppSDK` to make the build successful.
I confirmed that the Sidenotes app is still working as expected.

fix(deps): bump @contentful/field-editor-rich-text and @contentful/app-sdk

---

apps/sap-commerce-cloud/src/components/Dialog.tsx

Bugs were pointed out in #5599. This ticket is to address them
This had to do with pagination and total page size

fix bugs in sap-commerce cloud dialog

---

apps/commercetools-without-search/src/config.ts
apps/commercetools/src/config.ts

https://contentful.atlassian.net/browse/MONET-1737
`apiEndpoint` needs be to changed not `authApiEndpoint`. 🤦

fix: use apiEndpoint instead of authApiEndpoint [MONET-1737]

---

apps/microsoft-teams/app-actions/src/actions/handle-app-event.spec.ts
apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
apps/microsoft-teams/app-actions/src/constants.ts
apps/microsoft-teams/app-actions/src/helpers/entry-activity.spec.ts
apps/microsoft-teams/app-actions/src/helpers/entry-activity.ts
apps/microsoft-teams/app-actions/src/helpers/event-activity.ts
apps/microsoft-teams/app-actions/src/helpers/index.ts
apps/microsoft-teams/app-actions/src/types.ts
apps/microsoft-teams/app-actions/test/mocks.ts
apps/microsoft-teams/contentful-app-manifest.json

When an app event is triggered by an content management entry action, we need to possibly send a message to an MS teams channel with the details.
We will have a service that accepts incoming events from the App Event subscription, and this service will in turn call an app action which will be responsible for reading the notifications from the app config, checking if there are any "matching" notifications, then sending the message details to the API endpoint for the matching channels.
This PR introduces the HAA, build the entry activity object, and returns the result. It's sort of a work in progress.
Subsequent PRs will call the API as well as check the notification object.
* introduce handleAppEvent handler
* add a helper to take the basic event data we'll receive and transform it into …

feat: HAA for sending notification

---

apps/microsoft-teams/frontend/src/hooks/useGetTeamsChannels.ts

fix: remove text mode on get channels hook

---

apps/microsoft-teams/app-actions/src/helpers/entry-activity.spec.ts
apps/microsoft-teams/app-actions/src/helpers/entry-activity.ts
apps/microsoft-teams/app-actions/src/types.ts

Since we can't get users from an app, we don't need the code that tries!

chore: clean up user stuff

---

apps/side-notes-app/package-lock.json
apps/side-notes-app/package.json
apps/side-notes-app/src/locations/config/ContentTypeListContext.tsx

Side Notes App 🎶 is stuck on an earlier version of swr do to some type changes.
Problem identified here https://github.com/vercel/swr/issues/2826
* Add a third empty argument to match a different overload. See https://github.com/vercel/swr/issues/2826#issuecomment-1804077705

chore: upgrade swr to 2.2.3

---

apps/ai-content-generator/package-lock.json
apps/ai-content-generator/package.json
apps/bedrock-content-generator/package-lock.json
apps/bedrock-content-generator/package.json

* Upgrade to latest CMA to latest for AICG and BCG
* Resolve security dependabot upgrade https://github.com/contentful/apps/pull/6156

chore: upgrade cma to latest

---

apps/jira/functions/lib/oauth.spec.ts
apps/jira/functions/package-lock.json
apps/jira/functions/package.json

* Lodash type errors preventing dependabot upgrade https://github.com/contentful/apps/pull/5519
* Need to upgrade to latest TS to prevent unsupported types. See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/63022

chore: upgrade lodash and typescript for Jira

---

apps/microsoft-teams/app-actions/package-lock.json
apps/microsoft-teams/app-actions/package.json

* Upgrade manually because of blocked dependabot PR https://github.com/contentful/apps/pull/6164

chore: upgrade botbuilder

---

apps/brandfolder/package-lock.json

* The wrong package-lock somehow got included in the previous fix (https://app.circleci.com/pipelines/github/contentful/apps/27598/workflows/3cd626c4-3ea2-4ca9-a500-1600f1e2c4e6/jobs/87321)
* Re-run npm i

fix: replace incorrect package.json

---

apps/bedrock-content-generator/package-lock.json
apps/bedrock-content-generator/package.json

chore: upgrade f36 for bedrock content generator

---

apps/ai-image-generator/frontend/package-lock.json
apps/ai-image-generator/frontend/package.json

chore: upgrade f36 for aiig frontend

---

apps/ai-content-generator/package-lock.json
apps/ai-content-generator/package.json

chore: upgrade f36 for aicg

---

apps/vercel/package-lock.json
apps/vercel/package.json

chore: upgrade f36 for vercel

---

apps/side-notes-app/package-lock.json
apps/side-notes-app/package.json

chore: upgrade f36 for Side Notes App 🎶

---

apps/sap-commerce-cloud-with-air/frontend/package-lock.json
apps/sap-commerce-cloud-with-air/frontend/package.json

chore: upgrade f36 for sap commerce cloud with air

---

apps/salesforce-commerce-cloud/package-lock.json
apps/salesforce-commerce-cloud/package.json

chore: upgrade f36 for salesforce commercecloud

---

apps/json-viewer/package-lock.json
apps/json-viewer/package.json

chore: upgrade f36 for json viewer

---

apps/google-analytics-4/frontend/package-lock.json
apps/google-analytics-4/frontend/package.json

chore: upgrade f36 for ga4

---

apps/microsoft-teams/frontend/package-lock.json
apps/microsoft-teams/frontend/package.json

chore: upgrade f36 for ms teams

---

apps/color-picker/package-lock.json
apps/color-picker/package.json

chore: upgrade f36 for color picker

---

apps/aws-amplify/package-lock.json
apps/aws-amplify/package.json

chore: upgrade f36 for aws-amplify

---

examples/function-templates/javascript/INSTRUCTIONS.md
examples/function-templates/typescript/INSTRUCTIONS.md

[Ticket](https://contentful.atlassian.net/browse/MONET-1733)
This PR updates the documentation to make the templates a little easier to use.

docs: document  commands to improve the docs [MONET-1733]

---

apps/ai-content-generator/src/utils/aiApi/aiHelpers.ts

There's a bug in AICG where a customer is reporting a parse error in the console.
This is reproducible. The error is
```
useAI.tsx?t=1707179108609:72 SyntaxError: Unexpected token 'd', "data: {"id"... is not valid JSON
at JSON.parse (<anonymous>)
at streamToParsedText (aiHelpers.ts?t=1707178867600:21:27)
at Array.reduce (<anonymous>)
at AI.parseStream (index.ts?t=1707178867600:57:28)
at async generateMessage (useAI.tsx?t=1707179108609:64:30)
at async handleGenerate (CommonGenerator.tsx?t=1707179108609:83:7)
```
The problem seems to trace back to the `streamToParsedText` function, which takes the raw string from the stream, parses it as JSON, and pulls out the content from the parsed line.
The stream lines are actually coming back in two forms:
Without an initial "line break":
```
data: …
```

fix: handle linebreaks in stream parser correctly

---

apps/bedrock-content-generator/src/components/config/access-key/AccessKey.tsx
apps/bedrock-content-generator/src/components/config/configText.ts
apps/bedrock-content-generator/src/components/config/model/Model.tsx
apps/bedrock-content-generator/src/components/config/model/model.module.css
apps/bedrock-content-generator/src/components/config/parameterReducer.ts
apps/bedrock-content-generator/src/configs/aws/featuredModels.ts

- Fixed model selection when available models are restricted 
- Added ability to change settings without re-entering credentials

[bedrock-content-generator] Fix model selection on restricted availability and after installation

---

examples/function-mock-shop/build-functions.js
examples/function-mock-shop/contentful-app-manifest.json
examples/function-potterdb-rest-api/build-functions.js
examples/function-potterdb-rest-api/contentful-app-manifest.json
examples/function-potterdb/build-functions.js
examples/function-potterdb/contentful-app-manifest.json
examples/function-templates/javascript/build-functions.js
examples/function-templates/javascript/contentful-app-manifest.json
examples/function-templates/typescript/build-functions.js

[Ticket](https://contentful.atlassian.net/browse/MONET-1826)
This PR adds accepts parameter to examples and to function templates.

feat: add accepts parameter to examples [MONET-1826]

---

examples/function-templates/typescript/contentful-app-manifest.json

[TICKET](https://contentful.atlassian.net/browse/MONET-1826)
I missed one adding accepts parameter to of the examples.

chore: add missing prop [MONET-1826]

---

.github/dependabot.yml
examples/function-mock-shop/package-lock.json
examples/function-mock-shop/package.json
examples/function-potterdb-rest-api/package-lock.json
examples/function-potterdb-rest-api/package.json
examples/function-potterdb/package-lock.json
examples/function-potterdb/package.json

Functions weren't being being shown on `user_interface`. This PR 
- updates the packages 
- adds dependabot so that we prevent this bug happening again in the future.

fix: example package versions and add dependabot [MONET-1825]

---

.contentful/vault-secrets.yaml

Add Vault policy to CircleCI config so that it can read packages from GitHub. This is PR 1 of 2 for migrating to GitHub packages.
Followed directions in migration instructions.

chore: update vault config to read GH packages [INTEG-1809]

---

.circleci/config.yml
package.json

Revert "chore: migrate app-base package publishing to GitHub [INTEG-1809]"

---

apps/vercel/src/clients/Vercel.spec.ts
apps/vercel/src/clients/Vercel.ts
apps/vercel/src/components/config-screen/ConfigScreen.styles.tsx
apps/vercel/src/components/config-screen/ContentTypeSelect.tsx
apps/vercel/src/components/config-screen/ProjectSelect.tsx
apps/vercel/src/constants/defaultParams.ts
apps/vercel/src/locations/ConfigScreen.tsx

chore: [] - fix vercel client

---

examples/function-appevent-filter/javascript/INSTRUCTIONS.md
examples/function-appevent-filter/javascript/build-functions.js
examples/function-appevent-filter/javascript/contentful-app-manifest.json
examples/function-appevent-filter/javascript/example.js
examples/function-appevent-filter/javascript/package.json
examples/function-appevent-filter/typescript/INSTRUCTIONS.md
examples/function-appevent-filter/typescript/build-functions.js
examples/function-appevent-filter/typescript/contentful-app-manifest.json
examples/function-appevent-filter/typescript/example.ts
examples/function-appevent-filter/typescript/package-lock.json
examples/function-appevent-filter/typescript/package.json
examples/function-appevent-filter/typescript/tsconfig.json

feat: adds js + ts examples for appevent.filter function [EXT-5023]

---

examples/function-mock-shop/README.md

This PR fixes the cli command.

fix: command []

---

apps/microsoft-teams/frontend/package-lock.json
apps/microsoft-teams/frontend/package.json
apps/microsoft-teams/frontend/src/components/config/AccessSection/AccessSection.tsx
apps/microsoft-teams/frontend/src/index.tsx

We would like to track events in the MS Teams app
Note: This is dependent on a PR in the frontend toolkit. This will fail until that PR gets merged in.

feat: implement segment into ms teams

---

apps/slack/README.md
apps/slack/frontend/README.md

The purpose of this PR is to update the README within Slack to more succinctly communicate steps to running it locally. This is follow-up work from the audit of the Slack app.

docs: update Slack README

---

apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
apps/microsoft-teams/app-actions/src/types.ts

Update the `msteamsHandleAppEvent` app action to reflect the changes in the `workflow-consumer-service` that calls this action.
Update types to match payload in consumer.

fix: update workflow message app action to match workflow consumer [INTEG-1943]

---

apps/vercel/app-actions/src/actions/get-preview-envs.spec.ts
apps/vercel/app-actions/src/actions/get-preview-envs.ts
apps/vercel/app-actions/src/helpers/build-preview-urls-for-content-types.spec.ts
apps/vercel/app-actions/src/helpers/build-preview-urls-for-content-types.ts
apps/vercel/app-actions/src/helpers/construct-vercel-preview-url-parts.spec.ts
apps/vercel/app-actions/src/helpers/construct-vercel-preview-url-parts.ts
apps/vercel/app-actions/src/helpers/fetch-app-installation-parameters.spec.ts
apps/vercel/app-actions/src/helpers/fetch-app-installation-parameters.ts
apps/vercel/app-actions/src/services/vercel-service.spec.ts
apps/vercel/app-actions/src/services/vercel-service.ts
apps/vercel/app-actions/src/types.ts
apps/vercel/app-actions/test/mocks.ts
apps/vercel/package-lock.json
apps/vercel/package.json

Our hosted app action should build real URLs by fetching appropriate data from the Vercel API and saved app installation parameters.
This PR implements the "construction" parts of the action. A later PR will fetch the data from the Vercel API.
```
$ npm run call-app-action -- -a vercelGetPreviewEnvironments -s q5wv5ajna1af
> @contentful/vercel-app@1.0.0 call-app-action
> npx ts-node scripts/call-app-action.ts -a vercelGetPreviewEnvironments -s q5wv5ajna1af
APP ACTION RESULT
{
sys: {
id: '23yWjVk6iWcM3lYmemzCVj',
type: 'AppActionCallDetails',
space: { sys: { type: 'Link', linkType: 'Space', id: 'q5wv5ajna1af' } },
sys: { type: 'Link', linkType: 'Environment', id: 'master' },
createdBy: {
sys: {
type: 'Link',
linkType: 'AppAction',
id: 'vercelGetPreviewEnvironments'
}
},
createdAt: …
```

feature: build URLs from vercel data

---

apps/vercel/app-actions/src/services/vercel-service.spec.ts
apps/vercel/app-actions/src/services/vercel-service.ts

Previously we were specifying the wrong method in our fetch call to Vercel (`POST` instead of `GET`)
* Fix the method and update the test
Example app action call:
```
npm run call-app-action -- -a vercelGetPreviewEnvironments -s q5wv5ajna1af
> @contentful/vercel-app@1.0.0 call-app-action
> npx ts-node scripts/call-app-action.ts -a vercelGetPreviewEnvironments -s q5wv5ajna1af
APP ACTION RESULT
{
sys: {
id: '6mPEME3B1d2PbjfeWSZiep',
type: 'AppActionCallDetails',
space: { sys: { type: 'Link', linkType: 'Space', id: 'q5wv5ajna1af' } },
sys: { type: 'Link', linkType: 'Environment', id: 'master' },
createdBy: {
sys: {
type: 'Link',
linkType: 'AppAction',
id: 'vercelGetPreviewEnvironments'
}
},
createdAt: '2024-04-01T20:27:02.948Z'
},
request: { function: 'actions/get-preview-envs.js', …
```

fix: adjust api call method

---

apps/microsoft-teams/app-actions/src/actions/handle-app-event.ts
apps/microsoft-teams/app-actions/src/types.ts

We would like to show cards in the adaptive card. This is followup to our Workflows  changes

feat: add color fields to workflows payload

---

examples/function-appevent-handler/javascript/INSTRUCTIONS.md
examples/function-appevent-handler/javascript/build-functions.js
examples/function-appevent-handler/javascript/contentful-app-manifest.json
examples/function-appevent-handler/javascript/example.js
examples/function-appevent-handler/javascript/package-lock.json
examples/function-appevent-handler/javascript/package.json
examples/function-appevent-handler/typescript/INSTRUCTIONS.md
examples/function-appevent-handler/typescript/build-functions.js
examples/function-appevent-handler/typescript/contentful-app-manifest.json
examples/function-appevent-handler/typescript/example.ts
examples/function-appevent-handler/typescript/package-lock.json
examples/function-appevent-handler/typescript/package.json
examples/function-appevent-handler/typescript/tsconfig.json
examples/function-appevent-transformation/javascript/INSTRUCTIONS.md
examples/function-appevent-transformation/javascript/build-functions.js
examples/function-appevent-transformation/javascript/contentful-app-manifest.json
examples/function-appevent-transformation/javascript/example.js
examples/function-appevent-transformation/javascript/package.json
examples/function-appevent-transformation/typescript/INSTRUCTIONS.md
examples/function-appevent-transformation/typescript/build-functions.js
examples/function-appevent-transformation/typescript/contentful-app-manifest.json
examples/function-appevent-transformation/typescript/example.ts
examples/function-appevent-transformation/typescript/package-lock.json
examples/function-appevent-transformation/typescript/package.json
examples/function-appevent-transformation/typescript/tsconfig.json

- Example ts/js projects for app event handlers and transformations

Feat: App event transformation and handler examples [EXT-5133] [EXT-5139] 

---

.circleci/config.yml

small corrections from https://github.com/contentful/apps/pull/7285

fix: typos in build pipeline

---

examples/function-templates/javascript/INSTRUCTIONS.md
examples/function-templates/typescript/INSTRUCTIONS.md

Ticket: https://contentful.atlassian.net/browse/MONET-1986

fix: add external-references to cli readme [MONET-1986]

---

.github/dependabot.yml
examples/function-templates/typescript/package-lock.json
examples/function-templates/typescript/package.json

This PR updates the `node-apps-toolkit` version for function templates.

chore: update version []

---

apps/commercetools/package-lock.json
apps/commercetools/package.json
apps/commercetools/src/api/categories.ts
apps/commercetools/src/dialog.ts

This reverts commit 6bb127b6b788ad70682a2c9170ea6bf864a7ca12.
Reverting this commit to investigate an issue with the `ecommerce-app-base` and commercetools app introduced by this PR: https://github.com/contentful/apps/pull/7357/files

Revert "feat: add exact match search to category picker [INTEG-2018] (#7357)"

---

apps/microsoft-teams/README.md
apps/microsoft-teams/frontend/src/components/config/DisconnectModal/DisconnectModal.spec.tsx
apps/microsoft-teams/frontend/src/components/config/DisconnectModal/DisconnectModal.tsx
apps/microsoft-teams/frontend/src/constants/configCopy.ts

Updating README instructions for testing app actions and fixing a typo in the MS Teams app.

chore: update README and fix typo in ms teams app []

---

apps/commercetools/package-lock.json
apps/commercetools/package.json

This reverts commit f09d99eafbe0cd740cda6c87f54ee0ed21f7862f.

Revert "chore: bump ecommerce-base-app in commercetools (#7403)" []

---

apps/commercetools/package-lock.json
apps/commercetools/package.json

Trying a version that is not the most current version.

chore: bump ecom version to 3.5.43 []

---

.github/CODEOWNERS

[] add monet as COs to their examples

---

examples/function-potterdb/package-lock.json
examples/function-potterdb/package.json
examples/function-potterdb/src/components/CharacterBox.tsx
examples/function-potterdb/src/components/CharacterDetails.tsx
examples/function-potterdb/src/components/CharactersList.tsx
examples/function-potterdb/src/hooks/useCharacter.ts
examples/function-potterdb/src/hooks/useCharacters.ts
examples/function-potterdb/src/index.tsx
examples/function-potterdb/src/locations/Dialog.tsx
examples/function-potterdb/src/locations/Field.tsx
examples/function-potterdb/src/types.ts
examples/function-potterdb/tsconfig.json

Make the app framework part of the example (UI) better

feat: improve UI experience potter GQL [MONET-2052]

---

examples/function-potterdb/src/App.tsx

- Add Dialog to locations so it can be rendered by the app framework

fit: add missing Dialog location [NONE]

---

examples/function-potterdb-rest-api/src/hooks/useCharacters.ts
examples/function-potterdb-rest-api/src/locations/Dialog.tsx

You can search your favourite character now! 🪄 🎉

feat: add a search input for Potter characters []

---

apps/slack/frontend/src/useConnect.ts

Currently, the slack workflow on the configuration page requires a user to save the installation after authenticating with the Slack workspace in order to successfully render the listed channels. If the user does not save the configuration page before trying to configure a notification, the channels modal shows a warning that channels cannot be listed. 
When fetching channels, the app first needs to fetch the auth token from the auth token repository. We were receiving an error "Auth token not found" when trying to get channels as we were hitting [this line](https://github.com/contentful/apps/blob/master/apps/slack/lambda/lib/routes/auth-token/repository.ts#L100). In this get method, we are getting the installation parameters (including the installationUuid) from the CMA. I was able to …

fix: set installationUuid parameter on initial install [INTEG-1768]

---

apps/typeform/frontend/package-lock.json
apps/typeform/frontend/package.json
apps/typeform/frontend/src/utils.ts

#7417 has a build error caused by use of "any" in types
* Fix type
* Upgrade to react script 5

chore: fix types in field id list

---

examples/function-potterdb/src/hooks/useCharacters.ts
examples/function-potterdb/src/locations/Dialog.tsx

Adds search bar same as our [Rest example ](https://github.com/contentful/apps/pull/7632)

feat: add characters search bar to potter gql []

---

apps/ai-image-tagging/lambda/serverless.yml
apps/jira/functions/serverless.yml
apps/netlify/lambda/serverless.yml
apps/slack/lambda/serverless.yml
apps/smartling/lambda/serverless.yml
apps/typeform/lambda/serverless.yml

Merging into staging to test the upgrade

chore: update lambdas to nodev18

---

apps/ai-image-tagging/lambda/serverless.yml

chore: bump lambda runtime to node to v18

---

apps/ai-image-tagging/lambda/serverless.yml

This reverts commit 82e981787a6f9f38c80ea53cc36b20989821a62b.

Revert "chore(ai-image-tagging): bump lambda runtime to node to v18 [INTEG-1959] (#7769)"

---

apps/vercel/README.md
apps/vercel/app-actions/README.md

- Adds lite READMES for projects around the Vercel integration

chore: [INTEG-1732] - Update Vercel README(s)

---

apps/ai-content-generator/package-lock.json
apps/aws-amplify/package-lock.json
apps/brandfolder/package-lock.json
apps/color-picker/package-lock.json
apps/commercetools-without-search/package-lock.json
apps/commercetools/package-lock.json
apps/dropbox/package-lock.json
apps/frontify/package-lock.json
apps/gatsby/package-lock.json
apps/google-analytics/package-lock.json
apps/graphql-playground/package-lock.json
apps/image-focal-point/package-lock.json
apps/json-viewer/package-lock.json
apps/optimizely/package-lock.json
apps/saleor/package-lock.json
apps/salesforce-commerce-cloud/package-lock.json
apps/sap-commerce-cloud/package-lock.json
apps/wistia-videos/package-lock.json
package-lock.json

To resolve security vulnerabilities

upgrading braces and ip

---

apps/sap-commerce-cloud/package-lock.json
apps/sap-commerce-cloud/package.json
apps/sap-commerce-cloud/src/AppConfig/AppConfig.styles.ts
apps/sap-commerce-cloud/src/AppConfig/AppConfig.tsx
apps/sap-commerce-cloud/src/AppConfig/FieldSelector.styles.ts
apps/sap-commerce-cloud/src/AppConfig/FieldSelector.tsx
apps/sap-commerce-cloud/src/components/Dialog/Dialog.styles.ts
apps/sap-commerce-cloud/src/components/Dialog/Dialog.tsx
apps/sap-commerce-cloud/src/components/Field/Field.styles.ts
apps/sap-commerce-cloud/src/components/Field/Field.tsx
apps/sap-commerce-cloud/src/components/ProductPreviews/SortableListItem.styles.ts
apps/sap-commerce-cloud/src/components/ProductPreviews/SortableListItem.tsx
apps/sap-commerce-cloud/src/index.tsx

Consistent CSS for better app maintainability
Followed conventions of more modern apps where we have CSS files using emotion that export a style object for display components to import. 
Everything should look as it did before, testing that no CSS looks broken.

feat: standardize css in SAP app

---

apps/sap-commerce-cloud/package-lock.json
apps/sap-commerce-cloud/package.json
apps/sap-commerce-cloud/src/index.tsx

Feat: upgrade to react 18

---

apps/sap-commerce-cloud/src/components/Dialog/ProductList.tsx

refactor: switch ProductList from class to function [EXT-5599]

---

apps/graphql-playground-v2/LICENSE
apps/graphql-playground-v2/package.json

add deployment script so graphiQL can be published [to its prod location](https://app.contentful.com/account/organizations/5EJGHo8tYJcjnEhYWDxivp/apps/definitions/6o8NJOeW54fY2UYY8zQUZY/general)
https://app.contentful.com/spaces/lpjm8d10rkpy/environments/master/apps/app_installations/6o8NJOeW54fY2UYY8zQUZY/

[EXT-5608] deploy graphiql to prod

---

apps/sap-commerce-cloud/src/AppConfig/FieldSelector.tsx

Convert FieldSelector component to function component.
Check that the field selector in config is still working as expected

feat: convert FieldSelector to function component [EXT-5599]

---

apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.tsx

Feat: convert dialog component from class to function [EXT-5599]

---

apps/sap-commerce-cloud/frontend/package-lock.json
apps/sap-commerce-cloud/frontend/package.json
apps/sap-commerce-cloud/frontend/src/AppConfig/FieldSelector.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.tsx
apps/sap-commerce-cloud/frontend/src/components/Field/Field.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Field/Field.tsx
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableComponent.tsx

Removing console.logs, fixing typos, and making the linter happy.
Also fixed some issues in the `Field` and `Dialog` components that were causing tests to fail

fix: sap small fixes []

---

apps/typeform/frontend/.npmrc
apps/typeform/frontend/package-lock.json
apps/typeform/frontend/package.json
apps/typeform/frontend/src/TypeFormWidget.tsx
apps/typeform/frontend/src/module.d.ts

Fixes the broken preview functionality
https://github.com/user-attachments/assets/b9a87093-3b8a-496d-b0f5-4b696e675b3a

fix: (Typeform) use updated preview embed component

---

apps/sap-commerce-cloud/frontend/src/AppConfig/AppConfig.spec.tsx
apps/sap-commerce-cloud/frontend/src/AppConfig/AppConfig.tsx
apps/sap-commerce-cloud/frontend/src/__mocks__/mockCma.ts
apps/sap-commerce-cloud/frontend/src/components/Dialog/ProductList.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/ProductList.tsx
apps/sap-commerce-cloud/frontend/src/interfaces.ts

Package for app-sdk has already been updated to the latest.
This PR updates deprecated sdk methods/types.

feat: updates deprecated contentful app-sdk methods

---

apps/sap-commerce-cloud/frontend/src/AppConfig/AppConfig.tsx
apps/sap-commerce-cloud/frontend/src/AppConfig/FieldSelector.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/ProductList.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/ProductList.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/__snapshots__/Dialog.spec.tsx.snap
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableListItem.tsx

Auditing and adding any accessibility improvements.
In practice this was just adding/making more useful some aria labels. Most of the finer accessibility things are handled by the component library that we are using in the app. 
I also did manual testing throughout to verify that I could navigate the pages via keyboard.

feat: accessibility improvements for sap app [EXT-5645]

---

apps/sap-commerce-cloud/app-actions/src/actions/fetchProductPreview.spec.ts
apps/sap-commerce-cloud/app-actions/src/actions/fetchProductPreview.ts
apps/sap-commerce-cloud/app-actions/src/constants.ts
apps/sap-commerce-cloud/app-actions/src/services/sapService.ts
apps/sap-commerce-cloud/app-actions/src/types.ts
apps/sap-commerce-cloud/app-actions/test/mocks.ts
apps/sap-commerce-cloud/contentful-app-manifest.json
apps/sap-commerce-cloud/frontend/src/api/dataTransformers.ts

This updates the product previews HAA

feat: product previews

---

apps/sap-commerce-cloud/app-actions/src/actions/fetchProductList.spec.ts
apps/sap-commerce-cloud/app-actions/src/actions/fetchProductList.ts
apps/sap-commerce-cloud/app-actions/src/services/sapService.ts
apps/sap-commerce-cloud/app-actions/src/types.ts
apps/sap-commerce-cloud/app-actions/test/mocks.ts
apps/sap-commerce-cloud/contentful-app-manifest.json

fetch product list [ext-5616]

---

apps/sap-commerce-cloud/frontend/.eslint.json

Accessibility improvement - add a11y linting to enforce good accessibility practices going forward.

feat: adds es-lint a11y extension with suggested rules [EXT-5645]

---

apps/sap-commerce-cloud/README.md
apps/sap-commerce-cloud/app-actions/README.md
apps/sap-commerce-cloud/frontend/README.md

Conforming to the app audit checklist, we need a readme in each module. We had most of our instructions in the frontend folder README, some of these were updated. I also started to outline the README at the root folder and within app actions.

feat: README files in all modules for SAP app

---

apps/sap-commerce-cloud/frontend/src/__mocks__/mockProductPreview.ts
apps/sap-commerce-cloud/frontend/src/components/AppConfig/AppConfig.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/AppConfig/AppConfig.tsx
apps/sap-commerce-cloud/frontend/src/components/AppConfig/FieldSelector.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/AppConfig/FieldSelector.tsx
apps/sap-commerce-cloud/frontend/src/components/AppConfig/fields.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/AppConfig/parameters.spec.ts
apps/sap-commerce-cloud/frontend/src/components/AppConfig/parameters.ts
apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/ProductList.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/ProductList.tsx
apps/sap-commerce-cloud/frontend/src/components/Field/Field.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Field/Field.tsx
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableComponent.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableComponent.tsx
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableList.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableList.tsx
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableListItem.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableListItem.styles.ts
apps/sap-commerce-cloud/frontend/src/components/ProductPreviews/SortableListItem.tsx
apps/sap-commerce-cloud/frontend/src/hooks/useAPI.ts
apps/sap-commerce-cloud/frontend/src/index.spec.tsx
apps/sap-commerce-cloud/frontend/src/index.tsx
apps/sap-commerce-cloud/frontend/src/interfaces.ts
apps/sap-commerce-cloud/frontend/src/utils.ts
apps/sap-commerce-cloud/frontend/tsconfig.json
apps/sap-commerce-cloud/frontend/vite.config.ts

Writing the function components in a uniform way
Declaring/destructuring props in all function components consistently
Updating relative import paths to use new path definitions defined in ts/vite configs

feat: uniform function component and props definitions and update relative paths [EXT-5652]

---

apps/sap-commerce-cloud/frontend/package-lock.json
apps/sap-commerce-cloud/frontend/package.json
apps/sap-commerce-cloud/frontend/src/components/AppConfig/AppConfig.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/AppConfig/AppConfig.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Dialog/Dialog.tsx
apps/sap-commerce-cloud/frontend/src/components/Field/Field.spec.tsx
apps/sap-commerce-cloud/frontend/src/components/Field/Field.tsx
apps/sap-commerce-cloud/frontend/src/index.spec.tsx
apps/sap-commerce-cloud/frontend/src/index.tsx

- Use the more modern SDK Provider rather than passing the SDK as a prop https://www.contentful.com/developers/docs/extensibility/app-framework/react-apps-toolkit/ 
- fixing tests
https://contentful.atlassian.net/browse/EXT-5646

chore: use sdk provider

---

examples/native-external-references/README.md

Update README for Native External References - renaming

feat: update NER readme []

---

apps/ai-content-generator/src/configs/prompts/seoDescriptionPrompt.ts
apps/ai-content-generator/src/prompts.ts

Setting max to be 160 for SEO reasons
[EXT-5698]: https://contentful.atlassian.net/browse/EXT-5698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: changing max to be 160 [EXT-5698]

---

examples/function-appaction/package.json
examples/function-appevent-filter/javascript/package.json
examples/function-appevent-filter/typescript/package.json
examples/function-appevent-handler/javascript/package.json
examples/function-appevent-handler/typescript/package.json
examples/function-appevent-transformation/javascript/package.json
examples/function-appevent-transformation/typescript/package.json
examples/function-comment-bot/javascript/package.json
examples/function-comment-bot/typescript/package.json
examples/function-mock-shop/package.json
examples/function-potterdb-rest-api/package.json
examples/function-potterdb/package.json
examples/function-templates/javascript/package.json
examples/function-templates/typescript/package.json

fix: wrong import version []

---

apps/ai-content-generator/src/configs/prompts/seoDescriptionPrompt.ts
apps/ai-content-generator/src/prompts.ts

[EXT-5698](https://contentful.atlassian.net/browse/EXT-5698)
[EXT-5698]: https://contentful.atlassian.net/browse/EXT-5698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Setting seo limit to 150

---

apps/ai-content-generator/src/configs/prompts/seoDescriptionPrompt.ts
apps/ai-content-generator/src/prompts.ts

[EXT-5698](https://contentful.atlassian.net/browse/EXT-5698)
[EXT-5698]: https://contentful.atlassian.net/browse/EXT-5698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Setting seo limit to 100

---

packages/eslint-plugin-contentful-apps/package.json

Fixes the build script in `/packages/eslint-plugin-contentful-apps`

fix: eslint-plugin-contentful-apps build script

---

packages/eslint-plugin-contentful-apps/package.json

Fixes the exports configuration for eslint-plugin-contentful-apps

fix: eslint-plugin-contentful-apps build exports

---

packages/eslint-plugin-contentful-apps/package.json

fix: (eslint-plugin-contentful-apps) add repository config []

---

.circleci/config.yml
.npmrc
packages/eslint-plugin-contentful-apps/package.json

- remove package registry config in root-level npmrc

fix: (publish) remove registry config in repo npmrc

---

apps/vercel/frontend/package-lock.json
apps/vercel/frontend/package.json
apps/vercel/frontend/src/components/common/GrayInfoBox/GrayInfoBox.styles.ts
apps/vercel/frontend/src/components/common/SectionWrapper/SectionWrapper.styles.ts
apps/vercel/frontend/src/components/config-screen/AuthenticationSection/AuthenticationSection.styles.ts
apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/ContentTypePreviewPathSelectionRow/ContentTypePreviewPathSelectionRow.styles.ts
apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalModal.styles.ts
apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InfoTable/InfoTable.styles.ts
apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/InformationalModal/InformationalTables/InformationalTables.styles.ts
apps/vercel/frontend/src/components/config-screen/ContentTypePreviewPathSection/PreviewPathInfoNote/PreviewPathInfoNote.styles.ts
apps/vercel/frontend/src/locations/ConfigScreen.styles.tsx

Updates emotion for the Vercel app. This one is a more modern app already using Vite and already using modern F36 libraries.

Chore: update emotion css for vercel app [EXT-5807]

---

apps/ai-content-generator/package-lock.json
apps/ai-content-generator/package.json
apps/ai-content-generator/test/mocks/sdk/mockSdk.ts

Cleans up an unused package no longer used.

fix: AI Content Generator - cleanup unused packages 

---

apps/mux/frontend/package-lock.json
apps/mux/frontend/package.json
apps/mux/package-lock.json
apps/mux/package.json

chore: update mux app to remediate vuls INTEG-2263

---

apps/wistia-videos/package-lock.json
apps/wistia-videos/package.json

chore: wistia videos app package updates [INTEG-2290]

---

apps/smartling/frontend/package-lock.json
apps/smartling/frontend/package.json

chore: remove unused dep in smartling app

---

apps/smartling/frontend/package-lock.json
apps/smartling/frontend/package.json
apps/smartling/frontend/src/App.tsx
apps/smartling/frontend/src/AppConfig.tsx
apps/smartling/frontend/src/Sidebar.tsx
apps/smartling/frontend/src/index.spec.tsx
apps/smartling/frontend/src/index.tsx

chore: update smartling app sdk and other vuln packages [INTEG-2269]

---

apps/smartling/frontend/package-lock.json
apps/smartling/frontend/package.json
apps/smartling/frontend/src/App.tsx
apps/smartling/frontend/src/AppConfig.tsx
apps/smartling/frontend/src/Sidebar.tsx
apps/smartling/frontend/src/index.spec.tsx
apps/smartling/frontend/src/index.tsx

Revert "chore: update smartling app sdk and other vuln packages [INTEG-2269]"

---

apps/ai-content-generator/package-lock.json
apps/ai-content-generator/package.json
apps/ai-content-generator/src/components/config/model/Model.tsx
apps/ai-content-generator/src/configs/prompts/baseSystemPrompt.ts
apps/ai-content-generator/src/hooks/dialog/useAI.tsx
apps/ai-content-generator/src/utils/aiApi/index.ts

[INTEG-2272](https://contentful.atlassian.net/browse/INTEG-2272)
[INTEG-2272]: https://contentful.atlassian.net/browse/INTEG-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove vulnerable dependencies from AI Content Generator app

---

apps/bedrock-content-generator/package-lock.json
apps/bedrock-content-generator/package.json

chore: amazon bedrock content gen app remediate vuln deps [INTEG-2262]

---

apps/aws-amplify/package-lock.json
apps/aws-amplify/package.json

[INTEG-2273](https://contentful.atlassian.net/browse/INTEG-2273)
[INTEG-2273]: https://contentful.atlassian.net/browse/INTEG-2273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove vulnerable dependencies from AWS Amplify app

---

apps/brandfolder/package-lock.json
apps/brandfolder/package.json

[INTEG-2275](https://contentful.atlassian.net/browse/INTEG-2275)
[INTEG-2275]: https://contentful.atlassian.net/browse/INTEG-2275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove vulnerable dependencies from Brandfolder app

---

apps/color-picker/package-lock.json
apps/color-picker/package.json

[INTEG-2276](https://contentful.atlassian.net/browse/INTEG-2276)
[INTEG-2276]: https://contentful.atlassian.net/browse/INTEG-2276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove vulnerable dependencies from Color Picker app

---

apps/mux/app-actions/package-lock.json
apps/mux/app-actions/package.json

Chore: Update Mux app app-actions vulns

---

apps/graphql-playground-v2/package-lock.json
apps/graphql-playground-v2/package.json

chore: graphql v2 remediate vulnerable dependencies [INTEG-2282]

---

apps/vercel/app-actions/package-lock.json
apps/vercel/app-actions/package.json

chore: vercel app actions vulnerable deps [INTEG-2289]

---

apps/salesforce-commerce-cloud/package-lock.json
apps/salesforce-commerce-cloud/package.json

Chore: salesforce remediate vulnerable deps [integ-2287]

---

apps/commercetools/package-lock.json
apps/commercetools/package.json
apps/commercetools/src/dialog.ts
apps/commercetools/vite.config.js

Revert "chore: remove vulnerable dependencies from Commercetools app"

---

apps/salesforce-commerce-cloud/package.json

Chore: Update Salesforce env vars for ci deploys to staging

---

apps/image-focal-point/package-lock.json
apps/image-focal-point/package.json

chore: remediate vulnerable deps in Image Focal Point app INTEG-2283

---

apps/gatsby/package-lock.json
apps/gatsby/package.json
apps/gatsby/src/AppConfig/ContentTypesPanel.spec.jsx

Chore: gatsby vulnerable deps [integ-2279]

---

apps/netlify/frontend/package-lock.json
apps/netlify/frontend/package.json
apps/netlify/lambda/package-lock.json
apps/netlify/lambda/package.json

chore: update netlify frontend and lambda packages to resolve vuln deps [INTEG-2286]

---

apps/smartling/frontend/src/AppConfig.tsx
apps/smartling/lambda/config/serverless-env.prd.yml
apps/smartling/lambda/config/serverless-env.test.yml
apps/smartling/lambda/package.json
apps/smartling/lambda/serverless.yml

Chore: Set up deploys for Smartling staging environment

---

apps/json-viewer/package-lock.json
apps/json-viewer/package.json

chore: remediate vulns in json-viewer [INTEG-2281]

---

packages/ecommerce-app-base/package-lock.json
packages/ecommerce-app-base/package.json

chore: remediate vulns in ecommerce-app-base [INTEG-2303]

---

packages/dam-app-base/package-lock.json
packages/dam-app-base/package.json

chore: update contentful-management in dam-app-base [INTEG-2302]

---

apps/netlify/lambda/package-lock.json

update package-lock to change before customer issue [ZEND-5662]

---

apps/netlify/lambda/package-lock.json
apps/netlify/lambda/package.json

Chore: Move node-apps-toolkit out of Netlify devDependencies

---

apps/ai-image-tagging/frontend/src/components/AppView/AppView.spec.jsx
apps/ai-image-tagging/lambda/app.js

Deployed to staging and confirmed app loads: https://app.contentful.com/spaces/coag8600x9le/apps/538IEN6AHckEmN3HlEoQ2a

Fix - AI Image Tagging 502 error on frontend path [ZEND-5717]

---

packages/ecommerce-app-base/package.json

update build script for ecommerce base

---

apps/slack/lambda/.env.example
apps/slack/lambda/serverless.yml

Following up on #9427 it looks like another change is needed to actually load the ENV variable and its value into the lambda.

fix: add WEB_APP_URL env var [CFISO-2167]

---

apps/google-analytics-4/README.md

Need to trigger a build in slack

readme typo to trigger build

---

apps/slack/lambda/lib/errors/middleware.ts

Redeploy slack

---

apps/braze/index.html
apps/braze/package-lock.json
apps/braze/package.json
apps/braze/src/components/Splitter.tsx
apps/braze/src/locations/ConfigScreen.spec.tsx
apps/braze/src/locations/ConfigScreen.styles.tsx
apps/braze/src/locations/ConfigScreen.tsx
apps/braze/test/mocks/mockSdk.ts

- Add Config Screen layout
- Add ApiKey installation parameter
- We added automatic tests
- Tested locally:
https://github.com/user-attachments/assets/645b241d-78bd-46fc-bbd3-6039c2964df3
No breaking changes
- [Ticket in Jira](https://contentful.atlassian.net/browse/INTEG-2399)
-  [Epic for Braze app](https://contentful.atlassian.net/browse/INTEG-2348)
Thanks to @FBanfi for pairing this ticket with me!

[INTEG-2399] Braze app config screen

---

apps/jira/functions/lib/oauth.ts
apps/jira/functions/package-lock.json
apps/jira/functions/package.json
apps/jira/functions/serverless.yml

feat: upgrade jira app node version

---

.github/workflows/pr-title-check.yml

quick workflow check to ensure branches either have a jira ticket or [] attached to them

feat: add PR title check workflow []

---

apps/netlify/lambda/serverless.yml

We need to upgrade our node versions to LTS
[INTEG-2181](https://contentful.atlassian.net/browse/INTEG-2181)
[INTEG-2181]: https://contentful.atlassian.net/browse/INTEG-2181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: upgrade netlify node version [INTEG-2181]

---

apps/ai-image-tagging/lambda/serverless.yml

Upgrading node seems to have broken the app

chore: reverting node upgrade for ai image tagging []

---

apps/braze/src/helpers/assembleQuery.ts
apps/braze/src/helpers/generateLiquidTags.spec.ts
apps/braze/src/helpers/generateLiquidTags.ts
apps/braze/src/helpers/transformEntryFields.ts
apps/braze/src/helpers/utils.ts
apps/braze/src/locations/Dialog.spec.tsx
apps/braze/src/locations/Dialog.tsx
apps/braze/src/locations/Sidebar.spec.tsx
apps/braze/src/locations/Sidebar.tsx
apps/braze/test/mocks/mockCma.ts
apps/braze/test/mocks/mockSdk.ts

Add 3rd code block: json response example

Braze integ 2403

---

examples/javascript/vite.config.js
examples/typescript/vite.config.ts

See https://www.contentful.com/developers/docs/extensibility/app-framework/app-bundle/#limitations

fix: use relative paths in ts/js template vite configs [EXT-00]

---

apps/braze/src/components/CodeBlocksStep.tsx
apps/braze/src/components/FieldsSelectionStep.tsx
apps/braze/src/components/LocalesSelectionStep.tsx
apps/braze/src/locations/Dialog.spec.tsx
apps/braze/src/locations/Dialog.tsx

Add the ability to move forward and backwards in the dialog.
https://github.com/user-attachments/assets/60b0aaa7-8112-445a-b9e1-e9f59b8a28dd
We'll probably want to split the code in this component into multiple, but I'd rather do it when we know what to put into each

Setup dialog steps

---

apps/google-analytics-4/frontend/src/components/config-screen/assign-content-type/AssignContentTypeSection.tsx

The GA4 app only fetches 1 batch of 100 content types for its configuration. If you have more you might not be able to pick them, this adds pagination if needed.
Screenshot showing (you'll have to trust me a bit) 100+ CTs

fix: GA4 content type paging [ZEND-6079]

---

apps/braze/package-lock.json
apps/braze/package.json
apps/braze/src/components/CodeBlock.spec.tsx
apps/braze/src/components/CodeBlock.tsx
apps/braze/src/components/CodeBlocksStep.tsx
apps/braze/src/components/codeblock.style.tsx
apps/braze/src/helpers/assembleQuery.ts
apps/braze/src/helpers/generateLiquidTags.spec.ts
apps/braze/src/helpers/generateLiquidTags.ts
apps/braze/src/locations/Dialog.tsx

The code block component didn't exist. We created it and used it with the three generated code blocks
In order not to create the component with all it functionalities from scratch, we investigated different libraries that we could use. One of the options that fit us the most is the react-syntax-highlighter library, that provides us a code block component with a highlighter for the specific code language you want (in our case "liquid" and "json") and line numbers.
In addition to that, we use the forma36 copy button to copy to the clipboard the code from the code block.
To sum up, two functionalities will be added by using this code block component:
- Being able to display code to the user in a reusable component
https://github.com/user-attachments/assets/e31f65bd-fca5-4a6c-870e-af673d8622c2 …

Braze app code block component

---

apps/braze/package-lock.json
apps/braze/src/components/CodeBlock.tsx

- Highlight syntax for liquid tags and json in codeblock step

Updating highlighter

---

catalog-info.yaml

adds service definitions for each marketplace apps

chore: add service definitions for marketplace apps [EXT-6259]

---

apps/braze/package.json

Releasing Braze App
[INTEG-2413](https://contentful.atlassian.net/browse/INTEG-2413)
[INTEG-2413]: https://contentful.atlassian.net/browse/INTEG-2413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: braze app release [INTEG-2413]

---

examples/autotagger/functions/autotagger.ts
examples/autotagger/functions/prompts.ts
examples/autotagger/package.json
examples/function-appaction/functions/example.ts
examples/function-comment-bot/functions/bot-actions/bot-action-base.ts
examples/function-comment-bot/functions/bot-actions/publish-button-action.ts
function-examples/appaction-call/javascript/appaction-call-template.js
function-examples/appaction-call/typescript/appaction-call-template.ts

Updates examples and templates to highlight the suggested way to use the CMA within app functions.

feat: update function examples to highlight how to init a cma client within an app function [EXT-6303]

---

apps/braze/src/fields/Entry.ts
apps/braze/src/locations/Dialog.tsx
apps/braze/test/fields/Entry.spec.ts

Graphql calls would only work if the default environment was used. We now specify the current environment so the request calls in any environment
https://github.com/user-attachments/assets/26fc4046-5e2e-4996-9970-a7d4d7436331

Braze app: Specify environment in graphql request [INTEG-2564]

---

apps/color-picker/src/locations/Field.tsx

Updated the error message for color picker required fields to make it more user friendly.
Ticket: https://contentful.atlassian.net/browse/INTEG-2605

fix: change error message for color picker required field [INTEG-2605]

---

apps/braze/contentful-app-manifest.json
apps/braze/functions/createContentBlocks.ts
apps/braze/functions/tsconfig.json
apps/braze/functions/updateContentBlocks.ts
apps/braze/package-lock.json
apps/braze/package.json

Adding functions and actions to the app
- The functions were added by running `npx --no-install @contentful/app-scripts generate-function`
- That created the functions and the manifest file. It also updated the package.json file
- I created a new app definition and then uploaded a bundle by running `npm run build` and `npm run upload`
- Here I had to update the `build` script in the package.json: I had to use the `outDir` param so the result ends up in the `build` directory instead of the `dist` directory (the `upload` script expects the build to be in the `build` folder)
- I did a quick test using `cma.appActionCall.createWithResponse` to test the function that gets called from an action and I also subscribed the app to some events to test the other function. Both functions worked …

Braze app: Add functions and action skeleton [INTEG-2590]

---

apps/braze/contentful-app-manifest.json
apps/braze/functions/createContentBlocks.ts
apps/braze/src/components/create/CreateFlow.tsx
apps/braze/src/components/create/CreateStep.styles.ts
apps/braze/src/components/create/CreateStep.tsx
apps/braze/test/functions/createContentBlocks.test.ts

- Card component for wizard step
- Refactor the way we calculated names so we can edit them. Now we do it on the FE
- Added test to make sure we aren't breaking anything
https://github.com/user-attachments/assets/444fd9b2-fba3-44a5-b3f9-23331fec8ce8
INTEG-2538

Braze app: Layout and card component [INTEG-2538]

---

apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/OutputTextPanels.tsx
apps/ai-content-generator/src/hooks/dialog/useAI.tsx

Zendesk ticket: https://contentful.atlassian.net/browse/ZEND-6369

fix: add some debug logs to aicg [INTEG-2670]

---

apps/ai-content-generator/src/components/app/dialog/common-generator/output/output-text-panels/OutputTextPanels.tsx
apps/ai-content-generator/src/hooks/dialog/useAI.tsx

Reverts contentful/apps#9850
The issue is now fixed so undo the console logs

Revert "fix: add some debug logs to aicg [INTEG-2670]"

---

apps/jira/jira-app/src/components/App/Steps/ContentTypeStep.tsx
apps/jira/jira-app/src/components/App/Steps/InstanceStep.tsx
apps/jira/jira-app/src/components/App/Steps/JiraStep.tsx
apps/jira/jira-app/src/index.scss
apps/jira/jira-app/src/index.spec.tsx

**Customer Issue Video Link:** https://share.birdie.so/GBJHPKL3
**What I see in production with the live app now**: 
https://github.com/user-attachments/assets/d60b03fb-a149-49d7-97f0-a95e9290af24
**FIXED DEMO VID**
https://github.com/user-attachments/assets/0276d689-71ad-441e-89aa-7d49c1c1c508

feat: update jira config page to be more functional [INTEG-2672]

---

apps/bulk-edit/.gitignore
apps/bulk-edit/.npmrc
apps/bulk-edit/README.md
apps/bulk-edit/index.html
apps/bulk-edit/package-lock.json
apps/bulk-edit/package.json
apps/bulk-edit/src/App.tsx
apps/bulk-edit/src/components/LocalhostWarning.tsx
apps/bulk-edit/src/index.tsx
apps/bulk-edit/src/locations/ConfigScreen.spec.tsx
apps/bulk-edit/src/locations/ConfigScreen.tsx
apps/bulk-edit/src/locations/Dialog.spec.tsx
apps/bulk-edit/src/locations/Dialog.tsx
apps/bulk-edit/src/locations/EntryEditor.spec.tsx
apps/bulk-edit/src/locations/EntryEditor.tsx
apps/bulk-edit/src/locations/Field.spec.tsx
apps/bulk-edit/src/locations/Field.tsx
apps/bulk-edit/src/locations/Home.spec.tsx
apps/bulk-edit/src/locations/Home.tsx
apps/bulk-edit/src/locations/Page.spec.tsx
apps/bulk-edit/src/locations/Page.tsx
apps/bulk-edit/src/locations/Sidebar.spec.tsx
apps/bulk-edit/src/locations/Sidebar.tsx
apps/bulk-edit/src/setupTests.ts
apps/bulk-edit/test/mocks/index.ts
apps/bulk-edit/test/mocks/mockCma.ts
apps/bulk-edit/test/mocks/mockSdk.ts
apps/bulk-edit/tsconfig.json
apps/bulk-edit/vite.config.mts

Initialize the app for 10Pines

feat: initialize bulk-edit app []

---

apps/hubspot/.gitignore
apps/hubspot/.npmrc
apps/hubspot/README.md
apps/hubspot/index.html
apps/hubspot/package-lock.json
apps/hubspot/package.json
apps/hubspot/src/App.tsx
apps/hubspot/src/components/LocalhostWarning.tsx
apps/hubspot/src/index.tsx
apps/hubspot/src/locations/ConfigScreen.spec.tsx
apps/hubspot/src/locations/ConfigScreen.tsx
apps/hubspot/src/locations/Dialog.spec.tsx
apps/hubspot/src/locations/Dialog.tsx
apps/hubspot/src/locations/EntryEditor.spec.tsx
apps/hubspot/src/locations/EntryEditor.tsx
apps/hubspot/src/locations/Field.spec.tsx
apps/hubspot/src/locations/Field.tsx
apps/hubspot/src/locations/Home.spec.tsx
apps/hubspot/src/locations/Home.tsx
apps/hubspot/src/locations/Page.spec.tsx
apps/hubspot/src/locations/Page.tsx
apps/hubspot/src/locations/Sidebar.spec.tsx
apps/hubspot/src/locations/Sidebar.tsx
apps/hubspot/src/setupTests.ts
apps/hubspot/test/mocks/index.ts
apps/hubspot/test/mocks/mockCma.ts
apps/hubspot/test/mocks/mockSdk.ts
apps/hubspot/tsconfig.json
apps/hubspot/vite.config.mts

feat: initialize hubspot app []

---

.github/CODEOWNERS

We recently renamed our team in work day and that finally synced in github.
team-tundra -> team-extensibility

chore: rename team-tundra -> team-extensibility [EXT-6372]

---

apps/bulk-edit/src/locations/Page/components/SortMenu.tsx

Update text for the sorting button.
https://github.com/user-attachments/assets/1a98002d-7b0e-4bb5-9a63-f9b158689d9f

Bulk edit: sorting button adjustments [INTEG-2729]

---

apps/bulk-edit/src/locations/Page/index.tsx
apps/bulk-edit/src/locations/Page/utils/entryUtils.ts

Found 2 issue while creating the videos for the main feature branch in which using:
- using 0 made it as empty value
- we want to handle empty fields as well
Asked erin about this case, and fix it
https://github.com/user-attachments/assets/f3722fb2-34c0-45da-8ee8-2d3810203631

Fix no string for success notif and modal issue [INTEG-2708]

---

.circleci/config.yml
apps/klaviyo/frontend/package.json

feat: klaviyo deploy scripts [EXT-2789]

---

apps/braze/functions/createContentBlocks.ts
apps/braze/test/functions/createContentBlocks.spec.ts

We want to make sure the user understands that if a 401 (Unauthorize) appears it could be because of 2 reasons : 
- API key from Braze is incorrect
- Endpoint from Braze is incorrect
Currently, as we are using braze error message, it shows only that the api key might be wrong
Decided to catch te response status for 401 following the [braze fatal error documentation](https://www.braze.com/docs/api/errors/#fatal-errors)

Clarifying errors from Braze app [INTEG-2820]

---

apps/klaviyo/functions/entrySyncFunction.ts
apps/klaviyo/functions/klaviyoService.ts
apps/klaviyo/package.json
apps/klaviyo/src/locations/ConfigScreen.tsx
apps/klaviyo/src/locations/FieldMappingScreen.tsx
apps/klaviyo/src/utils/field-mappings.ts

feat: klaviyo app updates [INTEG-2598]

---

apps/iterable/src/locations/Sidebar.tsx
apps/iterable/test/mocks/locations/Sidebar.spec.tsx
apps/iterable/test/mocks/mockSdk.ts

Add localization to link
- Add part to REST API in charge for localization
- Add tests
https://github.com/user-attachments/assets/afaef8a7-534e-43b3-a862-4651656c26ec

Iterable: Add localization to link []

---

apps/iterable/src/locations/Sidebar.tsx

- Add max level of depth to link for iterable
Data feed
https://github.com/user-attachments/assets/5062751d-b1ab-41b4-8be5-1c2d72381eaa

Add 10 levels of depth to iterable []

---

apps/iterable/src/components/ContentTypeMultiSelect.tsx
apps/iterable/src/locations/ConfigScreen.tsx
apps/iterable/test/mocks/locations/ConfigScreen.spec.tsx

Minor fixes
- Update import
- Remove casting
- Update notifier
New notifier
https://github.com/user-attachments/assets/390e07c1-b02c-4280-96a5-5d2a964e2d27
Select Content type works as expected
https://github.com/user-attachments/assets/7b88421e-c787-4a00-9540-493ab72a5fed

Fix minor issues in iterable app []

---

apps/hubspot/src/components/ConnectedFieldsModal.styles.ts
apps/hubspot/src/components/ConnectedFieldsModal.tsx
apps/hubspot/src/locations/Page.tsx
apps/hubspot/src/locations/Sidebar.tsx
apps/hubspot/src/utils/utils.ts
apps/hubspot/test/locations/Page.spec.tsx

Add disconnect functionality
- Updated modal design (Consulted with Emily)
- Add disconnect functionality
- Remove unused types
- Add test
https://github.com/user-attachments/assets/8b8769f7-79a7-43d5-8b7b-6856bdc5456b

Hubspot disconnect - [INTEG-2782]

---

apps/hubspot/.env.example
apps/hubspot/.env.test
apps/hubspot/.gitignore
apps/hubspot/package-lock.json
apps/hubspot/package.json
apps/hubspot/src/scripts/createAppEventSubscription.ts
apps/hubspot/test/scripts/createAppEventSubscription.spec.ts
apps/hubspot/vite.config.mts
apps/hubspot/vitest.config.ts

We want to add a script for adding events to the Hubspot
- Create a script to upsert app events for Hubspot app 
- Add env.examples and env.test
- Add tests and configuration
- Install dependencies
Tests are still working
https://github.com/user-attachments/assets/6e857d23-7f97-4846-9420-ccf53934f18d

Hubspot add events scripts [INTEG-2970]

---

apps/mux/package-lock.json
apps/mux/package.json

To include the build functions script in the package.json

fix: Update package.json [INTEG-00]
